import { runOperationalProjectMutation } from './project-write-policy.js';
export class BudgetEntryError extends Error { constructor(message, code = 'BUDGET_ENTRY_INVALID', status = 400) { super(message); this.name = 'BudgetEntryError'; this.code = code; this.status = status; } }
function text(value, field, max) { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new BudgetEntryError(`${field} inválido.`); return value.trim(); }
function amount(value) { const n = Number(value); if (!Number.isFinite(n) || n < 0 || n > 999999999999) throw new BudgetEntryError('amount inválido.'); return n; }
function scope(value) { if (!value?.organizationId || !value?.projectId) throw new BudgetEntryError('Alcance incompleto.'); return value; }
function serialize(row) { return { ...row, amount: row.amount?.toString?.() ?? null, occurredAt: row.occurredAt?.toISOString?.() ?? null, createdAt: row.createdAt?.toISOString?.() ?? null, updatedAt: row.updatedAt?.toISOString?.() ?? null }; }
export async function listBudgetEntries(prisma, { projectId, budgetLineId, kind }) { const rows = await prisma.budgetEntry.findMany({ where: { projectId, ...(budgetLineId ? { budgetLineId } : {}), ...(kind && ['COMMITMENT', 'ACTUAL', 'FORECAST'].includes(kind) ? { kind } : {}) }, orderBy: { occurredAt: 'desc' }, take: 500 }); return { entries: rows.map(serialize) }; }
export async function createBudgetEntry(prisma, { scope: rawScope, actorId, input }) { const current = scope(rawScope); const actor = text(actorId, 'actorId', 190); const idempotencyKey = text(input.idempotencyKey, 'idempotencyKey', 190); const kind = input.kind; if (!['COMMITMENT', 'ACTUAL', 'FORECAST'].includes(kind)) throw new BudgetEntryError('kind inválido.'); return runOperationalProjectMutation(prisma, current, async (tx) => { const replay = await tx.budgetEntry.findFirst({ where: { projectId: current.projectId, idempotencyKey } }); if (replay) return { entry: serialize(replay), replayed: true }; const line = await tx.budgetLine.findFirst({ where: { id: input.budgetLineId, projectId: current.projectId } }); if (!line) throw new BudgetEntryError('La línea presupuestaria no pertenece a la obra.', 'BUDGET_LINE_SCOPE', 409); const row = await tx.budgetEntry.create({ data: { projectId: current.projectId, budgetLineId: line.id, idempotencyKey, kind, amount: amount(input.amount), externalRef: input.externalRef ? text(input.externalRef, 'externalRef', 190) : null, description: input.description ? text(input.description, 'description', 500) : null, occurredAt: input.occurredAt ? new Date(input.occurredAt) : undefined } }); await tx.auditLog.create({ data: { organizationId: current.organizationId, actorId: actor, action: 'budget_entry.created', entityType: 'BudgetEntry', entityId: row.id, metadata: { projectId: current.projectId, budgetLineId: line.id, kind, idempotencyKey } } }); return { entry: serialize(row), replayed: false }; }); }
export function budgetEntryErrorResponse(error) { if (!(error instanceof BudgetEntryError)) return null; return Response.json({ error: error.message, code: error.code }, { status: error.status }); }
