import { runOperationalProjectMutation } from './project-write-policy.js';
export class BudgetError extends Error { constructor(message, code = 'BUDGET_INVALID', status = 400) { super(message); this.name = 'BudgetError'; this.code = code; this.status = status; } }
function text(value, field, max) { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new BudgetError(`${field} inválido.`); return value.trim(); }
function money(value, field) { const n = Number(value); if (!Number.isFinite(n) || n < 0 || n > 999999999999) throw new BudgetError(`${field} inválido.`); return n; }
function scope(value) { if (!value?.organizationId || !value?.projectId) throw new BudgetError('Alcance incompleto.'); return value; }
function serialize(row) { return { ...row, lines: row.lines?.map((line) => ({ ...line, quantity: line.quantity?.toString?.() ?? null, unitRate: line.unitRate?.toString?.() ?? null, amount: line.amount?.toString?.() ?? null })) ?? undefined, createdAt: row.createdAt?.toISOString?.() ?? null, updatedAt: row.updatedAt?.toISOString?.() ?? null, approvedAt: row.approvedAt?.toISOString?.() ?? null }; }
export async function listBudgets(prisma, { projectId }) { const rows = await prisma.budgetVersion.findMany({ where: { projectId }, include: { lines: true }, orderBy: { version: 'desc' }, take: 100 }); return { budgets: rows.map(serialize) }; }
export async function createBudget(prisma, { scope: rawScope, actorId, input }) { const current = scope(rawScope); const actor = text(actorId, 'actorId', 190); const currency = text(input.currency, 'currency', 3).toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new BudgetError('currency inválida.'); if (!Array.isArray(input.lines) || input.lines.length > 2000) throw new BudgetError('lines inválidas.'); return runOperationalProjectMutation(prisma, current, async (tx) => { const latest = await tx.budgetVersion.findFirst({ where: { projectId: current.projectId }, orderBy: { version: 'desc' }, select: { version: true, id: true } }); const lines = input.lines.map((line) => ({ projectId: current.projectId, costCode: text(line.costCode, 'costCode', 64), description: text(line.description, 'description', 220), taskId: line.taskId || null, quantity: line.quantity == null ? null : money(line.quantity, 'quantity'), unit: line.unit ? text(line.unit, 'unit', 32) : null, unitRate: line.unitRate == null ? null : money(line.unitRate, 'unitRate'), amount: money(line.amount, 'amount') })); const row = await tx.budgetVersion.create({ data: { projectId: current.projectId, version: (latest?.version || 0) + 1, currency, baseVersion: latest?.version || null, lines: { create: lines } }, include: { lines: true } }); await tx.auditLog.create({ data: { organizationId: current.organizationId, actorId: actor, action: 'budget.created', entityType: 'BudgetVersion', entityId: row.id, metadata: { projectId: current.projectId, version: row.version, lineCount: lines.length } } }); return { budget: serialize(row) }; }); }
export async function activateBudget(prisma, { scope: rawScope, actorId, id, expectedRevision }) { const current = scope(rawScope); const actor = text(actorId, 'actorId', 190); const revision = Number(expectedRevision); if (!Number.isSafeInteger(revision) || revision < 0) throw new BudgetError('expectedRevision inválida.'); return runOperationalProjectMutation(prisma, current, async (tx) => { const result = await tx.budgetVersion.updateMany({ where: { id, projectId: current.projectId, revision, status: 'DRAFT' }, data: { status: 'ACTIVE', approvedAt: new Date(), revision: { increment: 1 } } }); if (result.count !== 1) throw new BudgetError('El presupuesto cambió o ya fue activado.', 'BUDGET_CONFLICT', 409); await tx.budgetVersion.updateMany({ where: { projectId: current.projectId, status: 'ACTIVE', id: { not: id } }, data: { status: 'SUPERSEDED' } }); await tx.auditLog.create({ data: { organizationId: current.organizationId, actorId: actor, action: 'budget.activated', entityType: 'BudgetVersion', entityId: id, metadata: { projectId: current.projectId, revision: revision + 1 } } }); return { status: 'ACTIVE', revision: revision + 1 }; }); }
export function budgetErrorResponse(error) { if (!(error instanceof BudgetError)) return null; return Response.json({ error: error.message, code: error.code }, { status: error.status }); }
