import { runOperationalProjectMutation } from './project-write-policy.js';
export class ExtraWorkError extends Error { constructor(message, code = 'EXTRA_WORK_INVALID', status = 400) { super(message); this.name = 'ExtraWorkError'; this.code = code; this.status = status; } }
const STATUSES = new Set(['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED']);
function text(value, field, max, required = true) { if ((value == null || value === '') && !required) return null; if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new ExtraWorkError(`${field} inválido.`); return value.trim(); }
function integer(value, field) { if (value == null || value === '') return null; const result = Number(value); if (!Number.isSafeInteger(result) || result < 0) throw new ExtraWorkError(`${field} inválido.`); return result; }
function scope(value) { if (!value?.organizationId || !value?.projectId) throw new ExtraWorkError('Alcance incompleto.'); return value; }
function serialize(row) { return { ...row, impactCost: row.impactCost?.toString?.() || null, createdAt: row.createdAt?.toISOString?.() || null, updatedAt: row.updatedAt?.toISOString?.() || null, submittedAt: row.submittedAt?.toISOString?.() || null, decidedAt: row.decidedAt?.toISOString?.() || null }; }
export async function listExtraWork(prisma, { projectId }) { const rows = await prisma.extraWorkRequest.findMany({ where: { projectId }, orderBy: { createdAt: 'desc' }, take: 100 }); return { requests: rows.map(serialize) }; }
export async function createExtraWork(prisma, { scope: rawScope, actorId, input }) { const currentScope = scope(rawScope); const actor = text(actorId, 'actorId', 190); return runOperationalProjectMutation(prisma, currentScope, async (tx) => { const taskId = text(input.taskId, 'taskId', 190, false); const requestedByWorkerId = text(input.requestedByWorkerId, 'requestedByWorkerId', 190, false); if (taskId && !(await tx.task.findFirst({ where: { id: taskId, projectId: currentScope.projectId, metadata: { path: ['source'], equals: 'canonical-task-v1' } } }))) throw new ExtraWorkError('La tarea no pertenece a la obra.'); if (requestedByWorkerId && !(await tx.worker.findFirst({ where: { id: requestedByWorkerId, projectId: currentScope.projectId, active: true } }))) throw new ExtraWorkError('El solicitante no pertenece a la obra.'); const row = await tx.extraWorkRequest.create({ data: { projectId: currentScope.projectId, taskId, requestedByWorkerId, title: text(input.title, 'title', 220), reason: text(input.reason, 'reason', 10000), description: text(input.description, 'description', 10000, false), impactDays: integer(input.impactDays, 'impactDays'), impactCost: input.impactCost == null ? null : Number(input.impactCost), currency: text(input.currency, 'currency', 3, false), status: 'DRAFT' } }); await tx.auditLog.create({ data: { organizationId: currentScope.organizationId, actorId: actor, action: 'extra_work.created', entityType: 'ExtraWorkRequest', entityId: row.id, metadata: { projectId: currentScope.projectId, taskId } } }); return { request: serialize(row) }; }); }
export async function decideExtraWork(prisma, { scope: rawScope, actorId, id, expectedRevision, status, decisionNote }) { const currentScope = scope(rawScope); const actor = text(actorId, 'actorId', 190); const revision = Number(expectedRevision); if (!Number.isSafeInteger(revision) || revision < 0 || !['APPROVED', 'REJECTED', 'CANCELLED'].includes(status)) throw new ExtraWorkError('Decisión inválida.'); return runOperationalProjectMutation(prisma, currentScope, async (tx) => { const result = await tx.extraWorkRequest.updateMany({ where: { id, projectId: currentScope.projectId, revision, status: { in: ['DRAFT', 'SUBMITTED'] } }, data: { status, revision: { increment: 1 }, decidedAt: new Date(), decisionNote: text(decisionNote, 'decisionNote', 10000, false) } }); if (result.count !== 1) throw new ExtraWorkError('La solicitud cambió o ya fue decidida.', 'EXTRA_WORK_CONFLICT', 409); await tx.auditLog.create({ data: { organizationId: currentScope.organizationId, actorId: actor, action: 'extra_work.decided', entityType: 'ExtraWorkRequest', entityId: id, metadata: { projectId: currentScope.projectId, status, revision: revision + 1 } } }); return { status, revision: revision + 1 }; }); }
export function extraWorkErrorResponse(error) { if (!(error instanceof ExtraWorkError)) return null; return Response.json({ error: error.message, code: error.code }, { status: error.status }); }
