import { runOperationalProjectMutation } from './project-write-policy.js';
export class PurchaseOrderError extends Error { constructor(message, code = 'PURCHASE_ORDER_INVALID', status = 400) { super(message); this.name = 'PurchaseOrderError'; this.code = code; this.status = status; } }
function text(v, f, max) { if (typeof v !== 'string' || !v.trim() || v.trim().length > max) throw new PurchaseOrderError(`${f} inválido.`); return v.trim(); }
function number(v, f, min = 0) { const n = Number(v); if (!Number.isFinite(n) || n < min || n > 999999999999) throw new PurchaseOrderError(`${f} inválido.`); return n; }
function scope(v) { if (!v?.organizationId || !v?.projectId) throw new PurchaseOrderError('Alcance incompleto.'); return v; }
function serialize(row) { return { ...row, total: row.total?.toString?.() ?? null, lines: row.lines?.map((line) => ({ ...line, quantity: line.quantity.toString(), unitPrice: line.unitPrice.toString() })) }; }
export async function listPurchaseOrders(prisma, { organizationId, projectId }) { const rows = await prisma.purchaseOrder.findMany({ where: { organizationId, projectId }, include: { lines: true, supplier: { select: { id: true, legalName: true } } }, orderBy: { createdAt: 'desc' }, take: 500 }); return { purchaseOrders: rows.map(serialize) }; }
export async function createPurchaseOrder(prisma, { scope: rawScope, actorId, input }) { const current = scope(rawScope); const actor = text(actorId, 'actorId', 190); const operationKey = text(input.operationKey, 'operationKey', 190); const numberValue = text(input.number, 'number', 64); const lines = Array.isArray(input.lines) ? input.lines : []; if (!lines.length) throw new PurchaseOrderError('La orden requiere al menos una línea.'); const normalized = lines.map((line) => ({ description: text(line.description, 'description', 220), unit: text(line.unit, 'unit', 32), quantity: number(line.quantity, 'quantity', 0.001), unitPrice: number(line.unitPrice, 'unitPrice'), costCode: line.costCode ? text(line.costCode, 'costCode', 96) : null })); const total = normalized.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0); return runOperationalProjectMutation(prisma, current, async (tx) => { const replay = await tx.purchaseOrder.findFirst({ where: { projectId: current.projectId, operationKey }, include: { lines: true } }); if (replay) return { purchaseOrder: serialize(replay), replayed: true }; const supplier = await tx.supplier.findFirst({ where: { id: input.supplierId, organizationId: current.organizationId, active: true } }); if (!supplier) throw new PurchaseOrderError('Proveedor inválido o inactivo.', 'PURCHASE_SUPPLIER_SCOPE', 409); const row = await tx.purchaseOrder.create({ data: { organizationId: current.organizationId, projectId: current.projectId, supplierId: supplier.id, operationKey, number: numberValue, currency: text(input.currency || supplier.currency, 'currency', 3).toUpperCase(), total, lines: { create: normalized } }, include: { lines: true } }); await tx.auditLog.create({ data: { organizationId: current.organizationId, actorId: actor, action: 'purchase_order.created', entityType: 'PurchaseOrder', entityId: row.id, metadata: { projectId: current.projectId, supplierId: supplier.id, operationKey, total } } }); return { purchaseOrder: serialize(row), replayed: false }; }); }
export async function decidePurchaseOrder(prisma, { scope: rawScope, actorId, id, expectedRevision, status }) { const current = scope(rawScope); const actor = text(actorId, 'actorId', 190); const revision = Number(expectedRevision); if (!Number.isSafeInteger(revision) || revision < 0 || !['SUBMITTED', 'APPROVED', 'CANCELLED'].includes(status)) throw new PurchaseOrderError('Decisión inválida.'); return runOperationalProjectMutation(prisma, current, async (tx) => { const result = await tx.purchaseOrder.updateMany({ where: { id, organizationId: current.organizationId, projectId: current.projectId, revision, status: { in: ['DRAFT', 'SUBMITTED'] } }, data: { status, revision: { increment: 1 } } }); if (result.count !== 1) throw new PurchaseOrderError('La orden cambió o ya fue decidida.', 'PURCHASE_ORDER_CONFLICT', 409); await tx.auditLog.create({ data: { organizationId: current.organizationId, actorId: actor, action: 'purchase_order.decided', entityType: 'PurchaseOrder', entityId: id, metadata: { projectId: current.projectId, status, revision: revision + 1 } } }); return { status, revision: revision + 1 }; }); }
export function purchaseOrderErrorResponse(error) { if (!(error instanceof PurchaseOrderError)) return null; return Response.json({ error: error.message, code: error.code }, { status: error.status }); }
