'use client';
import {useEffect, useRef, useState, useSyncExternalStore} from 'react';
import Link from 'next/link';
import styles from './onboarding-guide.module.css';

const targetIds = ['organization-context','office-join-title','office-review-title','company-bootstrap-heading','workspace-title','workspace-refresh','project-preparation-title','schedule-title','site-register-title','participant-title','inventory-title','field-title','customer-whatsapp-title','worker-channel-title','company-channel-title','customer-meta-title','constructor-crm-title'];
function subscribeTargets(callback) {
 const observer = new MutationObserver(callback);
 observer.observe(document.body, {childList:true, subtree:true, attributes:true, attributeFilter:['hidden','style','aria-hidden','disabled']});
 window.addEventListener('resize', callback);
 return () => { observer.disconnect(); window.removeEventListener('resize', callback); };
}
const readTargets = () => targetIds.filter(id => {const element=document.getElementById(id);return element?.getClientRects().length&&(id!=='workspace-refresh'||!element.disabled);}).join('|');
const noTargets = () => '';
const accessNotices={
 SESSION_REQUIRED:{title:'Sesión por verificar',text:'Esta consulta no pudo confirmar tu sesión. Usá Actualizar en Mis obras. Si el aviso continúa, volvé a ingresar con tu cuenta.'},
 WORKSPACE_MEMBERSHIP_REQUIRED:{title:'Permisos por consultar',text:'Esta consulta no confirmó tu acceso vigente a la empresa. Si el responsable ya lo habilitó, usá Actualizar en Mis obras. Si continúa el rechazo, pedile que revise tu acceso.'},
 WORKSPACE_PROJECT_UNAVAILABLE:{title:'Acceso a la obra por consultar',text:'Esta consulta no confirmó tu acceso a la obra. Usá Actualizar en Mis obras para consultar los permisos y las obras disponibles.'},
 WORKSPACE_CONTEXT_CHANGED:{title:'Tu contexto cambió',text:'Cambió la organización o el acceso durante la consulta. Usá Actualizar en Mis obras antes de continuar.'},
 PARTICIPANT_KYC_REVIEW_REQUIRED:{title:'Revisión de identidad pendiente',text:'La identidad de tu participación de campo requiere una revisión vigente. Podés presentar o consultar la documentación privada de la obra. Esto no solicita otra invitación ni cambia tu rol de oficina.'}
};
const safeAccessReason=value=>typeof value==='string'&&Object.hasOwn(accessNotices,value)?value:null;

// A visible destination is useful for navigation, but only a current authorized
// workspace response can supply this summary. None of these labels grants access.
export function onboardingGuideSummary(observation) {
 const pending={state:'UNOBSERVED',company:'Empresa: todavía no consultada en esta sesión.',schedule:'Cronograma: abrí una obra para consultar sus tareas.',whatsapp:'WhatsApp: vínculo personal todavía no consultado. La configuración del canal no confirma entrega real.'};
 if(!observation||observation.version!==1||!Number.isSafeInteger(observation.generation)||observation.generation<0)return pending;
 if(observation.state==='UNAVAILABLE'){const accessReason=safeAccessReason(observation.accessReason);return {...pending,state:'UNAVAILABLE',accessReason,company:accessReason?accessNotices[accessReason].text:'Esta consulta no confirmó tu acceso. Usá Actualizar en Mis obras y revisá su aviso antes de continuar.',schedule:'Cronograma: la consulta anterior ya no confirma el estado actual.',whatsapp:'WhatsApp: la consulta anterior ya no confirma el vínculo actual.'};}
 if(observation.state==='CONSULTING')return {...pending,state:'CONSULTING',company:'Consultando los registros autorizados de la empresa…',schedule:'Cronograma: esperando la consulta actual.',whatsapp:'WhatsApp: esperando la consulta actual.'};
 const roles={ADMIN:'Administrador',DIRECTOR:'Director de obra',SITE_MANAGER:'Jefe de obra',FINANCE:'Administración',AUDITOR:'Auditor'};
 const count=value=>Number.isSafeInteger(value)&&value>=0;
 const record=value=>value!==null&&typeof value==='object'&&!Array.isArray(value);
 const schedule=observation.schedule,channel=observation.channel,project=observation.projectId;
 if(observation.officeReviewOnly!==undefined&&typeof observation.officeReviewOnly!=='boolean')return pending;
 if(observation.state!=='OBSERVED'||typeof observation.scope!=='string'||!/^[a-f0-9]{64}$/.test(observation.scope)||!Object.hasOwn(roles,observation.role)||!count(observation.projectCount)||typeof observation.projectsPartial!=='boolean'||typeof observation.schedulePending!=='boolean'||(project!==null&&(observation.projectCount===0||typeof project!=='string'||!/^[A-Za-z0-9][A-Za-z0-9_-]{0,127}$/.test(project)))||(!project&&(schedule!==null||channel!==null||observation.schedulePending))||(schedule!==null&&(!record(schedule)||!count(schedule.loaded)||!(schedule.total===null||count(schedule.total)&&schedule.total>=schedule.loaded)||typeof schedule.partial!=='boolean'||!count(schedule.missingDates)||!count(schedule.invalidDates)||schedule.missingDates+schedule.invalidDates>schedule.loaded||observation.schedulePending||((schedule.total===null||schedule.total>schedule.loaded)&&!schedule.partial)))||(channel!==null&&(!record(channel)||typeof channel.ready!=='boolean'||typeof channel.ownLinked!=='boolean'||typeof channel.partial!=='boolean'||channel.ownLinked&&!channel.ready)))return pending;
 if(observation.officeReviewOnly===true){
  if(observation.role!=='AUDITOR'||schedule!==null||channel!==null||observation.schedulePending)return pending;
  return {state:'OBSERVED',officeReviewOnly:true,company:`Acceso de oficina consultado: ${observation.projectCount} ${observation.projectCount===1?'obra':'obras'} ${observation.projectsPartial?(observation.projectCount===1?'mostrada':'mostradas')+' (lista parcial)':observation.projectCount===1?'asignada':'asignadas'}${observation.projectCount===0?'; pedile al responsable que revise tu asignación':''}.`,office:project?'Obra seleccionada en esta consulta. Abrí Revisión de conexión y eventos para consultar lo que el administrador compartió. La configuración guardada sólo se muestra si fue compartida con esta invitación; no consulta el estado actual en Meta. La selección de obra no confirma su contenido.':'Abrí una obra asignada en Mis obras para consultar Revisión de conexión y eventos.',schedule:null,whatsapp:null};
 }
 let scheduleText=project?'Cronograma: consultá sus registros antes de confirmar la planificación.':pending.schedule;
 if(observation.schedulePending)scheduleText='Cronograma: hay una operación o consulta pendiente. Comprobá su resultado antes de confirmar el total.';
 else if(schedule)scheduleText=`Cronograma consultado: ${schedule.loaded} ${schedule.loaded===1?'tarea cargada':'tareas cargadas'}${schedule.total===null?' (total sin confirmar)':` de ${schedule.total}`}. ${schedule.partial?'Vista parcial: cargá más antes de evaluar toda la obra.':'Vista completa de esta consulta.'} ${schedule.missingDates} sin fechas; ${schedule.invalidDates} con fechas por revisar. Tener tareas sin fechas puede corresponder a una preobra; no confirma inicio ni avance.`;
 const whatsapp=channel?`WhatsApp consultado: ${channel.ready?'canal disponible para vinculación':'canal pendiente de habilitación'}. ${channel.ownLinked?'Tu vínculo personal está vigente en esta consulta.':'No se observa un vínculo personal vigente en los registros consultados.'}${channel.partial?' La lista consultada es parcial.':''} El consentimiento para avisos se decide aparte; esto no confirma envío ni entrega real.`:pending.whatsapp;
 return {state:'OBSERVED',...(observation.accessReason==='PARTICIPANT_KYC_REVIEW_REQUIRED'?{accessReason:observation.accessReason}:{}),company:`Empresa consultada con acceso ${roles[observation.role]}: ${observation.projectCount} ${observation.projectCount===1?'obra':'obras'} ${observation.projectsPartial?(observation.projectCount===1?'mostrada':'mostradas')+' (lista parcial)':observation.projectCount===1?'asignada':'asignadas'}${observation.projectCount===0?'; pedile al responsable que revise tu asignación':''}. Esta consulta no es un comprobante de alta.`,schedule:scheduleText,whatsapp};
}

const steps = [
 {key:'organization',title:'Elegí la organización',manual:'empezar',target:'organization-context',text:'Elegí tu constructora en Organización activa. Si te invitaron, seleccioná esa empresa.',detail:'Usá tu propia cuenta y verificá el correo. Crear una organización no crea todavía la empresa, la obra ni sus participantes.',dependency:'El selector de organización todavía no está disponible. Esperá a que se confirme tu sesión.'},
 {key:'company',title:'Empresa y primera obra',manual:'empezar',target:'company-bootstrap-heading',text:'Si sos administrador, completá el nombre de la empresa y de la primera obra. La dirección y las primeras tareas son opcionales. Revisá la confirmación antes de crear.',detail:'Esperá el comprobante y elegí Entrar a mi obra. Si no llega la respuesta, usá Comprobar creación: no repitas el alta en otra organización.',dependency:'Primero seleccioná una organización. El alta inicial corresponde a su administrador.'},
 {key:'preparation',title:'Prepará la obra',manual:'empezar',target:'project-preparation-title',text:'En Preparación de obra, el administrador o director registra el nombre, la dirección, el cliente y los equipos previstos. Distinguí alcance, fecha o fin de semana previsto y responsable pendiente en las notas.',detail:'Las etiquetas provisionales quedan pendientes de identificación. Un equipo previsto no crea personas, invitaciones, cuentas ni permisos. Conservá las tareas reales del cronograma; no vuelvas a agregarlas para describir la preparación.',dependency:'Abrí una obra. Guardar su preparación requiere el rol Administrador o Director de obra.'},
 {key:'tasks',title:'Organizá las tareas',manual:'cronograma',target:'schedule-title',text:'Abrí una obra en Mis obras y consultá su cronograma. Si sos administrador, director o jefe de obra, podés crear tareas o elegir Importar PDF o imagen para preparar un borrador del Gantt. Compará sus títulos y fechas con la fuente antes de aplicarlo.',detail:'La importación admite hasta 50 tareas por archivo y requiere autorización para la extracción con OpenAI. Un administrador o director aprueba agregarlas con avance cero; no reemplaza las tareas existentes. El resumen y la búsqueda consideran las tareas cargadas: cargá más si la vista es parcial. Una fecha prevista no registra trabajo; el avance cambia tras una aprobación autorizada.',dependency:'Primero completá el alta de la empresa y abrí una obra en Mis obras. Si no tenés una obra asignada, pedile acceso a su responsable.'},
 {key:'team',title:'Incorporá al equipo',manual:'equipo',target:'participant-title',text:'Consultá tu participación en esta obra. El responsable prepara tu ficha y envía la invitación al correo correcto; ingresá con tu cuenta y aceptá la participación.',detail:'Una ficha o un teléfono declarado no conceden acceso. Podés aceptar con un correo secundario verificado de tu propia cuenta, conservando el principal. Si el correo queda sin confirmar, consultá el resultado antes de volver a invitar.',dependency:'Abrí una obra para consultar Participantes y revisión de identidad. Invitar y administrar personas requiere el permiso correspondiente.'},
 {key:'identity',title:'Presentá y revisá la identidad',manual:'equipo',target:'participant-title',text:'En la web, presentá el frente y una selfie; el dorso es opcional con autorización separada. En nuevas capturas por WhatsApp, presentá frente, dorso y selfie después de autorizar el dorso. Otro responsable autorizado consulta las imágenes y registra su revisión.',detail:'Usá el autoservicio o el código privado IDENTIDAD del canal cliente activo. Las presentaciones anteriores por WhatsApp conservan su recorrido de dos imágenes. La revisión es humana. La lectura asistida y la comparación facial privada requieren autorizaciones independientes y son opcionales. La selfie es estática: no verifica prueba de vida ni aprueba la identidad. En WhatsApp, usá el código del responsable desde el teléfono exacto de tu ficha y confirmá Guardar identidad. Podés cancelar antes de confirmar. La captura previa a aceptar la invitación queda pendiente; ni guardar imágenes ni vincular WhatsApp concede permisos de campo.',dependency:'Si todavía no aceptaste la invitación, la captura por chat queda pendiente de aceptación de cuenta y no habilita permisos. Para continuar con la revisión, aceptá la invitación verificada y abrí la obra asignada.'},
 {key:'materials',title:'Organizá los materiales',manual:'trabajo',target:'inventory-title',text:'Abrí Inventario y consumo para consultar el catálogo y los saldos de esta obra. El responsable prepara los materiales y las entregas vinculadas antes de usarlos.',detail:'Informar consumo conserva un pedido de revisión. El stock sólo disminuye tras la aprobación autorizada y con saldo suficiente. La guía no confirma existencia física ni un saldo que todavía no consultaste.',dependency:'Abrí una obra para consultar Inventario y consumo. Las altas, entregas y aprobaciones requieren sus permisos actuales.'},
 {key:'field',title:'Registrá el trabajo',manual:'trabajo',target:'field-title',text:'Con participación y revisión vigentes, abrí Jornada y evidencia. El responsable prepara sectores y QR. En Inventario y consumo prepara el catálogo; las entregas vinculadas aumentan el saldo y los consumos requieren revisión.',detail:'En Sectores y QR, el responsable puede reimprimir el código vigente sin renovar la configuración. Elegí el sector y leé su QR con cámara; podés detenerla mientras esperás el permiso. La lectura queda en el formulario hasta que guardes. Para fichar, obtené la ubicación puntual y el QR cuando corresponda: una ubicación válida fuera del perímetro o la ausencia del QR requiere revisión; los errores de GPS se corrigen antes de fichar. Subir evidencia no aprueba avance. Informar consumo tampoco descuenta stock: otro administrador o director debe aprobarlo con saldo suficiente.',dependency:'Abrí una obra. La jornada y los reportes requieren tu ficha activa, identidad revisada y permisos actuales.'},
 {key:'whatsapp',title:'Prepará WhatsApp',manual:'whatsapp',target:'customer-whatsapp-title',text:'Podés trabajar desde la web mientras se prepara el canal. El responsable autoriza el número de la empresa con Meta; cada participante vincula el suyo desde su propia cuenta.',detail:'El código de SMS o llamada es distinto del PIN de registro. El código VINCULAR es privado y vence. Vincular un número no autoriza recordatorios: ese consentimiento se decide aparte.',dependency:'Abrí una obra con acceso a integraciones. Si sos participante, usá Mi WhatsApp de obra cuando el canal esté habilitado.'},
 {key:'clients',title:'Clientes y seguimiento',manual:'clientes',target:'constructor-crm-title',text:'El administrador de la empresa consulta Clientes para registrar oportunidades, contactos, etapas y la próxima fecha de seguimiento. Buscá por cliente, contacto, correo o teléfono en toda la empresa.',detail:'Las fichas pertenecen a la empresa, no sólo a la obra abierta. Una fecha de seguimiento no envía mensajes ni emite un presupuesto. Guardar un teléfono no concede permiso para escribirle por WhatsApp.',dependency:'Consultar Clientes requiere permiso de administración y el rol Administrador de la empresa. Abrí una obra con ese acceso; si tu rol no lo permite, pedile al responsable que gestione el seguimiento.'},
];

const officeSteps = [
 {key:'organization',title:'Comprobá la organización',manual:'equipo',target:'organization-context',text:'En Organización activa, comprobá que esté seleccionada la empresa que te invitó.',detail:'Si la invitación sigue pendiente, abrí su enlace, ingresá con tu propia cuenta y verificá el correo invitado. Aceptá primero la invitación de Clerk, seleccioná esa organización y consultá la misma invitación de oficina. La guía no realiza la aceptación.',dependency:'Esperá a que se confirme tu sesión para consultar la organización activa.'},
 {key:'office-access',title:'Actualizá Mis obras',manual:'equipo',target:'workspace-refresh',text:'Usá Actualizar en Mis obras para consultar tu acceso vigente y las obras asignadas. Si acabás de aceptar la invitación, hacé esta consulta antes de abrir la obra.',detail:'El acceso de esta consulta permite revisar lo que el administrador compartió. Si tu obra no aparece o hay un rechazo, consultá el aviso y pedile al responsable que revise la asignación.',dependency:'Esperá o resolvé la consulta pendiente en Mis obras antes de actualizar.'},
 {key:'office-open',title:'Abrí la obra asignada',manual:'equipo',target:'workspace-title',text:'Elegí la obra que vas a revisar en Mis obras. Abrirla muestra Revisión de conexión y eventos.',detail:'Las obras disponibles corresponden al acceso consultado en esta sesión. Al cambiar de organización o cuenta, consultá de nuevo antes de continuar.',dependency:'Consultá tu acceso vigente en Mis obras antes de abrir la obra.'},
 {key:'office-review',title:'Consultá conexión y eventos',manual:'equipo',target:'office-review-title',text:'En Revisión de conexión y eventos, consultá los saludos elegidos por el administrador. La configuración guardada de la conexión sólo aparece si la compartió con esta invitación.',detail:'Revisá el resultado del panel y sus avisos de carga o acceso. Actualizar comprueba tu acceso y la vigencia del registro guardado; no consulta el estado actual en Meta. Una configuración informada no confirma entrega real de mensajes ni amplía tu alcance.',dependency:'Primero abrí una obra asignada en Mis obras. La revisión se muestra con el acceso vigente a esa obra.'},
];

export function onboardingGuideSteps(observation) {
 return onboardingGuideSummary(observation).officeReviewOnly===true?officeSteps:steps;
}

export function OnboardingGuide({orgId=null,orgRole=null,observation=null}) {
 const summary=onboardingGuideSummary(observation),officeReviewOnly=summary.officeReviewOnly===true;
 return <OnboardingGuideFlow key={officeReviewOnly?'office':'workspace'} orgId={orgId} orgRole={orgRole} summary={summary} guideSteps={officeReviewOnly?officeSteps:steps} officeReviewOnly={officeReviewOnly}/>;
}

function OnboardingGuideFlow({orgId,orgRole,summary,guideSteps,officeReviewOnly}) {
 const [opened,setOpened] = useState(true), [index,setIndex] = useState(()=>orgId?1:0), [reviewed,setReviewed] = useState([]), [notice,setNotice] = useState('');
 const title = useRef(null), moveFocus = useRef(false), choices = useRef(null);
 const available = new Set(useSyncExternalStore(subscribeTargets, readTargets, noTargets).split('|'));
 const step = guideSteps[index], administrator = orgRole === 'org:admin';
 const accessNotice=orgId&&available.has('workspace-title')&&(summary.state!=='OBSERVED'||summary.accessReason)?summary.state==='CONSULTING'?{title:'Consultando tu acceso',text:'Esperá la consulta actual. Los datos anteriores no confirman tus permisos vigentes.'}:summary.accessReason?accessNotices[summary.accessReason]:{title:summary.state==='UNAVAILABLE'?'Acceso por actualizar':'Comprobá tu acceso',text:summary.state==='UNAVAILABLE'?summary.company:'Mis obras todavía no confirmó tu acceso en esta sesión. Usá Actualizar para consultar las obras disponibles.'}:null;
 const workspaceStep=step.key==='company'&&available.has('workspace-title');
 const teamRegister = step.key==='team'&&available.has('site-register-title');
 let target = step.target, dependency = step.dependency;
 if(step.key==='company') {
  if(!orgId) target=null;
  else if(available.has('workspace-title')) target='workspace-title';
  else if(!administrator) { target=null; dependency='El administrador debe completar el alta inicial. Cuando tengas una obra asignada, podrás consultarla en Mis obras.'; }
 }
 if(step.key==='whatsapp'&&!available.has(target)&&available.has('worker-channel-title')) target='worker-channel-title';
 if(teamRegister) target='site-register-title';
 const canGo=Boolean(target&&available.has(target));
 useEffect(()=>{if(moveFocus.current){title.current?.focus();moveFocus.current=false;}},[index]);
 function change(next){moveFocus.current=true;if(choices.current)choices.current.open=false;setNotice('');setIndex(next);}
 function go(destination=target){
  const element=destination&&document.getElementById(destination);
  if(!element?.getClientRects().length||element.disabled){setNotice(destination==='workspace-refresh'?'Esperá o resolvé la acción pendiente en Mis obras antes de actualizar.':dependency);return;}
  const temporary=!element.hasAttribute('tabindex');
  if(temporary){element.setAttribute('tabindex','-1');element.addEventListener('blur',()=>element.removeAttribute('tabindex'),{once:true});}
  element.scrollIntoView({behavior:'auto',block:'start'});element.focus({preventScroll:true});
 }
 return <section className={styles.guide} aria-labelledby="onboarding-guide-title">
  <div className={styles.heading}><div><p className={styles.eyebrow}>ACOMPAÑAMIENTO DE INICIO</p><h2 id="onboarding-guide-title" tabIndex={-1}>{officeReviewOnly?'Tu revisión de oficina, paso a paso':'Tu primera obra, paso a paso'}</h2></div><button type="button" aria-expanded={opened} aria-controls="onboarding-guide-content" onClick={()=>setOpened(value=>!value)}>{opened?'Ocultar guía':'Abrir guía'}</button></div>
  {opened&&<div id="onboarding-guide-content">
   <p className={styles.intro}>Te acompañamos sin guardar datos ni enviar mensajes.</p>
    {accessNotice&&<div className={styles.accessNotice} data-guide-access={summary.state} data-guide-access-reason={summary.accessReason||'UNCONFIRMED'} role="status" aria-live="polite"><strong>{accessNotice.title}</strong><p>{accessNotice.text}</p><button type="button" disabled={!available.has('workspace-refresh')||summary.state==='CONSULTING'} onClick={()=>go('workspace-refresh')}>Ir a Mis obras para actualizar</button>{available.has('office-join-title')&&<><p>Si tu invitación de oficina sigue pendiente, aceptá el enlace de Clerk con el correo invitado verificado, seleccioná la organización y consultá esa misma invitación.</p><button type="button" onClick={()=>go('office-join-title')}>Consultar mi invitación de oficina</button></>}</div>}
   <div><details className={styles.choices}><summary>{({OBSERVED:'Ver datos consultados',CONSULTING:'Consulta en curso',UNAVAILABLE:'Acceso por actualizar',UNOBSERVED:'Ver qué falta consultar'})[summary.state]}</summary><div data-guide-observation={summary.state} data-guide-mode={officeReviewOnly?'office-review':'workspace'} role="status" aria-live="polite"><p>{summary.company}</p>{summary.office&&<p>{summary.office}</p>}{summary.schedule&&<p>{summary.schedule}</p>}{summary.whatsapp&&<p>{summary.whatsapp}</p>}</div></details></div>
    <details className={styles.choices} ref={choices}><summary>Elegir otro paso</summary><nav aria-label="Pasos de inicio" className={styles.steps}>{guideSteps.map((item,position)=><button type="button" key={item.key} aria-current={position===index?'step':undefined} onClick={()=>change(position)}><span>{position+1}</span>{item.key==='company'&&orgId&&available.has('workspace-title')?'Comprobar acceso y abrir obra':item.title}{reviewed.includes(item.key)&&<small>Revisado por vos</small>}</button>)}</nav></details>
    <div className={styles.current}><p className={styles.position}>Paso {index+1} de {guideSteps.length}</p><h3 ref={title} tabIndex={-1}>{workspaceStep?summary.state==='OBSERVED'?'Abrí una obra':'Comprobá tu acceso':step.title}</h3><p>{workspaceStep?summary.state==='OBSERVED'?'Mis obras muestra el acceso de esta consulta. Elegí una obra disponible para consultar su información.':'Tu organización está seleccionada. En Mis obras, usá Actualizar para comprobar tu acceso actual antes de abrir una obra.':teamRegister?'Primero abrí Equipo, incidencias y materiales → Abrir registro → Agregar persona para guardar la ficha. Después, en Participantes y revisión de identidad, asigná los permisos y enviá la invitación al correo correcto. El invitado ingresa con su cuenta y acepta la participación en esa obra.':step.text}</p>
    <details key={step.key}><summary>Qué revisar en este paso</summary><p>{workspaceStep?'Consultá tu acceso vigente y las obras disponibles. Si el responsable ya confirmó tu rol, usá Actualizar antes de pedir otra revisión. El acceso de oficina y la identidad necesaria para tu participación de campo se consultan por separado.':step.detail}</p><label className={styles.review}><input type="checkbox" checked={reviewed.includes(step.key)} onChange={event=>setReviewed(previous=>event.target.checked?[...previous,step.key]:previous.filter(key=>key!==step.key))}/><span>Revisado por vos <small>Marca personal; no confirma guardado, permisos ni aceptación del proveedor.</small></span></label></details>
    {!canGo&&<p className={styles.dependency}>{dependency}</p>}
    <div className={styles.actions}><button type="button" className={styles.primary} disabled={!canGo} onClick={()=>go()}>Ir a este paso</button>{teamRegister&&available.has('participant-title')&&<a href="#participant-title" onClick={event=>{event.preventDefault();go('participant-title');}}>Invitaciones y permisos</a>}{step.key==='whatsapp'&&['company-channel-title','customer-meta-title'].filter(id=>available.has(id)).map(id=><a key={id} href={'#'+id} onClick={event=>{event.preventDefault();go(id);}}>{id==='company-channel-title'?'Canal de la empresa':'Conexión y permisos Meta'}</a>)}{!canGo&&available.has('workspace-title')&&<button type="button" onClick={()=>go('workspace-title')}>Consultar Mis obras</button>}<Link href={'/manual#'+step.manual}>Leer el paso en el manual</Link></div>
   </div>
   <p className={styles.notice} role="status" aria-live="polite">{notice}</p>
   <div className={styles.navigation}><button type="button" disabled={index===0} onClick={()=>change(index-1)}>Anterior</button><span>{reviewed.length} de {guideSteps.length} pasos revisados por vos</span>{index<guideSteps.length-1?<button type="button" onClick={()=>change(index+1)}>Siguiente</button>:<button type="button" onClick={()=>change(0)}>Volver al primer paso</button>}</div>
   <p className={styles.privacy}>Las marcas no se guardan. Al cambiar de cuenta u organización, empiezan de nuevo.</p>
  </div>}
 </section>;
}
