'use client';
import {useCallback,useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import {participantOnboardingNextStep,participantKycChatCapabilities,participantOnboardingDeliveryView,participantOnboardingContactNotice,participantOnboardingWhatsAppConsent,participantKycReviewImages,participantDocumentBackNotice,participantKycHistoricalReceipt} from './participant-onboarding-next-step.mjs';

import {browserRecoveryJournal,RECOVERY_EVENT,recoveryQuery,recoveryResult,PARTICIPANT_INTAKE_RECOVERY_ACTIONS} from './workspace-recovery-journal.mjs';
import {PRIVATE_BANK_ACTIONS} from './private-bank-account-format.mjs';
import {EmployeeIntakePanel} from './employee-intake-panel.js';
import {employeeIntakeInvitationQuery,employeeIntakeInvitationPreparation} from './employee-intake-continuity.mjs';
import {useWorkspaceRequest} from './workspace-request-lifecycle.js';
import {KycPhotoPreparation,KYC_PHOTO_LIMIT} from './kyc-photo-preparation.js';
import {PrivateBankAccountPanel} from './private-bank-account-panel.js';
import {ParticipantAccountDiscovery,ParticipantAccountDetails} from './participant-account-discovery.js';
import {participantAccountPage,participantAccountStamp,participantAccountSelectionAllowed,participantAccountReadDenied} from './participant-account-discovery-format.mjs';
import {PARTICIPANT_OFFICE_ASSIGN_ACTION,participantOfficeEmail,participantOfficeSnapshot,participantOfficeSelectionStamp,participantOfficeStateMessage,participantOfficeReceiptOutcome,participantOfficePrecommitRejected} from './participant-office-account-view.mjs';
import styles from './participant-panel.module.css';
const endpoint='/api/identity/participants',joinEndpoint='/api/identity/participant-join';
const imageKey=(row,image)=>row.id+':'+row.kyc.submissionId+':'+image.id;
const labels={NOT_INVITED:'Sin participación vinculada',INVITED:'Invitación pendiente',ACTIVE:'Participación activa en esta obra',REVOKED:'Participación revocada',NOT_SUBMITTED:'Sin presentar',PENDING_ACCOUNT_CLAIM:'Imágenes presentadas; falta aceptar la cuenta',PENDING_REVIEW:'Pendiente de revisión humana',APPROVED:'Aprobado por un responsable',REJECTED:'Requiere corrección',ATTEMPTED:'Envío sin confirmar',SENT:'Invitación creada en Clerk',ACCEPTED:'Invitación aceptada'};
const errors={PARTICIPANT_REVISION_CHANGED:'El registro cambió. Conservamos tu texto; actualizá para revisar la versión vigente.',PARTICIPANT_EMAIL_MISMATCH:'La invitación corresponde a otro correo verificado. Ingresá con la cuenta invitada.',PARTICIPANT_PROVIDER_ACCEPTANCE_REQUIRED:'Primero aceptá la invitación de Clerk y seleccioná la organización indicada.',PARTICIPANT_VERIFIED_EMAIL_REQUIRED:'Verificá tu correo antes de aceptar el acceso.',PARTICIPANT_INVITATION_REVOKED:'El responsable revocó esta invitación.',PARTICIPANT_INVITATION_EXPIRED:'La invitación venció. Pedí al responsable que revise el acceso.',PARTICIPANT_MEMBER_SESSION_REQUIRED:'Seleccioná la organización de la invitación con tu cuenta de participante.',PARTICIPANT_MEMBERSHIP_REVIEW_REQUIRED:'Tu acceso fue deshabilitado o requiere una revisión del administrador.',PARTICIPANT_ALREADY_INVITED:'Esta persona ya tiene una invitación. Comprobá su estado; no se envió otra.',PARTICIPANT_EMAIL_ALREADY_INVITED:'Ese correo ya tiene una invitación en esta obra.',PARTICIPANT_KYC_ALREADY_SUBMITTED:'Ya hay una presentación pendiente o aprobada. No se duplicó.',PARTICIPANT_MANAGE_REQUIRED:'Tu permiso no permite administrar participantes.',PARTICIPANT_SELF_REVIEW_REJECTED:'La identidad debe revisarla otra persona autorizada.',PARTICIPANT_ACCESS_REQUIRED:'No hay un acceso activo vinculado a tu cuenta en esta obra.',PARTICIPANT_IDENTITY_PROVIDER_UNAVAILABLE:'No se pudo verificar Clerk. Conservá el intento y comprobá su estado.',PARTICIPANT_OPERATION_CONFLICT:'Este intento corresponde a una solicitud distinta. No se reemplazó.',PARTICIPANT_PRIVATE_STORAGE_UNCONFIRMED:'No se confirmó el guardado privado de las imágenes. Conservá el intento.',PARTICIPANT_KYC_INTEGRITY:'El archivo no coincide con la evidencia presentada. No se mostró.',PARTICIPANT_PRIVACY_REQUIRED:'Leé el aviso y confirmá el uso de tus imágenes para revisión.',PARTICIPANT_OFFICE_ROLE_PROTECTED:'Este acceso está protegido o fue deshabilitado. No se modificó el rol.',WORKSPACE_ORGANIZATION_PERMISSION_REQUIRED:'Sólo el administrador puede cambiar los roles de empresa.'};
Object.assign(errors,{PARTICIPANT_DOCUMENT_BACK_CONSENT_REQUIRED:'Leé el aviso del dorso y confirmá su autorización independiente, o presentá sólo el frente y tu fotografía.',PARTICIPANT_OCR_CONSENT_REQUIRED:'Esta presentación no autoriza un análisis asistido vigente. La revisión manual sigue disponible.',PARTICIPANT_OCR_PROCESSING:'Ya hay una lectura en curso. Comprobá el mismo intento antes de iniciar otra.',PARTICIPANT_OCR_ALREADY_PROCESSED:'El análisis ya tiene resultado. Revisalo junto con las imágenes originales.',PARTICIPANT_OCR_PROCESSING_CHANGED:'La presentación o el intento cambió. El resultado anterior no se incorporó.'});
Object.assign(errors,{META_KYC_CHALLENGE_PARTICIPANT_REQUIRED:'Comprobá la participación, el teléfono internacional y la versión vigente antes de preparar el código.',META_KYC_CHALLENGE_AMBIGUOUS:'Ese teléfono corresponde a más de una participación. Corregí el registro antes de continuar.',WORKER_CHANNEL_CUSTOMER_CONNECTION_REQUIRED:'La obra necesita su propio WhatsApp empresarial conectado para recibir identidad.'});
Object.assign(errors,{PARTICIPANT_ONBOARDING_CONSENT_REQUIRED:'Leé el aviso de contacto vigente y confirmá la autorización de esta persona antes de solicitar instrucciones por WhatsApp.',PARTICIPANT_ONBOARDING_CONTEXT_CHANGED:'Cambió la invitación, el canal o el permiso para este envío. Consultá el mismo intento y el perfil vigente antes de continuar.',PARTICIPANT_ONBOARDING_ALREADY_REQUESTED:'Ya hay una solicitud de instrucciones. Consultá el estado del envío; no se creó otra.',PARTICIPANT_ONBOARDING_ISSUER_REQUIRED:'Sólo el responsable que creó la invitación puede solicitar este envío con su permiso vigente.'});
Object.assign(errors,{ATTENDANCE_PERSON_JOURNEY_OPEN:'La persona tiene una jornada abierta. Pedile que registre su salida antes de retirar el permiso de jornada. Conservamos los permisos y tu motivo.'});
Object.assign(errors,{PARTICIPANT_INTAKE_UNAVAILABLE:'La ficha de esta solicitud ya no está disponible con tu acceso. Consultá nuevamente los participantes.'});
Object.assign(errors,{PARTICIPANT_OFFICE_PROOF_CHANGED:'La identidad o su pertenencia en Clerk cambió. Consultá la cuenta y confirmá sus permisos otra vez.',PARTICIPANT_OFFICE_ACCOUNT_EXISTS:'Esta cuenta ya pertenece a la empresa. Consultá sus permisos existentes.',PARTICIPANT_OFFICE_TARGET_PROTECTED:'Esta cuenta tiene un acceso protegido. No se incorporó.',PARTICIPANT_OFFICE_ACCOUNT_RESTRICTED:'Esta cuenta tiene un acceso limitado que no se convierte automáticamente en Dirección.',PARTICIPANT_OFFICE_ACCOUNT_FIELD_BOUND:'La cuenta tiene una participación de campo. Continuá desde su ficha.',PARTICIPANT_OFFICE_RECEIPT_INVALID:'No se pudo comprobar el recibo y la cuenta vigente. Conservá la referencia del mismo intento.'});
errors.PARTICIPANT_OFFICE_HISTORY_UNCONFIRMED='Hay un alta de campo anterior sin vínculo verificable en esta empresa. Requiere revisión del administrador; no borres registros ni crees otro espacio.';
const accessDenied=error=>[401,403].includes(error.status)||['WORKSPACE_CONTEXT_CHANGED','WORKSPACE_PROJECT_UNAVAILABLE'].includes(error.code);
const changedContext=()=>Object.assign(new Error('La respuesta no corresponde a esta obra y este intento. Volvé a comprobar tu acceso.'),{code:'WORKSPACE_CONTEXT_CHANGED'});
function ParticipantOnboardingContactChoice({notice,checked,disabled,onChange}){
 if(!notice)return <p>Consultá el perfil vigente para comprobar el aviso de contacto por WhatsApp.</p>;
 return <div className={styles.evidence}><p>{notice.text}</p><label className={styles.consent}><input type="checkbox" disabled={disabled} checked={checked} onChange={event=>onChange(event.target.checked)}/>Enviar también las instrucciones por WhatsApp</label><small>La solicitud tiene seguimiento propio. Guardarla no confirma el envío, la entrega ni la identidad.</small></div>;
}
function ParticipantChatChallenge({challenge,clock,disabled,onExpire,onHide,onConsult,consultDisabled}){
 const [copying,setCopying]=useState(false),[feedback,setFeedback]=useState(''),alive=useRef(true),copyPending=useRef(false);
 const expiresAt=Date.parse(challenge.expiresAt),clockUnknown=!Number.isFinite(clock)||!Number.isFinite(expiresAt),expired=challenge.expired===true||!clockUnknown&&clock>=expiresAt;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function copyMessage(){
  if(disabled||copyPending.current||challenge.codeUnavailable||expired)return;
  const now=Date.now();
  if(!Number.isFinite(now)||!Number.isFinite(expiresAt)){setFeedback('No pudimos comprobar el reloj del dispositivo. Conservamos el código; consultá la presentación vigente antes de copiarlo.');return;}
  if(now>=expiresAt){onExpire();return;}
  copyPending.current=true;setCopying(true);setFeedback('');
  try{
   if(typeof navigator.clipboard?.writeText!=='function')throw new Error('Clipboard unavailable');
   await navigator.clipboard.writeText(challenge.code);
   if(alive.current)setFeedback('Mensaje copiado. Entregalo sólo al participante. Debe enviarlo desde su teléfono registrado al WhatsApp empresarial de esta obra.');
  }catch{if(alive.current)setFeedback('No se pudo copiar. Seleccioná el mensaje visible y copialo manualmente.');}
  finally{copyPending.current=false;if(alive.current)setCopying(false);}
 }
 return <div className={styles.evidence}><strong>Código privado de presentación por WhatsApp</strong>{expired?<><p>El código venció y dejó de mostrarse. El recibo de preparación se conserva. Consultá la presentación vigente; el responsable debe revisar su cierre antes de preparar otro código.</p><button type="button" disabled={consultDisabled} onClick={onConsult}>Consultar presentación vigente</button></>:challenge.codeUnavailable?<><p>El recibo de preparación está confirmado, pero el código se muestra una sola vez y ya no está disponible. Consultá la presentación vigente; si el responsable tiene permiso, podrá cerrarla antes de preparar un código distinto.</p><button type="button" disabled={consultDisabled} onClick={onConsult}>Consultar presentación vigente</button></>:<><p>Entregá este código sólo al participante. Debe enviarlo desde su teléfono registrado al WhatsApp empresarial de esta obra.</p><p style={{overflowWrap:'anywhere'}}><code>{challenge.code}</code></p><button type="button" disabled={disabled||copying||clockUnknown} onClick={copyMessage}>{copying?'Copiando mensaje…':'Copiar mensaje para WhatsApp'}</button>{clockUnknown&&<><p role="status">No pudimos comprobar el reloj del dispositivo. Conservamos el código; consultá la presentación vigente antes de copiarlo.</p><button type="button" disabled={consultDisabled} onClick={onConsult}>Consultar presentación vigente</button></>}<p role="status" aria-live="polite">{feedback}</p></>}<p>Vence: {new Date(challenge.expiresAt).toLocaleString('es-AR')}. Permite presentar imágenes. El responsable revisa la documentación.</p><button type="button" disabled={disabled} onClick={onHide}>Ocultar código</button></div>;
}
function useParticipantRequest(getSessionToken){
 const request=useWorkspaceRequest(getSessionToken);
 return async function api(params,options={},resource=endpoint,image=false,validate=value=>value){
  if(typeof getSessionToken!=='function')throw Object.assign(new Error('Tu sesión terminó. Volvé a ingresar.'),{status:401,code:'SESSION_REQUIRED',requestDispatched:false});
  const requestTimeoutMs=options.requestTimeoutMs??(options.method==='POST'?30000:params?.operationId?15000:20000);
  let retainedError;
  const result=await request(resource+(params?'?'+new URLSearchParams(params):''),{...options,requestTimeoutMs},async response=>{
   if(!response.ok){let value;try{value=await response.json();}catch{/* HTML denials must preserve the HTTP status. */}const code=value?.code||(response.status===401?'SESSION_REQUIRED':undefined),error=Object.assign(new Error(errors[code]||(response.status===401?'Tu sesión terminó. Volvé a ingresar.':response.status===403||['WORKSPACE_CONTEXT_CHANGED','WORKSPACE_PROJECT_UNAVAILABLE'].includes(code)?'Tu acceso cambió. Volvé a consultar cuando se restablezca.':'No se pudo confirmar la operación. Comprobá el estado antes de repetirla.')),{status:response.status,code});
    let officeAssignment=false;if(options.method==='POST'){try{officeAssignment=JSON.parse(options.body)?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION;}catch{/* The server rejects malformed commands. */}}if(officeAssignment)error.result=value;
    // A dispatched denial may follow a committed invitation or KYC write.
    // Resolve the consume without a receipt; the journal must retain its reference.
    if(options.method==='POST'&&(accessDenied(error)||officeAssignment&&!participantOfficePrecommitRejected(error))){retainedError=Object.assign(error,{retainAttempt:true});return undefined;}throw error;
   }
   const value=image?await response.blob():await response.json();
   try{return validate(value);}catch(error){if(options.method==='POST'){retainedError=Object.assign(error,{retainAttempt:true});return undefined;}throw error;}
  });
  if(retainedError)throw retainedError;
  return result;
 };
}
function refreshedDraft(draft,value,selectedAccount=null){
 const p=draft.payload,office=draft.action==='SET_OFFICE_ROLE',target=office?selectedAccount||value.existingAccounts?.find(row=>row.membershipId===p.membershipId):value.records?.find(row=>row.id===p.workerId);
 if(!target)return {allowed:false,description:value.nextCursor?'El registro no aparece en esta página. Consultá más participantes para buscarlo en el estado actualizado.':'El registro ya no está disponible con tu acceso vigente.'};
 let allowed=false;
 if(office)allowed=value.canManageOfficeRoles&&target.canChangeRole;
 else if(draft.action==='INVITE')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked||target.status==='INVITED'&&target.invitation?.state==='SENT'&&target.invitation.expired===true);
 else if(draft.action==='ASSIGN_EXISTING')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked)&&(selectedAccount?.membershipId===p.membershipId&&selectedAccount.status==='ACTIVE'||value.existingAccounts?.some(row=>row.membershipId===p.membershipId&&row.status==='ACTIVE'));
 else if(draft.action==='REVOKE')allowed=value.canManage&&target.active&&!['NOT_INVITED','REVOKED'].includes(target.status);
 else if(draft.action==='RESTORE_ACCESS')allowed=value.canManage&&target.active&&target.status==='REVOKED'&&target.accountLinked;
  else if(draft.action==='SET_FIELD_PERMISSIONS')allowed=value.canManage&&target.canManageFieldPermissions===true&&!target.self&&target.active&&target.status==='ACTIVE'&&target.accountLinked;
 else if(draft.action==='SUBMIT_KYC')allowed=target.self&&target.active&&target.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(target.kyc.status)&&value.privacyNotice.version===p.noticeVersion&&(!p.backConsent||participantDocumentBackNotice(value.documentBackNotice)?.version===p.backNoticeVersion&&participantDocumentBackNotice(value.documentBackNotice)?.sha256===p.backNoticeSha256);
 else if(draft.action==='REVIEW_KYC')allowed=value.canManage&&!target.self&&target.active&&target.status==='ACTIVE'&&target.kyc.status==='PENDING_REVIEW'&&target.kyc.submissionId===p.submissionId&&participantKycReviewImages(target.kyc);
  else if(draft.action==='PROCESS_KYC')allowed=value.canManage&&!target.self&&target.active&&target.status==='ACTIVE'&&target.kyc.status==='PENDING_REVIEW'&&target.kyc.submissionId===p.submissionId&&(target.kyc.ocrConsent?.allowed===true||target.kyc.biometricConsent?.allowed===true)&&!['RUNNING','EXTRACTED_UNVERIFIED','ADVISORY_UNREVIEWED'].includes(target.kyc.processing?.status);
 else if(draft.action==='PREPARE_KYC_CHAT')allowed=participantKycChatCapabilities(target,value.canManage,Date.now()).canPrepare;
  else if(draft.action==='CANCEL_KYC_CHAT'){const chat=participantKycChatCapabilities(target,value.canManage,Date.now());allowed=chat.canCancel&&chat.challenge.id===p.challengeId;}
 else if(['SEND_ONBOARDING_WHATSAPP','REVOKE_ONBOARDING_CONTACT'].includes(draft.action)){const delivery=participantOnboardingDeliveryView({context:{scope:value.scope,projectId:value.projectId,verified:true,now:Date.now()},snapshot:value,workerId:target.id});allowed=draft.action==='SEND_ONBOARDING_WHATSAPP'?delivery.canSend:delivery.canRevoke;}
 if(draft.sendWhatsApp){try{participantOnboardingWhatsAppConsent(value.onboardingContactNotice,true,draft.onboardingContactNotice);}catch{allowed=false;}}
 if(['INVITE','ASSIGN_EXISTING','RESTORE_ACCESS'].includes(draft.action)){const chat=participantKycChatCapabilities(target,value.canManage,Date.now());allowed=allowed&&chat.observed&&!['PENDING','CLAIMED'].includes(chat.challenge?.status);}
 return {allowed,revision:target.revision,description:office?'Rol vigente: '+target.roleLabel:'Participación: '+(labels[target.status]||target.status)+'. Identidad: '+(labels[target.kyc.status]||target.kyc.status)+'.'};
}
const localPhotoTarget=(projectId,scope,draft)=>draft?.action==='SUBMIT_KYC'?JSON.stringify([projectId,scope,draft.action,draft.payload.workerId,draft.payload.revision,draft.payload.noticeVersion,draft.payload.backConsent===true,draft.payload.backNoticeVersion,draft.payload.backNoticeSha256]):null;
export function ParticipantPanel(props){return <ParticipantPanelInner key={props.projectId+':'+props.scope} {...props}/>;}
function ParticipantPanelInner({projectId,scope,onPending,getSessionToken,channelSnapshot=null,onNavigate,presentation}){
 // Presentation changes copy only. The server snapshot owns every permission.
 const ownIdentityPresentation=presentation==='own-identity';
 const api=useParticipantRequest(getSessionToken);
 const [localRead,setLocalRead]=useState(null),[data,setData]=useState(null),[networkBusy,setBusy]=useState(false),[notice,setNotice]=useState(''),[draft,setDraft]=useState(null),[attempt,setAttempt]=useState(null),[receipt,setReceipt]=useState(null),[images,setImages]=useState({}),[recoveryRecord,setRecoveryRecord]=useState(null),[revisionReview,setRevisionReview]=useState(null),[accessBlocked,setAccessBlocked]=useState(false),[retryAllowed,setRetryAllowed]=useState(false);
 const [accountBusy,setAccountBusy]=useState(false),[directoryBusy,setDirectoryBusy]=useState(false),[accountSelection,setAccountSelection]=useState(null),[accountGeneration,setAccountGeneration]=useState(0);
 const [officeSelection,setOfficeSelection]=useState(null);
 const accountRequest=useRef({epoch:0,controller:null}),directoryPending=useCallback(value=>setDirectoryBusy(value),[]);
 const busy=networkBusy||Boolean(localRead)||accountBusy||directoryBusy;
 const [selectedId,setSelectedId]=useState(null),[durableReference,setDurableReference]=useState(null),[recoveryReady,setRecoveryReady]=useState(false),[consultationClosed,setConsultationClosed]=useState(false);
 const editor=useRef(null),profile=useRef(null),profileFocus=useRef(null),[clock,setClock]=useState(()=>Date.now());
 const editingKey=draft?draft.action+':'+draft.payload.workerId:null;
 const [chatChallenge,setChatChallenge]=useState(null),[bankPending,setBankPending]=useState({}),[intakePending,setIntakePending]=useState(false);
 useEffect(()=>{if(!data)return;const timer=setInterval(()=>{const now=Date.now();setClock(now);if(Number.isFinite(now))setChatChallenge(value=>value?.code&&Number.isFinite(Date.parse(value.expiresAt))&&now>=Date.parse(value.expiresAt)?{...value,code:undefined,expired:true}:value);},1000);return()=>clearInterval(timer);},[data]);
 const onBankPending=useCallback((workerId,value)=>setBankPending(prior=>prior[workerId]===value?prior:{...prior,[workerId]:value}),[]),hasBankPending=Object.values(bankPending).some(Boolean);
 const alive=useRef(true),sequence=useRef(0),fileSequence=useRef(0),urls=useRef([]),fileRead=useRef(null),committedFileTarget=useRef(null);
 useLayoutEffect(()=>{alive.current=true;const allocatedUrls=urls.current,localSequence=fileSequence,accountRead=accountRequest.current;return()=>{alive.current=false;profileFocus.current=null;localSequence.current++;fileRead.current?.cancel(null);accountRead.epoch++;accountRead.controller?.abort();allocatedUrls.forEach(url=>URL.revokeObjectURL(url));};},[]);
 useLayoutEffect(()=>{const target=localPhotoTarget(projectId,scope,draft);committedFileTarget.current=target;if(fileRead.current&&fileRead.current.target!==target){fileSequence.current++;fileRead.current.cancel(null);}},[projectId,scope,draft]);
 useEffect(()=>{onPending?.(busy||!consultationClosed&&Boolean(attempt)||Boolean(draft)||hasBankPending||intakePending);return()=>onPending?.(false);},[busy,attempt,draft,consultationClosed,hasBankPending,intakePending,onPending]);
 useEffect(()=>{let current=true;const read=async()=>{try{const refs=await browserRecoveryJournal.list(scope);if(current){setDurableReference(refs.find(ref=>ref.projectId===projectId&&ref.resource==='participants'&&!PRIVATE_BANK_ACTIONS.includes(ref.action)&&!PARTICIPANT_INTAKE_RECOVERY_ACTIONS.includes(ref.action))||null);setRecoveryReady(true);}}catch{if(current){setRecoveryReady(false);setNotice('No se pudieron comprobar las referencias pendientes. Consultá tu acceso antes de guardar.');}}};read();window.addEventListener(RECOVERY_EVENT,read);window.addEventListener('focus',read);return()=>{current=false;window.removeEventListener(RECOVERY_EVENT,read);window.removeEventListener('focus',read);};},[projectId,scope]);
 useEffect(()=>{if(editingKey){editor.current?.focus({preventScroll:true});editor.current?.scrollIntoView({block:'nearest',behavior:'auto'});}},[editingKey]);
 useEffect(()=>{
  const ticket=profileFocus.current;if(!ticket||busy||draft||attempt||durableReference||hasBankPending||intakePending)return;
  profileFocus.current=null;
  if(!alive.current||accessBlocked||ticket.sequence!==sequence.current||ticket.scope!==scope||ticket.projectId!==projectId||selectedId!==ticket.workerId||data?.scope!==scope||data?.projectId!==projectId||data?.participantFocus?.workerId!==ticket.workerId||data.records.filter(row=>row.id===ticket.workerId).length!==1||!profile.current)return;
  profile.current.focus({preventScroll:true});profile.current.scrollIntoView({block:'start',behavior:'auto'});
 },[data,selectedId,busy,draft,attempt,durableReference,hasBankPending,intakePending,accessBlocked,scope,projectId]);
 useEffect(()=>{if(!draft&&!attempt)return;const warn=event=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft,attempt]);
 function scoped(value,snapshot=false){if(value?.scope!==scope||(snapshot?value?.projectId!==projectId||!Array.isArray(value?.records):value?.projectId!==undefined&&value.projectId!==projectId))throw changedContext();return value;}
 function outcome(value,command){scoped(value);if(command.action===PARTICIPANT_OFFICE_ASSIGN_ACTION){if(participantOfficeReceiptOutcome(value,command,command)?.state!=='RECORDED')throw changedContext();return value;}const matches=command.action==='SET_OFFICE_ROLE'?value.account?.membershipId===command.payload.membershipId:value.participant?.id===(command.payload?.workerId||command.workerId);if(!matches||value.saved!==true||typeof value.receiptId!=='string'||!value.receiptId)throw changedContext();if(command.backConsent===true&&!participantKycHistoricalReceipt(value,command)&&(!participantKycReviewImages(value.participant?.kyc)||value.participant.kyc.documentBackConsent.noticeVersion!==command.backNoticeVersion||value.participant.kyc.documentBackConsent.noticeSha256!==command.backNoticeSha256))throw changedContext();if(command.action==='PREPARE_KYC_CHAT'&&(value.kind!=='PREPARE_KYC_CHAT'||!Number.isFinite(Date.parse(value.expiresAt))||typeof value.codeUnavailable!=='boolean'||!value.codeUnavailable&&!/^IDENTIDAD [A-Za-z0-9_-]{43}$/.test(value.code||'')||value.codeUnavailable&&value.code!==undefined))throw changedContext();return value;}
 function recovered(value,command){scoped(value);if(command.action===PARTICIPANT_OFFICE_ASSIGN_ACTION){if(!participantOfficeReceiptOutcome(value,command,command))throw changedContext();return value;}if(value.state==='RECORDED')return outcome(value,command);if(value.definitive!==false||value.saved===true||value.receiptId||value.receipt)throw changedContext();if(value.state==='NOT_OBSERVED')return value;if(value.state==='PROCESSING'&&command.action==='PROCESS_KYC'&&value.workerId===command.payload.workerId&&value.submissionId===command.payload.submissionId&&Number.isFinite(Date.parse(value.expiresAt))&&typeof value.retryAfterExpiration==='boolean')return value;if(value.state==='INVITATION_UNCONFIRMED'&&command.action==='INVITE'&&value.participant?.id===command.payload.workerId&&/^invite_[a-f0-9]{32}$/.test(value.participant.invitation?.id||''))return value;throw changedContext();}
 const operationResult=(value,command)=>command.action==='PROCESS_KYC'&&value.state==='PROCESSING'?recovered(value,command):outcome(value,command);
 async function acceptResult(value,command){if(value.state==='PROCESSING'){setDraft(null);setRetryAllowed(value.retryAfterExpiration);setNotice(value.retryAfterExpiration?'La lectura anterior no tiene resultado confirmado. Podés reintentar exactamente esta solicitud.':'El análisis está en curso. Comprobá el mismo intento; no se envió otro documento.');}else await confirm(value,command);}
 function invalidateAccountSelection(){accountRequest.current.epoch++;accountRequest.current.controller?.abort();accountRequest.current.controller=null;setAccountBusy(false);setAccountSelection(null);setOfficeSelection(null);setDraft(prior=>prior?.action==='ASSIGN_EXISTING'?{...prior,payload:{...prior.payload,membershipId:''}}:prior?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?{...prior,payload:{...prior.payload,clerkUserId:'',expectedProofDigest:'',confirmOfficePermissions:false}}:prior);}
 function hideDenied(error){if(!accessDenied(error))return false;profileFocus.current=null;sequence.current++;invalidateAccountSelection();fileSequence.current++;fileRead.current?.cancel(null);urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});setData(null);setDraft(null);setRevisionReview(null);setRecoveryRecord(null);setReceipt(null);setChatChallenge(null);setAccessBlocked(true);setRetryAllowed(false);setBusy(false);return true;}
 function hideAccountDenied(error){if(!participantAccountReadDenied(error))return false;const hidden=hideDenied(accessDenied(error)?error:Object.assign(new Error(error.message),{status:error.status,code:'WORKSPACE_CONTEXT_CHANGED'}));if(hidden)setNotice(error.message);return hidden;}
 function beginOfficeAccount(){if(busy||attempt||durableReference||!recoveryReady||draft||accessBlocked||hasBankPending||intakePending||!data?.canManageOfficeRoles||!data.canInvite)return;invalidateAccountSelection();setDraft({action:PARTICIPANT_OFFICE_ASSIGN_ACTION,payload:{email:'',clerkUserId:'',expectedProofDigest:'',role:'',reason:'',confirmOfficePermissions:false}});setReceipt(null);setNotice('Consultá el correo exacto de una cuenta que aceptó la invitación de Clerk.');}
 async function consultOfficeAccount({keepConfirmation=false}={}){
  if(networkBusy||attempt||durableReference||!recoveryReady||accessBlocked||hasBankPending||intakePending||draft?.action!==PARTICIPANT_OFFICE_ASSIGN_ACTION)return null;
  let email;try{email=participantOfficeEmail(draft.payload.email);}catch(error){setNotice(error.message);return null;}
  const prior=officeSelection?.row?.email===email?officeSelection:null,owner=accountRequest.current;owner.epoch++;owner.controller?.abort();const current=owner.epoch,context=sequence.current,controller=new AbortController();owner.controller=controller;
  setAccountBusy(true);setOfficeSelection(prior?{...prior,verified:false,confirmed:false}:null);setDraft(previous=>previous?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?{...previous,payload:{...previous.payload,confirmOfficePermissions:false}}:previous);
  try{
   const row=await api({projectId,scope,detail:'verified-office-account',email},{signal:controller.signal},endpoint,false,value=>participantOfficeSnapshot(value,{scope,projectId,email}));
   if(!alive.current||context!==sequence.current||current!==owner.epoch)return null;
   const ready=row.state==='READY',same=Boolean(prior&&participantOfficeSelectionStamp(prior.row)===participantOfficeSelectionStamp(row)),confirmed=keepConfirmation&&ready&&same&&prior.verified&&prior.confirmed;
   setOfficeSelection({row,verified:ready,confirmed});setDraft(previous=>previous?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?{...previous,payload:{...previous.payload,email,clerkUserId:ready?row.account.clerkUserId:'',expectedProofDigest:ready?row.account.proofDigest:'',confirmOfficePermissions:confirmed}}:previous);
   setNotice(keepConfirmation&&ready&&!confirmed?'La cuenta o su pertenencia cambió. Revisá la identidad vigente y confirmá otra vez.':participantOfficeStateMessage(row));return {row,confirmed};
  }catch(error){if(!alive.current||context!==sequence.current||current!==owner.epoch)return null;setOfficeSelection(null);setDraft(previous=>previous?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?{...previous,payload:{...previous.payload,clerkUserId:'',expectedProofDigest:'',confirmOfficePermissions:false}}:previous);if(!hideDenied(error))setNotice(error.status===503?'No se pudo comprobar Clerk. Conservamos el correo y el fundamento; volvé a consultar antes de confirmar.':error.message);else setNotice(error.message);return null;}
  finally{if(alive.current&&current===owner.epoch){owner.controller=null;setAccountBusy(false);}}
 }
 async function consultAccount(membershipId,action,{keepConfirmation=false}={}){
  if(networkBusy||attempt||durableReference||!recoveryReady||accessBlocked||hasBankPending||intakePending)return null;
  const prior=accountSelection?.account?.membershipId===membershipId?accountSelection:null;
  const owner=accountRequest.current;owner.epoch++;owner.controller?.abort();const current=owner.epoch,context=sequence.current,controller=new AbortController();owner.controller=controller;
  setAccountBusy(true);setAccountSelection(prior?{...prior,verified:false,confirmed:false}:null);
  if(action==='ASSIGN_EXISTING')setDraft(value=>value?.action===action?{...value,payload:{...value.payload,membershipId}}:value);
  try{
   const value=await api({projectId,scope,detail:'existing-accounts',accountId:membershipId},{signal:controller.signal},endpoint,false,value=>participantAccountPage(value,{scope,projectId,accountId:membershipId}));
   if(!alive.current||context!==sequence.current||current!==owner.epoch)return null;
   const account=value.existingAccounts[0],allowed=participantAccountSelectionAllowed(action,account,value),same=Boolean(prior&&participantAccountStamp(prior.account)===participantAccountStamp(account)),confirmed=keepConfirmation&&same&&prior.verified&&prior.confirmed&&allowed;
   setData(previous=>previous?{...previous,canInvite:value.canInvite,canManageOfficeRoles:value.canManageOfficeRoles}:previous);
   setAccountSelection({account,verified:allowed,confirmed});
   if(action==='SET_OFFICE_ROLE'&&allowed)setDraft(previous=>previous?.action===action&&previous.payload.membershipId===membershipId?{...previous,accountName:account.name,payload:{...previous.payload,...(!revisionReview?{revision:account.revision}:{})}}:previous?previous:{action,payload:{membershipId,revision:account.revision,role:account.role,reason:''},accountName:account.name});
   if(!allowed)setNotice('Esta cuenta ya no permite la decisión elegida. Conservamos tu fundamento; consultá el permiso vigente antes de continuar.');
   else if(keepConfirmation&&!confirmed)setNotice('La cuenta o sus permisos cambiaron. Revisá el estado vigente y volvé a confirmar; conservamos tu fundamento y el rol elegido.');
   else if(!keepConfirmation)setNotice('Cuenta vigente consultada. Revisá su nombre, correo y permisos antes de confirmar.');
   return {account,value,confirmed};
  }catch(error){if(!alive.current||context!==sequence.current||current!==owner.epoch)return null;if(!hideAccountDenied(error)){if(error.status===404){setAccountSelection(null);setAccountGeneration(generation=>generation+1);setData(previous=>previous?{...previous,existingAccounts:previous.existingAccounts.filter(row=>row.membershipId!==membershipId)}:previous);setDraft(previous=>previous?.action==='ASSIGN_EXISTING'?{...previous,payload:{...previous.payload,membershipId:''}}:previous?.action==='SET_OFFICE_ROLE'?{...previous,accountName:''}:previous);setNotice('La cuenta ya no está disponible. Conservamos tu fundamento; buscá una cuenta vigente antes de continuar.');}else setNotice('No se pudo comprobar la cuenta. Conservamos tu fundamento y el rol elegido. Volvé a comprobarla antes de confirmar.');}else setNotice(error.message);return null;}
  finally{if(alive.current&&current===owner.epoch){owner.controller=null;setAccountBusy(false);}}
 }
 async function load(append=false,fullList=false){
  if(busy||attempt||hasBankPending||intakePending)return;
  setBusy(true);const current=++sequence.current,accountDraft=draft&&revisionReview&&['ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action);
  try{
   const query=!append&&!fullList&&data?.participantFocus?{projectId,scope,...data.participantFocus}:{projectId,scope,...(append&&data?.nextCursor?{after:data.nextCursor}:{})};
   const value=await api(query,{},endpoint,false,value=>scoped(value,true));
   if(query.intakeId&&(value.participantFocus?.workerId!==query.workerId||value.participantFocus?.intakeId!==query.intakeId))throw changedContext();
   let account=null;
   if(accountDraft){const accounts=await api({projectId,scope,detail:'existing-accounts',accountId:draft.payload.membershipId},{},endpoint,false,value=>participantAccountPage(value,{scope,projectId,accountId:draft.payload.membershipId}));account=accounts.existingAccounts[0];}
   if(!alive.current||current!==sequence.current)return;
   const fresh=append?{...value,records:[...data.records,...value.records]}:value;
   setAccessBlocked(false);setConsultationClosed(false);setData(fresh);setAccountGeneration(generation=>generation+1);
   if(fullList)setSelectedId(value.records.find(row=>row.active)?.id||value.records[0]?.id||null);
   setAccountSelection(account?{account,verified:participantAccountSelectionAllowed(draft.action,account,fresh),confirmed:false}:null);
   if(append)setSelectedId(draft?.payload.workerId||value.records.find(row=>row.active)?.id||value.records[0]?.id||null);
   if(draft&&revisionReview){setRevisionReview({state:'LOADED',...refreshedDraft(draft,fresh,account)});if(draft.action==='REVIEW_KYC'){urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});}setNotice('Consultamos el estado vigente. Tu borrador se conserva; revisá el cambio antes de continuar.');}
  }catch(error){
   if(!alive.current||current!==sequence.current)return;
   if(hideUnavailableFocus(error)|| (accountDraft?hideAccountDenied(error):hideDenied(error))){setNotice(error.message);return;}
   setAccountSelection(prior=>prior?{...prior,verified:false,confirmed:false}:prior);
   if(accountDraft&&error.status===404){setAccountSelection(null);setAccountGeneration(generation=>generation+1);setData(previous=>previous?{...previous,existingAccounts:previous.existingAccounts.filter(row=>row.membershipId!==draft.payload.membershipId)}:previous);setDraft(previous=>previous?.action==='SET_OFFICE_ROLE'?{...previous,accountName:''}:previous);setRevisionReview({state:'LOADED',allowed:false,description:'La cuenta ya no está disponible. Conservamos tu fundamento; cancelá esta decisión y buscá una cuenta vigente.'});}
   setNotice(error.message);
  }finally{if(alive.current&&current===sequence.current)setBusy(false);}
 }
 async function confirm(value,command){outcome(value,command);const current=sequence.current,office=command.action==='SET_OFFICE_ROLE',officeAssigned=command.action===PARTICIPANT_OFFICE_ASSIGN_ACTION;invalidateAccountSelection();setAccessBlocked(false);setRetryAllowed(false);setReceipt(value.receiptId);setAttempt(null);setRecoveryRecord(null);setDraft(null);
  if(['PREPARE_KYC_CHAT','CANCEL_KYC_CHAT','SEND_ONBOARDING_WHATSAPP','REVOKE_ONBOARDING_CONTACT'].includes(command.action)||command.action==='INVITE'&&command.payload.whatsAppConsent)setData(prior=>prior?{...prior,records:prior.records.map(row=>row.id===command.payload.workerId?{...row,kycChatChallenge:undefined,onboardingDelivery:undefined,canSendOnboardingWhatsapp:undefined,canRevokeOnboardingContact:undefined}:row)}:prior);
  if(command.action==='PREPARE_KYC_CHAT')setChatChallenge({projectId,scope,workerId:command.payload.workerId,code:value.code,codeUnavailable:value.codeUnavailable,expiresAt:value.expiresAt});if(command.action==='CANCEL_KYC_CHAT')setChatChallenge(null);
  setNotice(value.kycSubmissionReceipt?.superseded===true?'El recibo original quedó confirmado. Hay una presentación más reciente; consultá su estado vigente para continuar.':officeAssigned?'La cuenta de oficina quedó incorporada con recibo. '+(command.payload.role==='DIRECTOR'?'Dirección gestiona todas las obras de la empresa.':'Los permisos aplican a esta obra asignada.')+' La lista muestra sus permisos vigentes.':command.action==='SET_FIELD_PERMISSIONS'?'Permisos de campo guardados con recibo. La identidad y la vinculación propia mantienen sus requisitos.':office?'El cambio de rol quedó registrado con recibo. La lista muestra el permiso vigente de la cuenta en la empresa.':command.action==='CANCEL_KYC_CHAT'?'Presentación por chat cerrada con recibo. Consultá el perfil vigente antes de preparar otro código.':command.action==='SEND_ONBOARDING_WHATSAPP'||command.action==='INVITE'&&command.payload.whatsAppConsent?'La solicitud quedó guardada con recibo. Consultá el seguimiento de WhatsApp; el envío, la entrega y la aceptación se comprueban por separado.':command.action==='REVOKE_ONBOARDING_CONTACT'?'Autorización de contacto retirada con recibo. Un mensaje ya aceptado por WhatsApp no puede retirarse desde esta acción.':'Operación guardada con recibo. La revisión humana y la habilitación de WhatsApp se acreditan por separado.');try{const readContext=value.participant?.id&&data?.participantFocus?.workerId===value.participant.id?{projectId,scope,...data.participantFocus}:{projectId,scope};const fresh=await api(readContext,{},endpoint,false,value=>scoped(value,true));if(readContext.intakeId&&(fresh.participantFocus?.workerId!==readContext.workerId||fresh.participantFocus?.intakeId!==readContext.intakeId))throw changedContext();if(alive.current&&current===sequence.current){setData(fresh);setAccountGeneration(generation=>generation+1);}}catch(error){if(alive.current&&current===sequence.current){if(hideUnavailableFocus(error))setNotice('El recibo quedó confirmado. La ficha ya no está disponible; consultá nuevamente los participantes.');else if(hideDenied(error))setNotice('El recibo quedó confirmado, pero tu acceso vigente ya no permite consultar esta obra.');else setNotice('El recibo está confirmado. Actualizá la lista para consultar el estado vigente.');}}}
 async function save(event){event.preventDefault();if(busy||accountRequest.current.controller||attempt||durableReference||!recoveryReady||!draft||revisionReview||accessBlocked||hasBankPending||intakePending)return;if(['ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action)){if(!accountSelection?.verified||!accountSelection.confirmed||accountSelection.account.membershipId!==draft.payload.membershipId){setNotice('Consultá la cuenta vigente y confirmá sus permisos antes de guardar.');return;}const checked=await consultAccount(draft.payload.membershipId,draft.action,{keepConfirmation:true});if(!checked?.confirmed)return;}if(draft.action==='CANCEL_KYC_CHAT'&&draft.payload.reason.trim().length<8){setNotice('Escribí un motivo de al menos 8 caracteres para cerrar esta presentación.');return;}
  if(draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION){if(!officeSelection?.verified||!officeSelection.confirmed||!draft.payload.role||!draft.payload.confirmOfficePermissions){setNotice('Consultá la cuenta aceptada en Clerk, elegí un rol y confirmá su alcance antes de guardar.');return;}const checked=await consultOfficeAccount({keepConfirmation:true});if(!checked?.confirmed)return;}
  let payload=draft.payload;
  if(draft.action==='SUBMIT_KYC'&&payload.backConsent===true){const current=participantDocumentBackNotice(data.documentBackNotice);if(!payload.back||!current||current.version!==payload.backNoticeVersion||current.sha256!==payload.backNoticeSha256){setNotice('Consultá el aviso vigente del dorso y revisá su fotografía, o retiralo para presentar sólo el frente y tu fotografía.');return;}}
  if(draft.action==='REVIEW_KYC'){const current=data.records.find(row=>row.id===payload.workerId);if(!participantKycReviewImages(current?.kyc)||current.kyc.images.some(image=>!images[imageKey(current,image)])){setNotice('Consultá todas las imágenes de esta presentación antes de registrar la revisión.');return;}}
  if(['SEND_ONBOARDING_WHATSAPP','REVOKE_ONBOARDING_CONTACT'].includes(draft.action)){const current=participantOnboardingDeliveryView({context:{scope,projectId,verified:!!data&&!accessBlocked,now:clock},snapshot:data,workerId:payload.workerId});if(draft.action==='SEND_ONBOARDING_WHATSAPP'?!current.canSend:!current.canRevoke){setNotice('Consultá el perfil vigente y el permiso para esta solicitud antes de continuar.');return;}}
  if(draft.action==='INVITE'||draft.action==='SEND_ONBOARDING_WHATSAPP'){try{const consent=participantOnboardingWhatsAppConsent(data.onboardingContactNotice,draft.sendWhatsApp,draft.onboardingContactNotice);if(draft.action==='SEND_ONBOARDING_WHATSAPP'&&!consent){setNotice('Confirmá la autorización de contacto de esta persona para solicitar el envío.');return;}payload={...payload,...(consent?{whatsAppConsent:consent}:{})};}catch(error){setNotice(error.message);return;}}
  const operationId=crypto.randomUUID(),command=draft.action==='SUBMIT_KYC'?{operationId,projectId,scope,...payload}:{operationId,projectId,scope,action:draft.action,payload};setAttempt(command);setRetryAllowed(false);setBusy(true);setNotice('');setReceipt(null);
  try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),requestTimeoutMs:['SUBMIT_KYC','PROCESS_KYC'].includes(draft.action)?55000:30000},endpoint,false,value=>operationResult(value,command));if(alive.current)await acceptResult(value,command);}catch(error){if(alive.current){const denied=hideDenied(error);if(!error.retainAttempt&&(error.requestDispatched===false||(command.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?participantOfficePrecommitRejected(error):error.status&&error.status<500))){setAttempt(null);if(command.action===PARTICIPANT_OFFICE_ASSIGN_ACTION)setOfficeSelection(prior=>prior?{...prior,verified:false,confirmed:false}:prior);if(error.code==='PARTICIPANT_REVISION_CHANGED'){setRevisionReview({state:'STALE'});setAccountSelection(prior=>prior?{...prior,verified:false,confirmed:false}:prior);}setNotice(error.message);}else setNotice(denied?error.message+' El resultado sigue sin confirmar. Comprobá el mismo intento cuando se restablezca tu acceso.':'El resultado quedó sin confirmar. Comprobá el recibo antes de volver a enviar.');}}finally{if(alive.current)setBusy(false);}}
 async function recover(){if(!attempt||busy)return;const current=sequence.current;setBusy(true);setRetryAllowed(false);try{
  if(attempt.action==='RECOVER_INVITATION'){const fresh=await api({projectId,scope},{},endpoint,false,value=>scoped(value,true));if(!alive.current||current!==sequence.current)return;const target=fresh.records.find(row=>row.id===attempt.payload.workerId);if(target?.invitation?.id!==attempt.payload.invitationId)throw changedContext();const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt)},endpoint,false,value=>outcome(value,attempt));if(alive.current&&current===sequence.current)await confirm(value,attempt);return;}
   const value=await api({projectId,scope,operationId:attempt.operationId,...(attempt.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?{action:attempt.action}:{})},{},endpoint,false,value=>recovered(value,attempt));if(!alive.current||current!==sequence.current)return;
  if(value.state==='RECORDED')await confirm(value,attempt);
  else if(value.state==='PROCESSING'){setAccessBlocked(false);await acceptResult(value,attempt);}
  else if(value.state==='INVITATION_UNCONFIRMED'){setAccessBlocked(false);if(value.participant.status==='REVOKED'){setAttempt(null);setDraft(null);setRecoveryRecord(null);setNotice('La participación quedó revocada. No se volvió a enviar la invitación.');return;}setRecoveryRecord(value.participant);const lookedUp=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:value.participant.id,invitationId:value.participant.invitation.id}})},endpoint,false,value=>outcome(value,attempt));if(!alive.current||current!==sequence.current)return;const recorded=await api({projectId,scope,operationId:attempt.operationId},{},endpoint,false,value=>recovered(value,attempt));if(!alive.current||current!==sequence.current)return;if(recorded.state!=='RECORDED'||recorded.receiptId!==lookedUp.receiptId)throw changedContext();await confirm(recorded,attempt);}
  else{setAccessBlocked(false);setRetryAllowed(!['INVITE','SEND_ONBOARDING_WHATSAPP'].includes(attempt.action));setNotice('Todavía no se observa un recibo. No se repitió la operación ni se declaró perdida.');}
 }catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function retryExact(){if(!attempt||busy||['INVITE','SEND_ONBOARDING_WHATSAPP'].includes(attempt.action)||accessBlocked||!retryAllowed)return;setBusy(true);setRetryAllowed(false);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt),requestTimeoutMs:attempt.front||attempt.action==='PROCESS_KYC'?55000:30000},endpoint,false,value=>operationResult(value,attempt));if(alive.current)await acceptResult(value,attempt);}catch(error){if(alive.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 async function revokeUncertain(){if(busy||hasBankPending||intakePending||!recoveryRecord||accessBlocked)return;const previous=attempt,command={operationId:crypto.randomUUID(),projectId,scope,action:'REVOKE',payload:{workerId:recoveryRecord.id,revision:recoveryRecord.revision,reason:'El administrador revocó explícitamente una invitación cuyo envío no se pudo confirmar.'}};setAttempt(command);setRetryAllowed(false);setRecoveryRecord(null);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},endpoint,false,value=>outcome(value,command));if(alive.current)await confirm(value,command);}catch(error){if(alive.current){const denied=hideDenied(error);if(!error.retainAttempt&&(error.requestDispatched===false||error.status&&error.status<500)){setAttempt(previous);if(!denied)setRecoveryRecord(recoveryRecord);}setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 function begin(action,row){if(busy||attempt||durableReference||!recoveryReady||hasBankPending||intakePending||accessBlocked)return;const chat=participantKycChatCapabilities(row,data?.canManage,clock);if(action==='PREPARE_KYC_CHAT'&&!chat.canPrepare||action==='CANCEL_KYC_CHAT'&&!chat.canCancel||['INVITE','RESTORE_ACCESS'].includes(action)&&(!chat.observed||['PENDING','CLAIMED'].includes(chat.challenge?.status))){setNotice('Consultá la presentación vigente antes de preparar o cerrar un código.');return;}
  if(['SEND_ONBOARDING_WHATSAPP','REVOKE_ONBOARDING_CONTACT'].includes(action)){const delivery=participantOnboardingDeliveryView({context:{scope,projectId,verified:!!data&&!accessBlocked,now:clock},snapshot:data,workerId:row.id});if(action==='SEND_ONBOARDING_WHATSAPP'?!delivery.canSend:!delivery.canRevoke){setNotice('Consultá el perfil vigente para comprobar la autorización de contacto.');return;}}
  if(action==='SET_FIELD_PERMISSIONS'&&(!data.canManage||row.canManageFieldPermissions!==true||row.self)){setNotice('Otra persona responsable debe revisar estos permisos desde el perfil vigente.');return;}
  setSelectedId(row.id);fileSequence.current++;fileRead.current?.cancel(null);setChatChallenge(null);setDraft({action,...(['INVITE','SEND_ONBOARDING_WHATSAPP'].includes(action)?{sendWhatsApp:false,onboardingContactNotice:participantOnboardingContactNotice(data.onboardingContactNotice)}:{}),payload:action==='SET_FIELD_PERMISSIONS'?{workerId:row.id,revision:row.revision,permissions:{...row.permissions},reason:''}:action==='INVITE'?{workerId:row.id,revision:row.revision,email:''}:['PREPARE_KYC_CHAT','SEND_ONBOARDING_WHATSAPP','REVOKE_ONBOARDING_CONTACT'].includes(action)?{workerId:row.id,revision:row.revision}:action==='CANCEL_KYC_CHAT'?{workerId:row.id,revision:row.revision,challengeId:chat.challenge.id,reason:''}:['REVOKE','RESTORE_ACCESS'].includes(action)?{workerId:row.id,revision:row.revision,reason:''}:action==='PROCESS_KYC'?{workerId:row.id,revision:row.revision,submissionId:row.kyc.submissionId}:action==='REVIEW_KYC'?{workerId:row.id,revision:row.revision,submissionId:row.kyc.submissionId,decision:'APPROVED',reason:''}:{workerId:row.id,revision:row.revision,noticeVersion:data.privacyNotice.version,consent:false,front:'',selfie:'',...(data.externalOcrNotice?{ocrConsent:false,ocrNoticeVersion:data.externalOcrNotice.version}:{}),...(data.privateBiometricNotice?{biometricConsent:false,biometricNoticeVersion:data.privateBiometricNotice.version}:{})}});setNotice('');setReceipt(null);}
 async function inviteIntake(application){
  if(busy||attempt||durableReference||!recoveryReady||draft||accessBlocked||hasBankPending||intakePending)return;
  const query=employeeIntakeInvitationQuery(application,{projectId,scope});if(!query)return;
  setBusy(true);const current=sequence.current;
  try{
   const fresh=await api(query,{},endpoint,false,value=>scoped(value,true));
   if(!alive.current||current!==sequence.current)return;
   const preparation=employeeIntakeInvitationPreparation(fresh,application,{projectId,scope,now:clock});if(!preparation)throw changedContext();
   clearPersonRam();setData(fresh);setSelectedId(preparation.workerId);
   if(preparation.canPrepare){
    setDraft({action:'INVITE',sendWhatsApp:false,onboardingContactNotice:participantOnboardingContactNotice(fresh.onboardingContactNotice),payload:preparation.payload});
    setNotice('Ficha y correo declarado consultados. Revisá la invitación antes de enviarla; el correo se verificará al aceptar.');
   }else{profileFocus.current={workerId:preparation.workerId,scope,projectId,sequence:current};setNotice('Ficha vigente consultada. Revisá el próximo paso del perfil; no se preparó otra invitación.');}
  }catch(error){if(alive.current&&current===sequence.current){if(!hideUnavailableFocus(error))hideDenied(error);setNotice(error.message);}}
  finally{if(alive.current&&current===sequence.current)setBusy(false);}
 }
 function edit(key,value){if(draft?.action===PARTICIPANT_OFFICE_ASSIGN_ACTION&&key==='email')invalidateAccountSelection();if(key==='role'){setAccountSelection(prior=>prior?{...prior,confirmed:false}:prior);setOfficeSelection(prior=>prior?{...prior,confirmed:false}:prior);}setDraft(prior=>prior?{...prior,payload:{...prior.payload,[key]:value,...(prior.action===PARTICIPANT_OFFICE_ASSIGN_ACTION&&['email','role'].includes(key)?{confirmOfficePermissions:false}:{})}}:prior);}
 function chooseDocumentBack(confirmed){
  if(!draft||draft.action!=='SUBMIT_KYC'||busy)return;
  const current=participantDocumentBackNotice(data?.documentBackNotice);if(confirmed&&!current)return;
  fileSequence.current++;fileRead.current?.cancel(null);
  setDraft(prior=>{if(!prior)return prior;const payload={...prior.payload};for(const key of ['back','backConsent','backNoticeVersion','backNoticeSha256'])delete payload[key];return {...prior,payload:{...payload,...(confirmed?{back:'',backConsent:true,backNoticeVersion:current.version,backNoticeSha256:current.sha256}:{})}};});
 }
 function chooseWhatsAppInstructions(confirmed){if(!draft)return;const next={...draft,sendWhatsApp:confirmed,onboardingContactNotice:participantOnboardingContactNotice(data?.onboardingContactNotice)};setDraft(next);if(revisionReview?.state==='LOADED')setRevisionReview({state:'LOADED',...refreshedDraft(next,data)});}
 function changeOfficeRole(membershipId){if(busy||attempt||durableReference||!recoveryReady||draft||accessBlocked||hasBankPending||intakePending)return;setNotice('');setReceipt(null);consultAccount(membershipId,'SET_OFFICE_ROLE');}
 function assignExisting(row){if(busy||attempt||durableReference||!recoveryReady||draft||accessBlocked||hasBankPending||intakePending)return;const chat=participantKycChatCapabilities(row,data?.canManage,clock);if(!chat.observed||['PENDING','CLAIMED'].includes(chat.challenge?.status)){setNotice('Consultá y cerrá la presentación pendiente antes de cambiar la participación.');return;}invalidateAccountSelection();setDraft({action:'ASSIGN_EXISTING',payload:{workerId:row.id,revision:row.revision,membershipId:'',reason:''}});setNotice('');setReceipt(null);}
 async function chooseFile(key,file,{signal}={}){
  const current=++fileSequence.current;fileRead.current?.cancel(null);setNotice('');
  if(!file){edit(key,'');return false;}if(signal?.aborted)return false;
  if(file.size>KYC_PHOTO_LIMIT||!['image/png','image/jpeg','image/webp'].includes(file.type)){setNotice('Elegí JPEG, PNG o WebP de hasta 1 MiB por imagen.');return false;}
  const target=localPhotoTarget(projectId,scope,draft);if(!target||committedFileTarget.current!==target)return false;
  const owner={id:current,target,cancel:null};setLocalRead({id:current});
  const result=await new Promise(resolve=>{
   let reader,timer,settled=false;
   const valid=()=>alive.current&&current===fileSequence.current&&committedFileTarget.current===target&&!signal?.aborted;
   const finish=(content,message)=>{
    if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',onSignalAbort);
    if(reader)reader.onload=reader.onerror=reader.onabort=null;
    if(fileRead.current===owner)fileRead.current=null;
    // Only this local read is released. The API busy state is never modified.
    if(alive.current)setLocalRead(prior=>prior?.id===current?null:prior);
    resolve({content,message});
   };
   owner.cancel=message=>{finish(null,message);if(reader?.readyState===1)try{reader.abort();}catch{/* The promise was already settled before aborting the resource. */}};
   const onSignalAbort=()=>owner.cancel(null);fileRead.current=owner;
   if(signal?.aborted){owner.cancel(null);return;}
   try{
    reader=new FileReader();
    reader.onload=()=>{const content=valid()&&fileRead.current===owner&&typeof reader.result==='string'?reader.result:null;finish(content,content?null:'No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');};
    reader.onerror=()=>finish(null,'No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');
    reader.onabort=()=>finish(null,'Lectura detenida. Conservamos esta copia y tu revisión. Podés volver a usarla.');
    signal?.addEventListener('abort',onSignalAbort,{once:true});
    timer=setTimeout(()=>owner.cancel('No se completó la lectura en 15 segundos. Conservamos la copia y tu revisión. Volvé a usarla o elegí otra fotografía.'),15000);
    reader.readAsDataURL(file);
   }catch{owner.cancel('No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');}
  });
  if(!alive.current||current!==fileSequence.current||committedFileTarget.current!==target||signal?.aborted)return false;
  if(result.content){edit(key,result.content);return true;}if(result.message)setNotice(result.message);return false;
 }
 async function viewImage(row,image){if(busy||attempt||hasBankPending||intakePending||accessBlocked)return;const current=sequence.current;setBusy(true);try{const blob=await api({projectId,scope,workerId:row.id,imageId:image.id},{},endpoint,true);if(!alive.current||current!==sequence.current)return;if(blob.size!==image.bytes||blob.type!==image.contentType)throw new Error('La imagen recibida no coincide con la presentación.');const url=URL.createObjectURL(blob);urls.current.push(url);setImages(prior=>({...prior,[imageKey(row,image)]:url}));}catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function recoverInvitation(row){if(busy||attempt||durableReference||!recoveryReady||draft||accessBlocked||hasBankPending||intakePending)return;const command={operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:row.id,invitationId:row.invitation.id}};setAttempt(command);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},endpoint,false,value=>outcome(value,command));if(alive.current)await confirm(value,command);}catch(error){if(alive.current){hideDenied(error);if(error.requestDispatched===false)setAttempt(null);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 const locked=busy||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||hasBankPending||intakePending,p=draft?.payload,reviewTarget=data?.records.find(row=>row.id===p?.workerId);
 const reviewImagesReady=draft?.action!=='REVIEW_KYC'||participantKycReviewImages(reviewTarget?.kyc)&&reviewTarget.kyc.images.every(image=>images[imageKey(reviewTarget,image)]);
 const selectedRow=data?.records.find(row=>row.id===selectedId)||data?.records[0];
 const onboardingContactNotice=participantOnboardingContactNotice(data?.onboardingContactNotice);
 const selectedDelivery=participantOnboardingDeliveryView({context:{scope,projectId,verified:!!data&&!accessBlocked,now:clock},snapshot:data,workerId:selectedRow?.id});
  const selectedChat=participantKycChatCapabilities(selectedRow,data?.canManage,clock);
 const participationChangeReady=selectedChat.observed&&!['PENDING','CLAIMED'].includes(selectedChat.challenge?.status);
 const nextStep=participantOnboardingNextStep({context:{scope,projectId,verified:!!data&&!accessBlocked,now:clock},snapshot:data,workerId:selectedRow?.id,channelSnapshot,pendingReference:attempt?{scope,projectId,resource:'participants',operationId:attempt.operationId}:durableReference});
 const primaryLabels={SET_FIELD_PERMISSIONS:'Revisar permisos de campo',INVITE:'Invitar a esta obra',RESTORE_ACCESS:'Revisar y reactivar participación',PREPARE_KYC_CHAT:'Preparar identidad por WhatsApp',CANCEL_KYC_CHAT:'Revisar cierre de presentación',REVIEW_KYC:'Registrar revisión humana',RECOVER_INVITATION:'Comprobar invitación en Clerk'};
 const progressCopy={WAIT_PERMISSIONS:'Tu participación es de consulta. Otra persona responsable puede revisar los permisos de jornada y reportes desde tu perfil.',FIELD_PERMISSIONS_REVIEW:'Esta persona tiene acceso de consulta y no puede registrar jornada ni reportes. Revisá sus permisos de campo; la identidad y el vínculo propio conservan sus comprobaciones.',ONBOARDING_WHATSAPP_PREPARATION:'Podés enviar las instrucciones privadas de alta con la autorización de contacto de esta persona.',ONBOARDING_TEMPLATE_REVIEW:'Las instrucciones siguen pendientes. Revisá la aprobación de la plantilla de alta y después consultá el estado de este mismo envío.',ONBOARDING_WHATSAPP_PENDING:'Las instrucciones están en seguimiento. Consultá el envío antes de preparar un código distinto.',WAIT_ACCOUNT:'La persona debe aceptar la invitación con su cuenta y correo verificado.',WAIT_REVIEW:'Otra persona autorizada debe revisar las imágenes.',IDENTITY_REVIEW:'Consultá todas las imágenes originales de esta presentación antes de decidir.',KYC_CHAT_PREPARATION:'Prepará el código y entregalo a esta persona. El envío y la revisión siguen pendientes.',KYC_CHAT_UNOBSERVED:'Consultá la presentación por chat antes de preparar o cerrar un código.',KYC_CHAT_PENDING:'Hay una presentación por chat pendiente. Consultá su estado antes de continuar.',KYC_CHAT_IN_PROGRESS:'La presentación por chat está en curso. Consultá su estado antes de continuar.',KYC_CHAT_CANCELLATION:'Podés revisar el cierre de esta presentación antes de preparar un código distinto.',CHANNEL_VERIFIED:'El vínculo está confirmado. Abrir el chat sólo prepara tu mensaje; no acredita entrega.',WAIT_OWN_CHANNEL:'La persona continúa desde su propia cuenta para vincular WhatsApp.',OPERATION_UNCERTAIN:'Comprobá el recibo original. No se envía otra operación automáticamente.'};
 function clearPersonRam({preserveReceipt=false}={}){profileFocus.current=null;invalidateAccountSelection();fileSequence.current++;fileRead.current?.cancel(null);urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});setDraft(null);setRevisionReview(null);setRecoveryRecord(null);if(!preserveReceipt)setReceipt(null);setChatChallenge(null);setRetryAllowed(false);}
 function hideUnavailableFocus(error){if(error.status!==404||error.code!=='PARTICIPANT_INTAKE_UNAVAILABLE')return false;clearPersonRam({preserveReceipt:true});setData(null);setSelectedId(null);return true;}
 function selectPerson(value){if(busy||attempt||hasBankPending||intakePending)return;sequence.current++;clearPersonRam();setSelectedId(value);setNotice('Perfil seleccionado. Los borradores y las imágenes anteriores se cerraron.');}
 function closeConsultation(){if(busy||hasBankPending||intakePending)return;sequence.current++;clearPersonRam();setAttempt(null);setData(null);setSelectedId(null);setConsultationClosed(true);setNotice('Consulta cerrada. La referencia pendiente se conserva; no se reenvía la operación.');}
 async function consultReference(){if(attempt)return recover();if(!durableReference||busy)return;const ref=durableReference,current=sequence.current;setBusy(true);try{const result=await api(null,{},recoveryQuery(ref),false,value=>{if(!recoveryResult(ref,value))throw changedContext();return value;});if(!alive.current||current!==sequence.current)return;setNotice(result.state==='RECORDED'?'Recibo confirmado. Consultá el perfil vigente antes de continuar.':'Todavía no se observa el recibo. Conservamos la referencia; no se repitió la operación.');if(result.state==='RECORDED'){clearPersonRam();setData(null);setDurableReference(null);}}catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 function nextAction(){const action=nextStep.primary?.action;if(action==='CONSULT_OPERATION')return consultReference();if(action==='REVIEW_ONBOARDING_TEMPLATE'){if(onNavigate)onNavigate({scope,projectId,workerId:selectedRow.id,target:'meta-onboarding'});else setNotice('Continuá en Conexión y plantillas para revisar la plantilla de alta de esta empresa. Después consultá el estado del mismo envío.');return;}if(['CONSULT_CHANNEL','REQUEST_CHALLENGE','OPEN_WHATSAPP'].includes(action)){onNavigate?.({scope,projectId,workerId:selectedRow.id,target:'worker-channel'});if(!onNavigate)setNotice('Continuá en Mi WhatsApp de obra y consultá tu vínculo. El número debe estar confirmado antes de abrir el chat.');return;}if(['CONSULT_PARTICIPANTS','CONSULT_ACCESS'].includes(action))return load();if(action==='RECOVER_INVITATION')return recoverInvitation(selectedRow);if(selectedRow)begin(action,selectedRow);}
 const primaryDisabled=busy||hasBankPending||intakePending||Boolean(draft)&&nextStep.primary?.action!=='CONSULT_OPERATION'||nextStep.primary?.action!=='CONSULT_OPERATION'&&(Boolean(attempt)||Boolean(durableReference)||!recoveryReady)||nextStep.primary?.action==='REVIEW_KYC'&&selectedRow.kyc.images.some(image=>!images[imageKey(selectedRow,image)]);
 return <section className={styles.panel} aria-labelledby="participant-title"><div className={styles.heading}><div><p className={styles.eyebrow}>{ownIdentityPresentation?'IDENTIDAD PRIVADA':'PERSONAS Y ACCESO'}</p><h3 id="participant-title" tabIndex={-1}>{ownIdentityPresentation?'Mi identidad':'Participantes y revisión de identidad'}</h3></div><button type="button" disabled={busy||Boolean(attempt)||hasBankPending||intakePending||Boolean(data&&draft)&&!revisionReview} onClick={()=>load()}>{revisionReview?'Actualizar registro conservando borrador':ownIdentityPresentation?'Consultar mi identidad':data?.participantFocus?'Actualizar esta ficha':'Consultar participantes'}</button></div>
  {data?.participantFocus&&<button type="button" disabled={locked||Boolean(draft)} onClick={()=>load(false,true)}>Volver a lista de participantes</button>}
  <p>{ownIdentityPresentation?'Presentá y consultá tu documentación privada para esta obra. Un responsable autorizado revisará tu identidad antes de habilitar el trabajo.':'Revisá cada perfil y su próximo paso. El acceso requiere cuenta verificada y la decisión de otra persona autorizada.'}</p><p role="status" aria-live="polite">{notice}</p>
  {accessBlocked&&<p>Ocultamos los datos y las imágenes de esta obra porque no pudimos confirmar tu acceso vigente.{attempt?' Conservamos el intento pendiente: comprobá su estado sin volver a enviarlo.':' Volvé a consultar cuando recuperes tu acceso.'}</p>}
  {data?.employeeIntake&&<EmployeeIntakePanel key={scope+':'+projectId} projectId={projectId} scope={scope} snapshot={data.employeeIntake} getSessionToken={getSessionToken} onPending={setIntakePending} onInvite={inviteIntake} canInvite={data.canInvite===true} disabled={busy||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||Boolean(draft)||hasBankPending||accessBlocked}/> }
  {data&&<><p>{data.canManage?'Invitaciones y participación de campo en esta obra. Los permisos de empresa se administran por separado.':'Tu participación en esta obra. Sólo podés presentar y consultar tu propia identidad.'}</p><label className={styles.personSelector}>Perfil de esta obra<select value={selectedRow?.id||''} disabled={busy||Boolean(attempt)||hasBankPending||intakePending} onChange={event=>selectPerson(event.target.value)}>{data.records.map(row=><option key={row.id} value={row.id}>{row.name}{row.self?' · Mi perfil':''}</option>)}</select></label><div className={styles.list}>{data.records.filter(row=>row.id===selectedRow?.id).map(row=><article key={row.id} ref={profile} tabIndex={-1} data-participant-profile={row.id} className={styles.card}><div className={styles.heading}><strong>{row.name}</strong><span>{labels[row.status]||row.status}</span></div><p>Identidad: {labels[row.kyc.status]||row.kyc.status}</p><div className={styles.nextStep} data-onboarding-step={nextStep.state}><p className={styles.eyebrow}>PRÓXIMO PASO</p>{progressCopy[nextStep.state]&&<p>{progressCopy[nextStep.state]}</p>}{nextStep.primary&&<button data-onboarding-primary type="button" disabled={primaryDisabled} onClick={nextAction}>{primaryLabels[nextStep.primary.action]||nextStep.primary.label}</button>}{nextStep.optionalBank&&<p className={styles.optional}>Cuenta bancaria privada: opcional, disponible sólo desde tu propio perfil.</p>}</div>{row.invitation&&<p>{labels[row.invitation.state]||row.invitation.state}{row.invitation.email?' · '+row.invitation.email:''}</p>}
    {row.kyc.review&&<p>Decisión registrada: {row.kyc.review.reason}</p>}
    {(onboardingContactNotice||row.onboardingDelivery!==undefined)&&<div className={styles.chatStatus} data-onboarding-delivery={selectedDelivery.state}><strong>Instrucciones por WhatsApp: {selectedDelivery.label}</strong><p>{selectedDelivery.description}</p>{selectedDelivery.observed&&selectedDelivery.contactAuthorized===false&&selectedDelivery.state!=='NOT_REQUESTED'&&<p>La autorización de contacto no está vigente.</p>}{selectedDelivery.revokeWarning&&<p>{selectedDelivery.revokeWarning}</p>}<div className={styles.actions}>{nextStep.primary?.action!=='SEND_ONBOARDING_WHATSAPP'&&selectedDelivery.canSend&&<button type="button" disabled={locked||Boolean(draft)} onClick={()=>begin('SEND_ONBOARDING_WHATSAPP',row)}>Solicitar instrucciones por WhatsApp</button>}{selectedDelivery.canRevoke&&<button type="button" disabled={locked||Boolean(draft)} onClick={()=>begin('REVOKE_ONBOARDING_CONTACT',row)}>Retirar autorización de contacto</button>}<button type="button" disabled={busy||Boolean(attempt)||hasBankPending||intakePending||Boolean(draft)} onClick={()=>load()}>Consultar estado del envío</button></div></div>}
    {row.kyc.status==='PENDING_ACCOUNT_CLAIM'&&<p>La persona debe aceptar su invitación con el correo verificado antes de que un responsable pueda aprobar estas imágenes. La presentación por chat no concede acceso.</p>}
    {!['PREPARE_KYC_CHAT','INVITE','RESTORE_ACCESS','SEND_ONBOARDING_WHATSAPP'].includes(nextStep.primary?.action)&&!['ONBOARDING_WHATSAPP_PENDING','ONBOARDING_TEMPLATE_REVIEW'].includes(nextStep.state)&&selectedChat.canPrepare&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('PREPARE_KYC_CHAT',row)}>Preparar identidad por WhatsApp</button>}
     {selectedChat.challenge&&<div className={styles.chatStatus}><strong>Presentación por WhatsApp: {selectedChat.challenge.status==='PENDING'?'código preparado':selectedChat.challenge.status==='CLAIMED'?'en curso':selectedChat.challenge.status==='COMPLETED'?'guardada':'cerrada'}</strong><p>Vencimiento del código: {new Date(selectedChat.challenge.expiresAt).toLocaleString('es-AR')}.{selectedChat.challenge.expired&&' El plazo está vencido; no se preparará otro código automáticamente.'}</p>{selectedChat.challenge.conversationExpiresAt&&<p>Plazo de la conversación: {new Date(selectedChat.challenge.conversationExpiresAt).toLocaleString('es-AR')}.</p>}{['PENDING','CLAIMED'].includes(selectedChat.challenge.status)&&selectedChat.challenge.blockedCode==='PARTICIPANT_KYC_CHAT_ISSUER_REQUIRED'&&<p>El cierre de esta presentación requiere al responsable que preparó el código. Pedile que consulte la presentación vigente y revise su cierre si corresponde.</p>}{nextStep.primary?.action!=='CANCEL_KYC_CHAT'&&selectedChat.canCancel&&<button type="button" disabled={locked||Boolean(draft)} onClick={()=>begin('CANCEL_KYC_CHAT',row)}>Revisar cierre de presentación</button>}</div>}
    {row.kyc.processing?.status==='RUNNING'&&<p>Análisis asistido en curso. La identidad continúa pendiente de revisión.</p>}
    {row.kyc.processing?.status==='FAILED_RETRYABLE'&&<p>No se confirmó el análisis asistido. Conservamos las imágenes; podés continuar con la revisión manual.</p>}
    {data.canManage&&row.kyc.processing?.biometrics&&<div className={styles.evidence}><strong>Comparación facial asistida</strong>{row.kyc.processing.biometrics.status==='ADVISORY_UNREVIEWED'?<><p>Similitud facial orientativa: {row.kyc.processing.biometrics.faceSimilarity.toFixed(3)}</p><p>Señal orientativa de captura: {row.kyc.processing.biometrics.captureRiskSignal.toFixed(3)}</p></>:<p>No se confirmó el análisis. Conservamos la revisión manual.</p>}<p>Prueba de vida no verificada. Estas señales no están calibradas para aprobar identidades y no acreditan autenticidad del documento.</p></div>}
    {data.canManage&&row.kyc.processing?.status==='EXTRACTED_UNVERIFIED'&&row.kyc.processing.fields&&<div className={styles.evidence}><strong>Texto extraído sin verificar</strong><p>Nombre: {row.kyc.processing.fields.nombreCompleto}</p><p>DNI: {row.kyc.processing.fields.dni}</p><p>CUIL: {row.kyc.processing.fields.cuil||'No se pudo leer'}</p><p>Compará estos datos con el documento original. La lectura no acredita autenticidad, biometría ni prueba de vida.</p></div>}
    {data.canManage&&!row.self&&row.active&&row.status==='ACTIVE'&&row.kyc.status==='PENDING_REVIEW'&&(row.kyc.ocrConsent?.allowed===true||row.kyc.biometricConsent?.allowed===true)&&!['RUNNING','EXTRACTED_UNVERIFIED','ADVISORY_UNREVIEWED'].includes(row.kyc.processing?.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('PROCESS_KYC',row)}>{row.kyc.ocrConsent?.allowed===true?'Preparar lectura asistida':'Preparar comparación facial'}</button>}
    <details className={styles.options}><summary>Más opciones de este perfil</summary><div className={styles.actions}>{nextStep.primary?.action!=='SET_FIELD_PERMISSIONS'&&data.canManage&&row.canManageFieldPermissions===true&&!row.self&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('SET_FIELD_PERMISSIONS',row)}>Revisar permisos de campo</button>}{nextStep.primary?.action!=='INVITE'&&participationChangeReady&&data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked)||(row.status==='INVITED'&&row.invitation?.state==='SENT'&&row.invitation.expired===true))&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('INVITE',row)}>Invitar a esta obra</button>}{nextStep.primary?.action!=='RESTORE_ACCESS'&&participationChangeReady&&data.canManage&&row.active&&row.status==='REVOKED'&&row.accountLinked&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('RESTORE_ACCESS',row)}>Revisar y reactivar participación</button>}{data.canManage&&row.status!=='NOT_INVITED'&&row.status!=='REVOKED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('REVOKE',row)}>Revocar participación de campo</button>}{nextStep.primary?.action!=='RECOVER_INVITATION'&&data.canManage&&row.invitation?.state==='ATTEMPTED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>recoverInvitation(row)}>Comprobar invitación en Clerk</button>}{nextStep.primary?.action!=='SUBMIT_KYC'&&row.self&&row.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(row.kyc.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('SUBMIT_KYC',row)}>Presentar mi identidad</button>}</div>
    </details>{row.self&&row.active&&row.status==='ACTIVE'&&row.kyc.status==='APPROVED'&&<PrivateBankAccountPanel projectId={projectId} scope={scope} workerId={row.id} getSessionToken={getSessionToken} onPending={onBankPending} locked={busy||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||Boolean(draft)||intakePending}/>}
    {/* Private object URLs must stay in this browser; an image optimizer must not receive KYC evidence. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    {row.kyc.images.map(image=><div key={image.id} className={styles.evidence}><button disabled={locked} type="button" onClick={()=>viewImage(row,image)}>{image.kind==='SELFIE'?'Consultar fotografía':image.kind==='DOCUMENT_BACK'?'Consultar dorso privado':'Consultar documento privado'}</button>{images[imageKey(row,image)]&&<img src={images[imageKey(row,image)]} alt={image.kind==='SELFIE'?'Fotografía presentada para revisión de identidad':image.kind==='DOCUMENT_BACK'?'Dorso presentado para revisión de identidad':'Frente presentado para revisión de identidad'}/>}</div>)}
    <details className={styles.options}><summary>Cuenta existente y revisión</summary>{participationChangeReady&&data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked))&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>assignExisting(row)}>Asignar una cuenta de la empresa</button>}
    {nextStep.primary?.action!=='REVIEW_KYC'&&data.canManage&&!row.self&&row.kyc.status==='PENDING_REVIEW'&&participantKycReviewImages(row.kyc)&&<button disabled={locked||Boolean(draft)||row.kyc.images.some(image=>!images[imageKey(row,image)])} type="button" onClick={()=>begin('REVIEW_KYC',row)}>Registrar revisión humana</button>}</details>
   </article>)}</div>{!data.records.length&&<p>No hay participantes vinculados a tu cuenta en esta obra.</p>}{data.nextCursor&&<button disabled={locked||Boolean(draft)&&revisionReview?.state!=='LOADED'} type="button" onClick={()=>load(true)}>Consultar más participantes</button>}</>}
  {data?.canManageOfficeRoles&&<details className={styles.office}><summary>Permisos de las cuentas en la empresa</summary><p>El rol pertenece a la cuenta verificada y se conserva al vincularla a una ficha. Revocar una participación de campo no elimina los permisos de oficina: Dirección mantiene su acceso a todas las obras de la empresa.</p><p>Los administradores y tu propia cuenta tienen acceso protegido. Esta sección no crea administradores ni cambia roles en Clerk.</p>{data.canInvite&&<button type="button" disabled={locked||Boolean(draft)} onClick={beginOfficeAccount}>Incorporar cuenta aceptada en Clerk</button>}<ParticipantAccountDiscovery key={'office:'+accountGeneration} projectId={projectId} scope={scope} snapshot={data} api={api} disabled={networkBusy||Boolean(localRead)||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||Boolean(draft)||hasBankPending||intakePending||accessBlocked} onSelect={changeOfficeRole} onInvalidate={invalidateAccountSelection} onDenied={hideAccountDenied} onPending={directoryPending}/></details>}
  {chatChallenge?.projectId===projectId&&chatChallenge.scope===scope&&chatChallenge.workerId===selectedRow?.id&&<ParticipantChatChallenge key={projectId+':'+scope+':'+chatChallenge.workerId+':'+chatChallenge.expiresAt} challenge={chatChallenge} clock={clock} disabled={locked||accessBlocked||!data?.canManage} onExpire={()=>setChatChallenge(value=>value===chatChallenge?{...value,code:undefined,expired:true}:value)} onHide={()=>setChatChallenge(null)} onConsult={()=>load()} consultDisabled={busy||Boolean(attempt)||hasBankPending||intakePending}/>}
  {data&&draft&&<form className={styles.form} onSubmit={save}><h4 ref={editor} tabIndex={-1}>{draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?'Incorporar cuenta de oficina':draft.action==='INVITE'?'Enviar invitación de acceso':draft.action==='SEND_ONBOARDING_WHATSAPP'?'Solicitar instrucciones por WhatsApp':draft.action==='REVOKE_ONBOARDING_CONTACT'?'Retirar autorización de contacto':draft.action==='REVOKE'?'Revocar participación':draft.action==='RESTORE_ACCESS'?'Reactivar participación existente':draft.action==='REVIEW_KYC'?'Decisión del responsable':draft.action==='PROCESS_KYC'?(reviewTarget?.kyc.ocrConsent?.allowed===true?'Leer texto del documento':'Comparar fotografías en privado'):draft.action==='PREPARE_KYC_CHAT'?'Preparar código privado de WhatsApp':draft.action==='CANCEL_KYC_CHAT'?'Cancelar presentación por WhatsApp':draft.action==='ASSIGN_EXISTING'?'Vincular cuenta existente':draft.action==='SET_OFFICE_ROLE'?'Cambiar rol de empresa':draft.action==='SET_FIELD_PERMISSIONS'?'Revisar permisos de campo':'Presentar identidad privada'}</h4>
   {draft.action!=='SET_OFFICE_ROLE'&&reviewTarget&&<><p>Participante: <strong>{reviewTarget.name}</strong>.</p><small className={styles.sourceReference}>Referencia de la ficha: {reviewTarget.id}{draft.action==='REVIEW_KYC'&&` · Presentación: ${p.submissionId}`}</small></>}
   {draft.action==='SET_OFFICE_ROLE'&&<><p>Cuenta: <strong>{draft.accountName}</strong>. El cambio aplica a sus permisos en toda la empresa. Conserva las obras asignadas y la vinculación de campo; se comprueba la cuenta vigente antes de guardar.</p><label>Rol de empresa<select required disabled={locked} value={p.role} onChange={event=>edit('role',event.target.value)}>{Object.entries(data.officeRoles).map(([role,value])=><option key={role} value={role}>{value.label}</option>)}</select></label><p className={styles.scope}>{data.officeRoles[p.role]?.scope}</p></>}
  {draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION&&<div data-verified-office-editor>
   <p>La persona debe aceptar la invitación de Clerk y verificar su correo. Consultá su cuenta antes de elegir el acceso a la empresa.</p>
   <label>Correo exacto de la cuenta invitada<input data-verified-office-email type="email" required maxLength={254} autoComplete="off" value={p.email} disabled={networkBusy||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||hasBankPending||intakePending||accessBlocked} onChange={event=>edit('email',event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();consultOfficeAccount();}}}/></label>
   <button type="button" disabled={locked} onClick={()=>consultOfficeAccount()}>Consultar cuenta en Clerk</button>
   {officeSelection?.row&&<div className={styles.accountReview} data-verified-office-state={officeSelection.row.state}><p>{participantOfficeStateMessage(officeSelection.row)}</p>{officeSelection.row.account&&<><strong>{officeSelection.row.account.name}</strong><p style={{overflowWrap:'anywhere'}}>{officeSelection.row.account.email}</p><p>Membresía aceptada en Clerk: miembro de la organización.</p></>}</div>}
   <label>Rol de empresa<select data-verified-office-role required disabled={locked||!officeSelection?.verified} value={p.role} onChange={event=>edit('role',event.target.value)}><option value="">Seleccioná un rol de empresa</option>{Object.entries(data.officeRoles||{}).map(([role,value])=><option key={role} value={role}>{value.label}</option>)}</select></label>
   {p.role&&<p className={styles.scope} data-verified-office-scope>{data.officeRoles[p.role]?.scope} {p.role==='DIRECTOR'?'Este permiso alcanza todas las obras de la empresa.':'El acceso queda asignado a la obra seleccionada.'}</p>}
   <label className={styles.consent}><input data-verified-office-confirm type="checkbox" required disabled={locked||!officeSelection?.verified||!p.role} checked={officeSelection?.confirmed===true&&p.confirmOfficePermissions===true} onChange={event=>{setOfficeSelection(prior=>prior?{...prior,confirmed:event.target.checked}:prior);edit('confirmOfficePermissions',event.target.checked);}}/>Confirmo esta cuenta y el alcance del rol de oficina elegido</label>
  </div>}
   {draft.action==='SET_FIELD_PERMISSIONS'&&<><p>Estos permisos corresponden sólo a la participación de esta persona en esta obra. La revisión de identidad y el vínculo de su propio WhatsApp siguen siendo necesarios para operar.</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.permissions.attendance} onChange={event=>edit('permissions',{...p.permissions,attendance:event.target.checked})}/>Registrar jornada</label><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.permissions.report} onChange={event=>edit('permissions',{...p.permissions,report:event.target.checked})}/>Enviar reportes</label>{!p.permissions.attendance&&!p.permissions.report&&<p>Quedará con acceso de consulta, sin fichajes ni reportes propios.</p>}</>}
    {draft.action==='REVOKE'&&<p>Se bloquean los fichajes y reportes de esta participación. Una cuenta con rol de oficina conserva sus permisos de empresa. Dirección continúa accediendo a todas las obras.</p>}
   {draft.action==='ASSIGN_EXISTING'&&<><p>Seleccioná una cuenta vigente de esta empresa para vincularla a la ficha. Se conserva su rol de empresa y se habilita su participación en esta obra. El servidor vuelve a comprobar la pertenencia y el correo en Clerk.</p><ParticipantAccountDiscovery key={'assignment:'+accountGeneration} mode="assignment" projectId={projectId} scope={scope} snapshot={data} api={api} disabled={networkBusy||Boolean(localRead)||Boolean(attempt)||Boolean(durableReference)||!recoveryReady||hasBankPending||intakePending||accessBlocked} selectedId={p.membershipId} selectedAccount={accountSelection?.account} onSelect={membershipId=>membershipId?consultAccount(membershipId,'ASSIGN_EXISTING'):invalidateAccountSelection()} onInvalidate={invalidateAccountSelection} onDenied={hideAccountDenied} onPending={directoryPending}/></>}
   {draft.action==='INVITE'&&<><p>Se solicitará una invitación por correo a través de Clerk. Aceptarla permite presentar y consultar la identidad privada. Para consultar la obra o registrar jornada y evidencia, la persona necesita una revisión humana aprobada y los permisos vigentes de esta obra. La invitación no permite aprobar avances ni administrar personas.</p><label>Correo del participante<input required type="email" maxLength={254} disabled={locked} value={p.email} onChange={event=>edit('email',event.target.value)}/></label></>}
   {(draft.action==='INVITE'&&onboardingContactNotice||draft.action==='SEND_ONBOARDING_WHATSAPP')&&<ParticipantOnboardingContactChoice notice={onboardingContactNotice} checked={draft.sendWhatsApp===true} disabled={locked} onChange={chooseWhatsAppInstructions}/>}
   {draft.action==='SEND_ONBOARDING_WHATSAPP'&&<p>Se utilizarán la invitación y el teléfono de esta ficha. El servidor comprobará el permiso del emisor original y el canal de la empresa antes del envío. La cuenta, la presentación de identidad y su revisión siguen siendo pasos individuales.</p>}
   {draft.action==='REVOKE_ONBOARDING_CONTACT'&&<p>{selectedDelivery.revokeWarning||'Se retira la autorización para futuros envíos de instrucciones por WhatsApp. La cuenta, la invitación y los permisos de obra se conservan.'}</p>}
   {draft.action==='REVIEW_KYC'&&<><p>Registrá tu revisión de todas las imágenes presentadas. La decisión no equivale a una certificación civil ni habilita WhatsApp.</p><label>Decisión<select disabled={locked} value={p.decision} onChange={event=>edit('decision',event.target.value)}><option value="APPROVED">Aprobar para esta obra</option><option value="REJECTED">Solicitar corrección</option></select></label></>}
   {draft.action==='PROCESS_KYC'&&reviewTarget?.kyc.ocrConsent?.allowed===true&&<p>El participante autorizó esta lectura opcional. Se enviará únicamente el frente del documento a OpenAI. La presentación conserva su revisión humana pendiente; la selfie no se envía a OpenAI y el resultado no aprueba la identidad.</p>}
   {draft.action==='PROCESS_KYC'&&reviewTarget?.kyc.biometricConsent?.allowed===true&&<p>El participante autorizó la comparación facial privada. El frente y la selfie se procesarán dentro de ObraSaaS para obtener señales orientativas. La prueba de vida no está verificada; este resultado tampoco aprueba la identidad.</p>}
   {draft.action==='PREPARE_KYC_CHAT'&&<p>El servidor comprobará la invitación o cuenta individual, el teléfono registrado y el canal autorizado para esta obra. En un canal compartido, el código conserva esta obra como destino; ninguna selección posterior lo cambia. La persona leerá el aviso, autorizará por separado el dorso del documento, elegirá si autoriza la lectura asistida y confirmará el frente, el dorso y la selfie dentro del chat. El código no concede permisos ni aprueba su identidad y se mostrará una sola vez.</p>}
   {draft.action==='CANCEL_KYC_CHAT'&&<p>La presentación anterior y su recibo quedan conservados. Esta persona deberá usar un código distinto para comenzar otra presentación; su cuenta y la revisión de identidad mantienen sus propios estados.</p>}
    {['REVIEW_KYC','REVOKE','RESTORE_ACCESS','ASSIGN_EXISTING','SET_OFFICE_ROLE','SET_FIELD_PERMISSIONS','CANCEL_KYC_CHAT',PARTICIPANT_OFFICE_ASSIGN_ACTION].includes(draft.action)&&<label>{draft.action==='CANCEL_KYC_CHAT'?'Motivo del cierre':'Fundamento'}<textarea required minLength={8} maxLength={800} disabled={locked} value={p.reason} onChange={event=>edit('reason',event.target.value)}/></label>}
   {draft.action==='SUBMIT_KYC'&&<><p>{data.privacyNotice.text}</p><KycPhotoPreparation kind="front" disabled={locked} onChange={(file,options)=>chooseFile('front',file,options)}/><KycPhotoPreparation kind="selfie" disabled={locked} onChange={(file,options)=>chooseFile('selfie',file,options)}/>{participantDocumentBackNotice(data.documentBackNotice)&&<details><summary>Dorso del documento opcional</summary><p>{data.documentBackNotice.text}</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.backConsent===true} onChange={event=>chooseDocumentBack(event.target.checked)}/>Leí el aviso del dorso y autorizo agregarlo para revisión humana.</label>{p.backConsent===true&&<KycPhotoPreparation kind="back" disabled={locked} onChange={(file,options)=>chooseFile('back',file,options)}/>}<p>Podés continuar con el frente y tu fotografía. En nuevas presentaciones por WhatsApp, el dorso requiere autorización separada.</p></details>}<label className={styles.consent}><input required type="checkbox" disabled={locked} checked={p.consent} onChange={event=>edit('consent',event.target.checked)}/>Leí el aviso y autorizo la presentación de estas imágenes para revisión.</label>{data.externalOcrNotice&&<details><summary>Lectura asistida opcional del documento</summary><p>{data.externalOcrNotice.text}</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.ocrConsent===true} onChange={event=>edit('ocrConsent',event.target.checked)}/>Autorizo enviar el frente de mi documento a OpenAI para extraer texto.</label></details>}{data.privateBiometricNotice&&<details><summary>Comparación facial privada opcional</summary><p>{data.privateBiometricNotice.text}</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.biometricConsent===true} onChange={event=>edit("biometricConsent",event.target.checked)}/>Autorizo la comparación facial privada y entiendo que la prueba de vida no está verificada.</label>{<p>Podés autorizar esta comparación sin autorizar el envío del documento a OpenAI. La revisión manual sigue disponible.</p>}</details>}</>}
   {revisionReview&&<div role="status"><p>{revisionReview.state==='STALE'?'Actualizá el registro para revisar el cambio sin perder tu borrador.':revisionReview.description}</p>{revisionReview.state==='LOADED'&&(revisionReview.allowed?<><p>{draft.action==='REVIEW_KYC'?'Volvé a consultar todas las imágenes de esta presentación antes de confirmar la revisión.':''}</p><button type="button" disabled={busy||hasBankPending||intakePending||!reviewImagesReady} onClick={()=>{setDraft(prior=>({...prior,payload:{...prior.payload,revision:revisionReview.revision}}));setRevisionReview(null);setNotice('Revisaste el estado vigente. Podés guardar tu solicitud cuando estés de acuerdo.');}}>Revisé el estado vigente y quiero continuar</button></>:!data.nextCursor&&<p>El estado vigente no permite repetir esta decisión. Conservamos tu texto para consultarlo; cancelá este borrador y revisá el registro antes de iniciar otra solicitud.</p>)}</div>}
   {['ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action)&&<div className={styles.accountReview} data-selected-account={accountSelection?.account.membershipId||''}>{accountSelection?.account&&<ParticipantAccountDetails account={accountSelection.account} assignment={draft.action==='ASSIGN_EXISTING'}/>}<p>Comprobamos esta cuenta antes de guardar. Si cambia su estado o sus permisos, vas a revisar y confirmar otra vez.</p>{p.membershipId&&<button type="button" disabled={locked||Boolean(revisionReview)} onClick={()=>consultAccount(p.membershipId,draft.action)}>Volver a comprobar cuenta</button>}<label className={styles.consent}><input required type="checkbox" checked={accountSelection?.confirmed===true} disabled={locked||Boolean(revisionReview)||!accountSelection?.verified} onChange={event=>setAccountSelection(prior=>prior?{...prior,confirmed:event.target.checked}:prior)}/>Confirmo la cuenta y sus permisos vigentes</label></div>}
   <div className={styles.actions}><button disabled={locked||Boolean(revisionReview)||draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION&&(!officeSelection?.verified||!officeSelection.confirmed||!p.role||!p.confirmOfficePermissions)||['ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action)&&!accountSelection?.confirmed||(draft.action==='SUBMIT_KYC'&&(!p.front||!p.selfie||!p.consent||p.backConsent===true&&!p.back))||draft.action==='SEND_ONBOARDING_WHATSAPP'&&(!draft.sendWhatsApp||!onboardingContactNotice)} type="submit">{draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?'Incorporar con estos permisos':draft.action==='INVITE'?'Enviar invitación':draft.action==='SEND_ONBOARDING_WHATSAPP'?'Guardar solicitud de envío':draft.action==='REVOKE_ONBOARDING_CONTACT'?'Confirmar retiro de autorización':draft.action==='SUBMIT_KYC'?'Presentar para revisión':draft.action==='PROCESS_KYC'?(reviewTarget?.kyc.ocrConsent?.allowed===true?'Leer texto del documento':'Comparar fotografías en privado'):draft.action==='PREPARE_KYC_CHAT'?'Crear código privado':draft.action==='CANCEL_KYC_CHAT'?'Confirmar cancelación':draft.action==='SET_OFFICE_ROLE'?'Guardar rol de empresa':draft.action==='SET_FIELD_PERMISSIONS'?'Guardar permisos de campo':'Guardar decisión'}</button><button type="button" disabled={draft.action===PARTICIPANT_OFFICE_ASSIGN_ACTION?networkBusy||Boolean(attempt)||Boolean(durableReference):locked} onClick={()=>{invalidateAccountSelection();fileSequence.current++;fileRead.current?.cancel(null);setDraft(null);setRevisionReview(null);}}>{draft.action==='CANCEL_KYC_CHAT'?'Volver al perfil':'Cancelar'}</button></div>
  </form>}{attempt&&<div className={styles.actions}>{(!data||attempt.action===PARTICIPANT_OFFICE_ASSIGN_ACTION)&&<button disabled={busy||hasBankPending||intakePending} type="button" onClick={recover}>Comprobar el mismo intento</button>}{!['INVITE','SEND_ONBOARDING_WHATSAPP'].includes(attempt.action)&&!accessBlocked&&retryAllowed&&<button disabled={busy||hasBankPending||intakePending} type="button" onClick={retryExact}>Reintentar exactamente esta solicitud</button>}{recoveryRecord&&<button disabled={busy||hasBankPending||intakePending} type="button" onClick={revokeUncertain}>Revocar acceso de esta invitación pendiente</button>}</div>}{recoveryRecord&&<p>Si el correo llega después, esta revocación impedirá completar el acceso mediante esa invitación.</p>}{(attempt||durableReference)&&<div className={styles.actions}>{!attempt&&<button type="button" disabled={busy} onClick={consultReference}>Comprobar el mismo intento</button>}<button type="button" disabled={busy||hasBankPending||intakePending} onClick={closeConsultation}>Cerrar consulta y conservar referencia</button></div>}{receipt&&<p className={styles.receipt}>Recibo: {receipt}</p>}
 </section>;
}
const readInvitation=()=>{const params=new URLSearchParams(window.location.search);return params.getAll('participar').length===1&&/^invite_[a-f0-9]{32}$/.test(params.get('participar'))?params.get('participar'):'';};
const subscribeInvitation=callback=>{window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback);};
const emptyInvitation=()=>'';
export function ParticipantSelfServicePanel({getSessionToken}){
 const invitationId=useSyncExternalStore(subscribeInvitation,readInvitation,emptyInvitation);
 return invitationId?<ParticipantInvitation key={invitationId} invitationId={invitationId} getSessionToken={getSessionToken}/>:null;
}
function ParticipantInvitation({invitationId,getSessionToken}){
 const api=useParticipantRequest(getSessionToken);
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[attempt,setAttempt]=useState(null),[canRetry,setCanRetry]=useState(false),alive=useRef(true),sequence=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const confirmed=value=>value.joined===true&&value.saved===true&&typeof value.receiptId==='string'&&Boolean(value.receiptId)&&typeof value.projectId==='string'&&Boolean(value.projectId);
 async function load(){if(busy||!invitationId)return;const current=++sequence.current;setBusy(true);setCanRetry(false);try{const value=await api({invitationId},{},joinEndpoint);if(!alive.current||current!==sequence.current)return;if(value.invitationId!==invitationId||!['INVITED','ACTIVE'].includes(value.state)||value.state==='ACTIVE'&&(!confirmed(value)||value.canAccept!==false)||value.state==='INVITED'&&value.canAccept!==true)throw new Error('No se pudo comprobar esta invitación y su recibo.');setData(value);if(value.state==='ACTIVE'){setAttempt(null);setNotice('Tu participación quedó registrada. Comprobamos el recibo y tu acceso vigente sin repetir la aceptación.');}else if(attempt){setCanRetry(true);setNotice('Todavía no se observa una aceptación confirmada. Podés reenviar explícitamente este mismo intento. No se reenvió automáticamente.');}}catch(error){if(alive.current&&current===sequence.current){setData(null);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function accept(){if(busy||!data?.canAccept||attempt&&!canRetry)return;const retrying=Boolean(attempt),current=++sequence.current,command=attempt||{invitationId,operationId:crypto.randomUUID()};setAttempt(command);setBusy(true);setCanRetry(false);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},joinEndpoint);if(alive.current&&current===sequence.current){if(!confirmed(value))throw new Error('No se confirmó el acceso.');setAttempt(null);setNotice('Tu participación quedó registrada. Actualizá tu cuenta para abrir la obra y presentar tu identidad.');setData(prior=>({...prior,canAccept:false,state:'ACTIVE',receiptId:value.receiptId,projectId:value.projectId}));}}catch(error){if(alive.current&&current===sequence.current){if(!retrying&&!error.retainAttempt&&(error.requestDispatched===false||error.status&&error.status<500))setAttempt(null);if(accessDenied(error))setData(null);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 if(!invitationId)return null;return <section className={styles.panel}><h2>Completar mi invitación de obra</h2><p>Ingresá con el correo invitado, aceptá el enlace de Clerk y seleccioná la organización indicada antes de continuar.</p><p role="status" aria-live="polite">{notice}</p>{!data&&!attempt&&<button type="button" disabled={busy} onClick={load}>Consultar mi invitación</button>}{data&&<><p><strong>{data.organizationName}</strong> · {data.projectName}</p><p>Participante: {data.participantName}. Podés consultar esta obra y presentar tu identidad. La actividad depende de tus permisos y su revisión.</p>{data.state==='ACTIVE'&&<><p className={styles.receipt}>Recibo: {data.receiptId}</p><a href={'/cuenta?'+new URLSearchParams({participar:invitationId,obra:data.projectId}).toString()}>Abrir mi obra en la cuenta</a><button type="button" disabled={busy} onClick={load}>Volver a comprobar mi acceso</button></>}{data.canAccept&&!attempt&&<button type="button" disabled={busy} onClick={accept}>Aceptar participación en esta obra</button>}</>}{attempt&&<><button type="button" disabled={busy} onClick={load}>Comprobar la misma aceptación</button>{canRetry&&<button type="button" disabled={busy} onClick={accept}>Reenviar la misma aceptación</button>}</>}</section>;
}
