'use client';
import {useEffect,useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import {useWorkspaceRequest} from './workspace-request-lifecycle.js';
import {KycPhotoPreparation,KYC_PHOTO_LIMIT} from './kyc-photo-preparation.js';
import styles from './participant-panel.module.css';
const endpoint='/api/identity/participants',joinEndpoint='/api/identity/participant-join';
const imageKey=(row,image)=>row.id+':'+row.kyc.submissionId+':'+image.id;
const labels={NOT_INVITED:'Sin participación vinculada',INVITED:'Invitación pendiente',ACTIVE:'Participación activa en esta obra',REVOKED:'Participación revocada',NOT_SUBMITTED:'Sin presentar',PENDING_ACCOUNT_CLAIM:'Imágenes presentadas; falta aceptar la cuenta',PENDING_REVIEW:'Pendiente de revisión humana',APPROVED:'Aprobado por un responsable',REJECTED:'Requiere corrección',ATTEMPTED:'Envío sin confirmar',SENT:'Invitación creada en Clerk',ACCEPTED:'Invitación aceptada'};
const errors={PARTICIPANT_REVISION_CHANGED:'El registro cambió. Conservamos tu texto; actualizá para revisar la versión vigente.',PARTICIPANT_EMAIL_MISMATCH:'La invitación corresponde a otro correo verificado. Ingresá con la cuenta invitada.',PARTICIPANT_PROVIDER_ACCEPTANCE_REQUIRED:'Primero aceptá la invitación de Clerk y seleccioná la organización indicada.',PARTICIPANT_VERIFIED_EMAIL_REQUIRED:'Verificá tu correo antes de aceptar el acceso.',PARTICIPANT_INVITATION_REVOKED:'El responsable revocó esta invitación.',PARTICIPANT_INVITATION_EXPIRED:'La invitación venció. Pedí al responsable que revise el acceso.',PARTICIPANT_MEMBER_SESSION_REQUIRED:'Seleccioná la organización de la invitación con tu cuenta de participante.',PARTICIPANT_MEMBERSHIP_REVIEW_REQUIRED:'Tu acceso fue deshabilitado o requiere una revisión del administrador.',PARTICIPANT_ALREADY_INVITED:'Esta persona ya tiene una invitación. Comprobá su estado; no se envió otra.',PARTICIPANT_EMAIL_ALREADY_INVITED:'Ese correo ya tiene una invitación en esta obra.',PARTICIPANT_KYC_ALREADY_SUBMITTED:'Ya hay una presentación pendiente o aprobada. No se duplicó.',PARTICIPANT_MANAGE_REQUIRED:'Tu permiso no permite administrar participantes.',PARTICIPANT_SELF_REVIEW_REJECTED:'La identidad debe revisarla otra persona autorizada.',PARTICIPANT_ACCESS_REQUIRED:'No hay un acceso activo vinculado a tu cuenta en esta obra.',PARTICIPANT_IDENTITY_PROVIDER_UNAVAILABLE:'No se pudo verificar Clerk. Conservá el intento y comprobá su estado.',PARTICIPANT_OPERATION_CONFLICT:'Este intento corresponde a una solicitud distinta. No se reemplazó.',PARTICIPANT_PRIVATE_STORAGE_UNCONFIRMED:'No se confirmó el guardado privado de las imágenes. Conservá el intento.',PARTICIPANT_KYC_INTEGRITY:'El archivo no coincide con la evidencia presentada. No se mostró.',PARTICIPANT_PRIVACY_REQUIRED:'Leé el aviso y confirmá el uso de tus imágenes para revisión.',PARTICIPANT_OFFICE_ROLE_PROTECTED:'Este acceso está protegido o fue deshabilitado. No se modificó el rol.',WORKSPACE_ORGANIZATION_PERMISSION_REQUIRED:'Sólo el administrador puede cambiar los roles de empresa.'};
Object.assign(errors,{PARTICIPANT_OCR_CONSENT_REQUIRED:'Esta presentación no autoriza un análisis asistido vigente. La revisión manual sigue disponible.',PARTICIPANT_OCR_PROCESSING:'Ya hay una lectura en curso. Comprobá el mismo intento antes de iniciar otra.',PARTICIPANT_OCR_ALREADY_PROCESSED:'El análisis ya tiene resultado. Revisalo junto con las imágenes originales.',PARTICIPANT_OCR_PROCESSING_CHANGED:'La presentación o el intento cambió. El resultado anterior no se incorporó.'});
Object.assign(errors,{META_KYC_CHALLENGE_PARTICIPANT_REQUIRED:'Comprobá la participación, el teléfono internacional y la versión vigente antes de preparar el código.',META_KYC_CHALLENGE_AMBIGUOUS:'Ese teléfono corresponde a más de una participación. Corregí el registro antes de continuar.',WORKER_CHANNEL_CUSTOMER_CONNECTION_REQUIRED:'La obra necesita su propio WhatsApp empresarial conectado para recibir identidad.'});
const accessDenied=error=>[401,403].includes(error.status)||['WORKSPACE_CONTEXT_CHANGED','WORKSPACE_PROJECT_UNAVAILABLE'].includes(error.code);
const changedContext=()=>Object.assign(new Error('La respuesta no corresponde a esta obra y este intento. Volvé a comprobar tu acceso.'),{code:'WORKSPACE_CONTEXT_CHANGED'});
function useParticipantRequest(getSessionToken){
 const request=useWorkspaceRequest(getSessionToken);
 return async function api(params,options={},resource=endpoint,image=false,validate=value=>value){
  if(typeof getSessionToken!=='function')throw Object.assign(new Error('Tu sesión terminó. Volvé a ingresar.'),{status:401,code:'SESSION_REQUIRED',requestDispatched:false});
  const requestTimeoutMs=options.requestTimeoutMs??(options.method==='POST'?30000:params?.operationId?15000:20000);
  let retainedError;
  const result=await request(resource+(params?'?'+new URLSearchParams(params):''),{...options,requestTimeoutMs},async response=>{
   if(!response.ok){let value;try{value=await response.json();}catch{/* HTML denials must preserve the HTTP status. */}const code=value?.code||(response.status===401?'SESSION_REQUIRED':undefined),error=Object.assign(new Error(errors[code]||(response.status===401?'Tu sesión terminó. Volvé a ingresar.':response.status===403||['WORKSPACE_CONTEXT_CHANGED','WORKSPACE_PROJECT_UNAVAILABLE'].includes(code)?'Tu acceso cambió. Volvé a consultar cuando se restablezca.':'No se pudo confirmar la operación. Comprobá el estado antes de repetirla.')),{status:response.status,code});
    // A dispatched denial may follow a committed invitation or KYC write.
    // Resolve the consume without a receipt; the journal must retain its reference.
    if(options.method==='POST'&&accessDenied(error)){retainedError=Object.assign(error,{retainAttempt:true});return undefined;}throw error;
   }
   const value=image?await response.blob():await response.json();
   try{return validate(value);}catch(error){if(options.method==='POST'){retainedError=Object.assign(error,{retainAttempt:true});return undefined;}throw error;}
  });
  if(retainedError)throw retainedError;
  return result;
 };
}
function refreshedDraft(draft,value){
 const p=draft.payload,office=draft.action==='SET_OFFICE_ROLE',target=office?value.existingAccounts?.find(row=>row.membershipId===p.membershipId):value.records?.find(row=>row.id===p.workerId);
 if(!target)return {allowed:false,description:value.nextCursor?'El registro no aparece en esta página. Consultá más participantes para buscarlo en el estado actualizado.':'El registro ya no está disponible con tu acceso vigente.'};
 let allowed=false;
 if(office)allowed=value.canManageOfficeRoles&&target.canChangeRole;
 else if(draft.action==='INVITE')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked||target.status==='INVITED'&&target.invitation?.state==='SENT'&&target.invitation.expired===true);
 else if(draft.action==='ASSIGN_EXISTING')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked)&&value.existingAccounts?.some(row=>row.membershipId===p.membershipId&&row.status==='ACTIVE');
 else if(draft.action==='REVOKE')allowed=value.canManage&&target.active&&!['NOT_INVITED','REVOKED'].includes(target.status);
 else if(draft.action==='RESTORE_ACCESS')allowed=value.canManage&&target.active&&target.status==='REVOKED'&&target.accountLinked;
 else if(draft.action==='SUBMIT_KYC')allowed=target.self&&target.active&&target.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(target.kyc.status)&&value.privacyNotice.version===p.noticeVersion;
 else if(draft.action==='REVIEW_KYC')allowed=value.canManage&&!target.self&&target.active&&target.status==='ACTIVE'&&target.kyc.status==='PENDING_REVIEW'&&target.kyc.submissionId===p.submissionId&&target.kyc.images.length===2;
  else if(draft.action==='PROCESS_KYC')allowed=value.canManage&&!target.self&&target.active&&target.status==='ACTIVE'&&target.kyc.status==='PENDING_REVIEW'&&target.kyc.submissionId===p.submissionId&&(target.kyc.ocrConsent?.allowed===true||target.kyc.biometricConsent?.allowed===true)&&!['RUNNING','EXTRACTED_UNVERIFIED','ADVISORY_UNREVIEWED'].includes(target.kyc.processing?.status);
 else if(draft.action==='PREPARE_KYC_CHAT')allowed=value.canManage&&target.active&&['INVITED','ACTIVE'].includes(target.status)&&['NOT_SUBMITTED','REJECTED'].includes(target.kyc.status);
 return {allowed,revision:target.revision,description:office?'Rol vigente: '+target.roleLabel:'Participación: '+(labels[target.status]||target.status)+'. Identidad: '+(labels[target.kyc.status]||target.kyc.status)+'.'};
}
const localPhotoTarget=(projectId,scope,draft)=>draft?.action==='SUBMIT_KYC'?JSON.stringify([projectId,scope,draft.action,draft.payload.workerId,draft.payload.revision,draft.payload.noticeVersion]):null;
export function ParticipantPanel({projectId,scope,onPending,getSessionToken}){
 const api=useParticipantRequest(getSessionToken);
 const [localRead,setLocalRead]=useState(null),[data,setData]=useState(null),[networkBusy,setBusy]=useState(false),[notice,setNotice]=useState(''),[draft,setDraft]=useState(null),[attempt,setAttempt]=useState(null),[receipt,setReceipt]=useState(null),[images,setImages]=useState({}),[recoveryRecord,setRecoveryRecord]=useState(null),[revisionReview,setRevisionReview]=useState(null),[accessBlocked,setAccessBlocked]=useState(false),[retryAllowed,setRetryAllowed]=useState(false);
 const busy=networkBusy||Boolean(localRead);
 const [chatChallenge,setChatChallenge]=useState(null);
 const alive=useRef(true),sequence=useRef(0),fileSequence=useRef(0),urls=useRef([]),fileRead=useRef(null),committedFileTarget=useRef(null);
 useLayoutEffect(()=>{alive.current=true;const allocatedUrls=urls.current,localSequence=fileSequence;return()=>{alive.current=false;localSequence.current++;fileRead.current?.cancel(null);allocatedUrls.forEach(url=>URL.revokeObjectURL(url));};},[]);
 useLayoutEffect(()=>{const target=localPhotoTarget(projectId,scope,draft);committedFileTarget.current=target;if(fileRead.current&&fileRead.current.target!==target){fileSequence.current++;fileRead.current.cancel(null);}},[projectId,scope,draft]);
 useEffect(()=>{onPending?.(busy||Boolean(attempt)||Boolean(draft));return()=>onPending?.(false);},[busy,attempt,draft,onPending]);
 useEffect(()=>{if(!draft&&!attempt)return;const warn=event=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft,attempt]);
 function scoped(value,snapshot=false){if(value?.scope!==scope||(snapshot?value?.projectId!==projectId||!Array.isArray(value?.records):value?.projectId!==undefined&&value.projectId!==projectId))throw changedContext();return value;}
 function outcome(value,command){scoped(value);const matches=command.action==='SET_OFFICE_ROLE'?value.account?.membershipId===command.payload.membershipId:value.participant?.id===(command.payload?.workerId||command.workerId);if(!matches||value.saved!==true||typeof value.receiptId!=='string'||!value.receiptId)throw changedContext();if(command.action==='PREPARE_KYC_CHAT'&&(value.kind!=='PREPARE_KYC_CHAT'||!Number.isFinite(Date.parse(value.expiresAt))||typeof value.codeUnavailable!=='boolean'||!value.codeUnavailable&&!/^IDENTIDAD [A-Za-z0-9_-]{43}$/.test(value.code||'')||value.codeUnavailable&&value.code!==undefined))throw changedContext();return value;}
 function recovered(value,command){scoped(value);if(value.state==='RECORDED')return outcome(value,command);if(value.definitive!==false||value.saved===true||value.receiptId||value.receipt)throw changedContext();if(value.state==='NOT_OBSERVED')return value;if(value.state==='PROCESSING'&&command.action==='PROCESS_KYC'&&value.workerId===command.payload.workerId&&value.submissionId===command.payload.submissionId&&Number.isFinite(Date.parse(value.expiresAt))&&typeof value.retryAfterExpiration==='boolean')return value;if(value.state==='INVITATION_UNCONFIRMED'&&command.action==='INVITE'&&value.participant?.id===command.payload.workerId&&/^invite_[a-f0-9]{32}$/.test(value.participant.invitation?.id||''))return value;throw changedContext();}
 const operationResult=(value,command)=>command.action==='PROCESS_KYC'&&value.state==='PROCESSING'?recovered(value,command):outcome(value,command);
 async function acceptResult(value,command){if(value.state==='PROCESSING'){setDraft(null);setRetryAllowed(value.retryAfterExpiration);setNotice(value.retryAfterExpiration?'La lectura anterior no tiene resultado confirmado. Podés reintentar exactamente esta solicitud.':'El análisis está en curso. Comprobá el mismo intento; no se envió otro documento.');}else await confirm(value,command);}
 function hideDenied(error){if(!accessDenied(error))return false;sequence.current++;fileSequence.current++;fileRead.current?.cancel(null);urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});setData(null);setDraft(null);setRevisionReview(null);setRecoveryRecord(null);setReceipt(null);setChatChallenge(null);setAccessBlocked(true);setRetryAllowed(false);setBusy(false);return true;}
 async function load(append=false){if(busy||attempt)return;setBusy(true);const current=++sequence.current;try{const value=await api({projectId,scope,...(append&&data?.nextCursor?{after:data.nextCursor}:{})},{},endpoint,false,value=>scoped(value,true));if(!alive.current||current!==sequence.current)return;const fresh=append?{...value,records:[...data.records,...value.records]}:value;setAccessBlocked(false);setData(fresh);if(draft&&revisionReview){setRevisionReview({state:'LOADED',...refreshedDraft(draft,fresh)});if(draft.action==='REVIEW_KYC'){urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});}setNotice('Consultamos el estado vigente. Tu borrador se conserva; revisá el cambio antes de continuar.');}}catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function confirm(value,command){outcome(value,command);const current=sequence.current,office=command.action==='SET_OFFICE_ROLE';setAccessBlocked(false);setRetryAllowed(false);setReceipt(value.receiptId);setAttempt(null);setRecoveryRecord(null);setDraft(null);if(command.action==='PREPARE_KYC_CHAT')setChatChallenge({code:value.code,codeUnavailable:value.codeUnavailable,expiresAt:value.expiresAt});setNotice(office?'El cambio de rol quedó registrado con recibo. La lista muestra el permiso vigente de la cuenta en la empresa.':'Operación guardada con recibo. La revisión humana y la habilitación de WhatsApp se acreditan por separado.');try{const fresh=await api({projectId,scope},{},endpoint,false,value=>scoped(value,true));if(alive.current&&current===sequence.current)setData(fresh);}catch(error){if(alive.current&&current===sequence.current){if(hideDenied(error))setNotice('El recibo quedó confirmado, pero tu acceso vigente ya no permite consultar esta obra.');else setNotice('El recibo está confirmado. Actualizá la lista para consultar el estado vigente.');}}}
 async function save(event){event.preventDefault();if(busy||attempt||!draft||revisionReview||accessBlocked)return;const operationId=crypto.randomUUID(),command=draft.action==='SUBMIT_KYC'?{operationId,projectId,scope,...draft.payload}:{operationId,projectId,scope,action:draft.action,payload:draft.payload};setAttempt(command);setRetryAllowed(false);setBusy(true);setNotice('');setReceipt(null);
  try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),requestTimeoutMs:['SUBMIT_KYC','PROCESS_KYC'].includes(draft.action)?55000:30000},endpoint,false,value=>operationResult(value,command));if(alive.current)await acceptResult(value,command);}catch(error){if(alive.current){const denied=hideDenied(error);if(!error.retainAttempt&&(error.requestDispatched===false||error.status&&error.status<500)){setAttempt(null);if(error.code==='PARTICIPANT_REVISION_CHANGED')setRevisionReview({state:'STALE'});setNotice(error.message);}else setNotice(denied?error.message+' El resultado sigue sin confirmar. Comprobá el mismo intento cuando se restablezca tu acceso.':'El resultado quedó sin confirmar. Comprobá el recibo antes de volver a enviar.');}}finally{if(alive.current)setBusy(false);}}
 async function recover(){if(!attempt||busy)return;const current=sequence.current;setBusy(true);setRetryAllowed(false);try{
  if(attempt.action==='RECOVER_INVITATION'){const fresh=await api({projectId,scope},{},endpoint,false,value=>scoped(value,true));if(!alive.current||current!==sequence.current)return;const target=fresh.records.find(row=>row.id===attempt.payload.workerId);if(target?.invitation?.id!==attempt.payload.invitationId)throw changedContext();const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt)},endpoint,false,value=>outcome(value,attempt));if(alive.current&&current===sequence.current)await confirm(value,attempt);return;}
  const value=await api({projectId,scope,operationId:attempt.operationId},{},endpoint,false,value=>recovered(value,attempt));if(!alive.current||current!==sequence.current)return;
  if(value.state==='RECORDED')await confirm(value,attempt);
  else if(value.state==='PROCESSING'){setAccessBlocked(false);await acceptResult(value,attempt);}
  else if(value.state==='INVITATION_UNCONFIRMED'){setAccessBlocked(false);if(value.participant.status==='REVOKED'){setAttempt(null);setDraft(null);setRecoveryRecord(null);setNotice('La participación quedó revocada. No se volvió a enviar la invitación.');return;}setRecoveryRecord(value.participant);const lookedUp=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:value.participant.id,invitationId:value.participant.invitation.id}})},endpoint,false,value=>outcome(value,attempt));if(!alive.current||current!==sequence.current)return;const recorded=await api({projectId,scope,operationId:attempt.operationId},{},endpoint,false,value=>recovered(value,attempt));if(!alive.current||current!==sequence.current)return;if(recorded.state!=='RECORDED'||recorded.receiptId!==lookedUp.receiptId)throw changedContext();await confirm(recorded,attempt);}
  else{setAccessBlocked(false);setRetryAllowed(attempt.action!=='INVITE');setNotice('Todavía no se observa un recibo. No se repitió la operación ni se declaró perdida.');}
 }catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function retryExact(){if(!attempt||busy||attempt.action==='INVITE'||accessBlocked||!retryAllowed)return;setBusy(true);setRetryAllowed(false);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt),requestTimeoutMs:attempt.front||attempt.action==='PROCESS_KYC'?55000:30000},endpoint,false,value=>operationResult(value,attempt));if(alive.current)await acceptResult(value,attempt);}catch(error){if(alive.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 async function revokeUncertain(){if(busy||!recoveryRecord||accessBlocked)return;const previous=attempt,command={operationId:crypto.randomUUID(),projectId,scope,action:'REVOKE',payload:{workerId:recoveryRecord.id,revision:recoveryRecord.revision,reason:'El administrador revocó explícitamente una invitación cuyo envío no se pudo confirmar.'}};setAttempt(command);setRetryAllowed(false);setRecoveryRecord(null);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},endpoint,false,value=>outcome(value,command));if(alive.current)await confirm(value,command);}catch(error){if(alive.current){const denied=hideDenied(error);if(!error.retainAttempt&&(error.requestDispatched===false||error.status&&error.status<500)){setAttempt(previous);if(!denied)setRecoveryRecord(recoveryRecord);}setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 function begin(action,row){fileSequence.current++;fileRead.current?.cancel(null);setChatChallenge(null);setDraft({action,payload:action==='INVITE'?{workerId:row.id,revision:row.revision,email:''}:action==='PREPARE_KYC_CHAT'?{workerId:row.id,revision:row.revision}:['REVOKE','RESTORE_ACCESS'].includes(action)?{workerId:row.id,revision:row.revision,reason:''}:action==='PROCESS_KYC'?{workerId:row.id,revision:row.revision,submissionId:row.kyc.submissionId}:action==='REVIEW_KYC'?{workerId:row.id,revision:row.revision,submissionId:row.kyc.submissionId,decision:'APPROVED',reason:''}:{workerId:row.id,revision:row.revision,noticeVersion:data.privacyNotice.version,consent:false,front:'',selfie:'',...(data.externalOcrNotice?{ocrConsent:false,ocrNoticeVersion:data.externalOcrNotice.version}:{}),...(data.privateBiometricNotice?{biometricConsent:false,biometricNoticeVersion:data.privateBiometricNotice.version}:{})}});setNotice('');setReceipt(null);}
 function edit(key,value){setDraft(prior=>prior?{...prior,payload:{...prior.payload,[key]:value}}:prior);}
 function changeOfficeRole(account){setDraft({action:'SET_OFFICE_ROLE',payload:{membershipId:account.membershipId,revision:account.revision,role:account.role,reason:''},accountName:account.name});setNotice('');setReceipt(null);}
 function assignExisting(row){setDraft({action:'ASSIGN_EXISTING',payload:{workerId:row.id,revision:row.revision,membershipId:'',reason:''}});setNotice('');setReceipt(null);}
 async function chooseFile(key,file,{signal}={}){
  const current=++fileSequence.current;fileRead.current?.cancel(null);setNotice('');
  if(!file){edit(key,'');return false;}if(signal?.aborted)return false;
  if(file.size>KYC_PHOTO_LIMIT||!['image/png','image/jpeg','image/webp'].includes(file.type)){setNotice('Elegí JPEG, PNG o WebP de hasta 1 MiB por imagen.');return false;}
  const target=localPhotoTarget(projectId,scope,draft);if(!target||committedFileTarget.current!==target)return false;
  const owner={id:current,target,cancel:null};setLocalRead({id:current});
  const result=await new Promise(resolve=>{
   let reader,timer,settled=false;
   const valid=()=>alive.current&&current===fileSequence.current&&committedFileTarget.current===target&&!signal?.aborted;
   const finish=(content,message)=>{
    if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',onSignalAbort);
    if(reader)reader.onload=reader.onerror=reader.onabort=null;
    if(fileRead.current===owner)fileRead.current=null;
    // Only this local read is released. The API busy state is never modified.
    if(alive.current)setLocalRead(prior=>prior?.id===current?null:prior);
    resolve({content,message});
   };
   owner.cancel=message=>{finish(null,message);if(reader?.readyState===1)try{reader.abort();}catch{/* The promise was already settled before aborting the resource. */}};
   const onSignalAbort=()=>owner.cancel(null);fileRead.current=owner;
   if(signal?.aborted){owner.cancel(null);return;}
   try{
    reader=new FileReader();
    reader.onload=()=>{const content=valid()&&fileRead.current===owner&&typeof reader.result==='string'?reader.result:null;finish(content,content?null:'No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');};
    reader.onerror=()=>finish(null,'No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');
    reader.onabort=()=>finish(null,'Lectura detenida. Conservamos esta copia y tu revisión. Podés volver a usarla.');
    signal?.addEventListener('abort',onSignalAbort,{once:true});
    timer=setTimeout(()=>owner.cancel('No se completó la lectura en 15 segundos. Conservamos la copia y tu revisión. Volvé a usarla o elegí otra fotografía.'),15000);
    reader.readAsDataURL(file);
   }catch{owner.cancel('No se pudo leer la imagen. Volvé a usar esta copia o elegí otra fotografía.');}
  });
  if(!alive.current||current!==fileSequence.current||committedFileTarget.current!==target||signal?.aborted)return false;
  if(result.content){edit(key,result.content);return true;}if(result.message)setNotice(result.message);return false;
 }
 async function viewImage(row,image){if(busy||attempt||accessBlocked)return;const current=sequence.current;setBusy(true);try{const blob=await api({projectId,scope,workerId:row.id,imageId:image.id},{},endpoint,true);if(!alive.current||current!==sequence.current)return;if(blob.size!==image.bytes||blob.type!==image.contentType)throw new Error('La imagen recibida no coincide con la presentación.');const url=URL.createObjectURL(blob);urls.current.push(url);setImages(prior=>({...prior,[imageKey(row,image)]:url}));}catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function recoverInvitation(row){if(busy||attempt)return;const command={operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:row.id,invitationId:row.invitation.id}};setAttempt(command);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},endpoint,false,value=>outcome(value,command));if(alive.current)await confirm(value,command);}catch(error){if(alive.current){hideDenied(error);if(error.requestDispatched===false)setAttempt(null);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 const locked=busy||Boolean(attempt),p=draft?.payload,reviewTarget=data?.records.find(row=>row.id===p?.workerId);
 const reviewImagesReady=draft?.action!=='REVIEW_KYC'||reviewTarget?.kyc.images.length===2&&reviewTarget.kyc.images.every(image=>images[imageKey(reviewTarget,image)]);
 return <section className={styles.panel} aria-labelledby="participant-title"><div className={styles.heading}><div><p className={styles.eyebrow}>PERSONAS Y ACCESO</p><h3 id="participant-title">Participantes y revisión de identidad</h3></div><button type="button" disabled={locked||Boolean(data&&draft)&&!revisionReview} onClick={()=>load()}>{revisionReview?'Actualizar registro conservando borrador':'Consultar participantes'}</button></div>
  <p>Una ficha del equipo no concede acceso. La invitación exige cuenta y correo verificado; la identidad requiere la decisión de otro responsable.</p><p role="status" aria-live="polite">{notice}</p>
  {accessBlocked&&<p>Ocultamos los datos y las imágenes de esta obra porque no pudimos confirmar tu acceso vigente.{attempt?' Conservamos el intento pendiente: comprobá su estado sin volver a enviarlo.':' Volvé a consultar cuando recuperes tu acceso.'}</p>}
  {data&&<><p>{data.canManage?'Invitaciones y participación de campo en esta obra. Los permisos de empresa se administran por separado.':'Tu participación en esta obra. Sólo podés presentar y consultar tu propia identidad.'}</p><div className={styles.list}>{data.records.map(row=><article key={row.id} className={styles.card}><div className={styles.heading}><strong>{row.name}</strong><span>{labels[row.status]||row.status}</span></div><p>Identidad: {labels[row.kyc.status]||row.kyc.status}</p>{row.invitation&&<p>{labels[row.invitation.state]||row.invitation.state}{row.invitation.email?' · '+row.invitation.email:''}</p>}
    {row.kyc.review&&<p>Decisión registrada: {row.kyc.review.reason}</p>}
    {row.kyc.status==='PENDING_ACCOUNT_CLAIM'&&<p>La persona debe aceptar su invitación con el correo verificado antes de que un responsable pueda aprobar estas imágenes. La presentación por chat no concede acceso.</p>}
    {data.canManage&&row.active&&['INVITED','ACTIVE'].includes(row.status)&&['NOT_SUBMITTED','REJECTED'].includes(row.kyc.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('PREPARE_KYC_CHAT',row)}>Preparar identidad por WhatsApp</button>}
    {row.kyc.processing?.status==='RUNNING'&&<p>Análisis asistido en curso. La identidad continúa pendiente de revisión.</p>}
    {row.kyc.processing?.status==='FAILED_RETRYABLE'&&<p>No se confirmó el análisis asistido. Conservamos las imágenes; podés continuar con la revisión manual.</p>}
    {data.canManage&&row.kyc.processing?.biometrics&&<div className={styles.evidence}><strong>Comparación facial asistida</strong>{row.kyc.processing.biometrics.status==='ADVISORY_UNREVIEWED'?<><p>Similitud facial orientativa: {row.kyc.processing.biometrics.faceSimilarity.toFixed(3)}</p><p>Señal orientativa de captura: {row.kyc.processing.biometrics.captureRiskSignal.toFixed(3)}</p></>:<p>No se confirmó el análisis. Conservamos la revisión manual.</p>}<p>Prueba de vida no verificada. Estas señales no están calibradas para aprobar identidades y no acreditan autenticidad del documento.</p></div>}
    {data.canManage&&row.kyc.processing?.status==='EXTRACTED_UNVERIFIED'&&row.kyc.processing.fields&&<div className={styles.evidence}><strong>Texto extraído sin verificar</strong><p>Nombre: {row.kyc.processing.fields.nombreCompleto}</p><p>DNI: {row.kyc.processing.fields.dni}</p><p>CUIL: {row.kyc.processing.fields.cuil||'No se pudo leer'}</p><p>Compará estos datos con el documento original. La lectura no acredita autenticidad, biometría ni prueba de vida.</p></div>}
    {data.canManage&&!row.self&&row.active&&row.status==='ACTIVE'&&row.kyc.status==='PENDING_REVIEW'&&(row.kyc.ocrConsent?.allowed===true||row.kyc.biometricConsent?.allowed===true)&&!['RUNNING','EXTRACTED_UNVERIFIED','ADVISORY_UNREVIEWED'].includes(row.kyc.processing?.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('PROCESS_KYC',row)}>{row.kyc.ocrConsent?.allowed===true?'Preparar lectura asistida':'Preparar comparación facial'}</button>}
    <div className={styles.actions}>{data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked)||(row.status==='INVITED'&&row.invitation?.state==='SENT'&&row.invitation.expired===true))&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('INVITE',row)}>Invitar a esta obra</button>}{data.canManage&&row.active&&row.status==='REVOKED'&&row.accountLinked&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('RESTORE_ACCESS',row)}>Revisar y reactivar participación</button>}{data.canManage&&row.status!=='NOT_INVITED'&&row.status!=='REVOKED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('REVOKE',row)}>Revocar participación de campo</button>}{data.canManage&&row.invitation?.state==='ATTEMPTED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>recoverInvitation(row)}>Comprobar invitación en Clerk</button>}{row.self&&row.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(row.kyc.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('SUBMIT_KYC',row)}>Presentar mi identidad</button>}</div>
    {/* Private object URLs must stay in this browser; an image optimizer must not receive KYC evidence. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    {row.kyc.images.map(image=><div key={image.id} className={styles.evidence}><button disabled={locked} type="button" onClick={()=>viewImage(row,image)}>{image.kind==='SELFIE'?'Consultar fotografía':'Consultar documento privado'}</button>{images[imageKey(row,image)]&&<img src={images[imageKey(row,image)]} alt={image.kind==='SELFIE'?'Fotografía presentada para revisión de identidad':'Documento presentado para revisión de identidad'}/>}</div>)}
    {data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked))&&data.existingAccounts?.length>0&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>assignExisting(row)}>Asignar una cuenta de la empresa</button>}
    {data.canManage&&!row.self&&row.kyc.status==='PENDING_REVIEW'&&<button disabled={locked||Boolean(draft)||row.kyc.images.some(image=>!images[imageKey(row,image)])} type="button" onClick={()=>begin('REVIEW_KYC',row)}>Registrar revisión humana</button>}
   </article>)}</div>{!data.records.length&&<p>No hay participantes vinculados a tu cuenta en esta obra.</p>}{data.nextCursor&&<button disabled={locked||Boolean(draft)&&revisionReview?.state!=='LOADED'} type="button" onClick={()=>load(true)}>Consultar más participantes</button>}</>}
  {data?.canManageOfficeRoles&&<details className={styles.office}><summary>Permisos de las cuentas en la empresa</summary><p>El rol pertenece a la cuenta verificada y se conserva al vincularla a una ficha. Revocar una participación de campo no elimina los permisos de oficina: Dirección mantiene su acceso a todas las obras de la empresa.</p><p>Los administradores y tu propia cuenta tienen acceso protegido. Esta sección no crea administradores ni cambia roles en Clerk.</p><div className={styles.list}>{data.existingAccounts.map(account=><article key={account.membershipId} className={styles.card}><div className={styles.heading}><strong>{account.name}{account.self?' · Tu cuenta':''}</strong><span>Rol de empresa: {account.roleLabel}</span></div><p>{account.email}</p><p>{account.roleScope}</p>{account.canChangeRole&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>changeOfficeRole(account)}>Cambiar rol de {account.name}</button>}</article>)}</div>{data.existingAccountsTruncated&&<p>Se muestran las primeras 100 cuentas. Las restantes requieren consulta del administrador.</p>}</details>}
  {chatChallenge&&<div className={styles.evidence}><strong>Código privado de presentación por WhatsApp</strong>{chatChallenge.codeUnavailable?<p>El recibo está confirmado, pero el código se muestra una sola vez. Si no lo conservaste, prepará otro código desde la participación.</p>:<><p>Entregá este código sólo al participante. Debe enviarlo desde su teléfono registrado al WhatsApp empresarial de esta obra.</p><p style={{overflowWrap:'anywhere'}}><code>{chatChallenge.code}</code></p></>}<p>Vence: {new Date(chatChallenge.expiresAt).toLocaleString('es-AR')}. Permite presentar imágenes; la cuenta y la revisión humana siguen pendientes.</p><button type="button" onClick={()=>setChatChallenge(null)}>Ocultar código</button></div>}
  {data&&draft&&<form className={styles.form} onSubmit={save}><h4>{draft.action==='INVITE'?'Enviar invitación de acceso':draft.action==='REVOKE'?'Revocar participación':draft.action==='RESTORE_ACCESS'?'Reactivar participación existente':draft.action==='REVIEW_KYC'?'Decisión del responsable':draft.action==='PROCESS_KYC'?(reviewTarget?.kyc.ocrConsent?.allowed===true?'Leer texto del documento':'Comparar fotografías en privado'):draft.action==='PREPARE_KYC_CHAT'?'Preparar código privado de WhatsApp':draft.action==='ASSIGN_EXISTING'?'Vincular cuenta existente':draft.action==='SET_OFFICE_ROLE'?'Cambiar rol de empresa':'Presentar identidad privada'}</h4>
   {draft.action==='SET_OFFICE_ROLE'&&<><p>Cuenta: <strong>{draft.accountName}</strong>. El cambio aplica a sus permisos en toda la empresa. Conserva las obras asignadas y la vinculación de campo; se comprueba la cuenta vigente antes de guardar.</p><label>Rol de empresa<select required disabled={locked} value={p.role} onChange={event=>edit('role',event.target.value)}>{Object.entries(data.officeRoles).map(([role,value])=><option key={role} value={role}>{value.label}</option>)}</select></label><p className={styles.scope}>{data.officeRoles[p.role]?.scope}</p></>}
   {draft.action==='REVOKE'&&<p>Se bloquean los fichajes y reportes de esta participación. Una cuenta con rol de oficina conserva sus permisos de empresa. Dirección continúa accediendo a todas las obras.</p>}
   {draft.action==='ASSIGN_EXISTING'&&<><p>Seleccioná una cuenta vigente de esta empresa para vincularla a la ficha. Se conserva el rol indicado en la lista, incluidos sus permisos de consulta o gestión, y se habilita su participación en esta obra. El servidor vuelve a comprobar la pertenencia y el correo en Clerk.</p><label>Cuenta de la empresa<select required disabled={locked} value={p.membershipId} onChange={event=>edit('membershipId',event.target.value)}><option value="">Seleccioná una cuenta</option>{data.existingAccounts.map(account=><option key={account.membershipId} value={account.membershipId}>{account.name} · {account.email} · {account.roleLabel}</option>)}</select></label>{data.existingAccountsTruncated&&<p>Se muestran las primeras 100 cuentas. Las restantes requieren consulta del administrador.</p>}</>}
   {draft.action==='INVITE'&&<><p>Clerk enviará una invitación por correo. El acceso permite consultar esta obra y presentar fichajes y evidencia propios; no permite aprobar avances ni administrar personas.</p><label>Correo del participante<input required type="email" maxLength={254} disabled={locked} value={p.email} onChange={event=>edit('email',event.target.value)}/></label></>}
   {draft.action==='REVIEW_KYC'&&<><p>Registrá tu revisión de las dos imágenes. La decisión no equivale a una certificación civil ni habilita WhatsApp.</p><label>Decisión<select disabled={locked} value={p.decision} onChange={event=>edit('decision',event.target.value)}><option value="APPROVED">Aprobar para esta obra</option><option value="REJECTED">Solicitar corrección</option></select></label></>}
   {draft.action==='PROCESS_KYC'&&reviewTarget?.kyc.ocrConsent?.allowed===true&&<p>El participante autorizó esta lectura opcional. Se enviará únicamente el frente del documento a OpenAI. La presentación conserva su revisión humana pendiente; la selfie no se envía a OpenAI y el resultado no aprueba la identidad.</p>}
   {draft.action==='PROCESS_KYC'&&reviewTarget?.kyc.biometricConsent?.allowed===true&&<p>El participante autorizó la comparación facial privada. El frente y la selfie se procesarán dentro de ObraSaaS para obtener señales orientativas. La prueba de vida no está verificada; este resultado tampoco aprueba la identidad.</p>}
   {draft.action==='PREPARE_KYC_CHAT'&&<p>El servidor comprobará el teléfono registrado y el WhatsApp empresarial de la obra. La persona leerá el aviso, elegirá si autoriza la lectura asistida y confirmará las dos imágenes dentro del chat. El código no concede permisos ni aprueba su identidad y se mostrará una sola vez.</p>}
   {['REVIEW_KYC','REVOKE','RESTORE_ACCESS','ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action)&&<label>Fundamento<textarea required minLength={8} maxLength={800} disabled={locked} value={p.reason} onChange={event=>edit('reason',event.target.value)}/></label>}
   {draft.action==='SUBMIT_KYC'&&<><p>{data.privacyNotice.text}</p><KycPhotoPreparation kind="front" disabled={locked} onChange={(file,options)=>chooseFile('front',file,options)}/><KycPhotoPreparation kind="selfie" disabled={locked} onChange={(file,options)=>chooseFile('selfie',file,options)}/><label className={styles.consent}><input required type="checkbox" disabled={locked} checked={p.consent} onChange={event=>edit('consent',event.target.checked)}/>Leí el aviso y autorizo la presentación de estas imágenes para revisión.</label>{data.externalOcrNotice&&<details><summary>Lectura asistida opcional del documento</summary><p>{data.externalOcrNotice.text}</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.ocrConsent===true} onChange={event=>edit('ocrConsent',event.target.checked)}/>Autorizo enviar el frente de mi documento a OpenAI para extraer texto.</label></details>}{data.privateBiometricNotice&&<details><summary>Comparación facial privada opcional</summary><p>{data.privateBiometricNotice.text}</p><label className={styles.consent}><input type="checkbox" disabled={locked} checked={p.biometricConsent===true} onChange={event=>edit("biometricConsent",event.target.checked)}/>Autorizo la comparación facial privada y entiendo que la prueba de vida no está verificada.</label>{<p>Podés autorizar esta comparación sin autorizar el envío del documento a OpenAI. La revisión manual sigue disponible.</p>}</details>}</>}
   {revisionReview&&<div role="status"><p>{revisionReview.state==='STALE'?'Actualizá el registro para revisar el cambio sin perder tu borrador.':revisionReview.description}</p>{revisionReview.state==='LOADED'&&(revisionReview.allowed?<><p>{draft.action==='REVIEW_KYC'?'Volvé a consultar las dos imágenes de esta presentación antes de confirmar la revisión.':''}</p><button type="button" disabled={busy||!reviewImagesReady} onClick={()=>{setDraft(prior=>({...prior,payload:{...prior.payload,revision:revisionReview.revision}}));setRevisionReview(null);setNotice('Revisaste el estado vigente. Podés guardar tu solicitud cuando estés de acuerdo.');}}>Revisé el estado vigente y quiero continuar</button></>:!data.nextCursor&&<p>El estado vigente no permite repetir esta decisión. Conservamos tu texto para consultarlo; cancelá este borrador y revisá el registro antes de iniciar otra solicitud.</p>)}</div>}
   <div className={styles.actions}><button disabled={locked||Boolean(revisionReview)||(draft.action==='SUBMIT_KYC'&&(!p.front||!p.selfie||!p.consent))} type="submit">{draft.action==='INVITE'?'Enviar invitación':draft.action==='SUBMIT_KYC'?'Presentar para revisión':draft.action==='PROCESS_KYC'?(reviewTarget?.kyc.ocrConsent?.allowed===true?'Leer texto del documento':'Comparar fotografías en privado'):draft.action==='PREPARE_KYC_CHAT'?'Crear código privado':draft.action==='SET_OFFICE_ROLE'?'Guardar rol de empresa':'Guardar decisión'}</button><button type="button" disabled={locked} onClick={()=>{fileSequence.current++;fileRead.current?.cancel(null);setDraft(null);setRevisionReview(null);}}>Cancelar</button></div>
  </form>}{attempt&&<div className={styles.actions}><button disabled={busy} type="button" onClick={recover}>Comprobar el mismo intento</button>{attempt.action!=='INVITE'&&!accessBlocked&&retryAllowed&&<button disabled={busy} type="button" onClick={retryExact}>Reintentar exactamente esta solicitud</button>}{recoveryRecord&&<button disabled={busy} type="button" onClick={revokeUncertain}>Revocar acceso de esta invitación pendiente</button>}</div>}{recoveryRecord&&<p>Si el correo llega después, esta revocación impedirá completar el acceso mediante esa invitación.</p>}{receipt&&<p className={styles.receipt}>Recibo: {receipt}</p>}
 </section>;
}
const readInvitation=()=>{const params=new URLSearchParams(window.location.search);return params.getAll('participar').length===1&&/^invite_[a-f0-9]{32}$/.test(params.get('participar'))?params.get('participar'):'';};
const subscribeInvitation=callback=>{window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback);};
const emptyInvitation=()=>'';
export function ParticipantSelfServicePanel({getSessionToken}){
 const invitationId=useSyncExternalStore(subscribeInvitation,readInvitation,emptyInvitation);
 return invitationId?<ParticipantInvitation key={invitationId} invitationId={invitationId} getSessionToken={getSessionToken}/>:null;
}
function ParticipantInvitation({invitationId,getSessionToken}){
 const api=useParticipantRequest(getSessionToken);
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[attempt,setAttempt]=useState(null),[canRetry,setCanRetry]=useState(false),alive=useRef(true),sequence=useRef(0);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const confirmed=value=>value.joined===true&&value.saved===true&&typeof value.receiptId==='string'&&Boolean(value.receiptId)&&typeof value.projectId==='string'&&Boolean(value.projectId);
 async function load(){if(busy||!invitationId)return;const current=++sequence.current;setBusy(true);setCanRetry(false);try{const value=await api({invitationId},{},joinEndpoint);if(!alive.current||current!==sequence.current)return;if(value.invitationId!==invitationId||!['INVITED','ACTIVE'].includes(value.state)||value.state==='ACTIVE'&&(!confirmed(value)||value.canAccept!==false)||value.state==='INVITED'&&value.canAccept!==true)throw new Error('No se pudo comprobar esta invitación y su recibo.');setData(value);if(value.state==='ACTIVE'){setAttempt(null);setNotice('Tu participación quedó registrada. Comprobamos el recibo y tu acceso vigente sin repetir la aceptación.');}else if(attempt){setCanRetry(true);setNotice('Todavía no se observa una aceptación confirmada. Podés reenviar explícitamente este mismo intento. No se reenvió automáticamente.');}}catch(error){if(alive.current&&current===sequence.current){setData(null);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function accept(){if(busy||!data?.canAccept||attempt&&!canRetry)return;const retrying=Boolean(attempt),current=++sequence.current,command=attempt||{invitationId,operationId:crypto.randomUUID()};setAttempt(command);setBusy(true);setCanRetry(false);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},joinEndpoint);if(alive.current&&current===sequence.current){if(!confirmed(value))throw new Error('No se confirmó el acceso.');setAttempt(null);setNotice('Tu participación quedó registrada. Actualizá tu cuenta para abrir la obra y presentar tu identidad.');setData(prior=>({...prior,canAccept:false,state:'ACTIVE',receiptId:value.receiptId,projectId:value.projectId}));}}catch(error){if(alive.current&&current===sequence.current){if(!retrying&&!error.retainAttempt&&(error.requestDispatched===false||error.status&&error.status<500))setAttempt(null);if(accessDenied(error))setData(null);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 if(!invitationId)return null;return <section className={styles.panel}><h2>Completar mi invitación de obra</h2><p>Ingresá con el correo invitado, aceptá el enlace de Clerk y seleccioná la organización indicada antes de continuar.</p><p role="status" aria-live="polite">{notice}</p>{!data&&!attempt&&<button type="button" disabled={busy} onClick={load}>Consultar mi invitación</button>}{data&&<><p><strong>{data.organizationName}</strong> · {data.projectName}</p><p>Participante: {data.participantName}. Podés consultar esta obra y presentar tu identidad. La actividad depende de tus permisos y su revisión.</p>{data.state==='ACTIVE'&&<><p className={styles.receipt}>Recibo: {data.receiptId}</p><a href='/cuenta'>Abrir mi obra en la cuenta</a><button type="button" disabled={busy} onClick={load}>Volver a comprobar mi acceso</button></>}{data.canAccept&&!attempt&&<button type="button" disabled={busy} onClick={accept}>Aceptar participación en esta obra</button>}</>}{attempt&&<><button type="button" disabled={busy} onClick={load}>Comprobar la misma aceptación</button>{canRetry&&<button type="button" disabled={busy} onClick={accept}>Reenviar la misma aceptación</button>}</>}</section>;
}
