'use client';
import {useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {useWorkspaceRequest} from './workspace-request-lifecycle.js';
import styles from './participant-panel.module.css';
const endpoint='/api/identity/participants',joinEndpoint='/api/identity/participant-join';
const imageKey=(row,image)=>row.id+':'+row.kyc.submissionId+':'+image.id;
const labels={NOT_INVITED:'Sin participación vinculada',INVITED:'Invitación pendiente',ACTIVE:'Participación activa en esta obra',REVOKED:'Participación revocada',NOT_SUBMITTED:'Sin presentar',PENDING_REVIEW:'Pendiente de revisión humana',APPROVED:'Aprobado por un responsable',REJECTED:'Requiere corrección',ATTEMPTED:'Envío sin confirmar',SENT:'Invitación creada en Clerk',ACCEPTED:'Invitación aceptada'};
const errors={PARTICIPANT_REVISION_CHANGED:'El registro cambió. Conservamos tu texto; actualizá para revisar la versión vigente.',PARTICIPANT_EMAIL_MISMATCH:'La invitación corresponde a otro correo verificado. Ingresá con la cuenta invitada.',PARTICIPANT_PROVIDER_ACCEPTANCE_REQUIRED:'Primero aceptá la invitación de Clerk y seleccioná la organización indicada.',PARTICIPANT_VERIFIED_EMAIL_REQUIRED:'Verificá tu correo antes de aceptar el acceso.',PARTICIPANT_INVITATION_REVOKED:'El responsable revocó esta invitación.',PARTICIPANT_INVITATION_EXPIRED:'La invitación venció. Pedí al responsable que revise el acceso.',PARTICIPANT_MEMBER_SESSION_REQUIRED:'Seleccioná la organización de la invitación con tu cuenta de participante.',PARTICIPANT_MEMBERSHIP_REVIEW_REQUIRED:'Tu acceso fue deshabilitado o requiere una revisión del administrador.',PARTICIPANT_ALREADY_INVITED:'Esta persona ya tiene una invitación. Comprobá su estado; no se envió otra.',PARTICIPANT_EMAIL_ALREADY_INVITED:'Ese correo ya tiene una invitación en esta obra.',PARTICIPANT_KYC_ALREADY_SUBMITTED:'Ya hay una presentación pendiente o aprobada. No se duplicó.',PARTICIPANT_MANAGE_REQUIRED:'Tu permiso no permite administrar participantes.',PARTICIPANT_SELF_REVIEW_REJECTED:'La identidad debe revisarla otra persona autorizada.',PARTICIPANT_ACCESS_REQUIRED:'No hay un acceso activo vinculado a tu cuenta en esta obra.',PARTICIPANT_IDENTITY_PROVIDER_UNAVAILABLE:'No se pudo verificar Clerk. Conservá el intento y comprobá su estado.',PARTICIPANT_OPERATION_CONFLICT:'Este intento corresponde a una solicitud distinta. No se reemplazó.',PARTICIPANT_PRIVATE_STORAGE_UNCONFIRMED:'No se confirmó el guardado privado de las imágenes. Conservá el intento.',PARTICIPANT_KYC_INTEGRITY:'El archivo no coincide con la evidencia presentada. No se mostró.',PARTICIPANT_PRIVACY_REQUIRED:'Leé el aviso y confirmá el uso de tus imágenes para revisión.',PARTICIPANT_OFFICE_ROLE_PROTECTED:'Este acceso está protegido o fue deshabilitado. No se modificó el rol.',WORKSPACE_ORGANIZATION_PERMISSION_REQUIRED:'Sólo el administrador puede cambiar los roles de empresa.'};
function useParticipantRequest(getSessionToken){
 const request=useWorkspaceRequest(getSessionToken);
 return async function api(params,options={},resource=endpoint,image=false){
  if(typeof getSessionToken!=='function')throw Object.assign(new Error('Tu sesión terminó. Volvé a ingresar.'),{status:401,code:'SESSION_REQUIRED',requestDispatched:false});
  const requestTimeoutMs=options.requestTimeoutMs??(options.method==='POST'?30000:params?.operationId?15000:20000);
  return request(resource+(params?'?'+new URLSearchParams(params):''),{...options,requestTimeoutMs},async response=>{
   if(!response.ok){const value=await response.json();const error=new Error(errors[value.code]||'No se pudo confirmar la operación. Comprobá el estado antes de repetirla.');error.status=response.status;error.code=value.code;throw error;}
   return image?await response.blob():await response.json();
  });
 };
}
function refreshedDraft(draft,value){
 const p=draft.payload,office=draft.action==='SET_OFFICE_ROLE',target=office?value.existingAccounts?.find(row=>row.membershipId===p.membershipId):value.records?.find(row=>row.id===p.workerId);
 if(!target)return {allowed:false,description:value.nextCursor?'El registro no aparece en esta página. Consultá más participantes para buscarlo en el estado actualizado.':'El registro ya no está disponible con tu acceso vigente.'};
 let allowed=false;
 if(office)allowed=value.canManageOfficeRoles&&target.canChangeRole;
 else if(draft.action==='INVITE')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked||target.status==='INVITED'&&target.invitation?.state==='SENT'&&target.invitation.expired===true);
 else if(draft.action==='ASSIGN_EXISTING')allowed=value.canInvite&&target.active&&(target.status==='NOT_INVITED'||target.status==='REVOKED'&&!target.accountLinked)&&value.existingAccounts?.some(row=>row.membershipId===p.membershipId&&row.status==='ACTIVE');
 else if(draft.action==='REVOKE')allowed=value.canManage&&target.active&&!['NOT_INVITED','REVOKED'].includes(target.status);
 else if(draft.action==='RESTORE_ACCESS')allowed=value.canManage&&target.active&&target.status==='REVOKED'&&target.accountLinked;
 else if(draft.action==='SUBMIT_KYC')allowed=target.self&&target.active&&target.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(target.kyc.status)&&value.privacyNotice.version===p.noticeVersion;
 else if(draft.action==='REVIEW_KYC')allowed=value.canManage&&!target.self&&target.active&&target.status==='ACTIVE'&&target.kyc.status==='PENDING_REVIEW'&&target.kyc.submissionId===p.submissionId&&target.kyc.images.length===2;
 return {allowed,revision:target.revision,description:office?'Rol vigente: '+target.roleLabel:'Participación: '+(labels[target.status]||target.status)+'. Identidad: '+(labels[target.kyc.status]||target.kyc.status)+'.'};
}
export function ParticipantPanel({projectId,scope,onPending,getSessionToken}){
 const api=useParticipantRequest(getSessionToken);
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[draft,setDraft]=useState(null),[attempt,setAttempt]=useState(null),[receipt,setReceipt]=useState(null),[images,setImages]=useState({}),[recoveryRecord,setRecoveryRecord]=useState(null),[revisionReview,setRevisionReview]=useState(null),[accessBlocked,setAccessBlocked]=useState(false);
 const alive=useRef(true),sequence=useRef(0),fileSequence=useRef(0),urls=useRef([]);
 useEffect(()=>{alive.current=true;const allocatedUrls=urls.current;return()=>{alive.current=false;allocatedUrls.forEach(url=>URL.revokeObjectURL(url));};},[]);
 useEffect(()=>{onPending?.(busy||Boolean(attempt)||Boolean(draft));return()=>onPending?.(false);},[busy,attempt,draft,onPending]);
 useEffect(()=>{if(!draft&&!attempt)return;const warn=event=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft,attempt]);
 function hideDenied(error){if(error.status!==401&&error.status!==403&&error.code!=='WORKSPACE_CONTEXT_CHANGED')return false;fileSequence.current++;urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});setData(null);setRecoveryRecord(null);setReceipt(null);setAccessBlocked(true);if(draft)setRevisionReview({state:'STALE'});return true;}
 async function load(append=false){if(busy||attempt)return;setBusy(true);const current=++sequence.current;try{const value=await api({projectId,scope,...(append&&data?.nextCursor?{after:data.nextCursor}:{})});if(!alive.current||current!==sequence.current)return;if(value.projectId!==projectId||value.scope!==scope)throw new Error('La respuesta no corresponde a esta obra.');const fresh=append?{...value,records:[...data.records,...value.records]}:value;setAccessBlocked(false);setData(fresh);if(draft&&revisionReview){setRevisionReview({state:'LOADED',...refreshedDraft(draft,fresh)});if(draft.action==='REVIEW_KYC'){urls.current.forEach(url=>URL.revokeObjectURL(url));urls.current.length=0;setImages({});}setNotice('Consultamos el estado vigente. Tu borrador se conserva; revisá el cambio antes de continuar.');}}catch(error){if(alive.current&&current===sequence.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current&&current===sequence.current)setBusy(false);}}
 async function confirm(value,command){const office=command.action==='SET_OFFICE_ROLE',matches=office?value.account?.membershipId===command.payload.membershipId:value.participant?.id===(command.payload?.workerId||command.workerId);if(!matches||value.saved!==true||value.scope!==scope||!value.receiptId)throw new Error('No se confirmó un recibo válido de esta obra.');setAccessBlocked(false);setReceipt(value.receiptId);setAttempt(null);setRecoveryRecord(null);setDraft(null);setNotice(office?'El cambio de rol quedó registrado con recibo. La lista muestra el permiso vigente de la cuenta en la empresa.':'Operación guardada con recibo. La revisión humana y la habilitación de WhatsApp se acreditan por separado.');try{const fresh=await api({projectId,scope});if(alive.current&&fresh.projectId===projectId&&fresh.scope===scope)setData(fresh);}catch(error){if(alive.current){if(hideDenied(error))setNotice('El recibo quedó confirmado, pero tu acceso vigente ya no permite consultar esta obra.');else setNotice('El recibo está confirmado. Actualizá la lista para consultar el estado vigente.');}}}
 async function save(event){event.preventDefault();if(busy||attempt||!draft||revisionReview||accessBlocked)return;const operationId=crypto.randomUUID(),command=draft.action==='SUBMIT_KYC'?{operationId,projectId,scope,...draft.payload}:{operationId,projectId,scope,action:draft.action,payload:draft.payload};setAttempt(command);setBusy(true);setNotice('');setReceipt(null);
  try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),requestTimeoutMs:draft.action==='SUBMIT_KYC'?55000:30000});if(alive.current)await confirm(value,command);}catch(error){if(alive.current){hideDenied(error);if(error.requestDispatched===false||error.status&&error.status<500){setAttempt(null);if(error.code==='PARTICIPANT_REVISION_CHANGED')setRevisionReview({state:'STALE'});setNotice(error.message);}else setNotice('El resultado quedó sin confirmar. Comprobá el recibo antes de volver a enviar.');}}finally{if(alive.current)setBusy(false);}}
 async function recover(){if(!attempt||busy)return;setBusy(true);try{if(attempt.action==='RECOVER_INVITATION'){const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt)});if(alive.current)await confirm(value,attempt);return;}const value=await api({projectId,scope,operationId:attempt.operationId});if(!alive.current)return;if(value.scope!==scope||value.projectId!==undefined&&value.projectId!==projectId)throw new Error('La respuesta no corresponde a esta obra.');setAccessBlocked(false);if(value.state==='RECORDED')await confirm(value,attempt);else if(value.state==='INVITATION_UNCONFIRMED'&&value.participant?.invitation?.id){setRecoveryRecord(value.participant);const recovered=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:value.participant.id,invitationId:value.participant.invitation.id}})});if(alive.current)await confirm(recovered,attempt);}else setNotice('Todavía no se observa un recibo. No se repitió la operación ni se declaró perdida.');}catch(error){if(alive.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 async function retryExact(){if(!attempt||busy||attempt.action==='INVITE'||accessBlocked)return;setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(attempt),requestTimeoutMs:attempt.front?55000:30000});if(alive.current)await confirm(value,attempt);}catch(error){if(alive.current){hideDenied(error);if(error.code==='PARTICIPANT_REVISION_CHANGED'&&draft){setAttempt(null);setRevisionReview({state:'STALE'});}setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 async function revokeUncertain(){if(busy||!recoveryRecord||accessBlocked)return;const previous=attempt,command={operationId:crypto.randomUUID(),projectId,scope,action:'REVOKE',payload:{workerId:recoveryRecord.id,revision:recoveryRecord.revision,reason:'El administrador revocó explícitamente una invitación cuyo envío no se pudo confirmar.'}};setAttempt(command);setRecoveryRecord(null);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});if(alive.current)await confirm(value,command);}catch(error){if(alive.current){const denied=hideDenied(error);if(error.requestDispatched===false||error.status&&error.status<500){setAttempt(previous);if(!denied)setRecoveryRecord(recoveryRecord);}setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 function begin(action,row){fileSequence.current++;setDraft({action,payload:action==='INVITE'?{workerId:row.id,revision:row.revision,email:''}:['REVOKE','RESTORE_ACCESS'].includes(action)?{workerId:row.id,revision:row.revision,reason:''}:action==='REVIEW_KYC'?{workerId:row.id,revision:row.revision,submissionId:row.kyc.submissionId,decision:'APPROVED',reason:''}:{workerId:row.id,revision:row.revision,noticeVersion:data.privacyNotice.version,consent:false,front:'',selfie:''}});setNotice('');setReceipt(null);}
 function edit(key,value){setDraft(prior=>({...prior,payload:{...prior.payload,[key]:value}}));}
 function changeOfficeRole(account){setDraft({action:'SET_OFFICE_ROLE',payload:{membershipId:account.membershipId,revision:account.revision,role:account.role,reason:''},accountName:account.name});setNotice('');setReceipt(null);}
 function assignExisting(row){setDraft({action:'ASSIGN_EXISTING',payload:{workerId:row.id,revision:row.revision,membershipId:'',reason:''}});setNotice('');setReceipt(null);}
 async function chooseFile(key,event){setNotice('');const file=event.target.files?.[0],current=++fileSequence.current;edit(key,'');if(!file)return;if(file.size>1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type)){setNotice('Elegí JPEG, PNG o WebP de hasta 1 MB por imagen.');return;}setBusy(true);try{const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('No se pudo leer la imagen.'));reader.readAsDataURL(file);});if(alive.current&&current===fileSequence.current)edit(key,content);}catch(error){if(alive.current&&current===fileSequence.current)setNotice(error.message);}finally{if(alive.current&&current===fileSequence.current)setBusy(false);}}
 async function viewImage(row,image){if(busy||attempt)return;setBusy(true);try{const blob=await api({projectId,scope,workerId:row.id,imageId:image.id},{},endpoint,true);if(!alive.current)return;if(blob.size!==image.bytes||blob.type!==image.contentType)throw new Error('La imagen recibida no coincide con la presentación.');const url=URL.createObjectURL(blob);urls.current.push(url);setImages(prior=>({...prior,[imageKey(row,image)]:url}));}catch(error){if(alive.current){hideDenied(error);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 async function recoverInvitation(row){if(busy||attempt)return;const command={operationId:crypto.randomUUID(),projectId,scope,action:'RECOVER_INVITATION',payload:{workerId:row.id,invitationId:row.invitation.id}};setAttempt(command);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});if(alive.current)await confirm(value,command);}catch(error){if(alive.current){hideDenied(error);if(error.requestDispatched===false)setAttempt(null);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 const locked=busy||Boolean(attempt),p=draft?.payload,reviewTarget=data?.records.find(row=>row.id===p?.workerId);
 const reviewImagesReady=draft?.action!=='REVIEW_KYC'||reviewTarget?.kyc.images.length===2&&reviewTarget.kyc.images.every(image=>images[imageKey(reviewTarget,image)]);
 return <section className={styles.panel} aria-labelledby="participant-title"><div className={styles.heading}><div><p className={styles.eyebrow}>PERSONAS Y ACCESO</p><h3 id="participant-title">Participantes y revisión de identidad</h3></div><button type="button" disabled={locked||Boolean(data&&draft)&&!revisionReview} onClick={()=>load()}>{revisionReview?'Actualizar registro conservando borrador':'Consultar participantes'}</button></div>
  <p>Una ficha del equipo no concede acceso. La invitación exige cuenta y correo verificado; la identidad requiere la decisión de otro responsable.</p><p role="status" aria-live="polite">{notice}</p>
  {accessBlocked&&<p>Ocultamos los datos y las imágenes de esta obra porque no pudimos confirmar tu acceso vigente.{attempt?' Conservamos el intento pendiente: comprobá su estado sin volver a enviarlo.':' Volvé a consultar cuando recuperes tu acceso.'}</p>}
  {data&&<><p>{data.canManage?'Invitaciones y participación de campo en esta obra. Los permisos de empresa se administran por separado.':'Tu participación en esta obra. Sólo podés presentar y consultar tu propia identidad.'}</p><div className={styles.list}>{data.records.map(row=><article key={row.id} className={styles.card}><div className={styles.heading}><strong>{row.name}</strong><span>{labels[row.status]||row.status}</span></div><p>Identidad: {labels[row.kyc.status]||row.kyc.status}</p>{row.invitation&&<p>{labels[row.invitation.state]||row.invitation.state}{row.invitation.email?' · '+row.invitation.email:''}</p>}
    {row.kyc.review&&<p>Decisión registrada: {row.kyc.review.reason}</p>}
    <div className={styles.actions}>{data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked)||(row.status==='INVITED'&&row.invitation?.state==='SENT'&&row.invitation.expired===true))&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('INVITE',row)}>Invitar a esta obra</button>}{data.canManage&&row.active&&row.status==='REVOKED'&&row.accountLinked&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('RESTORE_ACCESS',row)}>Revisar y reactivar participación</button>}{data.canManage&&row.status!=='NOT_INVITED'&&row.status!=='REVOKED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('REVOKE',row)}>Revocar participación de campo</button>}{data.canManage&&row.invitation?.state==='ATTEMPTED'&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>recoverInvitation(row)}>Comprobar invitación en Clerk</button>}{row.self&&row.status==='ACTIVE'&&['NOT_SUBMITTED','REJECTED'].includes(row.kyc.status)&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>begin('SUBMIT_KYC',row)}>Presentar mi identidad</button>}</div>
    {/* Private object URLs must stay in this browser; an image optimizer must not receive KYC evidence. */}
    {/* eslint-disable-next-line @next/next/no-img-element */}
    {row.kyc.images.map(image=><div key={image.id} className={styles.evidence}><button disabled={locked} type="button" onClick={()=>viewImage(row,image)}>{image.kind==='SELFIE'?'Consultar fotografía':'Consultar documento privado'}</button>{images[imageKey(row,image)]&&<img src={images[imageKey(row,image)]} alt={image.kind==='SELFIE'?'Fotografía presentada para revisión de identidad':'Documento presentado para revisión de identidad'}/>}</div>)}
    {data.canInvite&&row.active&&(row.status==='NOT_INVITED'||(row.status==='REVOKED'&&!row.accountLinked))&&data.existingAccounts?.length>0&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>assignExisting(row)}>Asignar una cuenta de la empresa</button>}
    {data.canManage&&!row.self&&row.kyc.status==='PENDING_REVIEW'&&<button disabled={locked||Boolean(draft)||row.kyc.images.some(image=>!images[imageKey(row,image)])} type="button" onClick={()=>begin('REVIEW_KYC',row)}>Registrar revisión humana</button>}
   </article>)}</div>{!data.records.length&&<p>No hay participantes vinculados a tu cuenta en esta obra.</p>}{data.nextCursor&&<button disabled={locked||Boolean(draft)&&revisionReview?.state!=='LOADED'} type="button" onClick={()=>load(true)}>Consultar más participantes</button>}</>}
  {data?.canManageOfficeRoles&&<details className={styles.office}><summary>Permisos de las cuentas en la empresa</summary><p>El rol pertenece a la cuenta verificada y se conserva al vincularla a una ficha. Revocar una participación de campo no elimina los permisos de oficina: Dirección mantiene su acceso a todas las obras de la empresa.</p><p>Los administradores y tu propia cuenta tienen acceso protegido. Esta sección no crea administradores ni cambia roles en Clerk.</p><div className={styles.list}>{data.existingAccounts.map(account=><article key={account.membershipId} className={styles.card}><div className={styles.heading}><strong>{account.name}{account.self?' · Tu cuenta':''}</strong><span>Rol de empresa: {account.roleLabel}</span></div><p>{account.email}</p><p>{account.roleScope}</p>{account.canChangeRole&&<button disabled={locked||Boolean(draft)} type="button" onClick={()=>changeOfficeRole(account)}>Cambiar rol de {account.name}</button>}</article>)}</div>{data.existingAccountsTruncated&&<p>Se muestran las primeras 100 cuentas. Las restantes requieren consulta del administrador.</p>}</details>}
  {data&&draft&&<form className={styles.form} onSubmit={save}><h4>{draft.action==='INVITE'?'Enviar invitación de acceso':draft.action==='REVOKE'?'Revocar participación':draft.action==='RESTORE_ACCESS'?'Reactivar participación existente':draft.action==='REVIEW_KYC'?'Decisión del responsable':draft.action==='ASSIGN_EXISTING'?'Vincular cuenta existente':draft.action==='SET_OFFICE_ROLE'?'Cambiar rol de empresa':'Presentar identidad privada'}</h4>
   {draft.action==='SET_OFFICE_ROLE'&&<><p>Cuenta: <strong>{draft.accountName}</strong>. El cambio aplica a sus permisos en toda la empresa. Conserva las obras asignadas y la vinculación de campo; se comprueba la cuenta vigente antes de guardar.</p><label>Rol de empresa<select required disabled={locked} value={p.role} onChange={event=>edit('role',event.target.value)}>{Object.entries(data.officeRoles).map(([role,value])=><option key={role} value={role}>{value.label}</option>)}</select></label><p className={styles.scope}>{data.officeRoles[p.role]?.scope}</p></>}
   {draft.action==='REVOKE'&&<p>Se bloquean los fichajes y reportes de esta participación. Una cuenta con rol de oficina conserva sus permisos de empresa. Dirección continúa accediendo a todas las obras.</p>}
   {draft.action==='ASSIGN_EXISTING'&&<><p>Seleccioná una cuenta vigente de esta empresa para vincularla a la ficha. Se conserva el rol indicado en la lista, incluidos sus permisos de consulta o gestión, y se habilita su participación en esta obra. El servidor vuelve a comprobar la pertenencia y el correo en Clerk.</p><label>Cuenta de la empresa<select required disabled={locked} value={p.membershipId} onChange={event=>edit('membershipId',event.target.value)}><option value="">Seleccioná una cuenta</option>{data.existingAccounts.map(account=><option key={account.membershipId} value={account.membershipId}>{account.name} · {account.email} · {account.roleLabel}</option>)}</select></label>{data.existingAccountsTruncated&&<p>Se muestran las primeras 100 cuentas. Las restantes requieren consulta del administrador.</p>}</>}
   {draft.action==='INVITE'&&<><p>Clerk enviará una invitación por correo. El acceso permite consultar esta obra y presentar fichajes y evidencia propios; no permite aprobar avances ni administrar personas.</p><label>Correo del participante<input required type="email" maxLength={254} disabled={locked} value={p.email} onChange={event=>edit('email',event.target.value)}/></label></>}
   {draft.action==='REVIEW_KYC'&&<><p>Registrá tu revisión de las dos imágenes. La decisión no equivale a una certificación civil ni habilita WhatsApp.</p><label>Decisión<select disabled={locked} value={p.decision} onChange={event=>edit('decision',event.target.value)}><option value="APPROVED">Aprobar para esta obra</option><option value="REJECTED">Solicitar corrección</option></select></label></>}
   {['REVIEW_KYC','REVOKE','RESTORE_ACCESS','ASSIGN_EXISTING','SET_OFFICE_ROLE'].includes(draft.action)&&<label>Fundamento<textarea required minLength={8} maxLength={800} disabled={locked} value={p.reason} onChange={event=>edit('reason',event.target.value)}/></label>}
   {draft.action==='SUBMIT_KYC'&&<><p>{data.privacyNotice.text}</p><label>Frente del documento · hasta 1 MB<input required disabled={locked} type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>chooseFile('front',event)}/></label><label>Fotografía del rostro · hasta 1 MB<input required disabled={locked} type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>chooseFile('selfie',event)}/></label><label className={styles.consent}><input required type="checkbox" disabled={locked} checked={p.consent} onChange={event=>edit('consent',event.target.checked)}/>Leí el aviso y autorizo la presentación de estas imágenes para revisión.</label></>}
   {revisionReview&&<div role="status"><p>{revisionReview.state==='STALE'?'Actualizá el registro para revisar el cambio sin perder tu borrador.':revisionReview.description}</p>{revisionReview.state==='LOADED'&&(revisionReview.allowed?<><p>{draft.action==='REVIEW_KYC'?'Volvé a consultar las dos imágenes de esta presentación antes de confirmar la revisión.':''}</p><button type="button" disabled={busy||!reviewImagesReady} onClick={()=>{setDraft(prior=>({...prior,payload:{...prior.payload,revision:revisionReview.revision}}));setRevisionReview(null);setNotice('Revisaste el estado vigente. Podés guardar tu solicitud cuando estés de acuerdo.');}}>Revisé el estado vigente y quiero continuar</button></>:!data.nextCursor&&<p>El estado vigente no permite repetir esta decisión. Conservamos tu texto para consultarlo; cancelá este borrador y revisá el registro antes de iniciar otra solicitud.</p>)}</div>}
   <div className={styles.actions}><button disabled={locked||Boolean(revisionReview)||(draft.action==='SUBMIT_KYC'&&(!p.front||!p.selfie||!p.consent))} type="submit">{draft.action==='INVITE'?'Enviar invitación':draft.action==='SUBMIT_KYC'?'Presentar para revisión':draft.action==='SET_OFFICE_ROLE'?'Guardar rol de empresa':'Guardar decisión'}</button><button type="button" disabled={locked} onClick={()=>{fileSequence.current++;setDraft(null);setRevisionReview(null);}}>Cancelar</button></div>
  </form>}{attempt&&<div className={styles.actions}><button disabled={busy} type="button" onClick={recover}>Comprobar el mismo intento</button>{attempt.action!=='INVITE'&&!accessBlocked&&<button disabled={busy} type="button" onClick={retryExact}>Reintentar exactamente esta solicitud</button>}{recoveryRecord&&<button disabled={busy} type="button" onClick={revokeUncertain}>Revocar acceso de esta invitación pendiente</button>}</div>}{recoveryRecord&&<p>Si el correo llega después, esta revocación impedirá completar el acceso mediante esa invitación.</p>}{receipt&&<p className={styles.receipt}>Recibo: {receipt}</p>}
 </section>;
}
const readInvitation=()=>{const params=new URLSearchParams(window.location.search);return params.getAll('participar').length===1&&/^invite_[a-f0-9]{32}$/.test(params.get('participar'))?params.get('participar'):'';};
const subscribeInvitation=callback=>{window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback);};
const emptyInvitation=()=>'';
export function ParticipantSelfServicePanel({getSessionToken}){
 const api=useParticipantRequest(getSessionToken);
 const invitationId=useSyncExternalStore(subscribeInvitation,readInvitation,emptyInvitation);const [data,setData]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[attempt,setAttempt]=useState(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function load(){if(busy||!invitationId)return;setBusy(true);try{const value=await api({invitationId},{},joinEndpoint);if(alive.current)setData(value);}catch(error){if(alive.current)setNotice(error.message);}finally{if(alive.current)setBusy(false);}}
 async function accept(){if(busy||!data)return;const retrying=Boolean(attempt),command=attempt||{invitationId,operationId:crypto.randomUUID()};setAttempt(command);setBusy(true);try{const value=await api(null,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)},joinEndpoint);if(alive.current){if(value.joined!==true||value.saved!==true||!value.receiptId)throw new Error('No se confirmó el acceso.');setAttempt(null);setNotice('Tu participación quedó registrada. Actualizá tu cuenta para abrir la obra y presentar tu identidad.');setData(prior=>({...prior,canAccept:false,state:'ACTIVE'}));}}catch(error){if(alive.current){if(!retrying&&(error.requestDispatched===false||error.status&&error.status<500))setAttempt(null);setNotice(error.message);}}finally{if(alive.current)setBusy(false);}}
 if(!invitationId)return null;return <section className={styles.panel}><h2>Completar mi invitación de obra</h2><p>Ingresá con el correo invitado, aceptá el enlace de Clerk y seleccioná la organización indicada antes de continuar.</p><p role="status" aria-live="polite">{notice}</p>{!data?<button type="button" disabled={busy} onClick={load}>Consultar mi invitación</button>:<><p><strong>{data.organizationName}</strong> · {data.projectName}</p><p>Participante: {data.participantName}. Acceso de campo propio y consulta de esta obra.</p>{data.state==='ACTIVE'&&<a href='/cuenta'>Abrir mi obra en la cuenta</a>}{data.canAccept&&<button type="button" disabled={busy} onClick={accept}>{attempt?'Comprobar la misma aceptación':'Aceptar participación en esta obra'}</button>}</>}</section>;
}
