import {verifyWorkspaceSession} from '../../../../lib/verified-session.mjs';
import {productionWorkspace} from '../../../../lib/workspace-runtime.mjs';
import {createCompanyChannelStore} from '../../../../lib/company-channel-store.mjs';
import {createCompanyChannelHandlers} from '../../../../lib/company-channel-http.mjs';
import {createOwnCompanyConnection} from '../../../../lib/meta-own-company-connection.mjs';
import {createMetaCustomerProvider} from '../../../../lib/meta-customer-provider.mjs';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const ownConnection=createOwnCompanyConnection({workspace:productionWorkspace,provider:createMetaCustomerProvider()});
const handlers=createCompanyChannelHandlers({verify:verifyWorkspaceSession,store:createCompanyChannelStore({workspace:productionWorkspace,ownConnection})});
export const GET=handlers.GET;
export const POST=handlers.POST;
