import assert from 'node:assert/strict';
import test from 'node:test';
import { linkJournalDraftToTask } from '../src/lib/journal-task-link.js';
import { confirmedJournalTaskLink, normalizeJournalTaskLink } from '../src/lib/journal-task-link-policy.js';
const scope = { organizationId: 'org-a', projectId: 'project-a' };
const options = change => ({ scope, actorId: 'actor-a', recordId: 'log-a', operationKey: 'request-00000000001', input: { taskId: 'task-a', expectedRevision: 0 }, ...change });
function database() {
  const state = { row: { id: 'log-a', projectId: scope.projectId, taskId: null, title: 'Parte de prueba', summary: 'Texto original', workDate: new Date('2026-09-18'), status: 'DRAFT', revision: 0 }, receipts: [], taskExists: true, projectExists: true, projectStatus: 'ACTIVE', failAudit: false, race: false, writes: 0 };
  const tx = { $executeRawUnsafe: async () => 1,
    project: { findFirst: async ({ where }) => state.projectExists && where.organizationId === scope.organizationId && where.id === scope.projectId ? { id: scope.projectId, organizationId: scope.organizationId, status: state.projectStatus } : null },
    dailyLog: { findFirst: async ({ where }) => state.row && where.id === state.row.id && where.projectId === state.row.projectId ? structuredClone(state.row) : null,
      updateMany: async ({ where, data }) => { if (state.race || Object.entries(where).some(([k, v]) => state.row[k] !== v)) return { count: 0 }; state.writes++; state.row.taskId = data.taskId; state.row.revision++; return { count: 1 }; } },
    task: { findFirst: async ({ where }) => { assert.equal(where.projectId, scope.projectId); assert.equal(where.type, 'TASK'); assert.equal(where.metadata.equals, 'canonical-task-v1'); return state.taskExists && ['task-a', 'task-b'].includes(where.id) ? { id: where.id } : null; } },
    auditLog: { findFirst: async ({ where }) => structuredClone(state.receipts.find(row => Object.entries(where).every(([k, v]) => row[k] === v)) || null), create: async ({ data }) => { if (state.failAudit) throw new Error('AUDIT_FAILED'); state.receipts.push(structuredClone(data)); return data; } },
  };
  let queue = Promise.resolve();
  return { state, prisma: { $transaction(operation) { const result = queue.then(async () => { const before = structuredClone(state); try { return await operation(tx); } catch (e) { Object.assign(state, before); throw e; } }); queue = result.catch(() => {}); return result; } } };
}
test('links the original draft without replacing content or making a second report', async () => {
  const { prisma, state } = database(); const result = await linkJournalDraftToTask(prisma, options());
  assert.equal(result.dailyLog.id, 'log-a'); assert.equal(result.dailyLog.status, 'DRAFT'); assert.equal(result.dailyLog.revision, 1); assert.equal(result.dailyLog.summary, 'Texto original'); assert.equal(state.receipts.length, 1); assert.equal(state.receipts[0].metadata.previousTaskId, null);
  assert.ok(!JSON.stringify(state.receipts).includes('Texto original'));
  assert.equal(confirmedJournalTaskLink(result, { recordId: 'log-a', projectId: scope.projectId, taskId: 'task-a', expectedRevision: 0 }), result.dailyLog);
});
test('retry after response loss produces one write and one audit event', async () => { const { prisma, state } = database(); const first = await linkJournalDraftToTask(prisma, options()); const second = await linkJournalDraftToTask(prisma, options()); assert.equal(first.assignment.replayed, false); assert.equal(second.assignment.replayed, true); assert.equal(state.writes, 1); assert.equal(state.receipts.length, 1); });
test('two concurrent retries retain a single assignment receipt', async () => { const { prisma, state } = database(); const results = await Promise.all([linkJournalDraftToTask(prisma, options()), linkJournalDraftToTask(prisma, options())]); assert.equal(results.filter(row => row.assignment.replayed).length, 1); assert.equal(state.writes, 1); });
test('replay after review does not roll the record back to draft', async () => { const { prisma, state } = database(); await linkJournalDraftToTask(prisma, options()); state.row.status = 'APPROVED'; state.row.revision = 3; const result = await linkJournalDraftToTask(prisma, options()); assert.equal(result.dailyLog.status, 'APPROVED'); assert.equal(state.row.revision, 3); });
test('same operation with different task fails instead of redirecting content', async () => { const { prisma } = database(); await linkJournalDraftToTask(prisma, options()); await assert.rejects(linkJournalDraftToTask(prisma, options({ input: { taskId: 'task-b', expectedRevision: 0 } })), { code: 'JOURNAL_TASK_LINK_REPLAY_CONFLICT' }); });
test('later assignment is not overwritten by an old retry', async () => { const { prisma, state } = database(); await linkJournalDraftToTask(prisma, options()); await linkJournalDraftToTask(prisma, options({ operationKey: 'request-00000000002', input: { taskId: 'task-b', expectedRevision: 1 } })); await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'JOURNAL_TASK_LINK_CHANGED' }); assert.equal(state.row.taskId, 'task-b'); assert.equal(state.receipts.length, 2); });
for (const status of ['SUBMITTED', 'APPROVED', 'REJECTED']) test('final or submitted records cannot be reassigned: ' + status, async () => { const { prisma, state } = database(); state.row.status = status; await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'JOURNAL_TASK_LINK_LOCKED' }); assert.equal(state.writes, 0); });
test('stale revision cannot edit the draft', async () => { const { prisma, state } = database(); state.row.revision = 1; await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'JOURNAL_TASK_LINK_STALE' }); assert.equal(state.writes, 0); });
test('cross-company project fails before record changes', async () => { const { prisma, state } = database(); await assert.rejects(linkJournalDraftToTask(prisma, options({ scope: { ...scope, organizationId: 'org-other' } })), { code: 'PROJECT_WRITE_SCOPE_INVALID' }); assert.equal(state.writes, 0); });
test('unknown task does not change the part', async () => { const { prisma, state } = database(); state.taskExists = false; await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'JOURNAL_TASK_LINK_TASK_NOT_FOUND' }); assert.equal(state.writes, 0); });
test('missing report does not leak other project data', async () => { const { prisma } = database(); await assert.rejects(linkJournalDraftToTask(prisma, options({ recordId: 'another-log' })), { code: 'JOURNAL_TASK_LINK_NOT_FOUND' }); });
test('closed project cannot be changed', async () => { const { prisma, state } = database(); state.projectStatus = 'COMPLETED'; await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'PROJECT_READ_ONLY' }); assert.equal(state.writes, 0); });
test('audit failure rolls back assignment', async () => { const { prisma, state } = database(); state.failAudit = true; await assert.rejects(linkJournalDraftToTask(prisma, options()), /AUDIT_FAILED/); assert.equal(state.row.taskId, null); assert.equal(state.row.revision, 0); });
test('version race fails without an audit claim of success', async () => { const { prisma, state } = database(); state.race = true; await assert.rejects(linkJournalDraftToTask(prisma, options()), { code: 'JOURNAL_TASK_LINK_STALE' }); assert.equal(state.receipts.length, 0); });
for (const input of [{ taskId: 'task-a', expectedRevision: -1 }, { taskId: 'task-a', expectedRevision: '1' }, { taskId: 'task-a', expectedRevision: 0, actorId: 'admin' }, { taskId: '../other', expectedRevision: 0 }, null]) test('strict assignment input: ' + JSON.stringify(input), () => assert.throws(() => normalizeJournalTaskLink(input)));
for (const change of [{ taskId: 'other' }, { projectId: 'other' }, { revision: 0 }, { status: 'UNRECOGNIZED' }]) test('invalid response cannot be confirmed: ' + JSON.stringify(change), () => { const response = { dailyLog: { id: 'log-a', projectId: scope.projectId, taskId: 'task-a', status: 'DRAFT', revision: 1, ...change }, assignment: { taskId: 'task-a', appliedRevision: 1, replayed: false } }; assert.throws(() => confirmedJournalTaskLink(response, { recordId: 'log-a', projectId: scope.projectId, taskId: 'task-a', expectedRevision: 0 }), { code: 'JOURNAL_TASK_LINK_UNCONFIRMED' }); });
