import assert from 'node:assert/strict';
import test from 'node:test';
import { BUSINESS_PROFILE_KINDS, businessProfileFromMetadata, normalizeBusinessProfile, businessProfilePaths, updateBusinessProfile } from '../src/lib/organization-business-profile.js';
const options = { organizationId:'org-a',actorId:'actor-a',input:{kind:'CONSTRUCTOR',market:'MIXED',expectedRevision:0} };
function database(metadata = {}) {
 const state={ org:{ id:'org-a',metadata,updatedAt:new Date('2026-09-18T00:00:00Z') }, audits:[],failAudit:false,conflict:false,updates:0,locks:[] };
 const tx={ $executeRawUnsafe:async(sql,...params)=>{state.locks.push({sql,params});return 1;},organization:{
  findUnique:async({where})=>where.id===state.org.id?structuredClone(state.org):null,
  updateMany:async({where,data})=>{assert.equal(where.id,'org-a');assert.equal(where.updatedAt.getTime(),state.org.updatedAt.getTime());if(state.conflict)return{count:0};state.org.metadata=structuredClone(data.metadata);state.updates++;return{count:1};},
 },auditLog:{create:async({data})=>{if(state.failAudit)throw new Error('AUDIT_FAILED');state.audits.push(structuredClone(data));return data;}}};
 return{state,prisma:{$transaction:async(fn)=>{const before=structuredClone(state);try{return await fn(tx);}catch(e){Object.assign(state,before);throw e;}}}};
}
test('no configuration stays explicit, without inventing an organization type',()=>{assert.deepEqual(businessProfileFromMetadata(null),{configured:false,kind:null,market:null,revision:0,updatedAt:null});assert.equal(businessProfileFromMetadata({internal:true}).configured,false);});
for(const kind of BUSINESS_PROFILE_KINDS)test('configured kind accepted: '+kind.key,async()=>{const{prisma,state}=database();const result=await updateBusinessProfile(prisma,{...options,input:{...options.input,kind:kind.key}});assert.equal(result.profile.kind,kind.key);assert.equal(result.profile.revision,1);assert.equal(state.audits.length,1);});
test('profile update preserves unrelated organization metadata and creates attributed audit',async()=>{const metadata={internal:true,aiProcessing:{revision:3,visualProgressEnabled:false},custom:'keep'};const{prisma,state}=database(metadata);await updateBusinessProfile(prisma,options);assert.equal(state.org.metadata.internal,true);assert.deepEqual(state.org.metadata.aiProcessing,metadata.aiProcessing);assert.equal(state.org.metadata.custom,'keep');assert.equal(state.audits[0].actorId,'actor-a');assert.equal(state.audits[0].organizationId,'org-a');assert.equal(state.locks[1].params[0],'org-a');});
test('identical retry verifies saved values without duplicate write or audit',async()=>{const{prisma,state}=database();await updateBusinessProfile(prisma,options);const replay=await updateBusinessProfile(prisma,options);assert.equal(replay.unchanged,true);assert.equal(replay.profile.revision,1);assert.equal(state.updates,1);assert.equal(state.audits.length,1);});
test('stale different choice cannot overwrite another administrator',async()=>{const{prisma,state}=database();await updateBusinessProfile(prisma,options);await assert.rejects(updateBusinessProfile(prisma,{...options,input:{...options.input,kind:'ARCHITECTURE'}}),{code:'BUSINESS_PROFILE_CONFLICT'});assert.equal(state.org.metadata.businessProfile.kind,'CONSTRUCTOR');});
test('new version increments and preserves previous profile in the audit',async()=>{const{prisma,state}=database();await updateBusinessProfile(prisma,options);const result=await updateBusinessProfile(prisma,{...options,input:{kind:'ARCHITECTURE',market:'PRIVATE',expectedRevision:1}});assert.equal(result.profile.revision,2);assert.equal(state.audits[1].metadata.previousKind,'CONSTRUCTOR');});
test('audit failure rolls back the profile',async()=>{const{prisma,state}=database();state.failAudit=true;await assert.rejects(updateBusinessProfile(prisma,options),/AUDIT_FAILED/);assert.deepEqual(state.org.metadata,{});assert.equal(state.updates,0);});
test('CAS conflict does not overwrite metadata',async()=>{const{prisma,state}=database({keep:1});state.conflict=true;await assert.rejects(updateBusinessProfile(prisma,options),{code:'BUSINESS_PROFILE_CONFLICT'});assert.deepEqual(state.org.metadata,{keep:1});assert.equal(state.audits.length,0);});
test('unknown organization never falls back to another tenant',async()=>{const{prisma,state}=database();await assert.rejects(updateBusinessProfile(prisma,{...options,organizationId:'org-b'}),{status:404});assert.equal(state.updates,0);});
for(const override of [{organizationId:'org-b'},{tenantRole:'ADMIN'},{subscriptionPlan:'ENTERPRISE'},{internal:false},{kind:'INVESTOR_PORTAL'},{market:'all'},{expectedRevision:-1},{expectedRevision:'0'}])test('client cannot inject authority or invalid fields: '+Object.keys(override)[0],()=>assert.throws(()=>normalizeBusinessProfile({...options.input,...override})));
for(const metadata of [[], 'invalid', {businessProfile:{}}, {businessProfile:{schemaVersion:2,kind:'CONSTRUCTOR',market:'PRIVATE',revision:1}}])test('unknown stored shape is not overwritten: '+JSON.stringify(metadata),async()=>{const{prisma,state}=database(metadata);await assert.rejects(updateBusinessProfile(prisma,options),{code:'BUSINESS_PROFILE_INTEGRITY'});assert.deepEqual(state.org.metadata,metadata);});
test('customer profile does not grant a route without its permission',()=>{const queried=[];const paths=businessProfilePaths({kind:'DEVELOPER'},permission=>{queried.push(permission);return permission==='org:projects:read';});assert.deepEqual(paths.map(p=>p.href),['/dashboard/projects']);assert.ok(queried.includes('org:contracts:read'));});
test('unconfigured and unknown profiles have no invented routes',()=>{assert.deepEqual(businessProfilePaths(null,()=>true),[]);assert.deepEqual(businessProfilePaths({kind:'unknown'},()=>true),[]);});
test('buyer identity is not a substitute for organization authority',()=>{assert.ok(!BUSINESS_PROFILE_KINDS.some(k=>k.key==='CLIENT' || k.key==='INVESTOR'));assert.ok(BUSINESS_PROFILE_KINDS.every(k=>!Object.hasOwn(k,'role')));});
test('public projection never returns unrelated fields or a malformed timestamp object',()=>{const result=businessProfileFromMetadata({internal:true,businessProfile:{schemaVersion:1,kind:'OWNER',market:'PRIVATE',revision:1,updatedAt:{private:'x'},actor:'hidden'}});assert.equal(result.updatedAt,null);assert.equal(result.actor,undefined);assert.equal(result.internal,undefined);});
