import assert from 'node:assert/strict';
import test from 'node:test';
import { buildWhatsAppChannelHealthMetadata } from '../src/lib/whatsapp/channel-health.js';
import { resolvePilotProofContext, readPilotChannelProof, sendPilotChannelProof, pilotProofReplyText } from '../src/lib/whatsapp/pilot-channel-proof.js';
const env={WHATSAPP_PREVIEW_ALLOWED_PUBLIC_ORIGINS:'https://preview.example.test',NEXT_PUBLIC_APP_URL:'https://preview.example.test',NEXT_PUBLIC_META_APP_ID:'app-fixture',META_APP_SECRET:'fixture-app',META_VERIFY_TOKEN:'fixture-verify',WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:'fixture-key',NEXT_PUBLIC_META_EMBEDDED_SIGNUP_CONFIG_ID:'fixture-config',VERCEL_ENV:'preview',WHATSAPP_PILOT_IMPORT_ENABLED:'true',WHATSAPP_PILOT_ALLOWED_ASSETS:'222333444555:111222333444'};
const principal={isSuperadmin:true,databaseUserId:'actor-a',userId:'user-a'};
const now=new Date('2026-09-19T01:00:00Z');
function fixture(){
 const state={membership:true,remote:true,internal:false,allowed:true,status:'CONNECTED',inbound:true,reply:null,sends:[]};
 const project={id:'project-a',organizationId:'org-a',name:'Obra piloto',organization:{id:'org-a',name:'Empresa piloto',clerkOrganizationId:'org_clerk',metadata:{internal:false}}};
 const connection={id:'connection-a',projectId:'project-a',phoneNumberId:'111222333444',whatsappBusinessId:'222333444555',displayPhoneNumber:'+15551230000',enabled:true,connectionStatus:'CONNECTED',embeddedSignupVersion:'pilot-preview-v1',metadata:buildWhatsAppChannelHealthMetadata({},{expiresAt:0,scopes:['whatsapp_business_management','whatsapp_business_messaging'],subscribed:true,phoneStatus:'CONNECTED',qualityRating:'GREEN'},{now})};
 const inbound={id:'inbound-a',conversationId:'conversation-a',sentAt:now,createdAt:now,conversation:{id:'conversation-a',projectId:'project-a',externalId:'meta:5492613168608'}};
 const prisma={project:{findFirst:async({where})=>where.id==='project-a'?{...project,organization:{...project.organization,metadata:{internal:state.internal}}}:null},
  tenantMembership:{findUnique:async({where})=>{assert.deepEqual(where.organizationId_userId,{organizationId:'org-a',userId:'actor-a'});return state.membership?{id:'membership-a',status:'ACTIVE',tenantRole:'ADMIN'}:null;}},
  whatsAppConnection:{findUnique:async({where,select})=>{assert.equal(where.projectId,'project-a');assert.equal(select.encryptedAccessToken,undefined);return {...connection,connectionStatus:state.status,phoneNumberId:state.allowed?connection.phoneNumberId:'9999999999'};}},
  message:{findFirst:async({where})=>{if(where.direction==='INBOUND'){assert.equal(where.conversation.projectId,'project-a');return state.inbound&&(!where.id||where.id==='inbound-a')?inbound:null;}assert.equal(where.conversationId,'conversation-a');return state.reply;}}
 };
 const clerk={organizations:{getOrganizationMembershipList:async({organizationId,userId})=>{assert.equal(organizationId,'org_clerk');assert.deepEqual(userId,['user-a']);return{data:state.remote?[{role:'org:admin',publicUserData:{userId:'user-a'}}]:[]};}}};
 return{state,prisma,clerk,project,connection,inbound,resolve:()=>resolvePilotProofContext({prisma,clerk,principal,projectId:'project-a',environment:env})};
}
const command={projectId:'project-a',connectionId:'connection-a',inboundId:'inbound-a',confirmSend:true};
test('reads a pilot only after local and remote administrative membership and exact asset checks',async()=>{const f=fixture();const c=await f.resolve();assert.equal(c.access.databaseUserId,'actor-a');assert.equal(c.access.tenantMembershipId,'membership-a');assert.equal(c.project.organizationId,'org-a');});
for(const [flag,value]of [['membership',false],['remote',false],['internal',true],['allowed',false],['status','PENDING']])test('fails closed for '+flag,async()=>{const f=fixture();f.state[flag]=value;await assert.rejects(f.resolve());assert.equal(f.state.sends.length,0);});
for(const environment of [{...env,VERCEL_ENV:'production'},{...env,WHATSAPP_PILOT_IMPORT_ENABLED:'false'}])test('disabled or production cannot run diagnostics',async()=>{await assert.rejects(resolvePilotProofContext({prisma:{},clerk:{},principal,projectId:'project-a',environment}),{status:404});});
test('ordinary tenant user cannot use the platform pilot tool',async()=>{await assert.rejects(resolvePilotProofContext({principal:{...principal,isSuperadmin:false},environment:env}),{status:404});});
test('does not fall back to another project',async()=>{const f=fixture();await assert.rejects(resolvePilotProofContext({prisma:f.prisma,clerk:f.clerk,principal,projectId:'foreign',environment:env}),{status:404});});
test('only existence, timestamp and last four digits leave the proof read model',async()=>{const f=fixture();const result=await readPilotChannelProof({prisma:f.prisma,context:await f.resolve(),env,now});assert.equal(result.inbound.contactLast4,'8608');assert.equal(result.inbound.canReply,true);assert.equal(result.workersAuthorizedByThisAction,false);assert.equal(result.reply,null);assert.ok(!JSON.stringify(result).includes('5492613168608'));assert.equal(result.inbound.body,undefined);});
test('absence of a received message is not represented as success',async()=>{const f=fixture();f.state.inbound=false;const result=await readPilotChannelProof({prisma:f.prisma,context:await f.resolve(),env,now});assert.equal(result.inbound,null);assert.equal(result.reply,null);});
for(const hours of [-1,24,25])test('does not offer free-form reply outside care window: '+hours,async()=>{const f=fixture();const result=await readPilotChannelProof({prisma:f.prisma,context:await f.resolve(),env,now:new Date(now.getTime()+hours*3600000)});assert.equal(result.inbound.canReply,false);});
test('receipt delivery state remains distinct from acceptance',async()=>{const f=fixture();f.state.reply={id:'reply-a',status:'delivered'};const result=await readPilotChannelProof({prisma:f.prisma,context:await f.resolve(),env,now});assert.deepEqual(result.reply,{id:'reply-a',status:'delivered'});});
for(const patch of [{confirmSend:false},{to:'+123'},{body:'arbitrary'},{projectId:'foreign'},{connectionId:'other'},{inboundId:'foreign'}])test('untrusted target or command rejected before send: '+Object.keys(patch)[0],async()=>{const f=fixture();await assert.rejects(sendPilotChannelProof({prisma:f.prisma,context:await f.resolve(),input:{...command,...patch},sendMessage:async()=>{f.state.sends.push(1);}}));assert.equal(f.state.sends.length,0);});
test('canonical sender receives the verified member and deterministic message/key on retry',async()=>{const f=fixture(),context=await f.resolve();const sendMessage=async input=>{f.state.sends.push(input);return{message:{id:'reply-a',status:'sent'},idempotent:f.state.sends.length>1};};const a=await sendPilotChannelProof({prisma:f.prisma,context,input:command,sendMessage});const b=await sendPilotChannelProof({prisma:f.prisma,context,input:command,sendMessage});assert.equal(a.reply.id,b.reply.id);assert.equal(b.idempotent,true);assert.equal(f.state.sends[0].idempotencyKey,f.state.sends[1].idempotencyKey);assert.equal(f.state.sends[0].body,pilotProofReplyText(f.project,f.inbound));assert.equal(f.state.sends[0].access.tenantMembershipId,'membership-a');assert.equal(a.workersAuthorizedByThisAction,false);});
test('missing sender result is not delivery confirmation',async()=>{const f=fixture();await assert.rejects(sendPilotChannelProof({prisma:f.prisma,context:await f.resolve(),input:command,sendMessage:async()=>({})}),{code:'PILOT_PROOF_UNCONFIRMED'});});
