import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {encryptCustomerSecret,decryptCustomerSecret} from '../src/lib/meta-customer-credentials.mjs';
import {createMetaCustomerProvider,metaCustomerReadiness,META_CUSTOMER_INSPECTION_PHASE} from '../src/lib/meta-customer-provider.mjs';
import {createMetaCustomerHandlers} from '../src/lib/meta-customer-http.mjs';
import {verifyMetaCustomerSignature,splitMetaCustomerEvents,createMetaCustomerCallbackHandlers} from '../src/lib/meta-customer-callback.mjs';
import {metaCustomerInboxIntent} from '../src/lib/meta-customer-inbox-review.mjs';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {buildCustomerTemplate,customerRemoteTemplateMatches} from '../src/lib/meta-customer-templates.mjs';
const environment={NEXT_PUBLIC_META_APP_ID:OBRASAAS_META_CHANNEL.appId,META_APP_SECRET:'synthetic-secret-only-12345678',META_CONFIG_ID:'123456789012345',META_GRAPH_API_VERSION:'v25.0',WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:Buffer.alloc(32,21).toString('base64'),META_EMBEDDED_SIGNUP_VERSION:'4',OBRASAAS_META_SIGNUP_RELEASE:'customer-self-service-v1',META_CUSTOMER_VERIFY_TOKEN:'synthetic-verify-token-only-'.repeat(2)};
const context={organizationId:'company-a',projectId:'p-a',purpose:'access-token',resourceId:'123456789'},token='synthetic-customer-token-only-12345678',wabaId='98765432101234',phoneNumberId='98765432105678';
test('customer ciphertext is scoped to organization, project, resource and purpose',()=>{const cipher=encryptCustomerSecret(token,context,environment);assert.doesNotMatch(cipher,/synthetic/);assert.equal(decryptCustomerSecret(cipher,context,environment),token);for(const patch of [{organizationId:'company-b'},{projectId:'p-b'},{resourceId:'other'},{purpose:'webhook'}])assert.throws(()=>decryptCustomerSecret(cipher,{...context,...patch},environment),{code:'META_CUSTOMER_CREDENTIAL_SCOPE_REJECTED'});assert.throws(()=>decryptCustomerSecret(cipher,context,{...environment,WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:Buffer.alloc(32,22).toString('base64')}));});
test('each absent release prerequisite fails closed while stored connection never proves acceptance',()=>{assert.equal(metaCustomerReadiness(environment).canLaunchMeta,true);assert.equal(metaCustomerReadiness(environment).operational,false);for(const name of Object.keys(environment)){const missing={...environment};delete missing[name];assert.equal(metaCustomerReadiness(missing).canLaunchMeta,false,name);}assert.equal(metaCustomerReadiness({...environment,NEXT_PUBLIC_META_APP_ID:'987654321'}).canLaunchMeta,false);});
test('existing embedded signup configuration alias works without regenerating ids and conflicting aliases fail closed',()=>{const existing={...environment,NEXT_PUBLIC_META_EMBEDDED_SIGNUP_CONFIG_ID:environment.META_CONFIG_ID};delete existing.META_CONFIG_ID;assert.equal(metaCustomerReadiness(existing).canLaunchMeta,true);assert.equal(metaCustomerReadiness({...existing,META_CONFIG_ID:'987654321012345'}).canLaunchMeta,false);});
test('dedicated customer key overrides an invalid legacy key without changing legacy configuration',()=>{const env={...environment,WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:'invalid-key',META_CUSTOMER_CREDENTIALS_KEY:Buffer.alloc(32,24).toString('base64')};assert.equal(metaCustomerReadiness(env).canLaunchMeta,true);const cipher=encryptCustomerSecret(token,context,env);assert.equal(decryptCustomerSecret(cipher,context,env),token);assert.equal(env.WHATSAPP_CREDENTIALS_ENCRYPTION_KEY,'invalid-key');});
test('template identity binds content and WABA and remote matches require exact message',()=>{const one=buildCustomerTemplate({id:'connection-a',whatsappBusinessId:wabaId},'participant_invitation'),two=buildCustomerTemplate({id:'connection-b',whatsappBusinessId:'98765432109876'},'participant_invitation');assert.notEqual(one.name,two.name);const remote={id:'12345678',name:one.name,language:one.language,category:'UTILITY',status:'PENDING',components:one.components};assert.equal(customerRemoteTemplateMatches(remote,one),true);assert.equal(customerRemoteTemplateMatches({...remote,components:[{type:'BODY',text:'Other private message'}]},one),false);assert.equal(customerRemoteTemplateMatches({...remote,name:two.name},one),false);});
function graph(responses){const calls=[];return {calls,provider:createMetaCustomerProvider({environment,fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});const result=responses.shift();if(result instanceof Error)throw result;return Response.json(result);},now:()=>Date.parse('2026-10-01T00:00:00Z')})};}
const debug=()=>({data:{is_valid:true,app_id:environment.NEXT_PUBLIC_META_APP_ID,scopes:['whatsapp_business_management','whatsapp_business_messaging'],expires_at:0,granular_scopes:[{scope:'whatsapp_business_management',target_ids:[wabaId]}]}});
const phone=(patch={})=>({data:[{id:phoneNumberId,is_on_biz_app:false,platform_type:'NOT_APPLICABLE',status:'PENDING',...patch}]});
const preflight={token,wabaId,phoneNumberId,numberMode:'DEDICATED',inspectionPhase:META_CUSTOMER_INSPECTION_PHASE.PRE_REGISTRATION};
test('provider accepts both WhatsApp grants without business portfolio permission and checks exact phone registration',async()=>{const fixture=graph([debug(),phone({code_verification_status:'VERIFIED'})]);const result=await fixture.provider.inspect(preflight);assert.deepEqual(result.scopes,['whatsapp_business_management','whatsapp_business_messaging']);assert.equal(result.registered,false);assert.equal(fixture.calls[1].options.headers.Authorization,'Bearer '+token);assert.equal(fixture.calls[1].url.pathname,`/v25.0/${wabaId}/phone_numbers`);assert.ok(fixture.calls[1].url.searchParams.has('appsecret_proof'));});
test('extra business portfolio permission remains compatible without becoming a requirement',async()=>{const body=debug();body.data.scopes.push('business_management');const fixture=graph([body,phone({platform_type:'CLOUD_API',status:'CONNECTED'})]);assert.equal((await fixture.provider.inspect({token,wabaId,phoneNumberId})).registered,true);assert.equal(fixture.calls.length,2);});
for(const [name,patch,code] of [['Business App',{is_on_biz_app:true,platform_type:'CLOUD_API'},'META_CUSTOMER_DEDICATED_PHONE_REQUIRED'],['on premise',{platform_type:'ON_PREMISE'},'META_CUSTOMER_EXISTING_API_REVIEW_REQUIRED'],['missing modality',{is_on_biz_app:undefined},'META_CUSTOMER_PHONE_MODE_UNCONFIRMED'],['missing platform',{platform_type:undefined},'META_CUSTOMER_PHONE_MODE_UNCONFIRMED'],['unknown status',{status:'UNKNOWN'},'META_CUSTOMER_PHONE_STATUS_UNCONFIRMED'],['missing status',{status:undefined},'META_CUSTOMER_PHONE_STATUS_UNCONFIRMED'],['contradictory registered',{status:'CONNECTED'},'META_CUSTOMER_PHONE_STATUS_UNCONFIRMED']])test('ordinary dedicated preserves '+name+' without granting register authority',async()=>{const f=graph([debug(),phone(patch)]);await assert.rejects(f.provider.inspect(preflight),{code});assert.ok(f.calls.every(c=>c.options.method==='GET'));await assert.rejects(f.provider.register({token,phoneNumberId,pin:'731902'}),{code:'META_CUSTOMER_REGISTRATION_INSPECTION_REQUIRED'});assert.equal(f.calls.length,2);});
for(const patch of [{platform_type:'NOT_APPLICABLE',status:'PENDING'},{platform_type:'CLOUD_API',status:'PENDING'},{platform_type:'CLOUD_API',status:'CONNECTED'}])test('ordinary dedicated keeps known provisioning and existing Cloud API signals separate '+JSON.stringify(patch),async()=>{const f=graph([debug(),phone(patch)]),verified=await f.provider.inspect(preflight);assert.equal(verified.registered,patch.status==='CONNECTED');assert.equal(f.calls.length,2);});
for(const missing of ['whatsapp_business_management','whatsapp_business_messaging'])test('provider rejects missing WhatsApp grant '+missing+' before querying customer assets',async()=>{const body=debug();body.data.scopes=body.data.scopes.filter(scope=>scope!==missing);body.data.scopes.push('business_management');const fixture=graph([body]);await assert.rejects(fixture.provider.inspect({token,wabaId,phoneNumberId}),{code:'META_CUSTOMER_TOKEN_SCOPE_REJECTED'});assert.equal(fixture.calls.length,1);});
test('provider rejects malformed grant list instead of accepting scope names inside text',async()=>{const body=debug();body.data.scopes=body.data.scopes.join(',');const fixture=graph([body]);await assert.rejects(fixture.provider.inspect({token,wabaId,phoneNumberId}),{code:'META_CUSTOMER_TOKEN_SCOPE_REJECTED'});assert.equal(fixture.calls.length,1);});

test('customer OAuth rejects omitted granular targets before querying customer phones',async()=>{const body=debug();delete body.data.granular_scopes[0].target_ids;const fixture=graph([body]);await assert.rejects(fixture.provider.inspect({token,wabaId,phoneNumberId}),{code:'META_CUSTOMER_WABA_SCOPE_REJECTED'});assert.equal(fixture.calls.length,1);assert.ok(fixture.calls.every(call=>call.options.method==='GET'));});
for(const mutate of [data=>{data.is_valid=false;},data=>{data.app_id='other';},data=>{data.scopes=[];},data=>{data.granular_scopes[0].target_ids=['other'];},data=>{data.expires_at=1;}])test('provider rejects unverified or crossed grant '+String(mutate),async()=>{const body=debug();mutate(body.data);const fixture=graph([body]);await assert.rejects(fixture.provider.inspect({token,wabaId,phoneNumberId}));assert.equal(fixture.calls.length,1);});
test('provider rejects a phone outside the granted WABA',async()=>{const fixture=graph([debug(),{data:[{id:'12345678',status:'CONNECTED'}]}]);await assert.rejects(fixture.provider.inspect({token,wabaId,phoneNumberId}),{code:'META_CUSTOMER_PHONE_WABA_MISMATCH'});});
test('subscription uses only the customer credential and per-WABA callback without changing app defaults',async()=>{const fixture=graph([{success:true},{data:[{whatsapp_business_api_data:{id:environment.NEXT_PUBLIC_META_APP_ID}}]}]);assert.equal(await fixture.provider.subscribe({token,wabaId}),true);assert.equal(fixture.calls[0].url.pathname,`/v25.0/${wabaId}/subscribed_apps`);const body=JSON.parse(fixture.calls[0].options.body);assert.equal(body.override_callback_uri,'https://obrasaas.com/api/meta/customer-callback');assert.equal(body.verify_token,environment.META_CUSTOMER_VERIFY_TOKEN);assert.equal(fixture.calls[0].options.headers.Authorization,'Bearer '+token);});
test('catalog reconstructs safe pagination from WABA/cursor and never follows an arbitrary provider URL',async()=>{const fixture=graph([{data:[{id:'12345678',name:'welcome',status:'APPROVED',language:'es_AR'}],paging:{next:'https://attacker.example/token',cursors:{after:'cursor-1'}}},{data:[{id:'12345679',name:'invite',status:'PENDING',language:'es_AR'}]}]);const result=await fixture.provider.templates({token,wabaId});assert.equal(result.complete,true);assert.equal(result.items.length,2);assert.equal(result.wabaId,wabaId);assert.ok(fixture.calls.every(call=>call.url.hostname==='graph.facebook.com'&&call.url.pathname===`/v25.0/${wabaId}/message_templates`));assert.equal(fixture.calls[1].url.searchParams.get('after'),'cursor-1');});
test('provider failure never reflects token, code, PIN or Graph text',async()=>{const provider=createMetaCustomerProvider({environment,fetchImpl:async()=>Response.json({error:{message:token,code:190}},{status:400})});await assert.rejects(provider.exchange('synthetic-code-only'),error=>error.code==='META_CUSTOMER_PROVIDER_REJECTED'&&!error.message.includes(token));});
for(const [status,code] of [[400,'META_CUSTOMER_PROVIDER_REJECTED'],[403,'META_CUSTOMER_PROVIDER_REJECTED'],[429,'META_CUSTOMER_PROVIDER_UNCONFIRMED'],[500,'META_CUSTOMER_PROVIDER_UNCONFIRMED']])test('registration distinguishes definitive rejection from an uncertain HTTP '+status,async()=>{
  const calls=[],provider=createMetaCustomerProvider({environment,fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});return options.method==='POST'?Response.json({error:{message:'Private PIN 731902 '+token}},{status}):Response.json(String(url).includes('debug_token')?debug():phone());}});
  const inspection=await provider.inspect(preflight);await assert.rejects(provider.register({token,phoneNumberId,pin:'731902',inspection}),error=>error.code===code&&!error.message.includes(token)&&!error.message.includes('731902'));
  assert.equal(calls.length,5);const call=calls.at(-1);assert.equal(call.url.pathname,`/v25.0/${phoneNumberId}/register`);assert.equal(call.options.method,'POST');assert.equal(call.options.headers.Authorization,'Bearer '+token);assert.ok(call.url.searchParams.has('appsecret_proof'));assert.deepEqual(JSON.parse(call.options.body),{messaging_product:'whatsapp',pin:'731902'});
});
test('lost registration response is uncertain and its consumed proof cannot retransmit',async()=>{let posts=0;const provider=createMetaCustomerProvider({environment,fetchImpl:async(url,options)=>{if(options.method==='POST'){posts++;throw new Error('Synthetic response lost');}return Response.json(String(url).includes('debug_token')?debug():phone());}}),inspection=await provider.inspect(preflight);await assert.rejects(provider.register({token,phoneNumberId,pin:'731902',inspection}),{code:'META_CUSTOMER_PROVIDER_UNCONFIRMED'});await assert.rejects(provider.register({token,phoneNumberId,pin:'731902',inspection}),{code:'META_CUSTOMER_REGISTRATION_INSPECTION_REQUIRED'});assert.equal(posts,1);});
for(const [name,patch] of [['coexistence',{is_on_biz_app:true,platform_type:'CLOUD_API'}],['existing API',{platform_type:'ON_PREMISE'}],['unknown status',{status:'UNKNOWN'}]])test('fresh provider change to '+name+' after reservation prevents register POST and is explicitly not sent',async()=>{const f=graph([debug(),phone(),debug(),phone(patch)]),inspection=await f.provider.inspect(preflight);await assert.rejects(f.provider.register({token,phoneNumberId,pin:'731902',inspection}),error=>error.registrationDispatched===false);assert.ok(f.calls.every(c=>c.options.method==='GET'));});
test('number registered between reservation and dispatch is preserved without another register',async()=>{const f=graph([debug(),phone(),debug(),phone({platform_type:'CLOUD_API',status:'CONNECTED'})]),inspection=await f.provider.inspect(preflight);assert.equal(await f.provider.register({token,phoneNumberId,pin:'731902',inspection}),true);assert.ok(f.calls.every(c=>c.options.method==='GET'));});
for(const platform_type of ['NOT_APPLICABLE','CLOUD_API'])test('fresh dedicated '+platform_type+' provisioning can register exactly once after private PRE proof',async()=>{const f=graph([debug(),phone({platform_type}),debug(),phone({platform_type}),{success:true}]),inspection=await f.provider.inspect(preflight);assert.equal(await f.provider.register({token,phoneNumberId,pin:'731902',inspection}),true);assert.equal(f.calls.filter(c=>c.options.method==='POST').length,1);await assert.rejects(f.provider.register({token,phoneNumberId,pin:'731902',inspection}),{code:'META_CUSTOMER_REGISTRATION_INSPECTION_REQUIRED'});assert.equal(f.calls.length,5);});
test('a copied, foreign credential or operational inspection cannot authorize registration',async()=>{const f=graph([debug(),phone(),debug(),phone()]),inspection=await f.provider.inspect(preflight),operational=await f.provider.inspect({token,wabaId,phoneNumberId});for(const proof of [undefined,{...inspection},operational])await assert.rejects(f.provider.register({token,phoneNumberId,pin:'731902',inspection:proof}),error=>error.code==='META_CUSTOMER_REGISTRATION_INSPECTION_REQUIRED'&&error.registrationDispatched===false);await assert.rejects(f.provider.register({token:'synthetic-other-token-only',phoneNumberId,pin:'731902',inspection}),{code:'META_CUSTOMER_REGISTRATION_INSPECTION_REQUIRED'});assert.equal(f.calls.length,4);});
const identity={authenticated:true,verification:'clerk-production-jwt',userId:'user_Meta',organizationId:'org_Meta',organizationRole:'org:admin'};
const request=(body,origin='https://obrasaas.com')=>new Request('https://obrasaas.com/api/identity/meta-onboarding',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
test('onboarding rejects anonymous, personal, cross-origin and oversized input before service access',async()=>{for(const session of [{authenticated:false},{...identity,organizationId:null}]){let count=0;const h=createMetaCustomerHandlers({verify:async()=>session,service:{command:()=>{count++;}}});assert.ok((await h.POST(request({}))).status>=400);assert.equal(count,0);}let count=0;const h=createMetaCustomerHandlers({verify:async()=>identity,service:{command:()=>{count++;}}});assert.equal((await h.POST(request({},'https://attacker.example'))).status,403);assert.equal((await h.POST(request('X'.repeat(32769)))).status,413);assert.equal(count,0);});
const payload=()=>({object:'whatsapp_business_account',entry:[{id:wabaId,changes:[{field:'messages',value:{metadata:{phone_number_id:phoneNumberId},messages:[{id:'wamid.'+'a'.repeat(24),from:'5491112345678',type:'text',text:{body:'private worker message'}}]}}]}]});
test('raw HMAC rejects missing signature, tampering, JSON reformatting and foreign key',()=>{const bytes=Buffer.from(JSON.stringify(payload())),signature='sha256='+createHmac('sha256',environment.META_APP_SECRET).update(bytes).digest('hex');assert.equal(verifyMetaCustomerSignature(bytes,signature,environment),true);assert.equal(verifyMetaCustomerSignature(bytes,null,environment),false);assert.equal(verifyMetaCustomerSignature(Buffer.from(JSON.stringify(payload(),null,2)),signature,environment),false);assert.equal(verifyMetaCustomerSignature(bytes,signature,{...environment,META_APP_SECRET:'foreign-secret-12345'}),false);});
test('same event has stable replay key across batches while changed content remains visible',()=>{const first=splitMetaCustomerEvents(payload())[0],next=payload();next.entry[0].changes[0].value.messages[0].text.body='changed private body';const second=splitMetaCustomerEvents(next)[0];assert.equal(first.externalId,second.externalId);assert.notEqual(first.payloadDigest,second.payloadDigest);const demo=payload();demo.entry[0].id=OBRASAAS_META_CHANNEL.wabaId;assert.throws(()=>splitMetaCustomerEvents(demo),{code:'META_CUSTOMER_DEMO_ASSET_REJECTED'});});
test('equivalent JSON property ordering preserves message and account-event replay digests',()=>{
 const first=payload(),reordered=payload(),message=first.entry[0].changes[0].value.messages[0];
 reordered.entry[0].changes[0].value.messages[0]={text:{body:message.text.body},type:message.type,from:message.from,id:message.id};
 assert.equal(splitMetaCustomerEvents(first)[0].payloadDigest,splitMetaCustomerEvents(reordered)[0].payloadDigest);
 first.entry[0].changes[0]={field:'account_update',value:{event:'PARTNER_ADDED',business_id:'1234567'}};
 reordered.entry[0].changes[0]={field:'account_update',value:{business_id:'1234567',event:'PARTNER_ADDED'}};
 const original=splitMetaCustomerEvents(first)[0],again=splitMetaCustomerEvents(reordered)[0];assert.equal(original.externalId,again.externalId);assert.equal(original.payloadDigest,again.payloadDigest);
});
test('enterprise intent contracts classify requests without applying commands or trusting client flow types',()=>{
 for(const [body,intent] of [['ayuda','HELP'],['fichar','ATTENDANCE_START'],['avance 30% tarea real','TASK_PROGRESS'],['aprobar VP-AAAAAAAAAAAA','COMMAND_CONFIRMATION'],['fuga de agua urgente','INCIDENT']])assert.equal(metaCustomerInboxIntent({type:'message',value:{type:'text',text:{body}}}),intent);
 assert.equal(metaCustomerInboxIntent({type:'message',value:{type:'location',location:{latitude:-34,longitude:-58}}}),'ATTENDANCE_LOCATION');
 for(const type of ['audio','video','image'])assert.equal(metaCustomerInboxIntent({type:'message',value:{type,[type]:{id:'private-provider-media'}}}),'EVIDENCE');
 assert.equal(metaCustomerInboxIntent({type:'message',value:{type:'interactive',interactive:{type:'nfm_reply',nfm_reply:{response_json:'{"flow_type":"attendance"}'}}}}),'EVIDENCE');
 assert.equal(metaCustomerInboxIntent({type:'message_status',value:{status:'read'}}),'MESSAGE_STATUS');
});
test('callback does not acknowledge an uncommitted inbox and rejects spoofing before record',async()=>{const bytes=JSON.stringify(payload()),signature='sha256='+createHmac('sha256',environment.META_APP_SECRET).update(bytes).digest('hex');let calls=0;const h=createMetaCustomerCallbackHandlers({environment,inbox:{record:async()=>{calls++;return {durable:false};}}});const callback=sig=>new Request('https://obrasaas.com/api/meta/customer-callback',{method:'POST',headers:{'Content-Type':'application/json','x-hub-signature-256':sig},body:bytes});assert.equal((await h.POST(callback('sha256='+'0'.repeat(64)))).status,403);assert.equal(calls,0);assert.equal((await h.POST(callback(signature))).status,503);assert.equal(calls,1);});
test('callback handshake requires exact configured verify token and unique known keys while ignoring extras',async()=>{const h=createMetaCustomerCallbackHandlers({environment,inbox:{}});const url='https://obrasaas.com/api/meta/customer-callback?'+new URLSearchParams({'hub.mode':'subscribe','hub.verify_token':environment.META_CUSTOMER_VERIFY_TOKEN,'hub.challenge':'123456'});const ok=await h.GET(new Request(url));assert.equal(await ok.text(),'123456');const extra=await h.GET(new Request(url+'&role=ADMIN'));assert.equal(extra.status,200);assert.equal(await extra.text(),'123456');assert.equal((await h.GET(new Request(url.replace(environment.META_CUSTOMER_VERIFY_TOKEN,'synthetic-wrong-token')+'&role=ADMIN'))).status,403);assert.equal((await h.GET(new Request(url+'&hub.verify_token='+environment.META_CUSTOMER_VERIFY_TOKEN))).status,400);assert.equal((await h.GET(new Request(url.replace('123456','')))).status,400);});

test('typed correction GET admits only exact signup and operation UUID and does not dispatch a Meta command',async()=>{let reads=0,commands=0;const session={authenticated:true,verification:'clerk-production-jwt',userId:'user_Read',organizationId:'org_Read',organizationRole:'org:admin'},id='12345678-1234-4234-8234-123456789012',params=new URLSearchParams({projectId:'p-a',scope:'a'.repeat(64),action:'reconcile',signupId:id,operationId:id}),api=createMetaCustomerHandlers({verify:async()=>session,service:{read:async(_session,context)=>{reads++;assert.equal(context.signupId,id);assert.equal(context.action,'reconcile');return {receipt:{state:'NOT_OBSERVED'}};},command:async()=>{commands++;}}});const get=query=>new Request('https://obrasaas.com/api/identity/meta-onboarding?'+query);assert.equal((await api.GET(get(params))).status,200);for(const extra of ['&eventId=customer_webhook_'+'a'.repeat(64),'&after=customer_webhook_'+'a'.repeat(64),'&signupId='+id,'&phone=%2B12025550123'])assert.ok((await api.GET(get(params+extra))).status>=400);assert.equal((await api.GET(get(new URLSearchParams({...Object.fromEntries(params),signupId:'bad'})))).status,400);assert.equal(reads,1);assert.equal(commands,0);});
