import test from 'node:test';
import assert from 'node:assert/strict';
import {createOfficeReviewStore} from '../src/lib/office-review-store.mjs';
import {createOfficeReviewHandlers} from '../src/lib/office-review-http.mjs';
import {officeCommand,officeEventProjection,assertOfficeGrant,officeReceiptId} from '../src/lib/office-review-policy.mjs';
import {createWorkspaceStore} from '../src/lib/workspace-store.mjs';
import {WorkspaceError,digest,checkScope,scopeStamp} from '../src/lib/workspace-policy.mjs';
import {encryptCustomerSecret} from '../src/lib/meta-customer-credentials.mjs';
import {metaCustomerContentDigest} from '../src/lib/meta-customer-callback.mjs';
import {customerOutboundId} from '../src/lib/meta-customer-outbound.mjs';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {identityAccountReturnPath,identityOfficeInvitationId} from '../src/lib/identity-return-path.mjs';
import {officeReviewSnapshot,officeEventLabels} from '../src/app/(identity)/cuenta/office-review-view.mjs';
import {createWorkspaceRecoveryJournal,officeReviewReceiptOutcome,recoveryQuery} from '../src/app/(identity)/cuenta/workspace-recovery-journal.mjs';

const owner={authenticated:true,verification:'clerk-production-jwt',userId:'user_Owner',organizationId:'org_Clerk',organizationRole:'org:admin'},reviewer={...owner,userId:'user_Reviewer',organizationRole:'org:member'};
const scope='a'.repeat(64),projectId='review-project',op='12345678-1234-4234-8234-123456789012',inviteId='office_invite_'+'b'.repeat(32);
const member={actorId:'owner',membershipId:'membership-owner',organizationId:'org-company',clerkUserId:owner.userId,clerkRole:'org:admin',role:'ADMIN'};
const reviewMember={actorId:'reviewer',membershipId:'membership-reviewer',organizationId:member.organizationId,clerkUserId:reviewer.userId,clerkRole:'org:member',role:'AUDITOR'};
const context={scope,projectId},command=(action='INVITE_AUDITOR',payload={email:'reviewer@example.invalid',connectionId:'channel-a',expiresAt:'2027-10-08T00:00:00.000Z',confirmReadOnly:true},operationId=op)=>({...context,action,payload,operationId});
const grant={version:1,kind:'OFFICE_AUDITOR_INVITATION_ACCEPTED',invitationId:inviteId,membershipId:reviewMember.membershipId,projectId,organizationId:member.organizationId,clerkUserId:reviewer.userId,connectionId:'channel-a',channelRevision:5,assignmentRevision:2,issuerId:'owner',expiresAt:'2027-10-08T00:00:00.000Z'};
const environment={META_CUSTOMER_CREDENTIALS_KEY:Buffer.alloc(32,31).toString('base64')};
const eventId='customer_webhook_'+'c'.repeat(64),eventPayload={type:'message',wabaId:'70000001',phoneNumberId:'70000002',value:{type:'text',from:'5491100001111',id:'wamid.synthetic',timestamp:'1791500000',text:{body:'HOLA'}}};
function signedEvent(payload=eventPayload){const aad={organizationId:member.organizationId,projectId:'anchor-project',resourceId:eventId},payloadDigest=metaCustomerContentDigest(payload);return {id:eventId,projectId:'anchor-project',provider:'meta-customer-v1',status:'PROCESSED',createdAt:new Date('2026-10-09T00:00:00.000Z'),payload:{organizationId:member.organizationId,channelId:'channel-a',payloadDigest,signatureVerified:true,signatureScheme:'meta-hmac-sha256-v1',encryptedPayload:encryptCustomerSecret(JSON.stringify(payload),{...aad,purpose:'webhook'},environment),encryptedProof:encryptCustomerSecret(JSON.stringify({scheme:'meta-hmac-sha256-v1',purpose:'CUSTOMER',appId:OBRASAAS_META_CHANNEL.appId,organizationId:member.organizationId,channelId:'channel-a',payloadDigest}),{...aad,purpose:'webhook-proof'},environment)}};}

// Controlled durable transactions and identity transport; no real Clerk/DB.
// Reconciliation tests run the production store and signed-vault decoder.
function fixture({role='ADMIN',providerLost=false,fieldBound=false,acceptedProvider=true}={}){
 const audit=new Map(),queries=[],providerCalls=[],users=new Map([['user_Reviewer',{id:'reviewer',clerkUserId:'user_Reviewer'}]]),members=new Map([['reviewer',{id:'membership-reviewer',status:'ACTIVE',role:'AUDITOR',clerkRole:'org:member'}]]),assignments=new Map();
 let currentAdmin={...member},currentRole=role,connected=true,issuerActive=true,now=new Date('2026-10-09T00:00:00.000Z'),eventRow=signedEvent(),outboundRows=[],providerRow=null,commitFailure=null;
 const cloneAudit=()=>new Map([...audit].map(([key,value])=>[key,structuredClone(value)]));
 async function connect(){let before;
  return {release(){},async query(sql,args=[]){queries.push({sql,args});
   if(sql.startsWith('BEGIN')){before={audit:cloneAudit(),assignments:new Map(assignments),users:new Map(users),members:new Map(members)};return {rows:[]};}
   if(sql==='ROLLBACK'){if(before){audit.clear();for(const [k,v] of before.audit)audit.set(k,v);assignments.clear();for(const [k,v] of before.assignments)assignments.set(k,v);users.clear();for(const [k,v] of before.users)users.set(k,v);members.clear();for(const [k,v] of before.members)members.set(k,v);before=null;}return {rows:[]};}
   if(sql==='COMMIT'){if(commitFailure){const mode=commitFailure;commitFailure=null;if(mode==='persisted')before=null;throw new Error('controlled COMMIT acknowledgement loss');}before=null;return {rows:[]};}
   if(sql.startsWith('SET')||sql.includes('pg_advisory_xact_lock'))return {rows:[]};
   if(sql.includes('clock_timestamp() AS now'))return {rows:[{now}]};
   if(sql.startsWith('INSERT INTO public."AuditLog"')){const [key,org,actor,action,entity,raw]=args;if(audit.has(key))throw new Error('duplicate audit');audit.set(key,{id:key,organizationId:org,actorId:actor,action,entityId:entity,metadata:JSON.parse(raw)});return {rows:[],rowCount:1};}
   if(sql.startsWith('UPDATE public."AuditLog"')){audit.get(args[0]).metadata=JSON.parse(args[1]);return {rows:[],rowCount:1};}
   if(sql.startsWith('UPDATE public."ProjectMembership"')){assignments.set('membership-reviewer','DISABLED');return {rows:[],rowCount:1};}
   if(sql.startsWith('INSERT INTO public."ProjectMembership"')){assignments.set(args[2],'ACTIVE');return {rows:[],rowCount:1};}
   if(sql.startsWith('INSERT INTO public."PlatformUser"')){users.set(args[1],{id:args[0],clerkUserId:args[1]});return {rows:[],rowCount:1};}
   if(sql.startsWith('INSERT INTO public."TenantMembership"')){members.set(args[2],{id:args[0],status:'ACTIVE',role:'AUDITOR'});return {rows:[],rowCount:1};}
   if(sql.includes('FROM public."Worker"'))return {rows:fieldBound?[{id:'field-worker'}]:[]};
   if(sql.includes('FROM public."PlatformUser" WHERE "clerkUserId"'))return {rows:users.has(args[0])?[users.get(args[0])]:[]};
   if(sql.includes('FROM public."PlatformUser" WHERE lower'))return {rows:[]};
   if(sql.includes('FROM public."TenantMembership" WHERE "organizationId"'))return {rows:members.has(args[1])?[members.get(args[1])]:[]};
   if(sql.includes('SELECT tm.id FROM public."TenantMembership"'))return {rows:issuerActive?[{id:'membership-owner'}]:[]};
   if(sql.includes('FROM public."WhatsAppConnection"'))return {rows:connected?[{id:'channel-a',projectId:'anchor-project',whatsappBusinessId:'70000001',phoneNumberId:'70000002',metadata:{credentialFormat:'tenant-aad-v2',credentialOrganizationId:member.organizationId},channelRevision:5,assignmentRevision:2}]:[]};
   if(sql.includes('FROM public."WebhookEvent"'))return {rows:sql.includes('meta-customer-outbound-v1')?structuredClone(outboundRows):eventRow?[structuredClone(eventRow)]:[]};
   if(sql.includes('FROM public."ProjectMembership"'))return {rows:assignments.has(args[1])?[{id:'pm-a',status:assignments.get(args[1])}]:[]};
   if(sql.includes('FROM public."Project"'))return {rows:[{id:projectId,name:'Review project'}]};
   if(sql.includes('FROM public."AuditLog"')){
    const all=[...audit.values()];
    if(sql.includes("'INVITATION_ACCEPTED'"))return {rows:[]};
    if(sql.includes('WHERE id=$1 AND'))return {rows:all.filter(r=>r.id===args[0]&&r.organizationId===args[1]&&r.actorId===args[2]&&['office.review.recorded','office.review.invitation.attempted'].includes(r.action))};
    if(sql.includes('FROM public."AuditLog" a JOIN public."Project"'))return {rows:all.filter(r=>r.action===args[0]&&r.metadata.invitationId===args[1]&&args[2]===owner.organizationId).map(r=>({...r,projectId:r.entityId,projectName:'Review project',organizationName:'Synthetic company'}))};
    if(sql.includes('FROM public."AuditLog" a JOIN public."PlatformUser"'))return {rows:all.filter(r=>r.action===args[0]&&r.organizationId===args[1]&&r.entityId===args[2]&&r.metadata.invitationId===args[3]&&r.metadata.clerkUserId===args[4]&&assignments.get('membership-reviewer')==='ACTIVE').map(r=>({...r,...reviewMember}))};
    if(sql.includes("action='office.review.revoked'"))return {rows:all.filter(r=>r.action==='office.review.revoked'&&r.organizationId===args[0]&&r.metadata.invitationId===args[1])};
    if(sql.includes("action='office.review.event.selected'"))return {rows:all.filter(r=>r.action==='office.review.event.selected'&&r.organizationId===args[0]&&r.entityId===args[1])};
    if(sql.includes('action=$1'))return {rows:all.filter(r=>r.action===args[0]&&r.organizationId===args[1]&&r.actorId===args[2]&&r.entityId===args[3]&&r.metadata.membershipId===args[4])};
    if(sql.includes('a.action=$3'))return {rows:all.filter(r=>r.organizationId===args[0]&&r.entityId===args[1]&&r.action===args[2]&&r.metadata.email===args[3])};
    throw new Error('Unhandled audit query');
   }
   throw new Error('Unhandled fixture query: '+sql);
  }};
 }
 const workspace={async organizationOperation(_session,ctx,writable,callback){checkScope(scope,ctx.scope);const client=await connect();await client.query(writable?'BEGIN':'BEGIN READ ONLY');try{const result=await callback(client,{...currentAdmin,role:currentRole},scope);await client.query(writable?'COMMIT':'ROLLBACK');return result;}catch(error){await client.query('ROLLBACK');throw error;}},async officeReviewRead(_session,ctx,callback){checkScope(scope,ctx.scope);if(assignments.get('membership-reviewer')!=='ACTIVE')throw new WorkspaceError('WORKSPACE_PROJECT_UNAVAILABLE',404);const client=await connect();await client.query('BEGIN READ ONLY');try{return await callback(client,reviewMember,scope,{id:projectId,name:'Review project'});}finally{await client.query('ROLLBACK');}}};
 const identity={async createInvitation(input){providerCalls.push('create');assert.ok([...audit.values()].some(r=>r.action==='office.review.invitation.attempted'),'Attempt committed before transport');assert.equal(queries.at(-1).sql,'COMMIT');providerRow={id:'orginv_Test',invitationId:input.invitationId,email:input.email,role:'org:member',state:acceptedProvider?'accepted':'pending',expiresAt:'2026-10-16T00:00:00.000Z'};if(providerLost)throw new WorkspaceError('PARTICIPANT_IDENTITY_PROVIDER_UNAVAILABLE',503);return providerRow;},async findInvitation(){providerCalls.push('find');return providerRow;},async verifiedEmail(){providerCalls.push('email');return 'reviewer@example.invalid';},async verifyMembership(){providerCalls.push('member');return {userId:reviewer.userId,organizationId:reviewer.organizationId,role:'org:member'};}};
 const store=createOfficeReviewStore({workspace,connect,identity,environment});
 return {store,audit,queries,providerCalls,identity,setRole:v=>{currentRole=v;},setAdmin:v=>{currentAdmin={...member,...v};},setIssuer:v=>{issuerActive=v;},setConnected:v=>{connected=v;},setNow:v=>{now=new Date(v);},setEvent:v=>{eventRow=v;},setOutbound:v=>{outboundRows=v;},setCommitFailure:v=>{commitFailure=v;},setMemberRole:v=>{members.get('reviewer').clerkRole=v;},invite:()=>store.command(owner,command())};
}

test('strict command accepts only the server-scoped read-only office contract',()=>{assert.equal(officeCommand(command()).action,'INVITE_AUDITOR');for(const edit of [c=>{c.tenantId='other';},c=>{c.payload.role='ADMIN';},c=>{c.payload.confirmReadOnly=false;},c=>{c.payload.expiresAt='never';},c=>{c.action='SEND_MESSAGE';}]){const value=command();edit(value);assert.throws(()=>officeCommand(value),{code:'OFFICE_REVIEW_INPUT_INVALID'});}});
test('read labels preserve uncertainty and attribute delivery only to Meta',()=>{assert.match(officeEventLabels({processingState:'PROCESSED',replyState:'SEND_STARTED',deliveryStatus:null}).reply,/sin confirmación/);assert.equal(officeEventLabels({replyState:'STATUS_OBSERVED',deliveryStatus:'delivered'}).delivery,'Entregado según Meta');assert.equal(officeEventLabels({replyState:'SENT'}).reply,'Respuesta aceptada por Meta');assert.equal(officeEventLabels({deliveryStatus:'arbitrary'}).delivery,null);});
test('safe projection omits all sender/text/document/outcome metadata',()=>{const source={id:eventId,createdAt:new Date(),status:'PROCESSED',from:'secret',metadata:{dni:'secret'},outcome:{workerId:'private'}};const value=officeEventProjection(source,eventPayload);assert.deepEqual(Object.keys(value).sort(),['id','receivedAt','kind','signatureVerified','processingState'].sort());assert.doesNotMatch(JSON.stringify(value),/secret|HOLA|worker|dni/);for(const value of ['Mi DNI 123','hola','HOLA\n','Nombre'])assert.throws(()=>officeEventProjection(source,{...eventPayload,value:{...eventPayload.value,text:{body:value}}}),{code:'OFFICE_REVIEW_EVENT_NOT_SAFE'});});
test('grant rejects changed role/organization/membership/connection/expiry and revocation',()=>{const ctx={member:reviewMember,projectId,connectionId:'channel-a',channelRevision:5,assignmentRevision:2,now:Date.parse('2026-10-09')};assert.doesNotThrow(()=>assertOfficeGrant(grant,ctx));for(const patch of [{member:{...reviewMember,role:'ADMIN'}},{member:{...reviewMember,clerkRole:'org:admin'}},{member:{...reviewMember,membershipId:'other'}},{member:{...reviewMember,organizationId:'other'}},{connectionId:'other'},{channelRevision:6},{assignmentRevision:3},{revoked:true},{now:Date.parse('2028-01-01')}])assert.throws(()=>assertOfficeGrant(grant,{...ctx,...patch}),{code:'OFFICE_REVIEW_ACCESS_REQUIRED'});});
test('lost provider acknowledgement preserves attempted reference; replay cannot send another invitation',async()=>{const f=fixture({providerLost:true});await assert.rejects(f.invite(),{status:503});const found=await f.store.status(owner,{...context,operationId:op});assert.equal(found.state,'INVITATION_UNCONFIRMED');assert.equal(found.definitive,false);await assert.rejects(f.invite(),{code:'OFFICE_REVIEW_INVITATION_UNCONFIRMED'});assert.deepEqual(f.providerCalls,['create']);const saved=await f.store.reconcile(owner,{...context,operationId:op,invitationId:found.invitationId});assert.equal(saved.state,'RECORDED');assert.deepEqual(f.providerCalls,['create','find']);assert.equal([...f.audit.values()].filter(r=>r.action==='office.review.invitation.attempted').length,1);});
test('different payload under same UUID is rejected before any second provider call',async()=>{const f=fixture();await f.invite();await assert.rejects(f.store.command(owner,command('INVITE_AUDITOR',{...command().payload,email:'other@example.invalid'})),{code:'OFFICE_REVIEW_OPERATION_CONFLICT'});assert.equal(f.providerCalls.filter(x=>x==='create').length,1);});
test('current ADMIN permission is checked again after provider response',async()=>{const f=fixture(),create=f.identity.createInvitation;f.identity.createInvitation=async input=>{const value=await create(input);f.setRole('AUDITOR');return value;};await assert.rejects(f.invite(),{code:'OFFICE_REVIEW_ADMIN_REQUIRED'});f.setRole('ADMIN');const pending=await f.store.status(owner,{...context,operationId:op});assert.equal(pending.state,'INVITATION_UNCONFIRMED');assert.equal(f.providerCalls.filter(x=>x==='create').length,1);});
test('Clerk acceptance creates only canonical AUDITOR + project membership, never Worker or KYC',async()=>{const f=fixture(),invited=await f.invite();assert.equal([...f.audit.values()].some(r=>r.action==='office.review.accepted'),false);const preview=await f.store.join(reviewer,{invitationId:invited.invitationId});assert.equal(preview.canAccept,true);assert.equal(f.queries.some(q=>q.sql.startsWith('INSERT INTO public."ProjectMembership"')),false);const joined=await f.store.join(reviewer,{invitationId:invited.invitationId,operationId:op},{accept:true});assert.equal(joined.readOnly,true);assert.equal(joined.joined,true);assert.equal(f.queries.some(q=>/^(INSERT|UPDATE).*"Worker"/.test(q.sql)),false);assert.equal([...f.audit.values()].filter(r=>r.action==='office.review.accepted').length,1);const replay=await f.store.join(reviewer,{invitationId:invited.invitationId,operationId:op},{accept:true});assert.equal(replay.receiptId,joined.receiptId);assert.equal([...f.audit.values()].filter(r=>r.action==='office.review.accepted').length,1);});
test('field-bound account cannot obtain an office KYC bypass',async()=>{const f=fixture({fieldBound:true}),invite=await f.invite();await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true}),{code:'OFFICE_REVIEW_FIELD_ACCOUNT_REJECTED'});assert.equal([...f.audit.values()].some(r=>r.action==='office.review.accepted'),false);});
test('unaccepted/wrong verified Clerk invitation never creates a grant',async()=>{const f=fixture({acceptedProvider:false}),invite=await f.invite();await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true}),{code:'PARTICIPANT_PROVIDER_ACCEPTANCE_REQUIRED'});assert.equal([...f.audit.values()].some(r=>r.action==='office.review.accepted'),false);});
test('selected signed HOLA is the only event shared; read-only projection contains no PII',async()=>{const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});await f.store.command(owner,command('SELECT_EVENT',{connectionId:'channel-a',eventId,confirmNoPersonalData:true},'22345678-1234-4234-8234-123456789012'));const data=await f.store.review(reviewer,context);assert.equal(data.items.length,1);assert.equal(data.canSend,false);assert.equal(data.items[0].signatureVerified,true);assert.doesNotMatch(JSON.stringify(data),/5491100001111|HOLA|encrypted|cipher|token|workerId|wamid/);officeReviewSnapshot(data,context);f.setEvent(signedEvent({...eventPayload,value:{...eventPayload.value,text:{body:'DNI secreto'}}}));await assert.rejects(f.store.review(reviewer,context),{code:'OFFICE_REVIEW_EVENT_NOT_SAFE'});});
test('revocation disables exact project membership and blocks accepted replay and projection',async()=>{const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});await f.store.command(owner,command('REVOKE_AUDITOR',{invitationId:invite.invitationId,reason:'Acceso de revisión terminado'},'32345678-1234-4234-8234-123456789012'));await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId}),{code:'OFFICE_REVIEW_ACCESS_REQUIRED'});await assert.rejects(f.store.review(reviewer,context),{code:'WORKSPACE_PROJECT_UNAVAILABLE'});assert.equal(f.queries.filter(q=>q.sql.startsWith('UPDATE public."ProjectMembership"')).length,1);});
test('issuer downgrade, channel suspension and grant expiry deny fresh projection',async()=>{for(const change of [f=>f.setIssuer(false),f=>f.setConnected(false),f=>f.setNow('2028-01-01')]){const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});change(f);await assert.rejects(f.store.review(reviewer,context),error=>error.status===403);}});
test('current ADMIN can permanently revoke a demoted issuer grant without letting it revive',async()=>{const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});f.setIssuer(false);f.setAdmin({actorId:'new-owner',membershipId:'new-owner-member',clerkUserId:'user_NewOwner'});const currentAdmin={...owner,userId:'user_NewOwner'};const result=await f.store.command(currentAdmin,command('REVOKE_AUDITOR',{invitationId:invite.invitationId,reason:'Responsable anterior dejó de administrar'},'62345678-1234-4234-8234-123456789012'));assert.equal(result.state,'RECORDED');assert.equal([...f.audit.values()].filter(row=>row.action==='office.review.revoked').length,1);f.setIssuer(true);await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId}),{code:'OFFICE_REVIEW_ACCESS_REQUIRED'});await assert.rejects(f.store.review(reviewer,context),{code:'WORKSPACE_PROJECT_UNAVAILABLE'});});
test('office user cannot enter ordinary modules or integration composition',async()=>{const rows=[];const store=createWorkspaceStore({connect:async()=>({release(){},query:async sql=>{rows.push(sql);return {rows:sql.includes('FROM public."PlatformUser" u JOIN')?[{...reviewMember,officeReviewOnly:true}]:[]};}})});let called=false;await assert.rejects(store.projectOperation(reviewer,{...context,scope:scopeStamp(reviewer,reviewMember)},true,()=>{called=true;}),{code:'OFFICE_REVIEW_ONLY'});await assert.rejects(store.integrationProject(reviewer,{...context,scope:scopeStamp(reviewer,reviewMember)},true,()=>{called=true;}),{code:'OFFICE_REVIEW_ONLY'});assert.equal(called,false);assert.equal(rows.some(sql=>/"Task"|"Worker"|"WebhookEvent"/.test(sql)),false);});

const request=(method='GET',body=null,q='',headers={})=>new Request('https://obrasaas.com/api/identity/office-review'+q,{method,headers:{...(method==='POST'?{origin:'https://obrasaas.com','content-type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
test('anonymous/cross-origin/duplicate-query denial precedes storage and response is no-store',async()=>{let calls=0;const store={command:async()=>{calls++;},review:async()=>{calls++;}};let api=createOfficeReviewHandlers({verify:async()=>({authenticated:false}),store});const result=await api.POST(request('POST',command()));assert.equal(result.status,401);assert.match(result.headers.get('cache-control'),/no-store/);api=createOfficeReviewHandlers({verify:async()=>owner,store});assert.equal((await api.POST(request('POST',command(),'',{origin:'https://other.invalid'}))).status,403);assert.equal((await api.GET(request('GET',null,'?projectId=a&projectId=b&scope='+scope))).status,400);assert.equal(calls,0);});
test('normal login navigation preserves office ID only, rejects ambiguity and ticket propagation',()=>{const office='office_invite_'+'f'.repeat(32);assert.equal(identityAccountReturnPath({oficina:office,token:'private',__clerk_ticket:'private'}),'/cuenta?oficina='+office);assert.equal(identityOfficeInvitationId({oficina:[office,office]}),'');assert.equal(identityAccountReturnPath({oficina:office,participar:'invite_'+'a'.repeat(32)}),'/cuenta');});
test('journal persists only receipt coordinates, retains denied dispatch and never replays an invitation',async()=>{const storage=new Map(),adapter={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k),key:i=>[...storage.keys()][i],get length(){return storage.size;}};const journal=createWorkspaceRecoveryJournal({getStorage:()=>adapter,now:()=>1234});const ticket=await journal.prepare('/api/identity/office-review',{method:'POST',body:JSON.stringify(command())});assert.doesNotMatch([...storage.values()].join(''),/reviewer@example|confirmReadOnly|expiresAt|connectionId|payload/);await journal.settle(ticket,null,Object.assign(new Error('denied'),{status:403}));assert.equal((await journal.list(scope)).length,1);const receipt={...context,operationId:op,action:'INVITE_AUDITOR',state:'RECORDED',saved:true,definitive:true,receiptId:officeReceiptId(member,projectId,op)+'_recorded',replayed:true,invitationId:inviteId};assert.equal(officeReviewReceiptOutcome(receipt,ticket.entry).state,'RECORDED');assert.equal(officeReviewReceiptOutcome({...receipt,operationId:'other'},ticket.entry),null);assert.match(recoveryQuery(ticket.entry),/operationId=/);await journal.settle(ticket,receipt);assert.equal((await journal.list(scope)).length,0);});

test('office acceptance cannot repair a canonical Clerk-role mismatch',async()=>{const f=fixture(),invite=await f.invite();f.setMemberRole('org:admin');await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true}),{code:'OFFICE_REVIEW_MEMBER_SESSION_REQUIRED'});assert.equal([...f.audit.values()].some(row=>row.action==='office.review.accepted'),false);});
test('lost acceptance COMMIT is recovered by the same invitation GET; rollback produces no grant',async()=>{
 for(const mode of ['persisted','rollback']){const f=fixture(),invite=await f.invite();f.setCommitFailure(mode);await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true}),{code:'OFFICE_REVIEW_OPERATION_UNCONFIRMED'});const value=await f.store.join(reviewer,{invitationId:invite.invitationId});assert.equal(value.joined===true,mode==='persisted');assert.equal(value.canAccept,mode==='rollback');assert.equal([...f.audit.values()].filter(row=>row.action==='office.review.accepted').length,mode==='persisted'?1:0);assert.equal(f.providerCalls.filter(call=>call==='create').length,1);}
});
test('office restrictions hold before private queries even after role promotion',async()=>{
 for(const role of ['AUDITOR','DIRECTOR','ADMIN']){const rows=[],session={...reviewer,organizationRole:role==='ADMIN'?'org:admin':'org:member'},currentMember={...reviewMember,role,clerkRole:session.organizationRole},ctx={...context,scope:scopeStamp(session,currentMember)};const workspace=createWorkspaceStore({connect:async()=>({release(){},async query(sql){rows.push(sql);return {rows:sql.includes('FROM public."PlatformUser" u JOIN')?[{...currentMember,officeReviewOnly:true}]:[]};}})});let called=false;for(const invoke of [()=>workspace.overview(session,ctx),()=>workspace.companyRead(session,ctx,()=>{called=true;}),()=>workspace.organizationOperation(session,ctx,false,()=>{called=true;},true),()=>workspace.projectOperation(session,ctx,true,()=>{called=true;},()=>{called=true;}),()=>workspace.integrationProject(session,ctx,true,()=>{called=true;},()=>{called=true;})])await assert.rejects(invoke(),{code:'OFFICE_REVIEW_ONLY'});assert.equal(called,false);assert.equal(rows.some(sql=>/FROM public\."(Task|Worker|Project|WebhookEvent)"/.test(sql)),false);}
});
test('wrong Clerk email and changed scope never record an office grant or selection',async()=>{const f=fixture(),invite=await f.invite();f.identity.verifiedEmail=async()=> 'different@example.invalid';await assert.rejects(f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true}),{code:'PARTICIPANT_EMAIL_MISMATCH'});await assert.rejects(f.store.command(owner,{...command('SELECT_EVENT',{connectionId:'channel-a',eventId,confirmNoPersonalData:true}),scope:'f'.repeat(64)}),{code:'WORKSPACE_CONTEXT_CHANGED'});assert.equal([...f.audit.values()].some(row=>['office.review.accepted','office.review.event.selected'].includes(row.action)),false);});
test('signed source tampering is rejected instead of trusting a projected signature flag',async()=>{const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});const row=signedEvent();row.payload.encryptedProof=row.payload.encryptedPayload;f.setEvent(row);await assert.rejects(f.store.command(owner,command('SELECT_EVENT',{connectionId:'channel-a',eventId,confirmNoPersonalData:true},'42345678-1234-4234-8234-123456789012')));assert.equal([...f.audit.values()].some(row=>row.action==='office.review.event.selected'),false);});
function signedOutbound(patch={}){
 const id=customerOutboundId(eventId),request={version:1,eventId,payloadDigest:signedEvent().payload.payloadDigest,organizationId:member.organizationId,channelId:'channel-a',to:eventPayload.value.from,replyTo:eventPayload.value.id,channelPurpose:'EMPLOYEE_INTAKE',applicationId:eventId,message:{type:'text',text:'Private intake prompt'},...patch};return {id,payload:{version:1,eventId,organizationId:member.organizationId,channelId:'channel-a',requestDigest:digest(request),encryptedPayload:encryptCustomerSecret(JSON.stringify(request),{organizationId:member.organizationId,projectId:'anchor-project',purpose:'outbound',resourceId:id},environment)},outcome:{state:'STATUS_OBSERVED',providerStatus:'delivered',messageId:'wamid.private',statusEventId:'status.private'}};
}
test('outbound observation shares only correlated states and rejects foreign/digest/recipient/purpose links',async()=>{
 const f=fixture(),invite=await f.invite();await f.store.join(reviewer,{invitationId:invite.invitationId,operationId:op},{accept:true});await f.store.command(owner,command('SELECT_EVENT',{connectionId:'channel-a',eventId,confirmNoPersonalData:true},'52345678-1234-4234-8234-123456789012'));f.setOutbound([signedOutbound()]);const read=await f.store.review(reviewer,context);assert.equal(read.items[0].replyState,'STATUS_OBSERVED');assert.equal(read.items[0].deliveryStatus,'delivered');assert.doesNotMatch(JSON.stringify(read),/Private intake|5491100001111|wamid|cipher|status.private/);
 for(const patch of [{eventId:'other'},{to:'5491100009999'},{replyTo:'wamid.other'},{channelPurpose:'KYC_CAPTURE'},{applicationId:'other'},{organizationId:'other'},{channelId:'other'},{payloadDigest:'f'.repeat(64)}]){f.setOutbound([signedOutbound(patch)]);await assert.rejects(f.store.review(reviewer,context),{code:'OFFICE_REVIEW_SOURCE_CHANGED'});}const invalid=signedOutbound();invalid.payload.requestDigest='f'.repeat(64);f.setOutbound([invalid]);await assert.rejects(f.store.review(reviewer,context),{code:'OFFICE_REVIEW_SOURCE_CHANGED'});
});
