import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {buildWorkerTemplateNotice,WORKER_TEMPLATE_NOTICE_VERSION,LEGACY_WORKER_TEMPLATE_NOTICE,LEGACY_WORKER_TEMPLATE_NOTICE_VERSION,LEGACY_WORKER_TEMPLATE_NOTICE_SHA256,WORKER_TEMPLATE_CONSENT_PURPOSE,workerTemplateConsentMatches} from '../src/lib/worker-channel-consent-policy.mjs';
import {workerChannelCommand,workerChannelCodeDigest,WORKER_CHANNEL_TTL_MS,assertWorkerCustomerConnection,decodeWorkerChannelProof,invalidateWorkerChannelIdentity,resolveOwnWorkerParticipant,createWorkerChannelStore,resolveWorkerChannelIdentity} from '../src/lib/worker-channel-identity.mjs';
import {META_CUSTOMER_PROTOCOL,META_DEMO_PILOT_PROTOCOL} from '../src/lib/meta-cloud-protocol.mjs';
import {createWorkerChannelHandlers} from '../src/lib/worker-channel-http.mjs';
import {encryptCustomerSecret} from '../src/lib/meta-customer-credentials.mjs';
import {metaCustomerContentDigest} from '../src/lib/meta-customer-callback.mjs';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {digest} from '../src/lib/workspace-policy.mjs';
import {adoptParticipantChannelKyc} from '../src/lib/participant-channel-kyc.mjs';
import {participantReceiptId} from '../src/lib/participant-policy.mjs';
const session={authenticated:true,verification:'clerk-production-jwt',userId:'user_Fixture',organizationId:'org_Fixture',organizationRole:'org:member'},scope='a'.repeat(64);
const input={operationId:randomUUID(),projectId:'project-fixture',scope,action:'REQUEST_CHALLENGE',payload:{workerId:'worker-fixture',revision:'2026-10-01T11:00:00.000001'}};
const env={META_CUSTOMER_CREDENTIALS_KEY:Buffer.alloc(32,6).toString('base64')};
const c={id:'connection-fixture',organizationId:'org-canonical',projectId:input.projectId,phoneNumberId:'1234500000',whatsappBusinessId:'1234600000',enabled:false,connectionStatus:'PENDING',encryptedAccessToken:'v2.fixture',metadata:{credentialFormat:'tenant-aad-v2',credentialOrganizationId:'org-canonical',customerVerification:{registered:true,expiresAt:null}}};
const demoConnection={...c,metadata:{...c.metadata,demoPilot:{grantId:'demo-grant-fixture'}}};
function proof(){const payload={wabaId:c.whatsappBusinessId,phoneNumberId:c.phoneNumberId,field:'messages',type:'message',value:{id:'wamid.fixture12345',type:'text',text:{body:'VINCULAR '+'A'.repeat(43)},from:'5491100001111',timestamp:String(Math.floor(Date.now()/1000))}},externalId=digest([payload.wabaId,payload.phoneNumberId,'message',payload.value.id]),id='customer_webhook_'+externalId,payloadDigest=metaCustomerContentDigest(payload),ctx={organizationId:c.organizationId,projectId:c.projectId,resourceId:id};return {id,projectId:c.projectId,provider:'meta-customer-v1',eventType:'message',externalId,payload:{version:1,organizationId:c.organizationId,channelId:c.id,payloadDigest,encryptedPayload:encryptCustomerSecret(JSON.stringify(payload),{...ctx,purpose:'webhook'},env),encryptedProof:encryptCustomerSecret(JSON.stringify({scheme:'meta-hmac-sha256-v1',appId:OBRASAAS_META_CHANNEL.appId,payloadDigest,channelId:c.id,organizationId:c.organizationId}),{...ctx,purpose:'webhook-proof'},env)}};}
test('strict own-session challenge and unlink contracts reject role/phone/proof injection',()=>{assert.equal(WORKER_CHANNEL_TTL_MS,300000);assert.deepEqual(workerChannelCommand(input),input);for(const value of [{...input,phone:'+5491100001111'},{...input,action:'BIND',payload:{...input.payload,code:'foo'}},{...input,payload:{...input.payload,clerkUserId:'user_Other'}},{...input,operationId:'bad'}])assert.throws(()=>workerChannelCommand(value));assert.equal(workerChannelCommand({...input,action:'UNLINK',payload:{...input.payload,reason:' Reviewed unlink reason '}}).payload.reason,'Reviewed unlink reason');});
test('only exact 256-bit challenge syntax is accepted, never arbitrary text/phone/short pin',()=>{const code='VINCULAR '+'A'.repeat(43);assert.match(workerChannelCodeDigest(code),/^[a-f0-9]{64}$/);for(const invalid of [code+' ',code.toLowerCase(),'123456','hola '+code,'+5491100001111',code.replace('A','!')])assert.equal(workerChannelCodeDigest(invalid),null);});
test('binding proof requires encrypted authenticated provenance and exact event asset AAD',()=>{const row=proof();assert.equal(decodeWorkerChannelProof(row,c,env).senderE164,'+5491100001111');for(const change of [{encryptedProof:null,signatureVerified:true,signatureScheme:'meta-hmac-sha256-v1'},{organizationId:'other'},{channelId:'other'},{payloadDigest:'f'.repeat(64)}])assert.throws(()=>decodeWorkerChannelProof({...row,payload:{...row.payload,...change}},c,env));assert.throws(()=>decodeWorkerChannelProof(row,{...c,phoneNumberId:'7777700000'},env));assert.throws(()=>decodeWorkerChannelProof({...row,id:'customer_webhook_other'},c,env));});
test('registered customer connection can prove identity before activation; work requires explicit activation',()=>{assert.equal(assertWorkerCustomerConnection(c,c.organizationId,c.projectId),c);assert.throws(()=>assertWorkerCustomerConnection(c,c.organizationId,c.projectId,Date.now(),{operational:true}),{code:'WORKER_CHANNEL_CUSTOMER_ACTIVATION_REQUIRED'});const active={...c,enabled:true,connectionStatus:'CONNECTED',metadata:{...c.metadata,customerSubscribed:true,customerVerification:{registered:true,expiresAt:null,scopes:['whatsapp_business_management','whatsapp_business_messaging']},customerActivation:{version:1,state:'ACTIVE',actorId:'owner'}}};assert.equal(assertWorkerCustomerConnection(active,c.organizationId,c.projectId,Date.now(),{operational:true}),active);for(const missing of active.metadata.customerVerification.scopes){const denied={...active,metadata:{...active.metadata,customerVerification:{...active.metadata.customerVerification,scopes:active.metadata.customerVerification.scopes.filter(scope=>scope!==missing)}}};assert.throws(()=>assertWorkerCustomerConnection(denied,c.organizationId,c.projectId,Date.now(),{operational:true}),{code:'WORKER_CHANNEL_CUSTOMER_ACTIVATION_REQUIRED'});}for(const value of [{...c,phoneNumberId:OBRASAAS_META_CHANNEL.phoneNumberId},{...c,whatsappBusinessId:OBRASAAS_META_CHANNEL.wabaId},{...c,metadata:{...c.metadata,credentialOrganizationId:'other'}},{...c,metadata:{...c.metadata,customerVerification:{registered:false}}}])assert.throws(()=>assertWorkerCustomerConnection(value,c.organizationId,c.projectId));});
test('revocation removes challenge and preserves source references without affecting other worker data',()=>{const original={unrelated:true,participant:{channelIdentity:{version:1,challenge:{codeDigest:'a'.repeat(64)},binding:{version:1,status:'VERIFIED',proofEventId:'event'}}}},value=invalidateWorkerChannelIdentity(original,{at:'2026-10-01T12:00:00Z',reasonCode:'SELF_SERVICE_UNLINK'});assert.equal(value.unrelated,true);assert.equal(value.participant.channelIdentity.challenge,null);assert.equal(value.participant.channelIdentity.binding.status,'REVOKED');assert.equal(value.participant.channelIdentity.binding.proofEventId,'event');assert.equal(original.participant.channelIdentity.binding.status,'VERIFIED');});
test('HTTP verifies Clerk and origin before own-store access and excludes caches/referrers',async()=>{let reads=0,writes=0;const handlers=createWorkerChannelHandlers({verify:async()=>session,store:{read:async()=>{reads++;return {records:[]};},command:async()=>{writes++;return {saved:true};}}}),url='https://obrasaas.com/api/identity/worker-channel';const read=await handlers.GET(new Request(url+'?projectId='+input.projectId+'&scope='+scope));assert.equal(read.status,200);assert.equal(read.headers.get('referrer-policy'),'no-referrer');assert.match(read.headers.get('cache-control'),/no-store/);assert.equal((await handlers.GET(new Request(url+'?projectId=x&projectId=y&scope='+scope))).status,400);assert.equal((await handlers.POST(new Request(url,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://other.invalid'},body:JSON.stringify(input)}))).status,403);assert.equal((await handlers.POST(new Request(url,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://obrasaas.com'},body:JSON.stringify(input)}))).status,200);assert.equal(reads,1);assert.equal(writes,1);const invalid=createWorkerChannelHandlers({verify:async()=>({...session,verification:'decoded-jwt'}),store:{read:async()=>{throw Error('must not read');}}});assert.equal((await invalid.GET(new Request(url+'?projectId=x&scope='+scope))).status,401);});

test('company notice identifies the canonical sender and exact Unicode text while legacy evidence remains immutable',()=>{
 const notice=buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'  Construcciones Ñandú & Hijos  '});
 assert.equal(notice.organizationName,'Construcciones Ñandú & Hijos');assert.match(notice.text,/Autorizo a Construcciones Ñandú & Hijos a enviarme/);assert.equal(notice.sha256,createHash('sha256').update(notice.text,'utf8').digest('hex'));
 assert.notEqual(notice.sha256,buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'Otra constructora'}).sha256);assert.equal(createHash('sha256').update(LEGACY_WORKER_TEMPLATE_NOTICE).digest('hex'),LEGACY_WORKER_TEMPLATE_NOTICE_SHA256);
 for(const change of [{organizationName:''},{organizationName:undefined},{organizationName:'Nombre\ninyectado'},{organizationName:'<empresa>'},{organizationName:'x'.repeat(121)},{organizationId:'other/tenant'}])assert.throws(()=>buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'Empresa',...change}),TypeError);
});
test('grant syntax preserves legacy replay but company hash authorization belongs to the canonical transaction',()=>{
 const notice=buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'Empresa'}),grant={...input,action:'GRANT_TEMPLATE_MESSAGES',payload:{...input.payload,confirmed:true,noticeVersion:notice.version,noticeSha256:notice.sha256}};assert.deepEqual(workerChannelCommand(grant),grant);
 for(const change of [{confirmed:false},{confirmed:'true'},{noticeVersion:'old'},{noticeSha256:'bad'}])assert.throws(()=>workerChannelCommand({...grant,payload:{...grant.payload,...change}}),{code:'WORKER_CHANNEL_CONSENT_NOTICE_REQUIRED'});
 // Structural validation cannot decide a company-specific hash without a DB member.
 assert.equal(workerChannelCommand({...grant,payload:{...grant.payload,noticeSha256:'f'.repeat(64)}}).action,'GRANT_TEMPLATE_MESSAGES');
 for(const extra of [{organizationName:'Invented'},{noticeOrganizationId:'foreign'},{phone:'+5491100001111'}])assert.throws(()=>workerChannelCommand({...grant,payload:{...grant.payload,...extra}}),{code:'WORKER_CHANNEL_INPUT_INVALID'});
 assert.equal(workerChannelCommand({...grant,payload:{...grant.payload,noticeVersion:LEGACY_WORKER_TEMPLATE_NOTICE_VERSION,noticeSha256:LEGACY_WORKER_TEMPLATE_NOTICE_SHA256}}).action,'GRANT_TEMPLATE_MESSAGES');assert.equal(workerChannelCommand({...input,action:'REVOKE_TEMPLATE_MESSAGES'}).action,'REVOKE_TEMPLATE_MESSAGES');
});
test('consent is current only for the same audited binding, company and notice; old grants stay historical',()=>{
 const notice=buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'Empresa'}),binding={id:'binding-one'},consent={version:1,status:'GRANTED',purpose:WORKER_TEMPLATE_CONSENT_PURPOSE,noticeVersion:notice.version,noticeSha256:notice.sha256,noticeOrganizationId:notice.organizationId,bindingId:binding.id,receiptId:'worker_channel_'+'a'.repeat(64),grantedAt:'2026-10-02T00:00:00Z'};
 assert.equal(workerTemplateConsentMatches(consent,binding,notice),true);
 for(const value of [undefined,{...consent,status:'REVOKED'},{...consent,receiptId:'declaration'},{...consent,revokedAt:'2026-10-02T01:00:00Z'},{...consent,noticeSha256:'b'.repeat(64)},{...consent,noticeOrganizationId:'company-b'},{...consent,noticeVersion:LEGACY_WORKER_TEMPLATE_NOTICE_VERSION,noticeSha256:LEGACY_WORKER_TEMPLATE_NOTICE_SHA256}])assert.equal(workerTemplateConsentMatches(value,binding,notice),false);
 assert.equal(workerTemplateConsentMatches(consent,binding),false);assert.equal(workerTemplateConsentMatches(consent,binding,buildWorkerTemplateNotice({organizationId:'company-b',organizationName:'Empresa'})),false);assert.equal(workerTemplateConsentMatches(consent,binding,buildWorkerTemplateNotice({organizationId:'company-a',organizationName:'Empresa nueva'})),false);assert.equal(workerTemplateConsentMatches(consent,{id:'new-binding'},notice),false);
 const original={preserve:true,participant:{channelIdentity:{binding:{...binding,status:'VERIFIED'},templateConsent:consent}}},revoked=invalidateWorkerChannelIdentity(original,{reasonCode:'KYC_REPLACED'});assert.equal(revoked.participant.channelIdentity.templateConsent.status,'REVOKED');assert.equal(revoked.participant.channelIdentity.templateConsent.receiptId,consent.receiptId);assert.equal(original.participant.channelIdentity.templateConsent.status,'GRANTED');
});
test('receipt GET accepts only a unique UUID and never accepts raw code or another recipient selector',async()=>{let contexts=[];const handlers=createWorkerChannelHandlers({verify:async()=>session,store:{read:async(_session,context)=>{contexts.push(context);return {state:'NOT_OBSERVED',definitive:false};}}}),url='https://obrasaas.com/api/identity/worker-channel?projectId='+input.projectId+'&scope='+scope;assert.equal((await handlers.GET(new Request(url+'&operationId='+input.operationId.toUpperCase()))).status,200);assert.equal(contexts[0].operationId,input.operationId);for(const extra of ['operationId=bad','operationId='+input.operationId+'&operationId='+input.operationId,'workerId=worker-other','code=VINCULAR','operationId='])assert.equal((await handlers.GET(new Request(url+'&'+extra))).status,400);assert.equal(contexts.length,1);});

function protocolProof(protocol,options={}){
 const signedPurpose=Object.hasOwn(options,'signedPurpose')?options.signedPurpose:protocol.purpose,envelopePurpose=Object.hasOwn(options,'envelopePurpose')?options.envelopePurpose:protocol.purpose,{scheme=protocol.scheme,payloadPurpose=protocol.payloadPurpose,proofPurpose=protocol.proofPurpose}=options,signedGrant=Object.hasOwn(options,'signedGrant')?options.signedGrant:demoConnection.metadata.demoPilot.grantId,envelopeGrant=Object.hasOwn(options,'envelopeGrant')?options.envelopeGrant:demoConnection.metadata.demoPilot.grantId;
 const original=proof(),payload={wabaId:c.whatsappBusinessId,phoneNumberId:c.phoneNumberId,field:'messages',type:'message',value:{id:'wamid.fixture12345',type:'text',text:{body:'VINCULAR '+'A'.repeat(43)},from:'5491100001111',timestamp:String(Math.floor(Date.now()/1000))}},id=protocol.eventPrefix+original.externalId,payloadDigest=metaCustomerContentDigest(payload),ctx={organizationId:c.organizationId,projectId:c.projectId,resourceId:id};
 return {...original,id,provider:protocol.provider,payload:{...original.payload,channelPurpose:envelopePurpose,grantId:envelopeGrant,payloadDigest,encryptedPayload:encryptCustomerSecret(JSON.stringify(payload),{...ctx,purpose:payloadPurpose},env),encryptedProof:encryptCustomerSecret(JSON.stringify({scheme,purpose:signedPurpose,grantId:signedGrant,appId:OBRASAAS_META_CHANNEL.appId,payloadDigest,channelId:c.id,organizationId:c.organizationId}),{...ctx,purpose:proofPurpose},env)}};
}

test('customer legacy proof remains valid and demo signed namespaces cannot be interchanged',()=>{
 const demo=protocolProof(META_DEMO_PILOT_PROTOCOL),customer=protocolProof(META_CUSTOMER_PROTOCOL);
 assert.equal(decodeWorkerChannelProof(proof(),c,env).senderE164,'+5491100001111');
 assert.equal(decodeWorkerChannelProof(customer,c,env).senderE164,'+5491100001111');
 assert.equal(decodeWorkerChannelProof(demo,demoConnection,env,META_DEMO_PILOT_PROTOCOL).senderE164,'+5491100001111');
 assert.throws(()=>decodeWorkerChannelProof(demo,c,env),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});
 assert.throws(()=>decodeWorkerChannelProof(customer,c,env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});
 for(const change of [{signedPurpose:undefined},{signedPurpose:'CUSTOMER'},{envelopePurpose:undefined},{envelopePurpose:'CUSTOMER'},{scheme:META_CUSTOMER_PROTOCOL.scheme}]){
  const row=protocolProof(META_DEMO_PILOT_PROTOCOL,change);
  assert.throws(()=>decodeWorkerChannelProof(row,demoConnection,env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});
 }
 for(const change of [{payloadPurpose:META_CUSTOMER_PROTOCOL.payloadPurpose},{proofPurpose:META_CUSTOMER_PROTOCOL.proofPurpose}])assert.throws(()=>decodeWorkerChannelProof(protocolProof(META_DEMO_PILOT_PROTOCOL,change),demoConnection,env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_PROOF_INTEGRITY'});
 const relabeled={...customer,id:demo.id,provider:demo.provider,payload:{...customer.payload,channelPurpose:'DEMO_PILOT'}};assert.throws(()=>decodeWorkerChannelProof(relabeled,demoConnection,env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_PROOF_INTEGRITY'});
 for(const change of [{signedGrant:undefined},{signedGrant:'retired-demo-grant'},{envelopeGrant:undefined},{envelopeGrant:'retired-demo-grant'}])assert.throws(()=>decodeWorkerChannelProof(protocolProof(META_DEMO_PILOT_PROTOCOL,change),demoConnection,env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});
 assert.throws(()=>decodeWorkerChannelProof(demo,{...demoConnection,metadata:{...demoConnection.metadata,demoPilot:{grantId:'renewed-demo-grant'}}},env,META_DEMO_PILOT_PROTOCOL),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});
});

test('channel factory capabilities cannot be supplied as a copied protocol or request payload',async()=>{
 assert.throws(()=>createWorkerChannelStore({workspace:{},protocol:{...META_DEMO_PILOT_PROTOCOL}}),{code:'META_CLOUD_PROTOCOL_REJECTED'});
 assert.throws(()=>createWorkerChannelStore({workspace:{},decodeProof:null}),TypeError);
 assert.throws(()=>workerChannelCommand({...input,protocol:META_DEMO_PILOT_PROTOCOL}),{code:'WORKER_CHANNEL_INPUT_INVALID'});
 let queries=0;const client={query:async()=>{queries++;return {rows:[protocolProof(META_DEMO_PILOT_PROTOCOL)]};}};
 await assert.rejects(resolveWorkerChannelIdentity(client,{eventId:protocolProof(META_DEMO_PILOT_PROTOCOL).id}),{code:'WORKER_CHANNEL_SIGNED_PROOF_REQUIRED'});assert.equal(queries,1);
 await assert.rejects(resolveWorkerChannelIdentity(client,{eventId:protocolProof(META_DEMO_PILOT_PROTOCOL).id,protocol:{...META_DEMO_PILOT_PROTOCOL}}),{code:'META_CLOUD_PROTOCOL_REJECTED'});assert.equal(queries,1);
});

function ownFixture({change=()=>{},assigned=true,submission=true,review=true}={}){
 const member={actorId:'person-canonical',membershipId:'membership-canonical',organizationId:'org-canonical',clerkUserId:'user_Fixture'},contentHash='f'.repeat(64),row={id:'worker-fixture',projectId:input.projectId,phone:'+5491100001111',active:true,metadata:{participant:{version:1,status:'ACTIVE',clerkUserId:member.clerkUserId,permissions:{attendance:true,report:false},kyc:{version:1,status:'APPROVED',submissionId:'submission-fixture',contentHash,images:[{id:'document-front'},{id:'selfie'}],review:{decision:'APPROVED',actorId:'reviewer-canonical',recordedAt:'2026-10-01T12:00:00Z'}}}}};change(row);const queries=[];
 return {member,row,queries,client:{query:async(sql)=>{queries.push(sql);if(sql.includes('FROM public."ProjectMembership"'))return {rows:assigned?[{id:'pm-fixture'}]:[]};if(sql.includes('FROM public."Worker"'))return {rows:[row]};if(sql.includes("kind'='REVIEW_KYC'"))return {rows:review?[{id:'review-fixture',metadata:{}}]:[]};if(sql.includes("kind'='KYC_SUBMITTED'"))return {rows:submission?[{id:'submission-audit',metadata:{contentHash}}]:[]};throw Error('Unexpected fixture query');}}};
}

test('own participant resolution reuses assignment, permission and audited separate-review checks',async()=>{
 const fixture=ownFixture(),options={clerkUserId:session.userId,projectId:input.projectId,workerId:'worker-fixture',permission:'attendance',lock:true};
 assert.equal(await resolveOwnWorkerParticipant(fixture.client,fixture.member,options),fixture.row);assert.match(fixture.queries[0],/FOR SHARE/);assert.match(fixture.queries[1],/FOR UPDATE/);
 const unassigned=ownFixture({assigned:false});await assert.rejects(resolveOwnWorkerParticipant(unassigned.client,unassigned.member,options),{code:'WORKER_CHANNEL_PARTICIPANT_REQUIRED'});assert.equal(unassigned.queries.length,1);
 for(const change of [row=>{row.metadata.participant.clerkUserId='user_Other';},row=>{row.active=false;},row=>{row.metadata.participant.status='REVOKED';}]){const f=ownFixture({change});await assert.rejects(resolveOwnWorkerParticipant(f.client,f.member,options),{code:'WORKER_CHANNEL_PARTICIPANT_REQUIRED'});}
 const denied=ownFixture();await assert.rejects(resolveOwnWorkerParticipant(denied.client,denied.member,{...options,permission:'report'}),{code:'WORKER_CHANNEL_PERMISSION_REQUIRED'});
 for(const setup of [{review:false},{submission:false},{change:row=>{row.metadata.participant.kyc.status='PENDING_REVIEW';}},{change:row=>{row.metadata.participant.kyc.review.actorId='person-canonical';}}]){const f=ownFixture(setup);await assert.rejects(resolveOwnWorkerParticipant(f.client,f.member,options),{code:'WORKER_CHANNEL_KYC_REVIEW_REQUIRED'});}
 const mismatch=ownFixture();await assert.rejects(resolveOwnWorkerParticipant(mismatch.client,mismatch.member,{...options,clerkUserId:'user_Other'}),{code:'WORKER_CHANNEL_PARTICIPANT_REQUIRED'});assert.equal(mismatch.queries.length,0);
 const readonly=ownFixture();await resolveOwnWorkerParticipant(readonly.client,readonly.member,{...options,lock:false});assert.ok(readonly.queries.every(sql=>!/FOR (UPDATE|SHARE)/.test(sql)));
});

async function adoptedCaptureFixture(){
 const f=ownFixture(),p=f.row.metadata.participant,invitationId='invite_'+'1'.repeat(32),acceptanceReceiptId=participantReceiptId(f.member.actorId,f.row.projectId,randomUUID()),captureReceiptId=participantReceiptId('issuer-canonical',f.row.projectId,randomUUID());
 f.row.organizationId=f.member.organizationId;p.invitation={id:invitationId,state:'ACCEPTED',email:'worker@example.invalid'};p.acceptanceReceiptId=acceptanceReceiptId;
 const capture={version:1,kind:'META_KYC_CHAT',receiptId:captureReceiptId,sourceDigest:'a'.repeat(64),challengeId:'challenge-canonical',invitationId,capturedParticipantClerkUserId:null,accountClaimRequired:true};
 p.kyc={...p.kyc,status:'PENDING_ACCOUNT_CLAIM',channelCapture:capture};delete p.kyc.review;
 const audits=[{id:captureReceiptId,organizationId:f.member.organizationId,actorId:'issuer-canonical',action:'participant.operation.recorded',entityType:'Worker',entityId:f.row.id,metadata:{version:1,projectId:f.row.projectId,kind:'KYC_SUBMITTED',status:'PENDING_ACCOUNT_CLAIM',submissionId:p.kyc.submissionId,contentHash:p.kyc.contentHash,channelCapture:structuredClone(capture)}}];
 const client={query:async(sql,args=[])=>{
  if(sql.includes('FROM public."ProjectMembership"'))return {rows:[{id:'pm-fixture'}]};
  if(sql.includes('FROM public."Worker"'))return {rows:[f.row]};
  if(sql==='SELECT clock_timestamp() AS now')return {rows:[{now:new Date('2026-10-01T11:30:00Z')}]};
  if(sql.startsWith('INSERT INTO public."AuditLog"')){audits.push({id:args[0],organizationId:args[1],actorId:args[2],action:'participant.kyc_chat.adopted',entityType:'Worker',entityId:args[3],metadata:JSON.parse(args[4])});return {rowCount:1,rows:[]};}
  if(sql.includes('FROM public."AuditLog"')){
   let rows;
   if(sql.includes('id=ANY'))rows=audits.filter(a=>a.organizationId===args[0]&&a.entityId===args[1]&&(args[2].includes(a.id)||a.action==='participant.operation.recorded'&&a.metadata.projectId===args[3]&&a.metadata.kind==='KYC_SUBMITTED'&&a.metadata.submissionId===args[4]));
   else if(sql.includes('WHERE id=$1'))rows=audits.filter(a=>a.id===args[0]&&a.organizationId===args[1]&&a.action==='participant.operation.recorded');
   else rows=audits.filter(a=>a.organizationId===args[0]&&a.actorId===args[1]&&a.entityId===args[2]&&a.action==='participant.operation.recorded'&&a.metadata.projectId===args[3]&&a.metadata.submissionId===args[4]&&a.metadata.kind===(sql.includes("kind'='REVIEW_KYC'")?'REVIEW_KYC':'KYC_SUBMITTED'));
   return {rows:structuredClone(rows)};
  }
  throw Error('Unexpected adopted-capture fixture query');
 }};
 const origin=JSON.stringify(audits[0]);assert.equal(await adoptParticipantChannelKyc(client,{row:f.row,participant:p,invitationId,actorId:f.member.actorId,clerkUserId:f.member.clerkUserId,acceptanceReceiptId}),true);
 audits.push({id:acceptanceReceiptId,organizationId:f.member.organizationId,actorId:f.member.actorId,action:'participant.operation.recorded',entityType:'Worker',entityId:f.row.id,metadata:{version:1,projectId:f.row.projectId,kind:'INVITATION_ACCEPTED',invitationId,requestDigest:digest([f.row.id,invitationId,f.member.clerkUserId,p.invitation.email])}});
 p.kyc={...p.kyc,status:'APPROVED',review:{decision:'APPROVED',actorId:'reviewer-canonical',recordedAt:'2026-10-01T12:00:00Z'}};
 audits.push({id:'review-fixture',organizationId:f.member.organizationId,actorId:'reviewer-canonical',action:'participant.operation.recorded',entityType:'Worker',entityId:f.row.id,metadata:{version:1,projectId:f.row.projectId,kind:'REVIEW_KYC',submissionId:p.kyc.submissionId,decision:'APPROVED'}});
 return {...f,client,audits,origin,options:{clerkUserId:f.member.clerkUserId,projectId:f.row.projectId,workerId:f.row.id,permission:'attendance',lock:true}};
}

test('canonical pre-account capture adoption enables own binding guard after separate human review without rewriting origin actor',async()=>{
 const f=await adoptedCaptureFixture();assert.equal(await resolveOwnWorkerParticipant(f.client,f.member,f.options),f.row);assert.equal(JSON.stringify(f.audits[0]),f.origin);assert.equal(f.audits[0].actorId,'issuer-canonical');assert.equal(f.row.metadata.participant.kyc.channelCapture.claimedActorId,f.member.actorId);
});

test('adopted KYC rejects missing, duplicate, foreign or copied canonical receipts',async t=>{
 const cases=[
  ['capture missing',f=>f.audits.splice(0,1)],['adoption missing',f=>f.audits.splice(1,1)],['acceptance missing',f=>f.audits.splice(2,1)],
  ['duplicate submission',f=>f.audits.push({...structuredClone(f.audits[0]),id:'participant_'+'b'.repeat(64)})],['duplicate acceptance',f=>f.audits.push(structuredClone(f.audits[2]))],['duplicate adoption',f=>f.audits.push(structuredClone(f.audits[1]))],
  ['capture foreign organization',f=>{f.audits[0].organizationId='foreign-company';}],['acceptance foreign organization',f=>{f.audits[2].organizationId='foreign-company';}],['adoption foreign organization',f=>{f.audits[1].organizationId='foreign-company';}],
  ['capture foreign worker',f=>{f.audits[0].entityId='other-worker';}],['acceptance foreign worker',f=>{f.audits[2].entityId='other-worker';}],['adoption foreign worker',f=>{f.audits[1].entityId='other-worker';}],
  ['capture foreign project',f=>{f.audits[0].metadata.projectId='other-project';}],['acceptance foreign project',f=>{f.audits[2].metadata.projectId='other-project';}],['adoption foreign project',f=>{f.audits[1].metadata.projectId='other-project';}],
  ['capture copied action',f=>{f.audits[0].action='worker.channel.identity.recorded';}],['acceptance copied action',f=>{f.audits[2].action='participant.kyc_chat.adopted';}],['adoption copied action',f=>{f.audits[1].action='participant.operation.recorded';}],
  ['capture wrong entity type',f=>{f.audits[0].entityType='TenantMembership';}],['acceptance wrong actor',f=>{f.audits[2].actorId='other-person';}],['adoption wrong actor',f=>{f.audits[1].actorId='other-person';}],
  ['capture stale submission',f=>{f.audits[0].metadata.submissionId='old-submission';}],['adoption stale submission',f=>{f.audits[1].metadata.submissionId='old-submission';}],['capture changed content',f=>{f.audits[0].metadata.contentHash='b'.repeat(64);}],['adoption changed content',f=>{f.audits[1].metadata.contentHash='b'.repeat(64);}],
  ['capture not pre-account',f=>{f.audits[0].metadata.status='PENDING_REVIEW';}],['capture unrelated invitation',f=>{f.audits[0].metadata.channelCapture.invitationId='invite_'+'2'.repeat(32);}],['acceptance unrelated invitation',f=>{f.audits[2].metadata.invitationId='invite_'+'2'.repeat(32);}],
  ['acceptance wrong Clerk digest',f=>{const p=f.row.metadata.participant;f.audits[2].metadata.requestDigest=digest([f.row.id,p.invitation.id,'user_Other',p.invitation.email]);}],['adoption wrong capture reference',f=>{f.audits[1].metadata.captureReceiptId='participant_'+'b'.repeat(64);}],['adoption wrong acceptance reference',f=>{f.audits[1].metadata.acceptanceReceiptId='participant_'+'b'.repeat(64);}],
 ];
 for(const [label,change] of cases)await t.test(label,async()=>{const f=await adoptedCaptureFixture();change(f);await assert.rejects(resolveOwnWorkerParticipant(f.client,f.member,f.options),{code:'WORKER_CHANNEL_KYC_REVIEW_REQUIRED'});});
});

test('adopted KYC remains tied to current individual invitation, claim and distinct review',async t=>{
 const cases=[
  ['unadopted presentation',p=>{delete p.kyc.channelCapture;}],['claim still required',p=>{p.kyc.channelCapture.accountClaimRequired=true;}],['wrong claimed actor',p=>{p.kyc.channelCapture.claimedActorId='other-person';}],['wrong claimed Clerk account',p=>{p.kyc.channelCapture.claimedClerkUserId='user_Other';}],
  ['wrong participant acceptance',p=>{p.acceptanceReceiptId='participant_'+'b'.repeat(64);}],['wrong claim acceptance',p=>{p.kyc.channelCapture.acceptanceReceiptId='participant_'+'b'.repeat(64);}],['wrong current invitation',p=>{p.invitation.id='invite_'+'2'.repeat(32);}],['invitation revoked',p=>{p.invitation.state='REVOKED';}],['invitation absent',p=>{p.invitation=null;}],['wrong current email',p=>{p.invitation.email='other@example.invalid';}],
  ['malformed claim time',p=>{p.kyc.channelCapture.claimedAt='not-a-date';}],['review predates claim',p=>{p.kyc.channelCapture.claimedAt='2026-10-01T12:30:00Z';}],['changed challenge',p=>{p.kyc.channelCapture.challengeId='other-challenge';}],['changed signed source',p=>{p.kyc.channelCapture.sourceDigest='b'.repeat(64);}],['unknown capture field',p=>{p.kyc.channelCapture.actorOverride='other-person';}],['captured account injected',p=>{p.kyc.channelCapture.capturedParticipantClerkUserId='user_Other';}],['self review',p=>{p.kyc.review.actorId='person-canonical';}],['not approved',p=>{p.kyc.status='PENDING_REVIEW';}],
 ];
 for(const [label,change] of cases)await t.test(label,async()=>{const f=await adoptedCaptureFixture();change(f.row.metadata.participant);await assert.rejects(resolveOwnWorkerParticipant(f.client,f.member,f.options),{code:'WORKER_CHANNEL_KYC_REVIEW_REQUIRED'});});
 const revoked=await adoptedCaptureFixture();revoked.row.metadata.participant.status='REVOKED';await assert.rejects(resolveOwnWorkerParticipant(revoked.client,revoked.member,revoked.options),{code:'WORKER_CHANNEL_PARTICIPANT_REQUIRED'});
 const reassigned=await adoptedCaptureFixture();reassigned.row.metadata.participant.clerkUserId='user_Other';await assert.rejects(resolveOwnWorkerParticipant(reassigned.client,reassigned.member,reassigned.options),{code:'WORKER_CHANNEL_PARTICIPANT_REQUIRED'});
});
