import test from 'node:test';
import assert from 'node:assert/strict';
import {templateSendSnapshot,templateSendResult,templateSendNotice} from '../src/app/(identity)/cuenta/template-send-view.mjs';
import {createWorkspaceRecoveryJournal} from '../src/app/(identity)/cuenta/workspace-recovery-journal.mjs';
import {createWorkspaceRequestLifecycle} from '../src/app/(identity)/cuenta/workspace-request-lifecycle.mjs';
const command={scope:'a'.repeat(64),projectId:'p-a',operationId:'01234567-89ab-4cde-8fab-0123456789ab',workerId:'worker-a',templateKey:'open_attendance_reminder'};
const context={projectId:command.projectId,scope:command.scope};
const receipt={id:'template-receipt-a',operationId:command.operationId,workerId:command.workerId,templateKey:command.templateKey};
const result=extra=>({...context,receipt,state:'ACCEPTED',saved:true,definitive:true,providerAccepted:true,providerStatus:null,deliveryConfirmed:false,...extra});
const snapshot=()=>({...context,projectName:'Obra sintética',canSend:true,template:{key:command.templateKey,title:'Jornada abierta',bodyText:'Tu jornada sigue abierta.',canSend:true,providerStatus:'APPROVED'},records:[{workerId:'worker-a',name:'Trabajador de ensayo',eligible:true}]});
test('snapshot rejects foreign project/scope, duplicate recipient and unsupported template',()=>{for(const value of [{...snapshot(),projectId:'p-b'},{...snapshot(),scope:'b'.repeat(64)},{...snapshot(),records:[...snapshot().records,...snapshot().records]},{...snapshot(),template:{...snapshot().template,key:'participant_invitation'}}])assert.throws(()=>templateSendSnapshot(value,context));assert.equal(templateSendSnapshot(snapshot(),context).records.length,1);});
test('accepted dispatch is explicit and is never interpreted as delivery or attendance',()=>{const value=templateSendResult(result(),command);assert.equal(value.deliveryConfirmed,false);assert.match(templateSendNotice(value),/aceptó.*entrega todavía no está confirmada/);assert.match(templateSendNotice(value),/no registra la salida/);assert.throws(()=>templateSendResult(result({deliveryConfirmed:true}),command));});
test('receipt attribution requires exact operation, recipient, template and project',()=>{for(const changed of [{operationId:'01234567-89ab-4cde-8fab-0123456789ac'},{workerId:'worker-b'},{templateKey:'field_evidence_request'},{id:''}])assert.throws(()=>templateSendResult(result({receipt:{...receipt,...changed}}),command));assert.throws(()=>templateSendResult(result({projectId:'p-b'}),command));});
test('unknown and missing outcomes stay uncertain without fabricated confirmation',()=>{for(const state of ['SEND_STARTED','SEND_UNKNOWN']){const value=templateSendResult(result({state,saved:false,definitive:false,providerAccepted:false}),command);assert.match(templateSendNotice(value),/sin confirmar/);assert.throws(()=>templateSendResult({...value,definitive:true},command));}const absent=templateSendResult({...context,state:'NOT_OBSERVED',definitive:false,providerAccepted:false,deliveryConfirmed:false},command);assert.match(templateSendNotice(absent),/no se genera otro envío/);assert.throws(()=>templateSendResult({...absent,definitive:true},command));});
test('signed delivery and failed statuses retain distinct user-facing results',()=>{for(const status of ['sent','delivered','read','failed','deleted']){const value=templateSendResult(result({state:'STATUS_OBSERVED',providerStatus:status,deliveryConfirmed:['delivered','read'].includes(status)}),command);if(['failed','deleted'].includes(status))assert.match(templateSendNotice(value),/falló o fue eliminado/);if(status==='read')assert.match(templateSendNotice(value),/lectura/);if(status==='delivered')assert.match(templateSendNotice(value),/entrega del mensaje/);}assert.throws(()=>templateSendResult(result({state:'STATUS_OBSERVED',providerStatus:'sent',deliveryConfirmed:true}),command));assert.throws(()=>templateSendResult(result({state:'STATUS_OBSERVED',providerStatus:'imaginary'}),command));});
test('definitive local stop and provider rejection have different messages',()=>{const value=templateSendResult(result({state:'REJECTED',saved:false,providerAccepted:false}),command);assert.match(templateSendNotice(value),/Se detuvo/);assert.match(templateSendNotice({...value,code:'META_CUSTOMER_PROVIDER_REJECTED'}),/Meta rechazó/);assert.throws(()=>templateSendResult({...value,saved:true},command));assert.throws(()=>templateSendResult({...value,providerAccepted:true},command));});
test('malformed POST or recovery result is rejected before a durable reference can be removed',async()=>{
 for(const method of ['POST','GET']){
  const rows=new Map(),storage={get length(){return rows.size;},key:index=>[...rows.keys()][index],getItem:key=>rows.get(key),setItem:(key,value)=>rows.set(key,value),removeItem:key=>rows.delete(key)};
  const journal=createWorkspaceRecoveryJournal({getStorage:()=>storage});journal.prepare('/api/identity/template-send',{method:'POST',body:JSON.stringify(command)});
  const transport=createWorkspaceRequestLifecycle(async()=>'controlled',{journal,fetchImpl:async()=>Response.json(result({receipt:{...receipt,workerId:'worker-b'}}))});
  const url='/api/identity/template-send'+(method==='GET'?'?'+new URLSearchParams({projectId:command.projectId,scope:command.scope,operationId:command.operationId}):'');
  await assert.rejects(transport.request(url,{method,...(method==='POST'?{body:JSON.stringify(command)}:{})},async response=>templateSendResult(await response.json(),command)));
  assert.equal(journal.list(command.scope).length,1);transport.abort();
 }
});
