import test from 'node:test';
import assert from 'node:assert/strict';
import {readOwnCompanyPolicy,createOwnCompanyCapability,ownCompanyCapabilityPolicy,ownCompanyConnectionPolicy,META_OWN_COMPANY_TTL_MS} from '../src/lib/meta-own-company-policy.mjs';
import {normalizeOwnCompanyCommand} from '../src/lib/meta-own-company-connection.mjs';
import {createMetaCustomerProvider,metaCustomerReadiness,metaCustomerScopedTransportReady} from '../src/lib/meta-customer-provider.mjs';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {digest} from '../src/lib/workspace-policy.mjs';
import {ownCompanyFixture} from './fixtures/own-company-meta.mjs';

const provider=f=>createMetaCustomerProvider({environment:f.environment,fetchImpl:f.fetchImpl,now:()=>f.time});
test('OWN_COMPANY is default closed, Production/source/review bound and expires within its separate four-hour capability',()=>{
 const f=ownCompanyFixture();assert.equal(readOwnCompanyPolicy({}),null);assert.ok(readOwnCompanyPolicy(f.environment,f.time));
 for(const patch of [{VERCEL_ENV:'preview'},{VERCEL_GIT_COMMIT_SHA:'c'.repeat(40)},{OBRASAAS_META_OWN_COMPANY_POLICY_REVIEW_SHA256:'d'.repeat(64)},{OBRASAAS_META_OWN_COMPANY_RELEASE:'customer-self-service-v1'}])assert.equal(readOwnCompanyPolicy({...f.environment,...patch},f.time),null);
 for(const patch of [{wabaId:OBRASAAS_META_CHANNEL.wabaId},{phoneNumberId:OBRASAAS_META_CHANNEL.phoneNumberId},{issuedAt:new Date(f.time+1).toISOString()},{expiresAt:new Date(f.time).toISOString()},{expiresAt:new Date(f.time+META_OWN_COMPANY_TTL_MS+1).toISOString()}]){const p={...f.policy,...patch};assert.equal(readOwnCompanyPolicy({...f.environment,OBRASAAS_META_OWN_COMPANY_POLICY:JSON.stringify(p),OBRASAAS_META_OWN_COMPANY_POLICY_REVIEW_SHA256:digest(p)},f.time),null);}
});
test('only the current canonical admin, Clerk organization and exact declaration can mint the opaque capability',()=>{
 const f=ownCompanyFixture(),cap=createOwnCompanyCapability(f.context,f.environment,f.time);assert.ok(ownCompanyCapabilityPolicy(cap,f.environment,f.time));assert.throws(()=>ownCompanyCapabilityPolicy({},f.environment,f.time));
 for(const context of [{...f.context,member:{...f.context.member,role:'DIRECTOR'}},{...f.context,member:{...f.context.member,actorId:'other'}},{...f.context,session:{...f.context.session,organizationId:'org_B'}},{...f.context,project:{...f.context.project,id:'project-b'}},{...f.context,project:{...f.context.project,organizationMetadata:{companyPhoneDeclaration:{...f.declaration,revision:2}}}}])assert.throws(()=>createOwnCompanyCapability(context,f.environment,f.time),e=>e.code==='META_OWN_COMPANY_UNAVAILABLE');
});
test('production provider audits SYSTEM_USER/business-owned app, WABA and user while all general customer gates stay closed',async()=>{
 const f=ownCompanyFixture(),base=provider(f),scoped=await base.forOwnCompany(f.context),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN;
 assert.equal(metaCustomerReadiness(f.environment).gates.review,false);assert.equal(metaCustomerReadiness(f.environment).flows.BUSINESS_APP.available,false);assert.equal(metaCustomerReadiness(f.environment).canLaunchMeta,false);assert.equal(scoped.readiness().canLaunchMeta,false);assert.equal(metaCustomerScopedTransportReady(scoped.readiness()),true);
 const verified=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId});assert.equal(verified.registered,true);assert.ok(scoped.ownProvenance(verified));assert.ok(f.calls.some(c=>c.path.endsWith('/owned_apps')));assert.ok(f.calls.every(c=>c.method==='GET'));
 await assert.rejects(base.sendReply({token,phoneNumberId:f.policy.phoneNumberId,to:'5491100001111',replyTo:'wamid.syntheticincoming12345',correlationId:'customer_outbound_'+'b'.repeat(64),message:{type:'text',body:'Synthetic reply'}}),e=>e.code==='META_CUSTOMER_CONFIGURATION_PENDING');
 await assert.rejects(scoped.templates({token,wabaId:f.policy.wabaId}),e=>e.code==='META_OWN_COMPANY_ADAPTER_UNAVAILABLE');
});
test('own import requires its dedicated token without global fallback; runtime remains bound to the vaulted token after import configuration removal',async()=>{
 const f=ownCompanyFixture(),globals={META_WHATSAPP_ACCESS_TOKEN:f.environment.META_WHATSAPP_ACCESS_TOKEN,WHATSAPP_TOKEN:f.environment.WHATSAPP_TOKEN},base=provider(f),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN,scoped=await base.forOwnCompany(f.context),verified=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId}),connection={id:'channel-own',projectId:f.policy.projectId,organizationId:f.policy.organizationId,whatsappBusinessId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,displayPhoneNumber:f.policy.expectedPhoneE164,metadata:{credentialOrganizationId:f.policy.organizationId,ownCompany:scoped.ownProvenance(verified)}},cap=createOwnCompanyCapability(f.context,f.environment,f.time);
 delete f.environment.META_OWN_COMPANY_ACCESS_TOKEN;const calls=f.calls.length;await assert.rejects(base.forOwnCompany(f.context),e=>e.code==='META_OWN_COMPANY_CONFIGURATION_PENDING');assert.equal(f.calls.length,calls);
 const runtime=await base.forConnection({capability:cap,connection,token});await runtime.sendReply({token,phoneNumberId:f.policy.phoneNumberId,to:'5491100001111',replyTo:'wamid.syntheticincoming12345',correlationId:'customer_outbound_'+'e'.repeat(64),message:{type:'text',body:'Synthetic vaulted own token'}});assert.equal(f.calls.filter(call=>call.method==='POST').length,1);assert.deepEqual({META_WHATSAPP_ACCESS_TOKEN:f.environment.META_WHATSAPP_ACCESS_TOKEN,WHATSAPP_TOKEN:f.environment.WHATSAPP_TOKEN},globals);
});
for(const [name,mutate] of [
 ['USER token',f=>f.debug.type='USER'],['extra scope',f=>f.debug.scopes.push('ads_read')],['missing scope',f=>f.debug.scopes.splice(1,1)],['duplicate scope',f=>f.debug.scopes[3]='business_management'],['missing messaging granular grant',f=>f.debug.granular_scopes.pop()],['malformed granular targets',f=>f.debug.granular_scopes[1].target_ids=null],['contradictory explicit granular target',f=>f.debug.granular_scopes[1].target_ids=['999999999']],['partial explicit messaging grant',f=>{f.debug.granular_scopes[1].target_ids=[f.policy.wabaId];f.debug.granular_scopes[2].target_ids=['999999999'];}],['indefinite token',f=>f.debug.expires_at=0],['token expires before policy',f=>f.debug.expires_at=Math.floor((f.time+1800000)/1000)],['data access expires before policy',f=>f.debug.data_access_expires_at=Math.floor((f.time+1800000)/1000)],['foreign app',f=>f.debug.app_id='999999999'],['unowned app',f=>f.state.missingEdge='owned_apps'],['unowned system user',f=>f.state.missingEdge='system_users'],['unowned WABA',f=>f.state.missingEdge='owned_whatsapp_business_accounts'],['paged ownership',f=>f.state.pagingEdge='owned_apps'],
])test('own provider rejects '+name+' before any mutation',async()=>{const f=ownCompanyFixture();mutate(f);await assert.rejects(provider(f).forOwnCompany(f.context));assert.ok(f.calls.every(c=>c.method==='GET'));});
test('exact declared phone and asset IDs reject aliases or unrelated phone/token, with real composition reply allowed only under an opaque own capability',async()=>{
 const f=ownCompanyFixture(),base=provider(f),scoped=await base.forOwnCompany(f.context),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN,verified=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId}),proof=scoped.ownProvenance(verified),connection={id:'channel-own',projectId:f.policy.projectId,organizationId:f.policy.organizationId,whatsappBusinessId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,displayPhoneNumber:f.policy.expectedPhoneE164,metadata:{credentialOrganizationId:f.policy.organizationId,ownCompany:proof}};
 assert.ok(ownCompanyConnectionPolicy(connection,f.environment,f.time));assert.throws(()=>ownCompanyConnectionPolicy({...connection,phoneNumberId:'999999999'},f.environment,f.time));
 const cap=createOwnCompanyCapability(f.context,f.environment,f.time),runtime=await base.forConnection({capability:cap,connection,token});await runtime.sendReply({token,phoneNumberId:f.policy.phoneNumberId,to:'5491100001111',replyTo:'wamid.syntheticincoming12345',correlationId:'customer_outbound_'+'b'.repeat(64),message:{type:'text',body:'Synthetic authorized own company reply'}});assert.equal(f.calls.filter(c=>c.method==='POST').length,1);
 await assert.rejects(runtime.sendReply({token:'synthetic-unrelated-server-token',phoneNumberId:f.policy.phoneNumberId,to:'5491100001111',replyTo:'wamid.syntheticincoming12345',correlationId:'customer_outbound_'+'b'.repeat(64),message:{type:'text',body:'Reject'}}));
 await assert.rejects(base.forConnection({capability:{},connection,token}));
 f.phone.display_phone_number='+541100009999';await assert.rejects(runtime.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId}),e=>e.code==='META_OWN_COMPANY_PHONE_REJECTED');
});
test('already registered dedicated number avoids register POST and copied inspection cannot authorize an unregistered number',async()=>{
 const f=ownCompanyFixture(),scoped=await provider(f).forOwnCompany(f.context),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN;
 const inspection=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,inspectionPhase:'PRE_REGISTRATION'});assert.equal(inspection.registered,true);
 await assert.rejects(scoped.register({token,phoneNumberId:f.policy.phoneNumberId,pin:'123456',inspection:{...inspection,registered:false}}),e=>e.registrationDispatched===false);assert.equal(f.calls.filter(c=>c.method==='POST').length,0);
});
test('own command excludes token/actor inputs and distinguishes a registration security PIN from an SMS code',()=>{
 const f=ownCompanyFixture(),input={projectId:'project-a',scope:'a'.repeat(64),operationId:'11111111-1111-4111-8111-111111111111',action:'CONNECT_OWN_NUMBER',payload:{connectionId:null,revision:0,companyPhoneRevision:1,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,confirmOwnBusiness:true,confirmReplacement:false}};
 assert.ok(normalizeOwnCompanyCommand(input));assert.throws(()=>normalizeOwnCompanyCommand({...input,payload:{...input.payload,token:'secret'}}));assert.throws(()=>normalizeOwnCompanyCommand({...input,actorId:'owner'}));
 const activation={...input,action:'ACTIVATE_OWN_NUMBER',payload:{...input.payload,connectionId:'channel-own',revision:2,confirmRegistration:false,securityPin:null}};assert.ok(normalizeOwnCompanyCommand(activation));assert.throws(()=>normalizeOwnCompanyCommand({...activation,payload:{...activation.payload,securityPin:'123456'}}));
});
test('own pending dedicated registration consumes fresh inspected authority once and preserves the operational phase boundary',async()=>{
 const f=ownCompanyFixture();f.state.registered=false;const scoped=await provider(f).forOwnCompany(f.context),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN,inspection=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,inspectionPhase:'PRE_REGISTRATION'});assert.equal(inspection.registered,false);
 assert.equal(await scoped.register({token,phoneNumberId:f.policy.phoneNumberId,pin:'123456',inspection}),true);assert.equal(f.calls.filter(call=>call.path.endsWith('/register')&&call.method==='POST').length,1);
 await assert.rejects(scoped.register({token,phoneNumberId:f.policy.phoneNumberId,pin:'123456',inspection}),e=>e.registrationDispatched===false);assert.equal(f.calls.filter(call=>call.path.endsWith('/register')&&call.method==='POST').length,1);
});
test('own registration lost provider acknowledgement consumes the original inspection and prevents another POST from that proof',async()=>{
 const f=ownCompanyFixture();f.state.registered=false;f.state.failPost=f.policy.phoneNumberId+'/register';const scoped=await provider(f).forOwnCompany(f.context),token=f.environment.META_OWN_COMPANY_ACCESS_TOKEN,inspection=await scoped.inspect({token,wabaId:f.policy.wabaId,phoneNumberId:f.policy.phoneNumberId,inspectionPhase:'PRE_REGISTRATION'});
 await assert.rejects(scoped.register({token,phoneNumberId:f.policy.phoneNumberId,pin:'123456',inspection}),e=>e.code==='META_CUSTOMER_PROVIDER_UNCONFIRMED');await assert.rejects(scoped.register({token,phoneNumberId:f.policy.phoneNumberId,pin:'123456',inspection}),e=>e.registrationDispatched===false);assert.equal(f.calls.filter(call=>call.path.endsWith('/register')&&call.method==='POST').length,1);
});
