import test from 'node:test';
import assert from 'node:assert/strict';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {createMetaCustomerProvider,metaCustomerReadiness,metaCustomerTransportReady,META_CUSTOMER_INSPECTION_PHASE} from '../src/lib/meta-customer-provider.mjs';
import {readDevelopmentPilotPolicy,createDevelopmentPilotCapability,developmentPilotCapabilityPolicy,developmentPilotPhoneMatches,META_DEVELOPMENT_PILOT_TTL_MS} from '../src/lib/meta-development-pilot-policy.mjs';

const time=Date.parse('2026-10-06T00:00:00.000Z'),customerToken='synthetic-customer-token-only-123456789',auditorToken='synthetic-existing-auditor-only-12345678',wabaId='123456789012345',phoneNumberId='123456789012346';
const policy={version:1,organizationId:'tenant_Synthetic',actorId:'actor_Synthetic',clerkUserId:'user_Synthetic',clerkOrganizationId:'org_Synthetic',projectId:'project_Synthetic',appId:OBRASAAS_META_CHANNEL.appId,configId:'123456789012347',businessId:'123456789012348',expectedPhoneE164:'+5491198765432',allowArgentinaMobileAlias:true,issuedAt:new Date(time).toISOString(),expiresAt:new Date(time+3600000).toISOString()};
const environment=()=>({NEXT_PUBLIC_META_APP_ID:OBRASAAS_META_CHANNEL.appId,META_APP_SECRET:'synthetic-app-secret-for-tests-only',META_CONFIG_ID:policy.configId,META_GRAPH_API_VERSION:'v25.0',META_EMBEDDED_SIGNUP_VERSION:'4',WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:Buffer.alloc(32,23).toString('base64'),META_CUSTOMER_VERIFY_TOKEN:'synthetic-callback-verifier-'.repeat(2),META_WABA_ID:OBRASAAS_META_CHANNEL.wabaId,META_PHONE_NUMBER_ID:OBRASAAS_META_CHANNEL.phoneNumberId,META_WHATSAPP_ACCESS_TOKEN:auditorToken,OBRASAAS_META_DEVELOPMENT_PILOT_POLICY:JSON.stringify(policy)});
const context=()=>({member:{actorId:policy.actorId,organizationId:policy.organizationId,role:'ADMIN'},session:{userId:policy.clerkUserId,organizationId:policy.clerkOrganizationId,organizationRole:'org:admin'},project:{id:policy.projectId,organizationId:policy.organizationId,metadata:{}}});
const scopes=['whatsapp_business_management','whatsapp_business_messaging'];
const auditor=()=>({data:{is_valid:true,app_id:policy.appId,type:'SYSTEM_USER',scopes:[...scopes,'business_management'],expires_at:Math.floor(time/1000)+3600}});
const grant=()=>({data:{is_valid:true,app_id:policy.appId,scopes:[...scopes],granular_scopes:[{scope:'whatsapp_business_management',target_ids:[wabaId]}],expires_at:Math.floor(time/1000)+3600}});
const phone=()=>({data:[{id:phoneNumberId,display_phone_number:'+54 11 9876-5432',status:'CONNECTED',code_verification_status:'VERIFIED',is_on_biz_app:false,platform_type:'CLOUD_API'}]});
function graph(responses,{env=environment(),clock=()=>time,hook=()=>{}}={}){const calls=[];return {env,calls,provider:createMetaCustomerProvider({environment:env,now:clock,fetchImpl:async(url,options)=>{calls.push({url:new URL(url),options});hook(calls.length);const next=responses.shift();if(next instanceof Error)throw next;return next instanceof Response?next:Response.json(next);}})};}

test('private development policy is default OFF and does not open global release',()=>{assert.equal(readDevelopmentPilotPolicy({}),null);const env=environment(),p=readDevelopmentPilotPolicy(env,time);assert.equal(p.projectId,policy.projectId);const r=metaCustomerReadiness(env);assert.equal(r.gates.review,false);assert.equal(r.canLaunchMeta,false);assert.equal(metaCustomerTransportReady(r),false);});
for(const [name,mutate] of [
 ['unknown key',p=>{p.ready=true;}],['actor invalid',p=>{p.actorId='';}],['Clerk mapping malformed',p=>{p.clerkUserId='other';}],['future issue',p=>{p.issuedAt=new Date(time+1).toISOString();}],['expired',p=>{p.expiresAt=new Date(time).toISOString();}],['too long',p=>{p.expiresAt=new Date(time+META_DEVELOPMENT_PILOT_TTL_MS+1).toISOString();}],['business invalid',p=>{p.businessId='client';}],['noncanonical date',p=>{p.issuedAt='2026-10-06T00:00:00Z';}],['other app',p=>{p.appId='123456789012399';}],['other configuration',p=>{p.configId='123456789012399';}],['foreign alias',p=>{p.expectedPhoneE164='+14155550123';}],
])test('private policy closes '+name,()=>{const env=environment(),p=structuredClone(policy);mutate(p);env.OBRASAAS_META_DEVELOPMENT_PILOT_POLICY=JSON.stringify(p);assert.equal(readDevelopmentPilotPolicy(env,time),null);});
test('conflicting configuration aliases close every policy consumer',()=>{assert.equal(readDevelopmentPilotPolicy({...environment(),NEXT_PUBLIC_META_EMBEDDED_SIGNUP_CONFIG_ID:'123456789012399'},time),null);});
test('Argentina alias is exact and explicit, never a suffix or general normalization',()=>{assert.equal(developmentPilotPhoneMatches(policy,'+54 (11) 9876-5432'),true);assert.equal(developmentPilotPhoneMatches(policy,'+54 9 11 9876-5432'),true);for(const value of ['+54 11 9876-5433','1198765432','+55 11 9876-5432'])assert.equal(developmentPilotPhoneMatches(policy,value),false);assert.equal(developmentPilotPhoneMatches({...policy,allowArgentinaMobileAlias:false},'+541198765432'),false);});
test('opaque capability cannot be forged or retained after TTL/policy replacement',()=>{const env=environment(),cap=createDevelopmentPilotCapability(context(),env,time);assert.ok(cap);assert.throws(()=>developmentPilotCapabilityPolicy({},env,time),{code:'META_DEVELOPMENT_PILOT_UNAVAILABLE'});assert.throws(()=>developmentPilotCapabilityPolicy(structuredClone(cap),env,time),{code:'META_DEVELOPMENT_PILOT_UNAVAILABLE'});assert.throws(()=>developmentPilotCapabilityPolicy(cap,env,time+3600000),{code:'META_DEVELOPMENT_PILOT_UNAVAILABLE'});env.OBRASAAS_META_DEVELOPMENT_PILOT_POLICY=JSON.stringify({...policy,expiresAt:new Date(time+3600001).toISOString()});assert.throws(()=>developmentPilotCapabilityPolicy(cap,env,time),{code:'META_DEVELOPMENT_PILOT_UNAVAILABLE'});});
for(const key of ['actorId','organizationId','projectId','clerkUserId','clerkOrganizationId','role'])test('other '+key+' never probes the existing auditor',async()=>{const c=context();if(key==='projectId')c.project.id='project_Other';else if(key==='clerkUserId')c.session.userId='user_Other';else if(key==='clerkOrganizationId')c.session.organizationId='org_Other';else c.member[key]=key==='role'?'DIRECTOR':'other_Synthetic';const f=graph([]);assert.equal(await f.provider.forWorkspace(c),f.provider);assert.equal(f.calls.length,0);});
test('auditor and customer credentials stay separate and global gates stay false',async()=>{const f=graph([auditor(),{data:[{id:wabaId}]},grant(),phone()]),scoped=await f.provider.forWorkspace(context()),r=scoped.readiness();assert.equal(r.mode,'DEVELOPMENT_PILOT');assert.equal(r.pilot.canLaunch,true);assert.equal(r.canLaunchMeta,false);assert.equal(r.gates.review,false);assert.equal(r.canUseCustomerTransport,false);assert.equal(r.flows.DEDICATED.available,false);assert.equal(f.calls[0].url.searchParams.get('input_token'),auditorToken);assert.equal(f.calls[0].options.method,'GET');assert.equal(f.calls[1].url.pathname,`/v25.0/${policy.businessId}/owned_whatsapp_business_accounts`);assert.equal(f.calls[1].options.headers.Authorization,'Bearer '+auditorToken);assert.equal(f.calls[1].url.searchParams.has('find'),false);const verified=await scoped.inspect({token:customerToken,wabaId,phoneNumberId});assert.equal(f.calls[2].url.searchParams.get('input_token'),customerToken);assert.equal(f.calls[3].options.headers.Authorization,'Bearer '+customerToken);assert.equal(scoped.pilotProvenance(verified).businessId,policy.businessId);assert.throws(()=>scoped.pilotProvenance({...verified}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});});
for(const [name,change] of [['missing portfolio scope',d=>{d.scopes=scopes;}],['user token',d=>{d.type='USER';}],['other app',d=>{d.app_id='123456789012399';}],['expired',d=>{d.expires_at=1;}],['invalid',d=>{d.is_valid=false;}],['malformed scopes',d=>{d.scopes='business_management';}]])test('auditor '+name+' closes launch before portfolio read',async()=>{const a=auditor();change(a.data);const f=graph([a]),scoped=await f.provider.forWorkspace(context());assert.equal(scoped.readiness().pilot.canLaunch,false);assert.equal(f.calls.length,1);await assert.rejects(scoped.exchange('synthetic-code-only'),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,1);});
for(const [name,owned] of [['paging',{data:[{id:wabaId}],paging:{next:'https://foreign.invalid/secret'}}],['malformed',{data:[{id:'other'}]}],['duplicate',{data:[{id:wabaId},{id:wabaId}]}],['denied',Response.json({error:{message:'private-provider-text'}},{status:403})]])test('owned edge '+name+' stays unavailable without alternate read',async()=>{const f=graph([auditor(),owned]),scoped=await f.provider.forWorkspace(context());assert.equal(scoped.readiness().pilot.canLaunch,false);assert.equal(f.calls.length,2);});
test('a valid auditor assigned only demo cannot prove the selected new WABA',async()=>{const f=graph([auditor(),{data:[{id:OBRASAAS_META_CHANNEL.wabaId}]}]),scoped=await f.provider.forWorkspace(context());await assert.rejects(scoped.inspect({token:customerToken,wabaId,phoneNumberId}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,2);});
test('wrong pinned number denies before credential provenance or register mutation',async()=>{const p=phone();p.data[0].display_phone_number='+5491198765433';const f=graph([auditor(),{data:[{id:wabaId}]},grant(),p]),scoped=await f.provider.forWorkspace(context());await assert.rejects(scoped.inspect({token:customerToken,wabaId,phoneNumberId}),{code:'META_DEVELOPMENT_PILOT_PHONE_REJECTED'});await assert.rejects(scoped.register({token:customerToken,phoneNumberId,pin:'123456'}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,4);assert.ok(f.calls.every(c=>!c.options.method||c.options.method==='GET'));});
test('expiry while auditor is in flight denies launch; removal denies every later request',async()=>{let clock=time;const f=graph([auditor(),{data:[{id:wabaId}]}],{clock:()=>clock,hook:n=>{if(n===2)clock=time+3600000;}}),scoped=await f.provider.forWorkspace(context());assert.equal(scoped.readiness().pilot.canLaunch,false);assert.equal(f.calls.length,2);const g=graph([auditor(),{data:[{id:wabaId}]}]),active=await g.provider.forWorkspace(context());delete g.env.OBRASAAS_META_DEVELOPMENT_PILOT_POLICY;assert.equal(active.readiness().pilot.canLaunch,false);await assert.rejects(active.exchange('synthetic-code-only'));assert.equal(g.calls.length,2);});
test('unwired adapters stay closed before any provider request',async()=>{const f=graph([auditor(),{data:[{id:wabaId}]}]),scoped=await f.provider.forWorkspace(context());for(const method of ['templates','findTemplate','createTemplate','syncAppData','sendTemplate','downloadMedia'])await assert.rejects(scoped[method]({token:customerToken,wabaId,phoneNumberId}),{code:'META_DEVELOPMENT_PILOT_ADAPTER_UNAVAILABLE'});assert.equal(f.calls.length,2);});

for(const value of [null,'',false])test('malformed auditor expiry stays closed '+String(value),async()=>{const a=auditor();a.data.expires_at=value;const f=graph([a]),scoped=await f.provider.forWorkspace(context());assert.equal(scoped.readiness().pilot.canLaunch,false);assert.equal(f.calls.length,1);});
for(const value of [null,'',false])test('malformed customer expiry stays closed '+String(value),async()=>{const g=grant();g.data.expires_at=value;const f=graph([auditor(),{data:[{id:wabaId}]},g]),scoped=await f.provider.forWorkspace(context());await assert.rejects(scoped.inspect({token:customerToken,wabaId,phoneNumberId}),{code:'META_CUSTOMER_TOKEN_EXPIRED'});assert.equal(f.calls.length,3);});
for(const [name,change] of [['Business App',p=>{p.is_on_biz_app=true;}],['unknown modality',p=>{delete p.is_on_biz_app;}],['unknown platform',p=>{delete p.platform_type;}],['other platform',p=>{p.platform_type='ON_PREMISE';}]])test('dedicated pilot denies remote '+name+' before any mutation',async()=>{const p=phone();change(p.data[0]);const f=graph([auditor(),{data:[{id:wabaId}]},grant(),p]),scoped=await f.provider.forWorkspace(context());await assert.rejects(scoped.inspect({token:customerToken,wabaId,phoneNumberId}),{code:'META_DEVELOPMENT_PILOT_DEDICATED_UNVERIFIED'});await assert.rejects(scoped.subscribe({token:customerToken,wabaId}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});await assert.rejects(scoped.register({token:customerToken,phoneNumberId,pin:'123456'}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,4);assert.ok(f.calls.every(c=>c.options.method==='GET'));});
test('explicit numeric zero expiry is valid, without coercing malformed values',async()=>{const a=auditor(),g=grant();a.data.expires_at=0;g.data.expires_at=0;const f=graph([a,{data:[{id:wabaId}]},g,phone()]),scoped=await f.provider.forWorkspace(context());assert.equal(scoped.readiness().pilot.canLaunch,true);assert.equal((await scoped.inspect({token:customerToken,wabaId,phoneNumberId})).expiresAt,null);});

const preRegistration=META_CUSTOMER_INSPECTION_PHASE.PRE_REGISTRATION;
const inspectInput={token:customerToken,wabaId,phoneNumberId};
const replyInput={token:customerToken,phoneNumberId,to:'5491100001111',message:{type:'text',body:'Synthetic fixture reply'},correlationId:'customer_outbound_'+'a'.repeat(64),replyTo:'wamid.synthetic_inbound'};
const pendingPhone=()=>{const p=phone();p.data[0].status='PENDING';p.data[0].platform_type='NOT_APPLICABLE';return p;};
test('pre-registration verifies a dedicated pending number without making it operational',async()=>{
 const f=graph([auditor(),{data:[{id:wabaId}]},grant(),pendingPhone(),{success:true}]),scoped=await f.provider.forWorkspace(context());
 const verified=await scoped.inspect({...inspectInput,inspectionPhase:preRegistration});assert.equal(verified.registered,false);assert.equal(verified.platformType,'NOT_APPLICABLE');assert.equal(scoped.pilotProvenance(verified).ownerVerified,true);
 await assert.rejects(scoped.sendReply(replyInput),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,4);
 await scoped.register({token:customerToken,phoneNumberId,pin:'123456'});assert.equal(f.calls.length,5);assert.equal(f.calls[4].url.pathname,`/v25.0/${phoneNumberId}/register`);assert.equal(f.calls[4].options.method,'POST');
});
for(const [name,change] of [
 ['not registered',p=>{p.platform_type='NOT_APPLICABLE';p.status='PENDING';}],['Cloud pending',p=>{p.status='PENDING';}],['Cloud unknown status',p=>{delete p.status;}],
])test('default operational inspection denies '+name+' before reply',async()=>{
 const p=phone();change(p.data[0]);const f=graph([auditor(),{data:[{id:wabaId}]},grant(),p]),scoped=await f.provider.forWorkspace(context());
 await assert.rejects(scoped.inspect(inspectInput),{code:'META_DEVELOPMENT_PILOT_DEDICATED_UNVERIFIED'});await assert.rejects(scoped.sendReply(replyInput),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,4);
});
for(const [name,change] of [
 ['contradictory connected',p=>{p.status='CONNECTED';}],['missing modality',p=>{delete p.is_on_biz_app;}],['null modality',p=>{p.is_on_biz_app=null;}],['string false modality',p=>{p.is_on_biz_app='false';}],['Business App',p=>{p.is_on_biz_app=true;}],['missing platform',p=>{delete p.platform_type;}],['null platform',p=>{p.platform_type=null;}],['on premise',p=>{p.platform_type='ON_PREMISE';}],['unknown platform',p=>{p.platform_type='OTHER';}],
])test('pre-registration denies '+name+' without acquiring mutation or reply authority',async()=>{
 const p=pendingPhone();change(p.data[0]);const f=graph([auditor(),{data:[{id:wabaId}]},grant(),p]),scoped=await f.provider.forWorkspace(context());
 await assert.rejects(scoped.inspect({...inspectInput,inspectionPhase:preRegistration}),{code:'META_DEVELOPMENT_PILOT_DEDICATED_UNVERIFIED'});await assert.rejects(scoped.register({token:customerToken,phoneNumberId,pin:'123456'}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});await assert.rejects(scoped.sendReply(replyInput),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,4);
});
for(const [name,inspectionPhase,p] of [['PRE success',preRegistration,pendingPhone()],['PRE failure',preRegistration,Response.json({error:{}},{status:403})],['OP failure',undefined,Response.json({error:{}},{status:403})]])test('fresh '+name+' invalidates the previous operational proof',async()=>{
 const second=p instanceof Response?[p]:[grant(),p],f=graph([auditor(),{data:[{id:wabaId}]},grant(),phone(),...second]),scoped=await f.provider.forWorkspace(context());
 const old=await scoped.inspect(inspectInput);assert.equal(old.registered,true);if(p instanceof Response)await assert.rejects(scoped.inspect({...inspectInput,inspectionPhase}));else await scoped.inspect({...inspectInput,inspectionPhase});
 assert.throws(()=>scoped.pilotProvenance(old),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});const count=f.calls.length;await assert.rejects(scoped.sendReply(replyInput),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal(f.calls.length,count);
});
test('only a fresh operational readback after PRE permits a reply',async()=>{
 const f=graph([auditor(),{data:[{id:wabaId}]},grant(),pendingPhone(),grant(),phone(),{messages:[{id:'wamid.synthetic_reply'}]}]),scoped=await f.provider.forWorkspace(context());
 await scoped.inspect({...inspectInput,inspectionPhase:preRegistration});await assert.rejects(scoped.sendReply(replyInput));const verified=await scoped.inspect(inspectInput);assert.equal(verified.registered,true);await assert.rejects(scoped.register({token:customerToken,phoneNumberId,pin:'123456'}),{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});assert.equal((await scoped.sendReply(replyInput)).messageId,'wamid.synthetic_reply');assert.equal(f.calls.filter(c=>c.options.method==='POST').length,1);
});
test('unknown internal phase is denied before IO and invalidates a previous proof',async()=>{
 const f=graph([auditor(),{data:[{id:wabaId}]},grant(),phone()]),scoped=await f.provider.forWorkspace(context()),old=await scoped.inspect(inspectInput);
 await assert.rejects(scoped.inspect({...inspectInput,inspectionPhase:'client-selected'}),{code:'META_CUSTOMER_INSPECTION_PHASE_INVALID'});assert.throws(()=>scoped.pilotProvenance(old));await assert.rejects(scoped.sendReply(replyInput));assert.equal(f.calls.length,4);
});
test('forConnection uses operational readback even when a caller supplies PRE',async()=>{
 const f=graph([auditor(),{data:[{id:wabaId}]},grant(),phone(),auditor(),{data:[{id:wabaId}]},grant(),pendingPhone()]),scoped=await f.provider.forWorkspace(context()),verified=await scoped.inspect(inspectInput),connection={projectId:policy.projectId,organizationId:policy.organizationId,whatsappBusinessId:wabaId,phoneNumberId,metadata:{credentialOrganizationId:policy.organizationId,developmentPilot:scoped.pilotProvenance(verified)}},capability=createDevelopmentPilotCapability(context(),f.env,time);
 await assert.rejects(f.provider.forConnection({capability,connection,token:customerToken,inspectionPhase:preRegistration}),{code:'META_DEVELOPMENT_PILOT_DEDICATED_UNVERIFIED'});assert.equal(f.calls.length,8);assert.ok(f.calls.every(c=>c.options.method==='GET'));
});
test('overlapping inspections cannot restore an older operational proof after a newer PRE',async()=>{
 let release,started;const blocked=new Promise(resolve=>release=resolve),ready=new Promise(resolve=>started=resolve);let inspections=0;
 // Hold the first phone response, while allowing the newer PRE to finish.
 const concurrent=createMetaCustomerProvider({environment:environment(),now:()=>time,fetchImpl:async(url)=>{const u=new URL(url);if(u.pathname.endsWith('/phone_numbers')&&++inspections===1){started();await blocked;return Response.json(phone());}if(u.pathname.endsWith('/debug_token'))return Response.json(u.searchParams.get('input_token')===auditorToken?auditor():grant());if(u.pathname.endsWith('/owned_whatsapp_business_accounts'))return Response.json({data:[{id:wabaId}]});if(u.pathname.endsWith('/phone_numbers'))return Response.json(pendingPhone());throw new Error('Unexpected synthetic branch');}}),current=await concurrent.forWorkspace(context());
 const old=current.inspect(inspectInput);await ready;await current.inspect({...inspectInput,inspectionPhase:preRegistration});release();await assert.rejects(old,{code:'META_DEVELOPMENT_PILOT_OWNER_UNVERIFIED'});await assert.rejects(current.sendReply(replyInput));
});
