import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createWorkspaceRecoveryJournal,recoveryResult,recoveryQuery} from '../src/app/(identity)/cuenta/workspace-recovery-journal.mjs';
import {PRIVATE_BANK_NOTICE_VERSION} from '../src/lib/participant-bank-format.mjs';
function fixture(){const values=new Map(),storage={get length(){return values.size;},key:i=>[...values.keys()][i]||null,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},journal=createWorkspaceRecoveryJournal({getStorage:()=>storage,now:()=>100});const body={scope:'a'.repeat(64),projectId:'bank-project',operationId:randomUUID(),action:'SAVE_PRIVATE_BANK_ACCOUNT',payload:{workerId:'bank-worker',revision:'2026-10-01T00:00:00.000001',expectedBankRevision:0,type:'CBU',number:'0000000000000000000001',consent:true,noticeVersion:PRIVATE_BANK_NOTICE_VERSION}},options={method:'POST',body:JSON.stringify(body)};return {values,journal,body,options};}
const outcome=(reference,state='RECORDED')=>({scope:reference.scope,actorId:'bank-actor',organizationId:'bank-company',projectId:reference.projectId,operationId:reference.operationId,action:reference.action,workerId:reference.workerId,state,saved:state==='RECORDED',definitive:true,replayed:false,receipt:{id:'participant_'+'a'.repeat(64),organizationId:'bank-company',actorId:'bank-actor',projectId:reference.projectId,workerId:reference.workerId,operationId:reference.operationId,action:reference.action,state,bankRevision:state==='RECORDED'?1:0,code:state==='RECORDED'?null:state==='CANCELLED'?'PARTICIPANT_BANK_ACCOUNT_CANCELLED':'PARTICIPANT_BANK_REVISION_CHANGED'}});
test('bank reference retains only action/Worker/UUID/context, never body, account, HMAC or consent',async()=>{
 const f=fixture(),ticket=await f.journal.prepare('/api/identity/participants',f.options);assert.deepEqual(Object.keys(ticket.entry).sort(),['action','createdAt','operationId','projectId','resource','scope','version','workerId']);const raw=[...f.values.values()].join('');for(const value of [f.body.payload.number,'CBU','noticeVersion','consent','requestCommitment','envelope','expectedBankRevision'])assert.equal(raw.includes(value),false);const url=new URL(recoveryQuery(ticket.entry),'https://obrasaas.com');assert.equal(url.searchParams.get('detail'),'private-bank-account');assert.equal(url.searchParams.get('workerId'),ticket.entry.workerId);assert.equal(url.searchParams.get('action'),ticket.entry.action);
});
for(const status of [400,401,403,409,503])test(`dispatched bank status${status} stays uncertain and blocks fresh UUID`,async()=>{
 const f=fixture(),ticket=await f.journal.prepare('/api/identity/participants',f.options);await f.journal.settle(ticket,null,{status});assert.equal((await f.journal.list(f.body.scope)).length,1);await assert.rejects(()=>f.journal.prepare('/api/identity/participants',{...f.options,body:JSON.stringify({...f.body,operationId:randomUUID()})}),{code:'WORKSPACE_RECOVERY_REQUIRED'});
 const absent={scope:ticket.entry.scope,actorId:'bank-actor',organizationId:'bank-company',projectId:ticket.entry.projectId,workerId:ticket.entry.workerId,operationId:ticket.entry.operationId,action:ticket.entry.action,state:'NOT_OBSERVED',saved:false,definitive:false};await f.journal.observe(recoveryQuery(ticket.entry),absent);assert.equal((await f.journal.list(f.body.scope)).length,1);
});
for(const state of ['RECORDED','REJECTED','CANCELLED'])test(`only exact correlated durable ${state} clears bank reference`,async()=>{
 const f=fixture(),ticket=await f.journal.prepare('/api/identity/participants',f.options),good=outcome(ticket.entry,state);
 for(const forged of [{...good,scope:'f'.repeat(64)},{...good,action:'REMOVE_PRIVATE_BANK_ACCOUNT'},{...good,receipt:{...good.receipt,workerId:'foreign'}},{...good,receipt:{...good.receipt,actorId:'foreign'}},{...good,receipt:{...good.receipt,organizationId:'foreign'}},{...good,number:f.body.payload.number},{scope:ticket.entry.scope,saved:true,receiptId:good.receipt.id}]){assert.equal(recoveryResult(ticket.entry,forged),null);await f.journal.settle(ticket,forged);assert.equal((await f.journal.list(f.body.scope)).length,1);}
 await f.journal.observe(recoveryQuery(ticket.entry),good);assert.equal((await f.journal.list(f.body.scope)).length,0);
});
test('cancel uses original durable ticket/action and never creates second operation reference',async()=>{
 const f=fixture(),ticket=await f.journal.prepare('/api/identity/participants',f.options),cancel={...f.body,action:'CANCEL_PENDING_PRIVATE_BANK_ACCOUNT',payload:{workerId:f.body.payload.workerId,originalAction:f.body.action,confirmed:true}},same=await f.journal.prepare('/api/identity/participants',{method:'POST',body:JSON.stringify(cancel)});assert.equal(same.existed,true);assert.deepEqual(same.entry,ticket.entry);await f.journal.settle(same,outcome(ticket.entry,'CANCELLED'));assert.equal((await f.journal.list(f.body.scope)).length,0);
});
test('new tab has GET recovery but cannot reconstruct retry payload from durable storage',async()=>{
 const f=fixture(),ticket=await f.journal.prepare('/api/identity/participants',f.options),restored=(await f.journal.list(f.body.scope))[0];assert.deepEqual(restored,ticket.entry);assert.equal(restored.payload,undefined);assert.equal(restored.number,undefined);assert.equal(recoveryResult(restored,outcome(restored,'CANCELLED')).state,'CANCELLED');
});
