import test from 'node:test';
import assert from 'node:assert/strict';
import {metaCustomerBeforeBindingModeRejection} from '../src/lib/meta-customer-onboarding.mjs';
import {metaOnboardingSnapshot,metaOnboardingModeReview,metaOnboardingModeClosureMatches,metaOnboardingReadinessView} from '../src/app/(identity)/cuenta/meta-onboarding-readiness-view.mjs';
import {metaCustomerReadiness} from '../src/lib/meta-customer-provider.mjs';
import {createMetaCustomerHandlers} from '../src/lib/meta-customer-http.mjs';
import {createWorkspaceRecoveryJournal,recoveryQuery,recoveryResult} from '../src/app/(identity)/cuenta/workspace-recovery-journal.mjs';
const id='12345678-1234-4234-8234-123456789012',lease='12345678-1234-4234-8234-123456789013',operation='12345678-1234-4234-8234-123456789014',scope='a'.repeat(64),context={actorId:'owner',organizationId:'company',projectId:'project',tokenDigest:'b'.repeat(64)};
const state=()=>({id,verificationLeaseId:lease,actorId:'owner',organizationId:'company',state:'REVIEW_REQUIRED',numberMode:'DEDICATED',encryptedToken:'v2.private-encrypted-grant',wabaId:'123456789012345',phoneNumberId:'123456789012346',lastCode:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED',beforeBindingModeRejection:{version:1,phase:'BEFORE_BINDING',code:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED',signupId:id,verificationLeaseId:lease,actorId:'owner',organizationId:'company',projectId:'project',wabaId:'123456789012345',phoneNumberId:'123456789012346',numberMode:'DEDICATED',tokenDigest:'b'.repeat(64),observedAt:'2026-10-07T12:00:00.000Z'}});
test('local modality closure requires the exact durable prebinding guard and has no uncertain registration history',()=>{
 assert.equal(metaCustomerBeforeBindingModeRejection(state(),context),true);
 for(const change of [s=>delete s.beforeBindingModeRejection,s=>s.state='REGISTRATION_UNKNOWN',s=>s.registrationOperationId=operation,s=>s.registrationAttempts=[{state:'NOT_SENT'}],s=>s.registrationAttempts={},s=>s.existingConnection={id:'old'},s=>s.developmentPilot={},s=>s.encryptedToken=null,s=>s.numberMode='BUSINESS_APP',s=>s.lastCode='META_CUSTOMER_PHONE_MODE_UNCONFIRMED',s=>s.beforeBindingModeRejection.phase='AFTER_BINDING',s=>s.beforeBindingModeRejection.signupId=operation,s=>s.beforeBindingModeRejection.verificationLeaseId=operation,s=>s.beforeBindingModeRejection.tokenDigest='c'.repeat(64),s=>s.beforeBindingModeRejection.phoneNumberId='999999999999999',s=>s.beforeBindingModeRejection.wabaId='999999999999999',s=>s.beforeBindingModeRejection.actorId='foreign',s=>s.beforeBindingModeRejection.organizationId='foreign',s=>s.beforeBindingModeRejection.projectId='foreign',s=>s.beforeBindingModeRejection.extra=true]){const s=state();change(s);assert.equal(metaCustomerBeforeBindingModeRejection(s,context),false);}
});
const ready=()=>metaCustomerReadiness({});
const snapshot=()=>({scope,projectId:'project',companyName:'Empresa de ensayo',projectName:'Obra de ensayo',prepared:true,numberMode:'DEDICATED',readiness:ready(),connection:null,signup:{id,state:'REVIEW_REQUIRED',numberMode:'DEDICATED',canCancel:true,canReconcile:true,canRegister:false,modeReview:{code:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED',phase:'BEFORE_BINDING',canCloseLocally:true}}});
const closure=()=>({action:'cancel',operationId:operation,signupId:id,projectId:'project',scope,state:'RECORDED',saved:true,receiptId:'meta_mode_closure_'+'d'.repeat(64),phase:'BEFORE_BINDING',code:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED',closedAt:'2026-10-07T12:00:00.000Z',remoteAuthorizationRevoked:false,remoteMutationDispatched:false});
test('public modality review and closure expose only the exact receipt and a correction path',()=>{
 const value=snapshot(),command={action:'cancel',operationId:operation,signupId:id,projectId:'project',scope};metaOnboardingSnapshot(value,{scope,projectId:'project'});assert.match(metaOnboardingModeReview(value.signup).detail,/conserva la app/);assert.match(metaOnboardingReadinessView(value).next,/Cerrá este intento local/);
 value.localModeClosure=closure();metaOnboardingSnapshot(value,{scope,projectId:'project'});assert.equal(metaOnboardingModeClosureMatches(value,command),true);
 for(const key of ['operationId','signupId','scope','projectId'])assert.equal(metaOnboardingModeClosureMatches(value,{...command,[key]:'foreign'}),false);
 for(const change of [v=>v.connection={recordPresent:true},v=>v.signup.modeReview.canCloseLocally=false,v=>v.signup.modeReview.privateToken='private',v=>v.localModeClosure.remoteMutationDispatched=true,v=>v.localModeClosure.tokenDigest='private',v=>v.localModeClosure.projectId='foreign']){const v=structuredClone(value);change(v);assert.throws(()=>metaOnboardingSnapshot(v,{scope,projectId:'project'}));}
 value.signup={...value.signup,state:'CANCELLED',canCancel:false};delete value.signup.modeReview;assert.match(metaOnboardingReadinessView(value).next,/Corregí y guardá la modalidad/);
});
test('absent platform prerequisites and no existing connection point to the platform owner',()=>{
 const value=snapshot();value.signup=null;value.activation={state:'NOT_ACCEPTED',operational:false,canActivate:false,canDeactivate:false,lastCode:'META_CUSTOMER_CONFIGURATION_PENDING'};metaOnboardingSnapshot(value,{scope,projectId:'project'});assert.match(metaOnboardingReadinessView(value).next,/equipo de ObraSaaS/);assert.doesNotMatch(metaOnboardingReadinessView(value).next,/Operación del canal/);
 value.connection={enabled:false,storedStatus:'DISABLED'};value.activation={state:'REVIEW_REQUIRED',operational:false,canActivate:false,canDeactivate:true,lastCode:'META_CUSTOMER_ACTIVATION_RECONNECTION_REQUIRED'};assert.match(metaOnboardingReadinessView(value).next,/Operación del canal/);
});
test('historical cancel GET admits only one exact owned reference and never dispatches a command',async()=>{
 let reads=0,commands=0;const session={authenticated:true,verification:'clerk-production-jwt',userId:'user_Read',organizationId:'org_Read',organizationRole:'org:admin'},api=createMetaCustomerHandlers({verify:async()=>session,service:{read:async(_s,c)=>{reads++;assert.deepEqual(c,{projectId:'project',scope,action:'cancel',signupId:id,operationId:operation});return {localModeClosure:closure()};},command:async()=>{commands++;}}}),params=new URLSearchParams({projectId:'project',scope,action:'cancel',signupId:id,operationId:operation}),get=q=>new Request('https://obrasaas.com/api/identity/meta-onboarding?'+q);
 assert.equal((await api.GET(get(params))).status,200);for(const extra of ['&eventId=customer_webhook_'+'a'.repeat(64),'&after=customer_webhook_'+'a'.repeat(64),'&signupId='+id,'&operationId='+operation,'&token=private'])assert.equal((await api.GET(get(params+extra))).status,400);for(const key of ['signupId','operationId']){const invalid=new URLSearchParams(params);invalid.set(key,'bad');assert.equal((await api.GET(get(invalid))).status,400);}assert.equal(reads,1);assert.equal(commands,0);
});
test('lost local closure survives a new page with identifiers only and another latest receipt cannot settle it',async()=>{
 const rows=new Map(),storage={get length(){return rows.size;},key:i=>[...rows.keys()][i]??null,getItem:k=>rows.get(k)??null,setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)},journal=createWorkspaceRecoveryJournal({getStorage:()=>storage,now:()=>123}),command={action:'cancel',operationId:operation,signupId:id,projectId:'project',scope,confirmLocalClosure:true,token:'private-token',marker:{secret:'private-grant'}};
 const ticket=await journal.prepare('/api/identity/meta-onboarding',{method:'POST',body:JSON.stringify(command)});await journal.settle(ticket,null,{status:503});const fresh=createWorkspaceRecoveryJournal({getStorage:()=>storage,now:()=>456}),entry=(await fresh.list(scope))[0];assert.deepEqual(Object.keys(entry).sort(),['version','resource','action','operationId','signupId','projectId','scope','createdAt'].sort());assert.doesNotMatch(JSON.stringify([...rows]),/confirmLocalClosure|private-token|private-grant|marker/);assert.equal(new URL(recoveryQuery(entry),'https://obrasaas.com').searchParams.get('action'),'cancel');
 const current={scope,projectId:'project',localModeClosure:{...closure(),operationId:lease}};assert.equal(recoveryResult(entry,current),null);await fresh.observe(recoveryQuery(entry),current);assert.equal((await fresh.list(scope)).length,1);await fresh.observe(recoveryQuery(entry),{...current,localModeClosure:closure()});assert.equal((await fresh.list(scope)).length,0);
});
test('only an exact final prebinding mode rejection settles a phone review before explicit closure',async()=>{
 const rows=new Map(),storage={get length(){return rows.size;},key:i=>[...rows.keys()][i]??null,getItem:k=>rows.get(k)??null,setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)},journal=createWorkspaceRecoveryJournal({getStorage:()=>storage,now:()=>123}),command={action:'reconcile',operationId:operation,signupId:id,projectId:'project',scope,expectedCompanyPhoneRevision:2,confirmCompanyPhoneRevision:true};
 const ticket=await journal.prepare('/api/identity/meta-onboarding',{method:'POST',body:JSON.stringify(command)});await journal.settle(ticket,null,{status:409,code:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED'});const entry=(await journal.list(scope))[0],receipt={action:'reconcile',operationId:operation,signupId:id,projectId:'project',scope,state:'REJECTED',saved:false,definitive:true,receiptId:'meta_company_phone_'+'d'.repeat(64),phase:'BEFORE_BINDING',code:'META_CUSTOMER_DEDICATED_PHONE_REQUIRED',expectedCompanyPhoneRevision:2},result={scope,projectId:'project',receipt};
 assert.equal((await journal.list(scope)).length,1);assert.deepEqual(recoveryResult(entry,result),{state:'REJECTED',receiptId:receipt.receiptId,phase:'BEFORE_BINDING',code:receipt.code});
 for(const change of [r=>r.operationId=lease,r=>r.signupId=lease,r=>r.phase='AFTER_BINDING',r=>r.code='META_CUSTOMER_PHONE_STATUS_UNCONFIRMED',r=>r.definitive=false,r=>r.saved=true,r=>r.expectedCompanyPhoneRevision=0,r=>r.privateToken='private']){const invalid=structuredClone(result);change(invalid.receipt);assert.equal(recoveryResult(entry,invalid),null);await journal.observe(recoveryQuery(entry),invalid);assert.equal((await journal.list(scope)).length,1);}
 await journal.observe(recoveryQuery(entry),result);assert.equal((await journal.list(scope)).length,0);assert.doesNotMatch(JSON.stringify([...rows]),/confirmCompanyPhoneRevision|expectedCompanyPhoneRevision/);
});
