import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {COMPANY_SCHEMA_REQUIREMENTS,checkCompanySchema,companyPreflightEnabled} from '../scripts/lib/company-schema-preflight.mjs';
const environment={OBRASAAS_CHECK_COMPANY_SCHEMA:'read-only-v1',VERCEL_ENV:'production',VERCEL_PROJECT_ID:'prj_68NErbCqCFsDVaMak81gcwsGI9pF',NEXT_PUBLIC_APP_URL:'https://obrasaas.com'};
const rows=Object.entries(COMPANY_SCHEMA_REQUIREMENTS).flatMap(([table_name,columns])=>columns.map(column_name=>({table_name,column_name})));
test('schema check is opt-in and scoped to the exact product',()=>{assert.equal(companyPreflightEnabled({}),false);assert.equal(companyPreflightEnabled(environment),true);for(const change of [{VERCEL_ENV:'preview'},{VERCEL_PROJECT_ID:'other'},{NEXT_PUBLIC_APP_URL:'https://another.example'},{OBRASAAS_CHECK_COMPANY_SCHEMA:'write'}])assert.throws(()=>companyPreflightEnabled({...environment,...change}));});
test('all required canonical columns must be present',()=>{assert.equal(checkCompanySchema(rows).compatible,true);for(const removed of rows){const result=checkCompanySchema(rows.filter(row=>row!==removed));assert.equal(result.compatible,false);assert.deepEqual(result.missing,[removed.table_name+'.'+removed.column_name]);}});
test('unknown extra tables do not satisfy a missing canonical column',()=>{assert.equal(checkCompanySchema([{table_name:'Tenant',column_name:'name'}]).compatible,false);});
test('durable inbox preflight rejects a schema that can receive events but cannot claim, finish or recover them',()=>{
 const processingColumns=['leaseToken','leaseExpiresAt','outcome','processedAt','appliedAt','lastError'];
 for(const column of processingColumns){assert.ok(COMPANY_SCHEMA_REQUIREMENTS.WebhookEvent.includes(column),column);const result=checkCompanySchema(rows.filter(row=>row.table_name!=='WebhookEvent'||row.column_name!==column));assert.equal(result.compatible,false);assert.deepEqual(result.missing,['WebhookEvent.'+column]);}
});
test('runtime probe has only a read-only catalogue query and never prints credentials',()=>{const source=readFileSync(new URL('../scripts/verify-company-onboarding-readonly.mjs',import.meta.url),'utf8');assert.match(source,/REPEATABLE READ READ ONLY/);assert.doesNotMatch(source,/INSERT INTO|UPDATE public|CREATE TABLE|JSON.stringify\(process.env|process.env.DATABASE_URL/);});
