import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {inventoryCatalog,inventoryCatalogHash,inventoryQuantity,changeInventoryBalance} from '../src/lib/material-inventory.mjs';
import {normalizeFieldCommand} from '../src/lib/field-operations-policy.mjs';
import {normalizePurchase} from '../src/lib/site-purchase-policy.mjs';
import {planMetaFieldConversation} from '../src/lib/meta-field-conversation.mjs';
import {inventoryOutcome,inventorySnapshot,mergeInventoryRows} from '../src/app/(identity)/cuenta/material-inventory-view.mjs';
import {createFieldHandlers} from '../src/lib/field-operations-http.mjs';
const material=()=>({id:'material-a',name:'Material sintético',unit:'bolsa',active:true,balance:'0.000'}),state=()=>({version:1,catalogVersion:1,materials:[material()]}),project=value=>({metadata:{materialInventory:value}}),context={projectId:'project-a',scope:'a'.repeat(64)},revision='2026-10-06T12:00:00.123456';
test('catalog validates bounded durable exact-unit entries and rejects corrupted balances instead of repairing stock',()=>{
 const full={...state(),materials:Array.from({length:200},(_,i)=>({...material(),id:'material-'+i}))};assert.equal(inventoryCatalog(project(full)).materials.length,200);
 for(const bad of [{...full,materials:[...full.materials,{...material(),id:'overflow'}]},{...state(),materials:[material(),material()]},{...state(),materials:[null]},{...state(),materials:[{...material(),balance:1}]},{...state(),materials:[{...material(),balance:'1.1'}]},{...state(),materials:[{...material(),unit:'tonelada'}]}])assert.throws(()=>inventoryCatalog(project(bad)),{code:'INVENTORY_INTEGRITY'});
 const before=state(),hash=inventoryCatalogHash(before),copy=inventoryCatalog(project(before));copy.materials[0].balance='1.000';assert.equal(before.materials[0].balance,'0.000');assert.equal(inventoryCatalogHash(copy),hash);copy.materials[0].unit='kg';assert.notEqual(inventoryCatalogHash(copy),hash);
});
test('exact balance arithmetic distinguishes one thousandth at Decimal(14,3) limits and never mutates on underflow or overflow',()=>{
 const m=material();changeInventoryBalance(m,'0.001','IN');changeInventoryBalance(m,'0.001','OUT');assert.equal(m.balance,'0.000');assert.throws(()=>changeInventoryBalance(m,'0.001','OUT'),{code:'INVENTORY_STOCK_INSUFFICIENT'});assert.equal(m.balance,'0.000');m.balance='99999999999.998';changeInventoryBalance(m,'0.001','IN');assert.equal(m.balance,'99999999999.999');assert.throws(()=>changeInventoryBalance(m,'0.001','IN'),{code:'INVENTORY_BALANCE_OVERFLOW'});assert.equal(m.balance,'99999999999.999');for(const bad of [1,'1e2','1,25','-1','0','1.0001','100000000000'])assert.throws(()=>inventoryQuantity(bad));
});
test('canonical consumption and reception contracts carry explicit stable material and catalog guard without name inference',()=>{
 const input={...context,operationId:randomUUID(),action:'PROPOSE_CONSUMPTION',payload:{workerId:'worker-a',taskId:null,sectorId:'sector-a',materialId:'material-a',catalogHash:'b'.repeat(64),quantity:'0001.001',reason:'Motivo de consumo sintético.'}};assert.equal(normalizeFieldCommand(input).payload.quantity,'1.001');assert.throws(()=>normalizeFieldCommand({...input,payload:{...input.payload,materialName:'Material sintético'}}));assert.throws(()=>normalizeFieldCommand({...input,payload:{...input.payload,quantity:1.001}}));
 const receipt={...context,operationId:randomUUID(),action:'RECEIVE_MATERIAL',payload:{requestId:'request-a',revision,quantity:'1.001',deliveryReference:'REM-1',reason:'Entrega autorizada sintética.',materialId:'material-a',inventoryCatalogHash:'b'.repeat(64)}};assert.equal(normalizePurchase(receipt).payload.materialId,'material-a');for(const key of ['materialId','inventoryCatalogHash']){const bad=structuredClone(receipt);delete bad.payload[key];assert.throws(()=>normalizePurchase(bad));}
});
test('WhatsApp catalog pages stay bounded, reject stale capabilities and pin exact quantity until explicit proposal confirmation',()=>{
 const now=new Date('2026-10-06T12:00:00Z'),facts={projectName:'Obra sintética',workerId:'worker-a',permissions:{attendance:true,report:true},tasks:[],sectors:[{id:'sector-a',name:'Sector sintético'}],evidence:[],proposals:[],latest:null,inventory:{catalogHash:'b'.repeat(64),materials:Array.from({length:19},(_,i)=>({...material(),id:'material-'+i,name:'Material '+i}))}};let seq=0;
 const run=(message,state=null,extra={})=>{const r=planMetaFieldConversation({message,state,eventId:'event-'+(++seq),facts,now,...extra});if(r.state)r.state={...r.state,version:1,expiresAt:new Date(now.getTime()+900000).toISOString()};return r;},say=(body,s,extra)=>run({type:'text',text:{body}},s,extra),pick=(plan,value,extra)=>{const i=plan.state.choices.findIndex(c=>c.value===value);assert.ok(i>=0);return run({type:'interactive',interactive:{type:'list_reply',list_reply:{id:plan.reply.sections[0].rows[i].id}}},plan.state,extra);};
 const tasks=say('CONSUMO'),sectors=pick(tasks,'NONE'),first=pick(sectors,'sector-a'),second=pick(first,'NEXT'),third=pick(second,'NEXT');for(const page of [first,second,third])assert.ok(page.reply.sections[0].rows.length<=10);const stale=pick(first,'material-0',{state:third.state});assert.equal(stale.command,undefined);assert.match(stale.reply.body,/paso anterior/);
 const chosen=pick(third,'material-18'),invalid=say('1.0001',chosen.state);assert.deepEqual(invalid.state,chosen.state);assert.match(invalid.reply.body,/conservan/);const amount=say('0001.001',chosen.state),confirm=say('Aplicado a la tarea sintética.',amount.state);assert.equal(say('sí',confirm.state).command,undefined);const result=pick(confirm,'CONFIRM');assert.equal(result.command.action,'PROPOSE_CONSUMPTION');assert.equal(result.command.payload.materialId,'material-18');assert.equal(result.command.payload.catalogHash,'b'.repeat(64));assert.equal(result.command.payload.quantity,'1.001');assert.equal(result.command.payload.decision,undefined);
 assert.equal(pick(confirm,'CONFIRM',{facts:{...facts,permissions:{attendance:true,report:false}}}).command,undefined);
});
test('WhatsApp global menu remains within ten provider rows in every attendance phase with full catalog and pagination',()=>{
 const now=new Date('2026-10-06T12:00:00Z'),facts={projectName:'Obra sintética',workerId:'worker-a',permissions:{attendance:true,report:true},tasks:[],sectors:[{id:'sector-a',name:'Sector sintético'}],evidence:[],proposals:[],inventory:{catalogHash:'b'.repeat(64),materials:Array.from({length:200},(_,i)=>({...material(),id:'material-'+i}))}};let seq=0;
 for(const latest of [null,{eventType:'CHECK_IN',phase:'WORKING'},{eventType:'BREAK_START',phase:'ON_BREAK'},{eventType:'BREAK_END',phase:'WORKING'},{eventType:'CHECK_OUT',phase:'CLOSED'}])for(const permissions of [{attendance:true,report:true},{attendance:false,report:true},{attendance:true,report:false}]){const r=planMetaFieldConversation({message:{type:'text',text:{body:'MENU'}},state:null,eventId:'menu-'+(++seq),facts:{...facts,permissions,latest},now}),rows=r.reply.sections.flatMap(s=>s.rows);assert.ok(rows.length<=10,latest?.phase);assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);}
 for(const offset of [0,8,96,192]){const state={version:1,step:'CONSUMPTION_MATERIAL',purpose:'CONSUMPTION',materialOffset:offset,expiresAt:'2026-10-06T12:15:00Z',nonce:'a'.repeat(20),choices:[{value:offset?'PREVIOUS':'NEXT',title:'Página'}]},r=planMetaFieldConversation({message:{type:'interactive',interactive:{type:'list_reply',list_reply:{id:'obra:'+'a'.repeat(20)+':0'}}},state,eventId:'page-'+(++seq),facts,now});assert.ok(r.reply.sections.flatMap(s=>s.rows).length<=10);}
});
test('inventory browser verifies current-operation receipt before acknowledging and refuses crossed/malformed snapshots',()=>{
 const command={...context,operationId:randomUUID(),action:'PROPOSE_CONSUMPTION'},good={...command,state:'RECORDED',saved:true,replayed:false,receiptId:'field_'+'c'.repeat(64),kind:'CONSUMPTION_PROPOSAL',consumption:{id:'consumption-a',state:'PENDING',materialId:'material-a',unit:'bolsa',quantity:'1.001'}};assert.equal(inventoryOutcome(good,command,{recorded:true}),good);for(const bad of [{...good,operationId:randomUUID()},{...good,scope:'d'.repeat(64)},{...good,action:'DECIDE_CONSUMPTION'},{...good,kind:'CONSUMPTION_DECISION'},{...good,receiptId:'field_fake'},{...good,consumption:null}])assert.throws(()=>inventoryOutcome(bad,command,{recorded:true}));
 const absent={...context,operationId:command.operationId,state:'NOT_OBSERVED',definitive:false};assert.equal(inventoryOutcome(absent,command),absent);assert.throws(()=>inventoryOutcome(absent,command,{recorded:true}));const snapshot={...context,projectRevision:revision,selfWorkers:[],sectors:[],inventory:{...state(),catalogHash:'b'.repeat(64),catalogLimit:200,canManage:true,consumptions:[],consumptionsTruncated:false,nextConsumptionCursor:null,movements:[],nextMovementCursor:null,adjustments:[],nextAdjustmentCursor:null,priorReceipts:[],priorReceiptsTruncated:false}};assert.equal(inventorySnapshot(snapshot,context),snapshot);assert.throws(()=>inventorySnapshot({...snapshot,projectId:'foreign'},context));assert.throws(()=>inventorySnapshot({...snapshot,inventory:{...snapshot.inventory,materials:[material(),material()]}},context));
 const fresh={id:'consumption-a',revision,state:'APPROVED'},older={...fresh,revision:'2026-10-06T12:00:00.123455',state:'PENDING'},other={id:'consumption-b',revision,state:'REJECTED'};assert.deepEqual(mergeInventoryRows([fresh],[older,other]),[fresh,other]);assert.deepEqual(mergeInventoryRows([older],[fresh]),[fresh]);assert.throws(()=>inventorySnapshot(snapshot,{...context,consumptionId:'missing'}));
});
test('existing field GET routes one validated inventory page or directed consumption and rejects ambiguous duplicate selectors before the store',async()=>{
 const calls=[],session={authenticated:true,verification:'clerk-production-jwt',userId:'user_Test',organizationId:'org_A',organizationRole:'org:admin'},handlers=createFieldHandlers({verify:async()=>session,operations:{inventoryHistory:async(s,input)=>{assert.equal(s,session);calls.push(input);return {scope:input.scope,projectId:input.projectId};}}}),query='?'+new URLSearchParams(context);
 for(const key of ['afterMovement','afterConsumption','consumptionId','afterAdjustment','adjustmentId']){const response=await handlers.GET(new Request('https://obrasaas.com/api/identity/field-operations'+query+'&'+key+'=record-a'));assert.equal(response.status,200);assert.equal(calls.at(-1)[key],'record-a');}
 const count=calls.length;for(const suffix of ['&afterConsumption=a&afterMovement=b','&afterConsumption=a&afterConsumption=b','&consumptionId=a&proposalId=b','&consumptionId=a&operationId='+randomUUID(),'&consumptionId=a&afterConsumption=b','&afterConsumption=bad%2Fid','&adjustmentId=a&afterAdjustment=b','&adjustmentId=a&consumptionId=b','&afterAdjustment=a&afterAdjustment=b','&adjustmentId=a&operationId='+randomUUID(),'&unknown=a'])assert.equal((await handlers.GET(new Request('https://obrasaas.com/api/identity/field-operations'+query+suffix))).status,400);assert.equal(calls.length,count);
});
test('opening, counted differences and historical receipt incorporation have strict exact source contracts and no client-supplied balance',()=>{
 const command={...context,operationId:randomUUID(),action:'PROPOSE_STOCK_ADJUSTMENT',payload:{materialId:'material-a',catalogHash:'b'.repeat(64),quantity:'0008.001',direction:'IN',source:{type:'OPENING',reference:'Recuento inicial 01'},reason:'Bolsas ya acopiadas verificadas por la empresa.'}};
 assert.equal(normalizeFieldCommand(command).payload.quantity,'8.001');
 for(const mutate of [p=>p.quantity=8,p=>p.balance='8.000',p=>p.direction='OUT',p=>p.source={type:'OPENING'},p=>p.source={type:'COUNT',reference:'x'},p=>p.source={type:'RECEIPT',requestId:'foreign',receiptOperationId:'fake'},p=>p.source={type:'UNKNOWN'}]){const bad=structuredClone(command);mutate(bad.payload);assert.throws(()=>normalizeFieldCommand(bad));}
 const count=structuredClone(command);count.payload.source={type:'COUNT',reference:'Recuento 02'};count.payload.direction='OUT';assert.equal(normalizeFieldCommand(count).payload.direction,'OUT');
 const receipt=structuredClone(command);receipt.payload.source={type:'RECEIPT',requestId:'request-a',receiptOperationId:randomUUID()};assert.equal(normalizeFieldCommand(receipt).payload.source.type,'RECEIPT');receipt.payload.direction='OUT';assert.throws(()=>normalizeFieldCommand(receipt));
});
test('stock adjustment browser correlation requires its proposal, material, normalized quantity and honest source',()=>{
 const command={...context,operationId:randomUUID(),action:'PROPOSE_STOCK_ADJUSTMENT',payload:{materialId:'material-a',quantity:'0008.001'}},adjustment={id:'adjustment-a',materialId:'material-a',quantity:'8.001',expectedBalance:'0.000',unit:'bolsa',state:'PENDING',direction:'IN',source:{type:'OPENING',reference:'Recuento 01'},submittedBy:'owner-a',catalogHash:'b'.repeat(64),reason:'Stock comprobado.'},result={...command,state:'RECORDED',saved:true,replayed:false,receiptId:'field_'+'c'.repeat(64),kind:'STOCK_ADJUSTMENT_PROPOSAL',stockChanged:false,adjustment};assert.equal(inventoryOutcome(result,command,{recorded:true}),result);
 for(const patch of [{materialId:'foreign'}, {quantity:'8.000'},{expectedBalance:'0'}, {source:{type:'RECEIPT',requestId:'request-a',receiptOperationId:'invalid'}},{submittedBy:null}])assert.throws(()=>inventoryOutcome({...result,adjustment:{...adjustment,...patch}},command,{recorded:true}));
 const decide={...command,action:'DECIDE_STOCK_ADJUSTMENT',payload:{proposalId:'adjustment-b'}};assert.throws(()=>inventoryOutcome({...result,action:decide.action,kind:'STOCK_ADJUSTMENT_DECISION'},decide,{recorded:true}));
});
