import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {createMetaCustomerOnboarding} from '../src/lib/meta-customer-onboarding.mjs';
import {metaCustomerReadiness} from '../src/lib/meta-customer-provider.mjs';
import {OBRASAAS_META_CHANNEL} from '../src/lib/meta-channel-binding.mjs';
import {WorkspaceError} from '../src/lib/workspace-policy.mjs';
const environment={NEXT_PUBLIC_META_APP_ID:OBRASAAS_META_CHANNEL.appId,META_APP_SECRET:'synthetic-company-phone-secret',META_CONFIG_ID:'123456789012345',META_GRAPH_API_VERSION:'v25.0',WHATSAPP_CREDENTIALS_ENCRYPTION_KEY:Buffer.alloc(32,21).toString('base64'),META_EMBEDDED_SIGNUP_VERSION:'4',OBRASAAS_META_SIGNUP_RELEASE:'customer-self-service-v1',META_CUSTOMER_VERIFY_TOKEN:'synthetic-company-phone-verify-token-only'};
const session={authenticated:true,verification:'clerk-production-jwt',userId:'user_A',organizationId:'org_A',organizationRole:'org:admin'},scope='a'.repeat(64);
const stored=()=>({version:1,status:'UNVERIFIED',e164:'+12025550123',revision:1,declaredAt:'2026-10-06T12:00:00.000Z',receiptId:'company_phone_'+'a'.repeat(64)});
function fixture({declaration=stored(),display='+12025550123',hook=null,verifiedPhoneId='98765432105678',subscriptionFailure=false}={}){
 const company={companyPhoneDeclaration:declaration};if(declaration===null)delete company.companyPhoneDeclaration;
 const project={id:'p-a',name:'Synthetic worksite',metadata:{whatsappWorkspace:{schemaVersion:2,assistantName:'Asistente',numberMode:'DEDICATED',initialProjectId:'p-a',useCases:['FIELD_REPORTS'],revision:1,updatedAt:'2026-10-06T12:00:00.000Z',ownership:'CUSTOMER',mode:'REVIEW_REQUIRED'}},organizationMetadata:company};
 const member={actorId:'actor-a',membershipId:'membership-a',organizationId:'company-a',organizationName:'Synthetic company',role:'ADMIN'};
 const calls={exchange:0,subscribe:0,register:0,bind:0,inspect:0},audits=new Map();let connection=null,registered=false,inspectionHook=hook;
 const query=async(sql,args=[])=>{
  if(sql.includes('to_regclass'))return {rows:[{present:false}]};
  if(sql.startsWith('SELECT metadata FROM public."Organization"')){assert.deepEqual(args,['company-a']);assert.match(sql,/FOR SHARE/);return {rows:[{metadata:company}]};}
  if(sql.startsWith('UPDATE public."Project"')){project.metadata=JSON.parse(args[2]);return {rows:[],rowCount:1};}
  if(sql.startsWith('INSERT INTO public."AuditLog"')){audits.set(args[0],{metadata:JSON.parse(args.at(-1))});return {rows:[],rowCount:1};}
  if(sql.startsWith('SELECT clock_timestamp()'))return {rows:[{now:new Date('2026-10-06T12:00:00Z')}]};
  if(sql.startsWith('SELECT id,metadata FROM public."AuditLog"'))return {rows:audits.has(args[0])?[{id:args[0],...audits.get(args[0])}]:[]};
  if(sql.startsWith('SELECT metadata FROM public."AuditLog"'))return {rows:audits.has(args[0])?[audits.get(args[0])]:[]};
  if(sql.startsWith('INSERT INTO public."WhatsAppConnection"')){calls.bind++;connection={id:args[0],projectId:args[1],phoneNumberId:args[2],whatsappBusinessId:args[3],displayPhoneNumber:args[4],enabled:false,status:'PENDING',connectionStatus:'PENDING',encryptedAccessToken:args[5],metadata:JSON.parse(args[7])};return {rows:[],rowCount:1};}
  if(sql.startsWith('UPDATE public."WhatsAppConnection"')){if(sql.includes('metadata=metadata||'))connection.metadata={...connection.metadata,...JSON.parse(args[2])};if(sql.includes('enabled=true')){connection.enabled=true;connection.connectionStatus='CONNECTED';}if(sql.includes('enabled=false'))connection.enabled=false;return {rows:[],rowCount:1};}
  if(sql.includes('FROM public."WhatsAppConnection"')&&!sql.includes('JOIN'))return {rows:connection&& !sql.includes('"projectId"<>')?[connection]:[]};
  return {rows:[],rowCount:1};
 };
 const workspace={integrationProject:async(identity,context,_writable,run)=>{if(identity.userId!==session.userId||identity.organizationId!==session.organizationId)throw new WorkspaceError('WORKSPACE_MEMBERSHIP_REQUIRED',403);if(context.scope!==scope||context.projectId!==project.id)throw new WorkspaceError('WORKSPACE_CONTEXT_CHANGED',409);project.organizationMetadata=company;return run({query},member,scope,project);}};
 const provider={readiness:()=>metaCustomerReadiness(environment),exchange:async()=>{calls.exchange++;return 'synthetic-only-customer-token-123456';},inspect:async()=>{calls.inspect++;if(inspectionHook){const callback=inspectionHook;inspectionHook=null;callback(company);}return {phoneNumberId:verifiedPhoneId,displayPhoneNumber:display,registered,scopes:['whatsapp_business_management','whatsapp_business_messaging'],verifiedBusinessName:'Synthetic customer'};},subscribe:async()=>{calls.subscribe++;if(subscriptionFailure)throw new WorkspaceError('META_CUSTOMER_SUBSCRIPTION_UNCONFIRMED',503);},register:async()=>{calls.register++;registered=true;},inspectSubscription:async()=>true};
 const service=createMetaCustomerOnboarding({workspace,provider,environment,now:()=>Date.parse('2026-10-06T12:00:00Z')});
 const command=(action,extra={})=>({action,scope,projectId:project.id,operationId:randomUUID(),...extra});
 const begin=()=>service.command(session,command('begin',{preparedRevision:1}));
 const complete=start=>service.command(session,command('complete',{signupId:start.signup.id,stateToken:start.stateToken,code:'synthetic-code-only',wabaId:'98765432101234',phoneNumberId:'98765432105678'}));
 return {service,project,company,calls,begin,complete,command,get connection(){return connection;},setHook:callback=>{inspectionHook=callback;}};
}
for(const display of ['+12025550124',null,'+1 invalid'])test('fresh declaration mismatch cannot bind subscribe register or activate '+display,async()=>{const f=fixture({display}),start=await f.begin();await assert.rejects(f.complete(start),{code:display===null||display.includes('invalid')?'META_CUSTOMER_COMPANY_PHONE_UNCONFIRMED':'META_CUSTOMER_COMPANY_PHONE_MISMATCH'});assert.equal(f.calls.bind,0);assert.equal(f.calls.subscribe,0);assert.equal(f.calls.register,0);assert.equal(f.project.metadata.metaSignup.state,'REVIEW_REQUIRED');assert.ok(f.project.metadata.metaSignup.encryptedToken);assert.equal(f.calls.exchange,1);await assert.rejects(f.service.command(session,f.command('reconcile',{signupId:start.signup.id})));assert.equal(f.calls.exchange,1);});
test('declaration changed during fresh inspect blocks binding while retaining escrow',async()=>{const f=fixture({hook:company=>{company.companyPhoneDeclaration={...company.companyPhoneDeclaration,revision:2};}}),start=await f.begin();await assert.rejects(f.complete(start),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});assert.equal(f.calls.bind,0);assert.equal(f.calls.subscribe,0);assert.ok(f.project.metadata.metaSignup.encryptedToken);});
test('full formatting-only equality binds disabled then requires exact declaration for manual activation',async()=>{const f=fixture({display:'1 (202) 555-0123'}),start=await f.begin(),linked=await f.complete(start);assert.equal(linked.signup.state,'REGISTRATION_REQUIRED');assert.equal(f.calls.bind,1);assert.equal(f.calls.subscribe,1);assert.equal(f.connection.enabled,false);assert.equal(f.connection.metadata.declaredCompanyPhone.e164,'+12025550123');f.company.companyPhoneDeclaration={...stored(),revision:2};await assert.rejects(f.service.command(session,f.command('activate_channel',{confirmActivation:true})),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});assert.equal(f.connection.enabled,false);assert.equal(f.calls.register,0);});
test('a fresh pre-registration phone change prevents register POST',async()=>{const f=fixture(),start=await f.begin();await f.complete(start);f.setHook(company=>{company.companyPhoneDeclaration={...stored(),e164:'+12025550124',revision:2};});await assert.rejects(f.service.command(session,f.command('register_number',{signupId:start.signup.id,pin:'123456',confirmRegistration:true})),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});assert.equal(f.calls.register,0);assert.equal(f.connection.enabled,false);});
test('legacy state keeps original HMAC shape and does not enforce new alias contract',async()=>{const f=fixture({declaration:null,display:'+54 synthetic'}),start=await f.begin();assert.equal(Object.hasOwn(f.project.metadata.metaSignup,'declaredCompanyPhone'),false);const state=f.project.metadata.metaSignup;assert.equal(start.stateToken,createHmac('sha256',environment.META_APP_SECRET).update(JSON.stringify([state.id,'actor-a','company-a','p-a',state.preparedRevision,state.expiresAt,state.numberMode,state.configId,state.signupVersion])).digest('base64url'));const result=await f.complete(start);assert.equal(result.signup.state,'REGISTRATION_REQUIRED');assert.equal(f.calls.subscribe,1);});
test('cancel and unknown exchange recovery remain available after malformed declaration',async()=>{const f=fixture(),start=await f.begin();f.company.companyPhoneDeclaration={malformed:true};const result=await f.service.command(session,f.command('cancel',{signupId:start.signup.id}));assert.equal(result.signup.state,'CANCELLED');assert.equal(result.declaredCompanyPhone.status,'REVIEW_REQUIRED');assert.equal(f.calls.exchange,0);});

test('manual same-asset correction preserves original snapshot escrow expiry and has exact GET receipt',async()=>{const f=fixture({hook:company=>{company.companyPhoneDeclaration={...stored(),revision:2};}}),start=await f.begin(),original=structuredClone(f.project.metadata.metaSignup.declaredCompanyPhone),expiresAt=f.project.metadata.metaSignup.expiresAt;await assert.rejects(f.complete(start),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});const escrow=f.project.metadata.metaSignup.encryptedToken,body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:2,confirmCompanyPhoneRevision:true});const corrected=await f.service.command(session,body);assert.equal(corrected.receipt.state,'RECORDED');assert.equal(corrected.receipt.operationId,body.operationId);assert.deepEqual(f.project.metadata.metaSignup.declaredCompanyPhone,original);assert.equal(f.project.metadata.metaSignup.encryptedToken,escrow);assert.equal(f.project.metadata.metaSignup.expiresAt,expiresAt);assert.equal(f.project.metadata.metaSignup.companyPhoneCorrections.length,1);assert.equal(f.calls.exchange,1);const before={...f.calls},read=await f.service.read(session,{action:'reconcile',signupId:start.signup.id,operationId:body.operationId,projectId:'p-a',scope});assert.equal(read.receipt.state,'RECORDED');assert.deepEqual(f.calls,before);assert.equal((await f.service.command(session,body)).receipt.state,'RECORDED');assert.deepEqual(f.calls,before);await assert.rejects(f.service.read({...session,userId:'user_Other'},body),{code:'WORKSPACE_MEMBERSHIP_REQUIRED'});await assert.rejects(f.service.read(session,{...body,signupId:randomUUID()}),{code:'META_CUSTOMER_SESSION_UNAVAILABLE'});await assert.rejects(f.service.command(session,{...body,expectedCompanyPhoneRevision:3}),{code:'META_CUSTOMER_OPERATION_CONFLICT'});});
test('manual correction rejects concurrent revision drift and never binds an unconfirmed phone',async()=>{const f=fixture({hook:company=>{company.companyPhoneDeclaration={...stored(),revision:2};}}),start=await f.begin();await assert.rejects(f.complete(start));f.setHook(company=>{company.companyPhoneDeclaration={...stored(),revision:3};});await assert.rejects(f.service.command(session,f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:2,confirmCompanyPhoneRevision:true})),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});assert.equal(f.calls.bind,0);assert.equal(f.calls.subscribe,0);assert.equal(f.project.metadata.metaSignup.companyPhoneCorrections,undefined);});

test('malformed correction metadata returns review on ordinary GET and cannot record a review receipt',async()=>{const f=fixture(),start=await f.begin();f.project.metadata.metaSignup.companyPhoneCorrections={malformed:true};const before={...f.calls},read=await f.service.read(session,{projectId:'p-a',scope});assert.equal(read.signup.companyPhoneRevision,null);assert.equal(read.signup.companyPhoneReviewCode,'COMPANY_PHONE_INTEGRITY');assert.equal(read.signup.canRegister,false);assert.equal(read.companyPhoneReviewCode,'COMPANY_PHONE_INTEGRITY');assert.equal(read.activation.canActivate,false);assert.deepEqual(f.calls,before);await assert.rejects(f.service.command(session,f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:1,confirmCompanyPhoneRevision:true})),{code:'COMPANY_PHONE_INTEGRITY'});assert.deepEqual(f.calls,before);});

test('selected asset mismatch prevents binding even when the complete displayed number matches',async()=>{const f=fixture({verifiedPhoneId:'98765432109999'}),start=await f.begin();await assert.rejects(f.complete(start),{code:'META_CUSTOMER_PHONE_WABA_MISMATCH'});assert.equal(f.calls.bind,0);assert.equal(f.calls.subscribe,0);assert.equal(f.calls.register,0);assert.ok(f.project.metadata.metaSignup.encryptedToken);});

test('manual phone review receipt survives later subscription failure without second remote POST on replay',async()=>{const f=fixture({hook:company=>{company.companyPhoneDeclaration={...stored(),revision:2};},subscriptionFailure:true}),start=await f.begin();await assert.rejects(f.complete(start));const body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:2,confirmCompanyPhoneRevision:true});await assert.rejects(f.service.command(session,body),{code:'META_CUSTOMER_SUBSCRIPTION_UNCONFIRMED'});assert.equal(f.project.metadata.metaSignup.companyPhoneCorrections.length,1);assert.equal(f.project.metadata.metaSignup.state,'REVIEW_REQUIRED');const calls={...f.calls},result=await f.service.read(session,{projectId:'p-a',scope,action:'reconcile',signupId:start.signup.id,operationId:body.operationId});assert.equal(result.receipt.state,'RECORDED');assert.equal(result.signup.state,'REVIEW_REQUIRED');assert.equal(result.connection.enabled,false);assert.equal((await f.service.command(session,body)).receipt.state,'RECORDED');assert.deepEqual(f.calls,calls);});

test('stale declaration command has durable own rejection before provider and identical late replay stays terminal',async()=>{
 const f=fixture({hook:company=>{company.companyPhoneDeclaration={...stored(),revision:2};}}),start=await f.begin();await assert.rejects(f.complete(start));
 const before=structuredClone(f.project.metadata),calls={...f.calls},body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:1,confirmCompanyPhoneRevision:true});
 const result=await f.service.command(session,body);assert.equal(result.receipt.state,'REJECTED');assert.equal(result.receipt.saved,false);assert.equal(result.receipt.definitive,true);assert.equal(result.receipt.phase,'BEFORE_PROVIDER');assert.equal(result.receipt.code,'META_CUSTOMER_COMPANY_PHONE_CHANGED');assert.equal(result.receipt.observedCompanyPhoneRevision,2);assert.deepEqual(f.project.metadata,before);assert.deepEqual(f.calls,calls);
 assert.deepEqual((await f.service.read(session,body)).receipt,result.receipt);f.company.companyPhoneDeclaration={...stored(),revision:1};assert.deepEqual((await f.service.command(session,body)).receipt,result.receipt);assert.deepEqual(f.calls,calls);
 await assert.rejects(f.service.command(session,{...body,expectedCompanyPhoneRevision:2}),{code:'META_CUSTOMER_OPERATION_CONFLICT'});await assert.rejects(f.service.read({...session,userId:'user_Other'},body),{code:'WORKSPACE_MEMBERSHIP_REQUIRED'});await assert.rejects(f.service.read(session,{...body,scope:'b'.repeat(64)}),{code:'WORKSPACE_CONTEXT_CHANGED'});await assert.rejects(f.service.read(session,{...body,signupId:randomUUID()}),{code:'META_CUSTOMER_SESSION_UNAVAILABLE'});
});
test('non-advanced revision rejection resolves one UUID and a fresh explicitly reviewed revision can proceed',async()=>{
 const f=fixture(),start=await f.begin();await f.complete(start);const calls={...f.calls},body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:1,confirmCompanyPhoneRevision:true}),before=structuredClone(f.project.metadata);
 const rejected=await f.service.command(session,body);assert.equal(rejected.receipt.state,'REJECTED');assert.equal(rejected.receipt.effectiveCompanyPhoneRevision,1);assert.deepEqual(f.project.metadata,before);assert.deepEqual(f.calls,calls);
 f.company.companyPhoneDeclaration={...stored(),revision:2};const fresh=await f.service.command(session,{...body,operationId:randomUUID(),expectedCompanyPhoneRevision:2});assert.equal(fresh.receipt.state,'RECORDED');assert.equal(f.project.metadata.metaSignup.companyPhoneCorrections.length,1);assert.equal(f.calls.exchange,calls.exchange);
});
test('provider leases and malformed declarations never become definitive rejection from a stale request',async()=>{
 for(const state of ['VERIFYING','REGISTRATION_STARTED','REGISTRATION_VERIFYING']){const f=fixture(),start=await f.begin();await f.complete(start);f.project.metadata.metaSignup={...f.project.metadata.metaSignup,state,verificationLeaseExpiresAt:'2026-10-05T12:00:00Z',registrationLeaseExpiresAt:'2026-10-05T12:00:00Z'};f.company.companyPhoneDeclaration={...stored(),revision:2};const body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:1,confirmCompanyPhoneRevision:true}),calls={...f.calls};await assert.rejects(f.service.command(session,body),{code:'META_CUSTOMER_COMPANY_PHONE_CHANGED'});assert.equal((await f.service.read(session,body)).receipt.state,'NOT_OBSERVED');assert.deepEqual(f.calls,calls);}
 const f=fixture(),start=await f.begin();await f.complete(start);f.company.companyPhoneDeclaration={malformed:true};const body=f.command('reconcile',{signupId:start.signup.id,expectedCompanyPhoneRevision:1,confirmCompanyPhoneRevision:true});await assert.rejects(f.service.command(session,body),{code:'COMPANY_PHONE_INTEGRITY'});assert.equal((await f.service.read(session,body)).receipt.state,'NOT_OBSERVED');
});
