import { AccessError, accessErrorResponse, getPlatformAccess, requireTenantPermission } from '@/lib/access';
import { getPrisma } from '@/lib/prisma';
import { RequestBodyError, readJsonRequest, requestBodyErrorResponse } from '@/lib/request-body';
import { resolveRequestCorrelationId, withCorrelationId } from '@/lib/request-correlation';
import { createPurchaseOrder, decidePurchaseOrder, listPurchaseOrders, purchaseOrderErrorResponse } from '@/lib/purchase-orders';

function respond(request, response) { return withCorrelationId(response, resolveRequestCorrelationId(request)); }
function known(request, error) { if (error instanceof AccessError) return respond(request, accessErrorResponse(error)); if (error instanceof RequestBodyError) return respond(request, requestBodyErrorResponse(error)); const domain = purchaseOrderErrorResponse(error); return domain ? respond(request, domain) : null; }
export async function GET(request) { try { const access = await getPlatformAccess(); requireTenantPermission(access, 'org:execution:read', { subscriptionMode: 'read' }); return respond(request, Response.json(await listPurchaseOrders(getPrisma(), { organizationId: access.organization.id, projectId: access.project.id }), { headers: { 'Cache-Control': 'private, no-store' } })); } catch (error) { return known(request, error) || respond(request, Response.json({ error: 'No se pudieron cargar órdenes.', code: 'PURCHASE_ORDER_READ_FAILED' }, { status: 500 })); } }
export async function POST(request) { try { const access = await getPlatformAccess(); requireTenantPermission(access, 'org:execution:manage', { subscriptionMode: 'write' }); const input = await readJsonRequest(request, { maxBytes: 64 * 1024 }); if (input.operation === 'DECIDE') return respond(request, Response.json(await decidePurchaseOrder(getPrisma(), { scope: { organizationId: access.organization.id, projectId: access.project.id }, actorId: access.databaseUserId, id: input.id, expectedRevision: input.expectedRevision, status: input.status }))); return respond(request, Response.json(await createPurchaseOrder(getPrisma(), { scope: { organizationId: access.organization.id, projectId: access.project.id }, actorId: access.databaseUserId, input }), { status: 201 })); } catch (error) { return known(request, error) || respond(request, Response.json({ error: 'No se pudo procesar la orden.', code: 'PURCHASE_ORDER_WRITE_FAILED' }, { status: 500 })); } }
