import { AccessError, accessErrorResponse, getPlatformAccess, requireTenantPermission } from '@/lib/access';
import { getPrisma } from '@/lib/prisma';
import { RequestBodyError, readJsonRequest, requestBodyErrorResponse } from '@/lib/request-body';
import { resolveRequestCorrelationId, withCorrelationId } from '@/lib/request-correlation';
import { createGoodsReceipt, goodsReceiptErrorResponse } from '@/lib/goods-receipts';

function respond(request, response) { return withCorrelationId(response, resolveRequestCorrelationId(request)); }
function known(request, error) { if (error instanceof AccessError) return respond(request, accessErrorResponse(error)); if (error instanceof RequestBodyError) return respond(request, requestBodyErrorResponse(error)); const domain = goodsReceiptErrorResponse(error); return domain ? respond(request, domain) : null; }
export async function POST(request) { try { const access = await getPlatformAccess(); requireTenantPermission(access, 'org:execution:manage', { subscriptionMode: 'write' }); const input = await readJsonRequest(request, { maxBytes: 32 * 1024 }); return respond(request, Response.json(await createGoodsReceipt(getPrisma(), { scope: { organizationId: access.organization.id, projectId: access.project.id }, actorId: access.databaseUserId, input }), { status: 201 })); } catch (error) { return known(request, error) || respond(request, Response.json({ error: 'No se pudo registrar recepción.', code: 'GOODS_RECEIPT_CREATE_FAILED' }, { status: 500 })); } }
export async function GET(request) { try { const access = await getPlatformAccess(); requireTenantPermission(access, 'org:execution:read', { subscriptionMode: 'read' }); const purchaseOrderId = new URL(request.url).searchParams.get('purchaseOrderId') || undefined; const rows = await getPrisma().goodsReceipt.findMany({ where: { projectId: access.project.id, ...(purchaseOrderId ? { purchaseOrderId } : {}) }, include: { lines: true }, orderBy: { receivedAt: 'desc' }, take: 500 }); return respond(request, Response.json({ receipts: rows.map((row) => ({ ...row, receivedAt: row.receivedAt.toISOString(), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), lines: row.lines.map((line) => ({ ...line, quantity: line.quantity.toString() })) })) }, { headers: { 'Cache-Control': 'private, no-store' } })); } catch (error) { return known(request, error) || respond(request, Response.json({ error: 'No se pudieron cargar recepciones.', code: 'GOODS_RECEIPT_READ_FAILED' }, { status: 500 })); } }
