import Link from 'next/link';
import {ObraSaasLogo} from './brand/brand-logo';
import {LandingMenu,LandingMotion,LandingShowcase,LandingVideo} from './landing-interactions';
import {LandingPhoneScene} from './landing-phone-scene';
import styles from './page.module.css';

const questions=[
 ['¿Puedo empezar sin conectar WhatsApp?','Sí. Creá tu cuenta, abrí tu empresa y prepará la primera obra desde la web. Podés incorporar al equipo, organizar tareas y revisar registros antes de conectar el canal.'],
 ['¿Qué hace falta para usar WhatsApp en mi obra?','Necesitás el canal de tu empresa, un número autorizado y completar los requisitos que solicite Meta. Después vinculás a cada participante con su propio teléfono, identidad revisada y permisos de obra. Mi cuenta muestra qué está preparado y cuál es el próximo paso.'],
 ['¿La inteligencia artificial aprueba identidades o avances?','La lectura del documento y la comparación facial son ayudas opcionales, con consentimientos independientes. Otro responsable revisa la identidad; una selfie estática no verifica prueba de vida. Las evidencias y propuestas de avance también requieren una decisión humana autorizada.'],
 ['¿Qué voy a encontrar en la demo?','Una constructora y Torre Palermo Soho como obra de ejemplo: cronograma, materiales, incidencias, equipo y clientes. También podés probar el recorrido guiado de operario, encargado y director.'],
 ['¿Qué pasa si una operación queda sin confirmar?','Podés comprobar el mismo intento y su recibo antes de repetirlo. El sistema conserva la referencia pendiente y no reenvía una operación de obra automáticamente.'],
];
function Arrow({diagonal=false}){return <svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none"><path d={diagonal?'M6 18 18 6M6 6h12v12':'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function ScheduleExample(){return <div className={styles.schedule} data-landing-example="schedule"><div className={styles.scheduleHeader}><strong>Plan de obra</strong><span className={styles.exampleLabel}>Ejemplo ilustrativo</span></div><div className={styles.scheduleWeeks}><span>TAREA</span><span>SEM 01</span><span>SEM 02</span><span>SEM 03</span><span>SEM 04</span></div>{[['Estructura','structure'],['Mampostería','masonry'],['Instalaciones','services']].map(([name,bar])=><div className={styles.scheduleRow} key={bar}><span>{name}</span><div className={styles.scheduleTrack}><span className={styles[bar]}/></div></div>)}<div className={styles.scheduleNote}><span className={styles.pendingTag}>Propuesta pendiente</span><span>El cronograma se actualiza con una decisión autorizada.</span></div></div>;}

export default function Home(){return <div className={styles.page}>
 <a className={styles.skipLink} href="#contenido">Saltar al contenido</a>
 <header className={styles.header}><div className={styles.headerInner}><Link className={styles.brand} href="/" aria-label="ObraSaaS, inicio"><ObraSaasLogo markSize={44} variant="dark"/></Link><nav className={styles.desktopNav} aria-label="Navegación principal"><a href="#plataforma">La plataforma</a><a href="#whatsapp">WhatsApp en obra</a><Link href="/manual">Cómo empezar</Link></nav><div className={styles.headerActions}><Link href="/cuenta" className={styles.accountLink}>Mi cuenta <Arrow diagonal/></Link><LandingMenu/></div></div></header>
 <main id="contenido" tabIndex={-1}>
  <section className={styles.hero} aria-labelledby="hero-title"><div className={styles.heroAtmosphere} aria-hidden="true"/><div className={styles.heroGrid}><div className={styles.heroCopy}><LandingMotion className={styles.heroBrand} kind="brand"><ObraSaasLogo markSize={56} variant="inverse"/></LandingMotion><p className={styles.eyebrow}><span/>GESTIÓN PARA CONSTRUCTORAS</p><h1 id="hero-title">Tu obra,<br/><em>bien organizada.</em></h1><p className={styles.heroLead}>Jornadas, avances y materiales de cada obra. El equipo registra; los responsables revisan con sus permisos.</p><div className={styles.heroActions}><Link href="/sign-up" className={styles.primary}>Crear mi cuenta <Arrow/></Link><Link href="/demo" className={styles.heroSecondary}>Recorrer la demo <Arrow diagonal/></Link></div><p className={styles.heroNote}>Empezá por la web. Prepará WhatsApp desde tu cuenta.</p><div className={styles.heroProof}><span>Una persona.</span><span>Una obra.</span><strong>Un registro para revisar.</strong></div></div><div className={styles.heroVisual}><LandingPhoneScene/></div></div><div className={styles.heroIndex}><span><b>01</b> Tu empresa</span><span><b>02</b> Cada obra</span><span><b>03</b> El equipo</span><span className={styles.heroIndexEnd}>REGISTRO Y REVISIÓN</span></div></section>
  <section className={styles.presentation} aria-labelledby="presentation-title"><div className={styles.presentationCopy}><p className={styles.sectionKicker}>CONOCÉ OBRASAAS</p><h2 id="presentation-title">Jornadas, avances y materiales.<br/>Un registro por obra.</h2><p>El equipo registra. El responsable revisa. Tu empresa conserva el seguimiento de cada obra.</p><Link href="/demo" className={styles.textLink}>Explorar la empresa de ejemplo <Arrow diagonal/></Link><p className={styles.presentationScope}>La conexión de WhatsApp se prepara desde tu cuenta y requiere la autorización de Meta.</p></div><LandingVideo/></section><section className={styles.platform} id="plataforma" aria-labelledby="platform-title"><div className={styles.sectionHeading}><div><p className={styles.sectionKicker}>01 / LA PLATAFORMA</p><h2 id="platform-title">Cada obra,<br/>con su propio orden.</h2></div><p>La información llega desde el equipo. Vos definís quién participa, qué puede hacer y quién revisa cada decisión.</p></div><div className={styles.capabilityGrid}><article className={styles.companyCard}><span className={styles.cardIndex}>EMPRESA / OBRA / PERSONAS</span><div className={styles.companyDrawing} aria-hidden="true"><span className={styles.companyNode}>Empresa</span><span className={styles.nodeConnector}/><div><span>Obra A</span><span>Obra B</span></div></div><h3>Una empresa.<br/>Una vista de cada obra.</h3><p>Prepará tareas, fechas y responsables. Cada integrante entra con su cuenta y accede según sus permisos.</p><Link href="/manual#empezar">Conocer el recorrido <Arrow diagonal/></Link></article><div className={styles.featureColumn}><article className={styles.featureRow}><span className={styles.featureNumber}>01</span><div><h3>El equipo, con acceso propio.</h3><p>Incorporá participantes, revisá su identidad y definí permisos de campo. La ficha de una persona y su acceso se administran por separado.</p></div></article><article className={styles.featureRow}><span className={styles.featureNumber}>02</span><div><h3>Cada parte, con su evidencia.</h3><p>Jornadas, incidencias, notas y archivos privados quedan vinculados a la obra. Los responsables consultan el registro y su recibo.</p></div></article><article className={styles.featureRow}><span className={styles.featureNumber}>03</span><div><h3>Materiales, del pedido a la recepción.</h3><p>El equipo presenta lo que necesita. Los responsables revisan compras y registran entregas parciales o completas.</p></div></article></div></div><div className={styles.planningGrid}><div><p className={styles.sectionKicker}>PLANIFICACIÓN CON RESPONSABLES</p><h3>El avance se propone.<br/>La decisión se registra.</h3><p>Relacioná una propuesta con la tarea y su evidencia. El responsable revisa antes de actualizar el avance aprobado.</p><Link href="/demo" className={styles.textLink}>Ver el circuito en la demo <Arrow diagonal/></Link></div><ScheduleExample/></div></section>
  <section className={styles.whatsapp} id="whatsapp" aria-labelledby="whatsapp-title"><div className={styles.whatsappGrid}><div className={styles.whatsappCopy}><p className={styles.eyebrow}><span/>02 / REGISTROS POR OBRA</p><h2 id="whatsapp-title">Un mensaje<br/>desde la obra.<br/><em>Un registro<br/>para tu equipo.</em></h2><p>Audio, fotos y ubicación compartida desde el teléfono. Cada participante actúa con su identidad y sus permisos; el responsable revisa la evidencia y las propuestas.</p><Link href="/manual#whatsapp" className={styles.lightLink}>Cómo preparar el canal <Arrow diagonal/></Link><p className={styles.channelNote}>La conexión requiere un número autorizado y completar los requisitos de Meta. Podés empezar por la web.</p></div><LandingShowcase/></div></section>
  <section className={styles.start} id="recorrido" aria-labelledby="start-title"><div className={styles.sectionHeading}><div><p className={styles.sectionKicker}>03 / PARA EMPEZAR</p><h2 id="start-title">Primero, tu empresa.<br/>Después, tu primera obra.</h2></div><Link href="/manual" className={styles.textLink}>Manual de inicio <Arrow diagonal/></Link></div><ol className={styles.steps}><li><span>01</span><h3>Creá tu cuenta.</h3><p>Ingresá con tu identidad personal y completá la verificación que te indique el acceso.</p></li><li><span>02</span><h3>Prepará la obra.</h3><p>Abrí tu empresa, nombrá la primera obra y organizá sus tareas y fechas previstas.</p></li><li><span>03</span><h3>Sumá al equipo.</h3><p>Invitá responsables y participantes. Revisá sus permisos antes de registrar actividad.</p></li></ol><div className={styles.startActions}><Link href="/sign-up" className={styles.primary}>Crear mi cuenta <Arrow/></Link><span>¿Ya tenés acceso? <Link href="/cuenta">Abrir Mi cuenta <Arrow diagonal/></Link></span></div></section>
  <section className={styles.faq} aria-labelledby="faq-title"><div><p className={styles.sectionKicker}>ANTES DE EMPEZAR</p><h2 id="faq-title">Respuestas claras.<br/>Decisiones informadas.</h2><p>Conocé el recorrido y qué necesita cada circuito para funcionar en tu empresa.</p></div><div className={styles.faqList}>{questions.map(([question,answer],index)=><details className={styles.faqItem} key={question} data-landing-faq={index}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
  <section className={styles.closing} aria-labelledby="closing-title"><p className={styles.sectionKicker}>OBRASAAS / REGISTRO Y REVISIÓN</p><div><h2 id="closing-title">El próximo parte.<br/><em>En el lugar correcto.</em></h2><Link href="/sign-up" className={styles.primary}>Crear mi cuenta <Arrow/></Link></div></section>
 </main>
 <footer className={styles.footer}><div className={styles.footerGrid}><div data-public-site-identity="obrasaas" className={styles.publicIdentity}><Link href="/" aria-label="ObraSaaS, inicio" className={styles.footerBrand}><ObraSaasLogo markSize={30} variant="inverse"/></Link><p>ObraSaaS, un producto de Inmovar LATAM</p><p>Ing. Marcelo Ariel Guillén Alba · Fundador</p><p>Arq. María Victoria Schiaffino · Socia</p><p className={styles.legalOwner}>Titular: <strong>GUILLEN ALBA, MARCELO ARIEL</strong></p><p>Nombre registrado en ARCA: <strong>GUILLEN MARCELO ARIEL</strong></p></div><nav className={styles.footerNav} aria-label="Enlaces del sitio"><Link href="/manual">Manual de inicio <Arrow diagonal/></Link><Link href="/demo">Recorrer la demo <Arrow diagonal/></Link><Link href="/cuenta">Mi cuenta <Arrow diagonal/></Link></nav><div className={styles.footerSignature}><span>CONSTRUIR.</span><span>REGISTRAR.</span><span>DECIDIR.</span></div></div></footer>
</div>;}
